### ISSUE TITLE
improvement in  image registration using ECC algorithm.

### ISSUE THREAD

**Issue by epitalon** [Itseez/opencv#4230]
My purpose is to compare two successive images in time of a growing set of bacteria colonies
For that purpose, I tested OpenCV image registration using ECC algorithm.
I suggest one improvement, already discussed with the original author of this module: Georgios Evangelidis.

source code is in opencv/modules/video/src/ecc.cpp
I used an euclidean transformation `(motionType == MOTION_EUCLIDEAN)`
When updating the warping matrix in the function "update_warping_matrix_ECC()", source code below computes angle new_theta from arc cosinus of mapPtr[0] (which is the cosinus of previous angle theta)
```.cpp
    if (motionType == MOTION_EUCLIDEAN) {
        double new_theta = updatePtr[0];
        if (mapPtr[3]>0)
            new_theta += acos(mapPtr[0]);

        if (mapPtr[3]<0)
            new_theta -= acos(mapPtr[0]);
```
It is better to compute it from sinus : since angle theta is small, its cosinus is close to 1 and departure from 1 is small of an order of theta squared.
Therefore, cosinus value has some rounding error.
Computing acos(cosinus) causes some rounding error on new_theta. 

I suggest the following code:
```.cpp
    if (motionType == MOTION_EUCLIDEAN) {
        double new_theta = updatePtr[0];
        new_theta += asin(mapPtr[3]);
```
which is also simpler;
Notice that mapPtr[3] is the sinus of previous angle theta.
I tested this change on my application. The accuracy in overlapping images is much better.

Actually, in my project, I used the orginal source code of Georgios Evangelidis, available at http://xanthippi.ceid.upatras.gr/people/evangelidis/ecc/ and liked it with OpenCV 2.0. But source code in OpenCV 3.0 has not evolved much. so that I am pretty sure about the code change that I suggest above.

Good luck.
epitalon@orange.fr

**Comment by JulianVolodia** [comment]
BTW, about GitHub - Markdown do formatting - you didn't left one blank line so code block isn't adjusted properly.
