### ISSUE TITLE
Can you put all OpenCV binary versions on Github?

### ISSUE THREAD

**Issue by aswmtjdsj** [Itseez/opencv#4236]
Hi,

I have seen in the OpenCV download page that the Linux/Mac binary is on Github, and sourceforge is currently not very stable, as just went through some kind of server corruption or something alike, so I'm asking whether you can put all versions of OpenCV binary on Github or not.

If you agree, I think that would save us a lot of time and work. Thank you!

**Comment by JulianVolodia** [comment]
Why? For what platform? Compiled with what settings? Diffs will be awful :-( -1

I think it not good way, also because git isn't good to handle binary files (repository size increases very very fast).

**Comment by Leprechaunius** [comment]
It doesn't really matter where the downloads are hosted...
What we really need is official maven support from the build team.

**Comment by StevenPuttemans** [comment]
I do not see why in fact this is needed. The download page just says that for Linux you need to download source code and built it yourself. I suggest keeping it the way it is.

**Comment by mshabunin** [comment]
It can be useful to have mirror for binary files like Windows pack, iOS framework and Android SDK. GitHub allows to attach such files to releases, so it will be easy to add them.

I think we will discuss this feature some time later.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by mshabunin** [comment]
Considering this issue done.
