### ISSUE TITLE
Unable to set CAP_PROP_XI_DOWNSAMPLING in Python

### ISSUE THREAD

**Issue by Anki11** [Itseez/opencv#5085]
Hi,

I am not able to set a Value for CAP_PROP_XI_DOWNSAMPLING in Python.
My example:
```python
import cv2
cam = cv2.VideoCapture(0)
successful = cam.set(CAP_PROP_XI_DOWNSAMPLING, 2.0)
print successful
# False
cam.release()
```

**Comment by StevenPuttemans** [comment]
Well it is possible that
1. your camera does not support it
2. the interface that you are using the parameter with is not supporting it yet

So can you please, add some more information like camera used, which cap interfaces, ...

**Comment by Anki11** [comment]
The cam is a XIMEA MQ022RG-CM. However, I was checking the wrong line. It has no binning feature. Sorry for the circumstances. All the best

**Comment by StevenPuttemans** [comment]
:+1:
