### ISSUE TITLE
CUDA ARCH BIN 5.0 FAILURE

### ISSUE THREAD

**Issue by kevg-42** [Itseez/opencv#5101]
Dear All,

The bin is incompatible with graphic card version 5.0.

General problem : 
The problem is in CUDA_ARCH_BIN because no support 5.0 version and only proposed 3.0 3.5 version for Kepler generation, and PTX don't create.

The program don't function in CUDA but is function in openCL.
Because the graphic card don't accept the cubin different of 5.0

The problem is worse with Auto detect generation because the program don't compile and the error is : nvcc : architecture is not compatible.

Description problem:
In set Kepler config. 
I modify in CMake 5.0 in CUDA_ARCH_BIN and after config the value in CUDA_ARCH_BIN is automatically reset to 3.0 3.5 and the PTX is reset in never. 

For forced CMake I have modify  CMakeCache.txt in the build folder
I test this :
//Specify 'real' GPU architectures to build binaries for, BIN(PTX)
// format is supported
CUDA_ARCH_BIN:STRING=3.0 3.5 5.0

//Specify 'virtual' PTX architectures to build PTX intermediate
// code for
CUDA_ARCH_PTX:STRING=

//Attach the build rule to the CUDA source file.  Enable only when
// the CUDA source file is added to at most one target.
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON

//Generate and parse .cubin files in Device mode.
CUDA_BUILD_CUBIN:BOOL=OFF

The result is same

After I test this : 
//Specify 'real' GPU architectures to build binaries for, BIN(PTX)
// format is supported
CUDA_ARCH_BIN:STRING=3.0 3.5 5.0

//Specify 'virtual' PTX architectures to build PTX intermediate
// code for
CUDA_ARCH_PTX:STRING= 5.0

//Attach the build rule to the CUDA source file.  Enable only when
// the CUDA source file is added to at most one target.
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON

//Generate and parse .cubin files in Device mode.
CUDA_BUILD_CUBIN:BOOL=ON

The result is same

I resolve the problem with no-compliance method but the program good run
I modify in OpenCVDetectCUDA.cmake in the source/cmake folder
This is my modification : 

  set(__cuda_arch_ptx "")
  if(CUDA_GENERATION STREQUAL "Fermi")
    set(__cuda_arch_bin "2.0 2.1(2.0)")
  elseif(CUDA_GENERATION STREQUAL "Kepler")
    if(${CUDA_VERSION} VERSION_LESS "5.0")
      set(__cuda_arch_bin "3.0")
    else()
      set(__cuda_arch_bin "3.0 3.5 5.0")
    endif()
  elseif(CUDA_GENERATION STREQUAL "Auto")
    execute_process( COMMAND "${CUDA_NVCC_EXECUTABLE}" "${OpenCV_SOURCE_DIR}/cmake/checks/OpenCVDetectCudaArch.cu" "--run"

My software config : 
Cuda toolkit v7.0
OpenCV v2.4.10
CMake v3.2.0

My hardware config : 
GPU name: NVIDIA Quadro K2200
GPU version: 5.0
GPU multiProc: 5

I expect my message help you for a correct modification.
If please let us know if you need anything else.

best regards
Kevin GARDETTE

**Comment by jet47** [comment]
You can manually specify the `CUDA_ARCH_BIN` option in CMake command line:

    cmake -DCUDA_ARCH_BIN=5.0 <path to opencv>

**Comment by kevg-42** [comment]
Thank you for your reply and take time for the answer to my problem.
I apologize for my late response.

I run the command line and the result is there:

- Detected CUDA 7.0
- CUDA NVCC targets flags: -gencode ; arch = compute_30 , code = sm_30 ; -gencode ; arch = com
pute_35 , code = sm_35

It the same result as my amendment to the CMakeCache.txt
failure is CMakeCache.txt :

// Format is supported
CUDA_ARCH_BIN : String = 3.0 3.5

I expect my message help you for a correct modification.
If please let us know if you need anything else.

best regards

**Comment by jet47** [comment]
Did you set `CUDA_GENERATION`? Try to unset it:

```
cmake -DCUDA_GENERATION="" -DCUDA_ARCH_BIN=5.0
```

**Comment by kevg-42** [comment]
Thank you for your reply more quickly

And for more accuracy

It seems that the line:
set(__cuda_arch_bin "3.0 3.5")

in cmake/OpenCVDetectCUDA.cmake sets CUDA_ARCH_BIN back to "3.0 3.5" 
whatever we specifiy with -DARCH_CUDA_BIN

It solved the problem temporarily by modifying this line to:
set(__cuda_arch_bin "3.0 3.5 5.0")

And I try your operation tomorrow
Thank you

**Comment by kevg-42** [comment]
Thank you for the support and the time pass

In efect, I try Keppler and Auto in  CUDA_GENERATION= and I had the problem in my first post .
And the problem is solved with this jet47 with the last Post : 
-DCUDA_GENERATION cmake = "" = 5.0 -DCUDA_ARCH_BIN
