### ISSUE TITLE
Name of "OpenCV for iOS" is still opencv2.framework.

### ISSUE THREAD

**Issue by yosei** [Itseez/opencv#5108]
Should it be opencv3.framework?

**Comment by StevenPuttemans** [comment]
The 2 in opencv2 framework is actually not related to the version of OpenCV which is supported but more from historical reasons.
opencv.framework --> the ancient and now deprecated C-API
opencv2.famework --> the newer C++ API

The 2 was added to make sure that people could still combine both frameworks together if they really desire it.

**Comment by yosei** [comment]
I understand. Thanks for the explanation!
