### ISSUE TITLE
documentation needs correction

### ISSUE THREAD

**Issue by sturkmen72** [Itseez/opencv#5111]
http://docs.opencv.org/master/d2/de8/group__core__array.html#gaf0d056b5bd1dc92500d6f6cf6bac41ef

**solved**

**Comment by sturkmen72** [comment]
http://docs.opencv.org/master/d2/de8/group__core__array.html#ga7d7b4d6c6ee504b30a20b1680029c7b4&gsc.tab=0

**Comment by sturkmen72** [comment]
https://github.com/Itseez/opencv/blob/master/modules/highgui/include/opencv2/highgui.hpp#L84-L122

**Comment by pieteradejong** [comment]
issue still open, or closed?

**Comment by sturkmen72** [comment]
issue is open. see also http://answers.opencv.org/question/74762
