### ISSUE TITLE
opencv3.0 deepflow

### ISSUE THREAD

**Issue by yangangw** [Itseez/opencv#5133]
I have compared the code of deepflow given in current opencv and the code provided by the author, I found that current code in opencv does not include the deepmatching component, when will it be finished?

Thanks!

**Comment by StevenPuttemans** [comment]
Deepflow is part of the opencv_contrib repository and thus this issue does not belong here. That being said it has already been reported there https://github.com/Itseez/opencv_contrib/issues/319 and we already answered why it is not in yet and why it will not ever be in...
