### ISSUE TITLE
The width of Rect

### ISSUE THREAD

**Issue by wm-cv** [Itseez/opencv#5134]
opencv souce code:
template<typename _Tp> inline
Rect_<_Tp>::Rect_(const Point_<_Tp>& pt1, const Point_<_Tp>& pt2)
{
    x = std::min(pt1.x, pt2.x);
    y = std::min(pt1.y, pt2.y);
    width = std::max(pt1.x, pt2.x) - x;
    height = std::max(pt1.y, pt2.y) - y;
}

When i do some thing like this:
Mat roi = img(Rect(pt1, pt2));

Now, roi.cols is equal to std::max(pt1.x, pt2.x) - x,  rather than std::max(pt1.x, pt2.x) - x + 1.

Anybody got an idea about this?

**Comment by mshabunin** [comment]
The [documentation](http://docs.opencv.org/master/d2/d44/classcv_1_1Rect__.html#details) says: 

    OpenCV typically assumes that the top and left boundary of the rectangle are inclusive, 
    while the right and bottom boundaries are not.
