### ISSUE TITLE
SVM error when input data size is too large (exception in calc_non_rbf_base function)

### ISSUE THREAD

**Issue by LorenaGdL** [Itseez/opencv#5137]
When using large training datasets (combination of number of samples and number of features per sample), the SVM train function throws and exception. Specifically, the exception arises in calc_non_rbf_base function from svm.cpp source file.

Major findings about the issue:
- Caused when the used combination of large number of samples and large number of features per sample goes above some threshold.
- Independent on input data values.
- Dependent on the proportion of positive and negative samples in dataset.

More info about the issue, including tests, results and screenshots can be found in this Q&A post: http://answers.opencv.org/question/67137/svm-error-when-input-data-size-is-too-large-calc_non_rbf_base/

System information: OpenCV 2.4.12 (build with CMake, basic options enabled), Visual Studio 2013, Windows 7 64 bits, 16GB RAM

Code to reproduce the issue can be found here: https://gist.github.com/LorenaGdL/526bad96ea35c982eec4

If you need any other info, feel absolutely free to ask. Thank you all.

**Comment by mshabunin** [comment]
Should be fixed, please check.

**Comment by LorenaGdL** [comment]
Seems it works like a charm! Thank you so so much :)
