### ISSUE TITLE
Multiblock Local Binary Pattern in object detect module confusion.

### ISSUE THREAD

**Issue by warmspringwinds** [Itseez/opencv#5138]
Hello.

Recently I was following the original [paper](http://sdpy.googlecode.com/svn/tags/temp/unsorted3/to_delete/tmp/unsorted/to_remove/research/my_papers/phdthesis/review/survey/MB-LBP/fulltext.pdf) about the gentle adaboost training.

I was a little bit confused by the fact that in the paper they use multi-branch tree with 256 values, but the implementation of `traincascade` and [cascade xml files](https://github.com/Itseez/opencv/blob/master/data/lbpcascades/lbpcascade_frontalface.xml#L34) have a two branch tree. Is it a problem or a special trick. I didn't find any information in documentation. I would be really glad if someone briefly explains this thing or point me out the part in documentation where this thing is described.

Thank you.

**Comment by StevenPuttemans** [comment]
The default setting of OpenCV is to use stumps as weak classifiers, which means we use decisions trees based on only a single feature value. Then the weak features are combined into a stage that has to reach a certain performance. You can however change this by playing round with the following parameters

<pre>
-maxDepth < max_depth_of_weak_tree >
-maxWeakCount < max_weak_tree_count >
</pre>

**Comment by warmspringwinds** [comment]
@StevenPuttemans Thank you for your help.

I am trying to implement the training stage and more interested in how the fitting of the tree is done in OpenCV, because it is clearly done differently from how it's stated in referenced paper.

Good point. I moved it [here](http://answers.opencv.org/question/68041/multiblock-local-binary-pattern-in-object-detect-module-confusion/).

Thank you.

**Comment by StevenPuttemans** [comment]
:+1: Seems valid to close this one down and continue our discussion on the Q&A?

**Comment by warmspringwinds** [comment]
@StevenPuttemans Could you, please, point me out in the code where the binary tree is created in the case of LBP where we have 256 categorial values?

**Comment by StevenPuttemans** [comment]
I have no exact idea, since I did not yet dig that deep into the code yet. But I am guessing that it will be somewhere in the boosting functionality.

**Comment by warmspringwinds** [comment]
@StevenPuttemans sorry for bombing you with questions :)
Maybe you know someone who wrote this part or have a deep understanding?
I saw @CheeseWiz wrote it, but he seems to be away.
Because the question about binary tree can be really quickly answered by the author.

**Comment by StevenPuttemans** [comment]
I do not know it exactly .. and my experience is that not everyone grasps the inner details, which are sometimes hard to comprehend if you did not program them yourself. I might take a look at it later today.

**Comment by warmspringwinds** [comment]
@StevenPuttemans thank you. The behaviour clearly deviates from the paper. And maybe it would be appropriate to later explicitly write about it in the documentation.

**Comment by StevenPuttemans** [comment]
I am guessing that the maximum categorical values are hardcoded [here](https://github.com/Itseez/opencv/blob/master/apps/traincascade/lbpfeatures.cpp#L9).

Then all possible features are being collected [here](https://github.com/Itseez/opencv/blob/master/apps/traincascade/lbpfeatures.cpp#L35), exactly like it would be in the HAAR wavelet feature case.

And as initial guess I would say that the tree construction is being done [here](https://github.com/Itseez/opencv/blob/master/apps/traincascade/boost.cpp#L511), inside the boosting algorithm.

**Comment by StevenPuttemans** [comment]
[Here](https://github.com/Itseez/opencv/blob/master/apps/traincascade/boost.cpp#L520) you can see that the 256 values are used to restrict the training size of the trees.

**Comment by warmspringwinds** [comment]
@StevenPuttemans Thank you so much :)
Yes, I already saw this things, now I just feel more confident that I search in the right place.

The question that I am concerned with right now is how OpenCV gets a binary tree with value for each of the two branches for each of 256 possible values in case of LBP features.

Because in the paper they do a regression tree with 256 branches. I guess the answer is located [here](https://github.com/Itseez/opencv/blob/master/apps/traincascade/old_ml_tree.cpp#L2436).
But it's really hard to read without any links and comments. Would be cool to know what algo is used here.

@vpisarev Could you, please, help me with this small question?
