### ISSUE TITLE
isOpen() returns true even if there is no camera

### ISSUE THREAD

**Issue by PhilLab** [Itseez/opencv#5141]
*Migrated from http://code.opencv.org/issues/3880#note-4*

I am hitting a bug on opencv 2.4.10, ubuntu 14.04 and gcc 4.8.2. isOpen() returns true even if there is no camera in my machine. Then get this message:

GStreamer Plugin: Embedded video playback halted; module v4l2src0 reported: Cannot identify device '/dev/video0'.
OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
) in icvStartPipeline, file /home/coutinho/src/opencv-2.4.10/modules/highgui/src/cap_gstreamer.cpp, line 383
terminate called after throwing an instance of 'cv::Exception'
what(): /home/coutinho/src/opencv-2.4.10/modules/highgui/src/cap_gstreamer.cpp:383: error: (-2) GStreamer: unable to start pipeline
in function icvStartPipeline

Aborted (core dumped)

**Comment by StevenPuttemans** [comment]
Confirmed bug on latest 2.4 branch! Using Ubuntu 14.04 x64, no webcam connected to the system.

<pre>
#include <opencv2/opencv.hpp>
#include <iostream>

using namespace std;
using namespace cv;

int main( int argc, const char** argv )
{
    VideoCapture test(0);
    Mat frame;
    if(test.isOpened()){
        cerr << "The camera is open!" << endl;
    }
    return 0;
}
</pre>

**Comment by ilya-lavrenov** [comment]
fixed in https://github.com/Itseez/opencv/pull/5202
