### ISSUE TITLE
a question about issues

### ISSUE THREAD

**Issue by sturkmen72** [Itseez/opencv#5158]
hi all, in my spare times i read issues. is there a way to mark an issue to find it later easily ?
if i comment on the issue my name @sturkmen72 i can find it easily. is this way permissible?

**Comment by PhilLab** [comment]
If it is an issue you find valuable, commenting with a :+1: is a good idea to show other people that this issue is of certain interest. Posting ":+1: @sturkmen72 " is also ok and suits your needs

**Comment by StevenPuttemans** [comment]
If you look to the side panel then you can see there is a subscribe button. Then you can check the overview of all topics you subscibed to.

**Comment by sturkmen72** [comment]
@StevenPuttemans i have checked watch on top , thus i am subscribed to all issue.

**Comment by StevenPuttemans** [comment]
Why would you do that? :D

**Comment by sturkmen72** [comment]
i thought some conversation has useful information for me to understand source code. i liked to read them
