### ISSUE TITLE
make error with python

### ISSUE THREAD

**Issue by lz199144** [Itseez/opencv#5160]
opencv 2.4.11 
Linking CXX shared library ../../lib/cv2.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/cv2.so] Error 1
make[1]: *** [modules/python/CMakeFiles/opencv_python.dir/all] Error 2
make: *** [all] Error 2

**Comment by alalek** [comment]
It is not OpenCV issue.
You should check custom python build (Hint: `--enable-shared` configure option).
