### ISSUE TITLE
BgSegm is not wrapped for Java

### ISSUE THREAD

**Issue by LgArcida** [Itseez/opencv#5163]
There a a lot of modules that cannot be enabled for Java developing.
The original question remains unanswered
http://answers.opencv.org/question/68081/opencv-30-contrib-java/

What are the steps to enable the contrib modules for Java?

**Comment by StevenPuttemans** [comment]
Could you please add this issue to the issue section of the opencv_contrib repository (https://github.com/Itseez/opencv_contrib/issues)? This will enable it to better follow up on it. Then you can clsoe this one.

Thank you in advance!

**Comment by LgArcida** [comment]
I know this issue was moved to opencv_contrib, but after a couple of days there is no response yet.
Does anybody has any idea how I could fix this?

**Comment by StevenPuttemans** [comment]
@LgArcida I know that some days have passed by, but please be a bit patient. Resources for OpenCV developers are limited, so they need some time to get to you.
