### ISSUE TITLE
Segmentation fault deallocating a static cv::Mat

### ISSUE THREAD

**Issue by dorian3d** [Itseez/opencv#5174]
I get a segmentation fault running this code:

    #include <iostream>
    #include <opencv2/core.hpp>

    int main() {
      std::cout << "start" << std::endl;
      static cv::Mat a;
      a.create(3, 3, CV_32F);
      std::cout << "end" << std::endl;
    }

The output is:

    start
    end
    pure virtual method called
    terminate called without an active exception
    Aborted (core dumped)

The OpenCV version is 3.0.0. The compiler is `g++-4.8 (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4` running on `Linux 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 GNU/Linux`.

I suspect the same problem is behind other segmentation faults that I get from time to time when a local `cv::Mat` is deallocated at the end of a function. The debugger takes me to the call to `deallocate()` in `cv::Mat::release`. However, I couldn't find a MWE for this error.

**Comment by alalek** [comment]
Get latest code from master branch and try it. It should be fixed.

**Comment by dorian3d** [comment]
You're right, it is already fixed in master. I close this issue.

**Comment by manuvt** [comment]
I face this error after I upgraded to opencv 3 on Aug 28<sup>th</sup>  . Could please tell me how to resolve this issue?

**Comment by dorian3d** [comment]
@alalek Do you know what commit fixed this issue?

**Comment by alalek** [comment]
There are many attempts to fix issue with `pure virtual method called` problem.
The latest commit is 53fc5440d78fd9ebe727c51243528e1eac3b5e35
