### ISSUE TITLE
Problem with UMat with operator()

### ISSUE THREAD

**Issue by LaurentBerger** [Itseez/opencv#5181]
I have ot a system exception using this program (Visual studio 2013 win10 64 bits  opencv 3.0-dev with GTX 970 and Visual studio 2013 win 7 64 bits  opencv 3.0-dev with GT 630 
```.cpp
#include <opencv2/opencv.hpp> 
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/core/core.hpp"
#include "opencv2/core/ocl.hpp"
#include <iostream>
#include <map>
#include <fstream>
using namespace cv;
using namespace std;


int main(int argc, char **argv)
{
    UMat imUMat = UMat::zeros(256,256, CV_8U);  // type of mask is CV_8U
    Mat imMat = Mat::zeros(256,256, CV_8U);  // type of mask is CV_8U
    Rect r(0,0,10,10);

    imUMat(r) = 255;
    r = Rect(0,0,0,0);
    imUMat(r) = 255; // BUG when rect is empty
return 0;
}
```

**Comment by StevenPuttemans** [comment]
@LaurentBerger I am actually not of the opinion that this is a bug, since asking for a region of interest of 0 pixels is just wrong ... the code works from the moment you provide at least 1 pixel... This is just how you should address the function.

What you could do is add a check into the Mat ( Rect() ) creation that avoids this.

**Comment by LaurentBerger** [comment]
No I'm not agree. In my post I have test beahavior for Mat with opencl or not and UMat with or without opencl. This exception occurs only when Opencl is on and rect is empty using UMat

rect

**Comment by alalek** [comment]
IMHO, OpenCV (and other many libraries/frameworks/tools/etc) should detect when user want to shoot yourself in the leg. In this case it is empty ROI.
So my suggestion is to add exceptions for all cases of empty ROI to show that something is going wrong and application developer should take a look on code.

**Comment by StevenPuttemans** [comment]
:+1: to that :D

**Comment by LaurentBerger** [comment]
@StevenPuttemans I'm agree asking a empty region is wrong. But I think like @alalek opencv should take care of parameters validity (not like my own program who send empty rect to UMat)
