### ISSUE TITLE
numThreads = 0 in parallel.cpp when building to iOS

### ISSUE THREAD

**Issue by danageva** [Itseez/opencv#5184]
When building OpenCV to iOS the "numThreads" variable is always set to 0, as a direct result the parallel_for_ method doesn't use the GCD queues. 
Changing the if in the beginning of the method to use "getNumThreads" fixed it, but I'm not sure it's the right solution. 

Any help would be appreciated.

**Comment by mshabunin** [comment]
Isn't numThreads set to `-1` for GCD? ([here](https://github.com/Itseez/opencv/blob/master/modules/core/src/parallel.cpp#L213))
