### ISSUE TITLE
cv::ml::TrainData::loadFromCSV doesn't read the last column if there are only 2 rows in csv

### ISSUE THREAD

**Issue by jskang** [Itseez/opencv#5188]
For OpenCV 3.0
```.cpp
cv::Ptr<cv::ml::TrainData> raw_data = cv::ml::TrainData::loadFromCSV(argv[2], 0);
cv::Mat data = raw_data->getSamples();
cout << data << endl;
```
If the csv only has two rows it does not read the last column of the last row

**Comment by mshabunin** [comment]
Try to print contents of `raw_data->getResponses()`. Isn't it your missing column?

**Comment by jskang** [comment]
Yes you're right. Sorry I thought it was a bug
