### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by bhack** [Itseez/opencv#5200]
See https://github.com/blog/1184-contributing-guidelines

**Comment by ilya-lavrenov** [comment]
agree :+1:

**Comment by StevenPuttemans** [comment]
PR with guidelines for both 2.4 and master branches added. Suggestions more than welcome!

**Comment by bhack** [comment]
Could we use the same for contrib?

**Comment by alalek** [comment]
Awesome!
@StevenPuttemans Thank you!

**Comment by StevenPuttemans** [comment]
@bhack yeah sure! just a sec!

**Comment by StevenPuttemans** [comment]
There you go :)

**Comment by bhack** [comment]
Nice!

**Comment by StevenPuttemans** [comment]
@bhack the files have been provided as seen in these two PRs
https://github.com/Itseez/opencv/pull/5358#event-414646998
https://github.com/Itseez/opencv/pull/5359#event-414651958

However I am not yet seeing the message displayed when creating a PR

**Comment by alalek** [comment]
Done for opencv repo and it works!
@StevenPuttemans Thanks!

**Comment by StevenPuttemans** [comment]
@alalek, could you merge the same one for the contrib repo before closing this down? We need a seperate file for each repository.

**Comment by alalek** [comment]
@StevenPuttemans Could you update https://github.com/Itseez/opencv_contrib/pull/336 please (address this comment: https://github.com/Itseez/opencv/pull/5217#issuecomment-134088400)?

**Comment by StevenPuttemans** [comment]
Ow didn't know i forgot to change that one! will fix it after my class I am supervising now
