### ISSUE TITLE
cv::imwrite() always crashes when accessing the params vector (Windows 8.1 x86)

### ISSUE THREAD

**Issue by mielleman** [Itseez/opencv#5227]
When writing an image to disk (`cv:imwrite`) using an encoding which accesses the `Vector<int>& params` the code __will always crash during runtime with an "Access violation"__. I am able to reproduce with encodings JPG and PNG. If an encoding is used which doesn't use the `params` vector the problem doesn't exist (e.g. BMP).

I am running Windows 8.1 Pro with Visual Studio 2013 and OpenCV from git (master). If needed I have all build settings and files stored and can rebuild/test upon request.

Code to reproduce:
`std::string filename = "file.png";`
`cv::Mat image cv::Mat(600, 800, CV_8U);`
`cv::imwrite(filename.c_str(), image);`

Second code to reproduce:
`std::string filename = "file.jpg";`
`cv::Mat image cv::Mat(600, 800, CV_8U);`
`std::vector<int> my_params;`
`my_params.push_back(CV_IMWRITE_JPEG_QUALITY);`
`my_params.push_back(80);`
`cv::imwrite(filename.c_str(), image, my_params);`

A workaround is to just use a different `params` vector which is cleanly created inside the `imwrite_` static function. _This workaround **FORGETS** and silently **IGNORES** any given parameters and let's the functions fall back to any default opencv parameters for the specific image encoding._

Open `modules\imgcodecs\src\loadsave.cpp` change function:
`static bool imwrite_( const String& filename, const Mat& image, const std::vector<int>& params, bool flipv )`
Find the following line:
`bool code = encoder->write(*pimage, params);`
Replace with:
`//bool code = encoder->write(*pimage, params);`
`bool code = encoder->write(*pimage, {});`

**Comment by ilya-lavrenov** [comment]
Could you create merge-request with proposed changes and regression tests?

**Comment by mielleman** [comment]
@ilya-lavrenov the workaround is really not suitable for a merge-request as it just forgets the params given. More research is needed to determine the platform specific cause of this bug.

**Comment by mielleman** [comment]
I found the following stackoverflow questions explaining they are encountering exactly this problem:
http://stackoverflow.com/questions/13496712/opencv-unhandled-exception-when-writing-a-file
http://stackoverflow.com/questions/29287117/opencv-imwrite-params-read-access-violation

Both questions are answered with a non working solution, either -DWITH-JPEG=ON or using BMP instead.

I was also able to reproduce this problem by installing the Windows opencv-3.0.0 binary installation package from the OpenCV website:
http://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.0.0/opencv-3.0.0.exe/download

**Comment by MaverickTse** [comment]
Just to report that an up-to-date build of OpenCV using MSVC or INTEL compiler(32bit build), No CUDA, No OpenEXR, No contrib, CAN output PNG.

**Comment by Dikay900** [comment]
Can confirm this is not an issue anymore with latest sources. Using the params exactly like the reproducable code.

**Comment by alalek** [comment]
Thanks for checks!

**Comment by kikaxa** [comment]
can we reopen this?
i still get this same crash with msvc2010, opencv 3.1

**Comment by alalek** [comment]
@kikaxa Open a new issue with complete reproducer code and OpenCV build configuration.
There are many cases where `imwrite` used, and it works without crashes.

**Comment by kikaxa** [comment]
after some painfull debugging, it might be the app/compiler/crt that is bugged.
it crashed with mixed debug(app)/release(opencv) modes, and a lot of other things were broken, too.
for now it works in regular build, i'll open the new bug if crash reappears.

**Comment by PkLab** [comment]
I've same issue (Win7, VS2013, OCV 3.1.0/x64 home build)

> it crashed with mixed debug(app)/release(opencv) modes

Both cases _debug(app)/debug(opencv)_ and _release(app)/release(opencv)_ works fine

I think that a new issue should be opened

**Comment by alalek** [comment]
> new issue should be opened

Crashes in mixed debug/release mode can't be solved in OpenCV - it is MSVS runtime specific.

**Comment by PkLab** [comment]
Do you want to say that, OpenCV Release build can't be used with end user application Debug build due to MSVS runtime specific ?

any investigation might be useful also around other functions and maybe a workaround or a compiler switch exists.

...looking at imwrite [here](https://github.com/opencv/opencv/blob/3.1.0/modules/imgcodecs/include/opencv2/imgcodecs.hpp#L225) the `params`  isn't correctly assigned/initialized/linked in **Debug build**

Adding [here](https://github.com/opencv/opencv/blob/3.1.0/modules/imgcodecs/src/loadsave.cpp#L483) a simple 
```
std::cout << "params.size()=" << params.size() << std::endl;
``` 

The following test prints out `params.size()=184467440736......`
``` 
imwrite("Test.jpg", mat,params);
``` 

The following test prints out `params.size()=32`
```    vector<int> params;
    params.push_back(0);
    params.push_back(0);
    imwrite("Test.jpg", mat,params);
```

**Comment by alalek** [comment]
ABI is different in debug/release builds for most C++/STL structures, so you can't used them in mixed mode.

Please take a look on this thread in QT project:
http://www.qtcentre.org/threads/54332-Mixing-Debug-and-Release-binaries

The only thing that probably can be done in OpenCV to help users - it is to prevent successful builds (raise some error).

**Comment by PkLab** [comment]
@alalek thank you very much for your useful answer. quoting the user from the referring thread 

> I'm wondering that some software i use do not need to ship the debug dlls
