### ISSUE TITLE
Memory leak in DescriptorExtractor.compute

### ISSUE THREAD

**Issue by rock2193** [Itseez/opencv#5233]
OpenCV version : 2.4.11
Using javacv bindings for java
Code:

    CvMat featureDetect(IplImage image){
        logger.info("Detecting Sift KeyPoints ..............");
        SIFT sift = null;
        FeatureDetector featureDetector = null;
        KeyPoint keyPoints = null;
        DescriptorExtractor extractor = null;
        try {
            sift = new SIFT();
            featureDetector  = FeatureDetector.create("SIFT");
            keyPoints = new KeyPoint();
            featureDetector.detect(image, keyPoints, null);
            extractor  = DescriptorExtractor.create("SIFT");
            System.out.println(keyPoints.capacity() + "  " + extractor.descriptorSize());
            CvMat descriptors = cvCreateMat(keyPoints.capacity(), extractor.descriptorSize(), CV_32F);
            extractor.compute(image, keyPoints, descriptors);
            if(keyPoints.isNull() || descriptors.isNull()) {
                return null;
            }
            return descriptors;
        }finally {
            if(sift != null)    sift.deallocate();
            if(featureDetector != null)     featureDetector.deallocate();
            if(keyPoints != null)   keyPoints.deallocate();
            if(extractor != null)   extractor.deallocate();
        }
       }
       public static void main(String[] args) throws IOException {
           while (true){
                    IplImage image1 = null;
                    CvMat result1 = null;
                    try {
                             image1 = cvLoadImage("wallpaper.jpg");
                             result1 = featureDetect(image1);
                    }finally {
                             if(image1 != null) cvReleaseImage(image1);
                             if(result1 != null)  cvReleaseMat(result1);
                    } }                    
            }

When i run this function 1000 times for same image , my memory consumption increases from 2% to 10%, but when i comment this line,
 
extractor.compute(image, keyPoints, descriptors);

 my memory consumption remain static.

**Comment by mshabunin** [comment]
We do not support javacv bindings. If you could reproduce the problem with OpenCV's java bindings or C++ code - feel free to reopen this issue with corresponding example.
