### ISSUE TITLE
How to run faceDetect faster 

### ISSUE THREAD

**Issue by chfakht** [Itseez/opencv#5247]
Hi i'm a newbie in opencv , i want to run the code faceDetect on a raspberry pi 2 overclocked to 1GHZ , i'm using faceDetect.cpp to detect face and eye gaze  
the program is a little bit slow due to the detection i want that the program runs in real time ... the only improvement that i can done is to increase the scale but the accuracy decreases a lot ... is there any alternative that can i done without affecting much the accuracy !!!
thanks  a lot

**Comment by sturkmen72** [comment]
http://answers.opencv.org is the correct place for your question. i am sure you will get an answer

**Comment by chfakht** [comment]
I was looking for an answer from @avdmitry  and @vpisarev , i don't know if they can be tagged ... that's because they are the developpers of the facedetection example , so they know exactly what can be done and what can be improved ...
thanks :octocat: @sturkmen72  i will try there too :mag:

**Comment by StevenPuttemans** [comment]
@chfakht please stick with the suggestion of @sturkmen72. Also if you have multiple questions about a single example, put them together and not all in a single and seperate issues...
