### ISSUE TITLE
modules/imgproc/src/hough.cpp contains 3 bogus bytes at start

### ISSUE THREAD

**Issue by CV-GPhL** [Itseez/opencv#5253]
It semes that at
  https://github.com/Itseez/opencv/blob/e88bf2bc3081863bac276589a7c9c960c1545952/modules/imgproc/src/hough.cpp
three bogus bytes have been introduced right at the start of the file as present in opencv-3.0.0.zip (MD5SUM = 09004c275d8092cbdf5b61675cecd399). Only after removing those with

  mv hough.cpp hough.cpp.old
  dd if="hough.cpp.old" of="hough.cpp" bs=1 skip=3

on Linux can I compile OpenCV 3.0.0 on CentOS 5.11 (using GCC 4.1.2).

**Comment by mshabunin** [comment]
@CV-GPhL, can you please provide pull request with this change?

**Comment by CV-GPhL** [comment]
Hi,

On Wed, Aug 26, 2015 at 09:01:13AM -0700, Maksim Shabunin wrote:
> @CV-GPhL, can you please provide pull request with this change?

Sorry - I'm not an expert with Git/Github ... just that I saw this in
the opencv-3.0.0.zip file and wanted to record that problem in the
(hopefully?) appropriate place.

Cheers

Clemens

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Itseez/opencv/issues/5253#issuecomment-135079353

-- 

***************************************************************
* Clemens Vonrhein, Ph.D.     vonrhein AT GlobalPhasing DOT com
*
*  Global Phasing Ltd.
*  Sheraton House, Castle Park 
*  Cambridge CB3 0AX, UK
*--------------------------------------------------------------
* BUSTER Development Group      (http://www.globalphasing.com)
***************************************************************
