### ISSUE TITLE
Multiple simultaneous umat.getMat() fail

### ISSUE THREAD

**Issue by apavlenko** [Itseez/opencv#5259]
The test is (already in):
```
TEST(UMat, map_unmap_counting)
{
    if (!cv::ocl::useOpenCL())
    {
        std::cout << "OpenCL is not enabled. Skip test" << std::endl;
        return;
    }
    std::cout << "Host memory: " << cv::ocl::Device::getDefault().hostUnifiedMemory() << std::endl;
    Mat m(Size(10, 10), CV_8UC1);
    UMat um = m.getUMat(ACCESS_RW);
    {
        Mat d1 = um.getMat(ACCESS_RW);
        Mat d2 = um.getMat(ACCESS_RW);
        d1.release();
    }
    void* h = NULL;
    EXPECT_NO_THROW(h = um.handle(ACCESS_RW));
    std::cout << "Handle: " << h << std::endl;
}
```

Result:
```
[ RUN      ] UMat.map_unmap_counting
Host memory: 1
Handle: 00000002972CED80
unknown file: error: C++ exception with description "C:\builds\...\opencv\modules\core\src\ocl.cpp:4578: error: (-215) retval == 0 in function cv::ocl::OpenCLAllocator::deallocate
" thrown in the test body.
[  FAILED  ] UMat.map_unmap_counting (0 ms)
```

**Comment by apavlenko** [comment]
Investigation showed that the test fails on Intel platform due to failing multiple buffer Map/Unmap operations.

The corresponding bug report is submitted to Intel: https://software.intel.com/en-us/forums/topic/590312

**Comment by apavlenko** [comment]
Here is the response from Intel:

After consulting with our driver architect, we think that you program is actually operating correctly. According to rev19 of the 1.2 spec, page 123, section 5.4.3. https://www.khronos.org/registry/cl/specs/opencl-1.2.pdf
```
“Mapping (and unmapping) overlapped regions in a memory object and/or associated memory
objects (sub-buffer objects or 1D image buffer objects that overlap this region) for writing is an
error and will result in CL_INVALID_OPERATION error returned by  clEnqueueMapBuffer, or
clEnqueueMapImage.”
``` 
-59 is CL_INVALID_OPERATION, so you are getting expected behavior.

The problem here is in the 1.2 man pages, which don't have the above wording. The spec takes precedence, though :) Both 1.1 and 2.0 man pages have this wording:
 
https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/clEnqueueMapBuffer.html

https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/clEnqueueMapBuffer.html

**So let's implement a map/unmap reference counter in `UMat`**

**Comment by apavlenko** [comment]
@alalek , what's the latest status?

**Comment by alalek** [comment]
#5317
