### ISSUE TITLE
Found simple bug in tutorial code for calib3d (PnPProblem.cpp)

### ISSUE THREAD

**Issue by ScottJohnson2718** [Itseez/opencv#5270]
PnPProblem.cpp is a part of the calib3d tutorial code.

In order to set a 3x3 rotation matrix and a translation vector the function set_P_matrix should copy 12 items.  It only copies 11.  It is missing the copy of the 2,2 element in the matrix. 

Scott

PS.  Before posting I searched for PnPProblem.cpp and found nothing.

**Comment by berak** [comment]
https://github.com/Itseez/opencv/blob/master/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/PnPProblem.cpp#L101
