### ISSUE TITLE
"Installation in Linux" documentation is weak

### ISSUE THREAD

**Issue by SoajanII** [Itseez/opencv#5273]
"Building OpenCV from Source Using CMake, Using the Command Line" section is not informative enough for new users. My folders are in total mess, and had to format Ubuntu a few times in a row.

Please offer an solution without Cmake, or be more specific. Novice users like me, doesn't really care much about cross platform code porting nor Cmake.

**Comment by mshabunin** [comment]
@SoajanII, unfortunately you can not build OpenCV without cmake. Three main dependencies needed for build are: `cmake`, `make` and the compiler.

Make sure you've installed all dependencies mentioned in the tutorial:
```.sh
sudo apt-get install build-essential
sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
```

**Comment by SoajanII** [comment]
Hi Maksim

I had already installed the dependencies on the tutorial. I think you
didn't get the point.

I have no idea with the cmake, and its mechanism. I'm just a newbie, not
have much idea with computer science. Example on cmake -D command is not
realy clear, since it ends with ".." You had to be much more specific on
the example.

**Comment by mshabunin** [comment]
The `..` means _parent directory_ and should be typed as-is. The tutorial suggests to create following folder structure:
```
~
└──opencv
   └──build
```
When you run cmake inside `build` directory, you should provide path to `opencv` folder and the relative path is `..`

You can also try to install `cmake-gui` utility and provide all paths via graphical interface as mentioned in tutorial.

**Comment by SoajanII** [comment]
I have tried exactly what you said on Cmake-gui. But libraries are still
missing in my computer. I'm preparing a question to stackoverflow atm, hope
it will be solved.

Thanks for the help

**Comment by alalek** [comment]
> I have no idea with the cmake, and its mechanis

Try to read CMake documentation, like this page: http://www.cmake.org/runningcmake/

There are some commands that we use for OpenCV testing: http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV-lin64

**Comment by mshabunin** [comment]
@SoajanII , feel free to reopen this issue if you have more specific description of the problem. Please note that questions are better to be addressed on users forum: http://answers.opencv.org
