### ISSUE TITLE
AGAST is ~30x slower than FAST

### ISSUE THREAD

**Issue by JefferyRPrice** [Itseez/opencv#5278]
In experimenting with the AGAST detector, I found it to be about 30x slower than the FAST detector, which was highly unexpected (and even way slower than the GFTTDetector). I created a [simple gist](https://gist.github.com/JefferyRPrice/8a9550e3a3d85969af21) and have included the example.jpg used therein.
![example](https://cloud.githubusercontent.com/assets/1270864/9590596/a39c73bc-5003-11e5-9279-08ea2cd23223.jpg)

**Comment by StevenPuttemans** [comment]
@cbalint13 I guess this is an interesting one for you!

**Comment by cbalint13** [comment]
@JefferyRPrice , @StevenPuttemans 

* I will look into this. It is clear that non-max suppression is way suboptimal for AGAST.
* Also, keep in mind that:

1. detection part itself for AGAST should be faster but there are also the scoring routines.
2. scoring can slow down things for AGAST but scoring is much qualitative that of FAST !
3. We can add a switch to disable scoring if someone want just raw "points" with no scores.

The nomax suppression for AGAST is terribly slow, this will be the first thing i should fix it. The original nonmax supression code was much terrible (as far i remember).

* with maxsupp:
$ ./gist 
AGAST, 3715, 27658
FAST, 3735, 633

* without nonmax:
AGAST, 16467, 2216
FAST, 16467, 460

And we still miss ~5x (i belive the scoring routines are expensive for AGAST).

**Comment by cbalint13** [comment]
@mshabunin, @JefferyRPrice  not sure this is a **"bug"** , but *yes* there are room for improvement !

* if we  take literally by original code we are still 1:1 "there" with the code as authors wanted.
* we can improve the obvious odd nonmax suppression (will handle that, i think is my fault there).
* we can add a flag to disable "scoring" which is done in much extensive ways than of FAST.
* lets not forget that FAST is cpu intrinisic optimised , so its not fair to compare with AGAST !
* 9_16 pattern quality for FAST is **way** bellow AGAST one, i remeber that BRISK was happy only with AGAST not FAST (it accounted by very large margins for BRISK case) !

I believe quality always come with a price !

**Comment by JefferyRPrice** [comment]
@cbalint13 I certainly appreciate your contribution! I agree it may not really be a bug, I was just surprised in that everything I've read, only cursorily I admit, made me suspect AGAST would be faster. In fact,  when visiting the [URL in the AGAST documentation reference from the bibliography](http://www6.in.tum.de/Main/ResearchAgast), the subtitle there says "AGAST Corner Detector: faster than FAST and even FAST-ER" which was not exactly the case.

**Comment by cbalint13** [comment]
@JefferyRPrice ,

  * Totally agree, yes :) "Fast than fast, or even so". Let me tackle with it, we cannot leave it in this state at x30 slowness, the nonmax part is very slow and its not original authors fault. I suspect nonmax was slowed down by me, i had to rewrite it all for opencv's keypoints structure. Will got some time today and try fix it. I would be happy to make it at x2 , x3 slower than FAST including scoring part in this slowness, and facts FAST is SIMD optimized here.

  * Also i am afraid cannot add flag for peoples who want disable the scoring part inside AGAST, i will break API / ABI for opencv, its not allowed within this release.

**Comment by yashwanthyashu** [comment]
thank i understood about open cv

**Comment by alalek** [comment]
@JefferyRPrice PR #5406 has been merged. Please close this issue if problem is resolved.
