### ISSUE TITLE
Release openCV 3 with bitcode enabled for iOS9

### ISSUE THREAD

**Issue by stojanovicigi** [Itseez/opencv#5319]
OpenCV 3.0 wasn't build with enabled bitcode flag. Please make a build with this flag enabled.

**Comment by JetForMe** [comment]
+1

**Comment by aledalgrande** [comment]
+1

**Comment by changizi** [comment]
+1

**Comment by schickling** [comment]
+1

**Comment by dlahyani** [comment]
+1

**Comment by kapoorsahil** [comment]
+1

**Comment by jmbapps** [comment]
+1  Please, it is urgent.  Thank you.

**Comment by heXiangpeng** [comment]
+1

**Comment by mshabunin** [comment]
Please check updated `platforms/ios/build_framework.py` script (#5654), it should add the requested flags.

**Comment by Codermonk** [comment]
Will this fix be released soon for the OpenCV 3.0 Cocoa Pod?

**Comment by alalek** [comment]
https://github.com/Itseez/opencv/releases/tag/3.1.0

**Comment by aussiDavid** [comment]
In my Podfile I have

    pod 'OpenCV', '~> 3.1.0'

And get this error

    [!] Unable to satisfy the following requirements:
    
    - `OpenCV (~> 3.1.0)` required by `Podfile`

Has anyone been able to download the Pod with built with bitcode enabled?

**Comment by kapoorsahil** [comment]
@aussiDavid Same error for me.

**Comment by aussiDavid** [comment]
bump

**Comment by 8masterofpuppets8** [comment]
Any news on this guys? I'm still getting this error..

**Comment by mshabunin** [comment]
@aussiDavid , @8masterofpuppets8 , @kapoorsahil , we are not mainaining the OpenCV Cocoa Pod, please contact maintainers stated on the pod page: https://cocoapods.org/pods/OpenCV

**Comment by jmbapps** [comment]
This is no longer an issue and hasnt been for some time.  Use the latest versions, build with CMake, copy/paste additional lib's into project.  Done.
