### ISSUE TITLE
Documentation for connectedComponentsWithStats

### ISSUE THREAD

**Issue by psalvaggio** [Itseez/opencv#5326]
Hello,

The documentation for connectedComponentsWithStats() isn't clear on how you access all of the information about the connected components. The data types of the stats (CV_32S) and centroids (CV_64F) matrix are not given. It is also not clear how to access the centroids (centroids(label, 0) for x and centroids(label, 1) for y).

Would it be possible to update the documentation with this information?

Thanks,
Phil

**Comment by mshabunin** [comment]
@psalvaggio, feel free to create pull request with the fix. Documentation for master branch (version 3.0) is generated from header files: [connectedComponentsWithStats](https://github.com/Itseez/opencv/blob/bd43c62a75e3cc4185fe020c6243179cd9f662fb/modules/imgproc/include/opencv2/imgproc.hpp#L3412)

**Comment by sturkmen72** [comment]
this issue can be closed down
