### ISSUE TITLE
clipLine not working properly

### ISSUE THREAD

**Issue by StevenPuttemans** [Itseez/opencv#5330]
The function clipLine, which can be found here: https://github.com/Itseez/opencv/blob/666de1b087b70e2ea463be89173ea15b5fcda057/modules/imgproc/src/drawing.cpp#L80, does not provide the proper output.

**Test case**
There exists a line in between [-3405, 0] and [0,205].
We want to clip that line to an image of 800x600.

**Output**
The result is that both points a and b become [0, 205], whereas this is not correctly.

Anyone has an idea what is going wrong?

**Comment by LorenaGdL** [comment]
Why is it not correct? The only part of the line inside the image is the point [0, 205], so the returned segment of the line is in fact just a point

**Comment by StevenPuttemans** [comment]
Dammit... should have seen that one indeed. Ik forget this bug and lets work around our problem leading to rhis obvious error..
