### ISSUE TITLE
Documentation:Color Spaces: Code snippet has incorrect variable

### ISSUE THREAD

**Issue by rajneeshbajaj** [Itseez/opencv#5338]
http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html#converting-colorspaces

```.py
    # define range of blue color in HSV
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])

    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_green, upper_green)
```
lower_green, upper_green****
should be actually *****lower_blue and upper_blue

**Comment by LorenaGdL** [comment]
That has already been fixed in master docs (not beta): http://docs.opencv.org/master/df/d9d/tutorial_py_colorspaces.html#gsc.tab=0
