### ISSUE TITLE
Small test programm does not link under odroid Ubuntu 14.04.3

### ISSUE THREAD

**Issue by juerrose** [Itseez/opencv#5353]
Hello,

I try to compile a small program under odroid Ubuntu 14.04.3 opencv-2.4.8 with:

```
 gcc -v `pkg-config --cflags opencv` `pkg-config --libs opencv` -lm -o display_two_cams_c-style_8a_c display_two_cams_c-style_8a_c.c
```

which fails with:

```
 as -v -I /usr/include/opencv -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -meabi=5 -o /tmp/cctMJrTY.o /tmp/ccaceoPU.s
GNU assembler version 2.24 (arm-linux-gnueabihf) using BFD version (GNU Binutils for Ubuntu) 2.24
COMPILER_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/
LIBRARY_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../../lib/:/lib/arm-linux-gnueabihf/:/lib/../lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/../lib/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-I' '/usr/include/opencv' '-o' 'display_two_cams_c-style_8a_c' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
 /usr/lib/gcc/arm-linux-gnueabihf/4.8/collect2 --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu --as-needed -m armelf_linux_eabi -z relro -o display_two_cams_c-style_8a_c /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crt1.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crti.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/crtbegin.o -L/usr/lib/gcc/arm-linux-gnueabihf/4.8 -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../../lib -L/lib/arm-linux-gnueabihf -L/lib/../lib -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/../lib -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../.. /usr/lib/arm-linux-gnueabihf/libopencv_calib3d.so /usr/lib/arm-linux-gnueabihf/libopencv_contrib.so /usr/lib/arm-linux-gnueabihf/libopencv_core.so /usr/lib/arm-linux-gnueabihf/libopencv_features2d.so /usr/lib/arm-linux-gnueabihf/libopencv_flann.so /usr/lib/arm-linux-gnueabihf/libopencv_gpu.so /usr/lib/arm-linux-gnueabihf/libopencv_highgui.so /usr/lib/arm-linux-gnueabihf/libopencv_imgproc.so /usr/lib/arm-linux-gnueabihf/libopencv_legacy.so /usr/lib/arm-linux-gnueabihf/libopencv_ml.so /usr/lib/arm-linux-gnueabihf/libopencv_objdetect.so /usr/lib/arm-linux-gnueabihf/libopencv_ocl.so /usr/lib/arm-linux-gnueabihf/libopencv_photo.so /usr/lib/arm-linux-gnueabihf/libopencv_stitching.so /usr/lib/arm-linux-gnueabihf/libopencv_superres.so /usr/lib/arm-linux-gnueabihf/libopencv_ts.so /usr/lib/arm-linux-gnueabihf/libopencv_video.so /usr/lib/arm-linux-gnueabihf/libopencv_videostab.so -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lm /tmp/cctMJrTY.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/arm-linux-gnueabihf/4.8/crtend.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crtn.o
/tmp/cctMJrTY.o: In function `cvRound':
display_two_cams_c-style_8a_c.c:(.text+0xe): undefined reference to `lrint'
/tmp/cctMJrTY.o: In function `cvDecRefData':
display_two_cams_c-style_8a_c.c:(.text+0xaa8): undefined reference to `cvFree_'
display_two_cams_c-style_8a_c.c:(.text+0xb02): undefined reference to `cvFree_'
/tmp/cctMJrTY.o: In function `cvGetRow':
display_two_cams_c-style_8a_c.c:(.text+0xbd6): undefined reference to `cvGetRows'
/tmp/cctMJrTY.o: In function `cvGetCol':
display_two_cams_c-style_8a_c.c:(.text+0xbfa): undefined reference to `cvGetCols'
....
```

The same command works like a charm under Gentoo Intel with opencv-2.4.10. Any hint is appreciated.

**Comment by juerrose** [comment]
Here is the source code of a still smaller program

rose@odroid1:/home/rose/Txt/projects/OpenCV/Examples(8)$ cat cv_version.c 
#include "cv.h"
#include "highgui.h"
#include "opencv2/core/version.hpp"

#include <stdio.h>

int main( int argc, char** argv ) {
        fprintf(stderr,"CV_MAJOR_VERSION=[%%d]%d    CV_MINOR_VERSION=[%%d]%d\n",
                                        CV_MAJOR_VERSION,CV_MINOR_VERSION);

#if defined CV_MAJOR_VERSION == 3
        fprintf(stderr,"CV_MAJOR_VERSION=3 is defined  (if defined)\n");
#endif

#ifdef CV_MAJOR_VERSION
        fprintf(stderr,"CV_MAJOR_VERSION is defined  (ifdef)\n");
#endif

#if CV_MAJOR_VERSION == 3
        fprintf(stderr,"CV_MAJOR_VERSION=3  (if CV_MAJOR_VERSION == 3)\n");
#endif
        // return 0 to indicate successfull execution of the program
        return 0;
}

Trying to compile under odroid gives:

rose@odroid1:/home/rose/Txt/projects/OpenCV/Examples(9)$ gcc -v `pkg-config --cflags opencv` `pkg-config --libs opencv` -lm -ocv_version cv_version.c 
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc-4.8.real
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.8.4 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04) 
COLLECT_GCC_OPTIONS='-v' '-I' '/usr/include/opencv' '-o' 'cv_version' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
 /usr/lib/gcc/arm-linux-gnueabihf/4.8/cc1 -quiet -v -I /usr/include/opencv -imultiarch arm-linux-gnueabihf cv_version.c -quiet -dumpbase cv_version.c -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -mthumb -mtls-dialect=gnu -auxbase cv_version -version -fstack-protector -Wformat -Wformat-security -o /tmp/ccV5bdQU.s
GNU C (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04) version 4.8.4 (arm-linux-gnueabihf)
        compiled by GNU C version 4.8.4, GMP version 5.1.3, MPFR version 3.1.2-p3, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/opencv
 /usr/lib/gcc/arm-linux-gnueabihf/4.8/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/4.8/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04) version 4.8.4 (arm-linux-gnueabihf)
        compiled by GNU C version 4.8.4, GMP version 5.1.3, MPFR version 3.1.2-p3, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 9c9c18dee58554b3dcdad94a42678c32
COLLECT_GCC_OPTIONS='-v' '-I' '/usr/include/opencv' '-o' 'cv_version' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
 as -v -I /usr/include/opencv -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -meabi=5 -o /tmp/ccUMIjB4.o /tmp/ccV5bdQU.s
GNU assembler version 2.24 (arm-linux-gnueabihf) using BFD version (GNU Binutils for Ubuntu) 2.24
COMPILER_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/
LIBRARY_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.8/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../../lib/:/lib/arm-linux-gnueabihf/:/lib/../lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/../lib/:/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-I' '/usr/include/opencv' '-o' 'cv_version' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
 /usr/lib/gcc/arm-linux-gnueabihf/4.8/collect2 --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu --as-needed -m armelf_linux_eabi -z relro -o cv_version /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crt1.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crti.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/crtbegin.o -L/usr/lib/gcc/arm-linux-gnueabihf/4.8 -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../../lib -L/lib/arm-linux-gnueabihf -L/lib/../lib -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/../lib -L/usr/lib/gcc/arm-linux-gnueabihf/4.8/../../.. /usr/lib/arm-linux-gnueabihf/libopencv_calib3d.so /usr/lib/arm-linux-gnueabihf/libopencv_contrib.so /usr/lib/arm-linux-gnueabihf/libopencv_core.so /usr/lib/arm-linux-gnueabihf/libopencv_features2d.so /usr/lib/arm-linux-gnueabihf/libopencv_flann.so /usr/lib/arm-linux-gnueabihf/libopencv_gpu.so /usr/lib/arm-linux-gnueabihf/libopencv_highgui.so /usr/lib/arm-linux-gnueabihf/libopencv_imgproc.so /usr/lib/arm-linux-gnueabihf/libopencv_legacy.so /usr/lib/arm-linux-gnueabihf/libopencv_ml.so /usr/lib/arm-linux-gnueabihf/libopencv_objdetect.so /usr/lib/arm-linux-gnueabihf/libopencv_ocl.so /usr/lib/arm-linux-gnueabihf/libopencv_photo.so /usr/lib/arm-linux-gnueabihf/libopencv_stitching.so /usr/lib/arm-linux-gnueabihf/libopencv_superres.so /usr/lib/arm-linux-gnueabihf/libopencv_ts.so /usr/lib/arm-linux-gnueabihf/libopencv_video.so /usr/lib/arm-linux-gnueabihf/libopencv_videostab.so -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lm /tmp/ccUMIjB4.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/arm-linux-gnueabihf/4.8/crtend.o /usr/lib/gcc/arm-linux-gnueabihf/4.8/../../../arm-linux-gnueabihf/crtn.o
/tmp/ccUMIjB4.o: In function `cvRound':
cv_version.c:(.text+0xe): undefined reference to `lrint'
/tmp/ccUMIjB4.o: In function `cvDecRefData':
cv_version.c:(.text+0xaa8): undefined reference to `cvFree_'
cv_version.c:(.text+0xb02): undefined reference to `cvFree_'
/tmp/ccUMIjB4.o: In function `cvGetRow':
cv_version.c:(.text+0xbd6): undefined reference to `cvGetRows'
/tmp/ccUMIjB4.o: In function `cvGetCol':
cv_version.c:(.text+0xbfa): undefined reference to `cvGetCols'
/tmp/ccUMIjB4.o: In function `cvReleaseMatND':
cv_version.c:(.text+0xc12): undefined reference to `cvReleaseMat'
/tmp/ccUMIjB4.o: In function `cvSubS':
cv_version.c:(.text+0xd3e): undefined reference to `cvAddS'
/tmp/ccUMIjB4.o: In function `cvCloneSeq':
cv_version.c:(.text+0xd72): undefined reference to `cvSeqSlice'
/tmp/ccUMIjB4.o: In function `cvSetNew':
cv_version.c:(.text+0xdbe): undefined reference to `cvSetAdd'
/tmp/ccUMIjB4.o: In function `cvGetSetElem':
cv_version.c:(.text+0xe3e): undefined reference to `cvGetSeqElem'
/tmp/ccUMIjB4.o: In function `cvEllipseBox':
cv_version.c:(.text+0xf32): undefined reference to `cvEllipse'
/tmp/ccUMIjB4.o: In function `cvFont':
cv_version.c:(.text+0xf7e): undefined reference to `cvInitFont'
/tmp/ccUMIjB4.o: In function `cvReadIntByName':
cv_version.c:(.text+0x100c): undefined reference to `cvGetFileNodeByName'
/tmp/ccUMIjB4.o: In function `cvReadRealByName':
cv_version.c:(.text+0x10ae): undefined reference to `cvGetFileNodeByName'
/tmp/ccUMIjB4.o: In function `cvReadStringByName':
cv_version.c:(.text+0x1114): undefined reference to `cvGetFileNodeByName'
/tmp/ccUMIjB4.o: In function `cvReadByName':
cv_version.c:(.text+0x1140): undefined reference to `cvGetFileNodeByName'
cv_version.c:(.text+0x114c): undefined reference to `cvRead'
/tmp/ccUMIjB4.o: In function `cvContourPerimeter':
cv_version.c:(.text+0x1180): undefined reference to `cvArcLength'
/tmp/ccUMIjB4.o: In function `cvCalcHist':
cv_version.c:(.text+0x11aa): undefined reference to `cvCalcArrHist'
collect2: error: ld returned 1 exit status

**Comment by mshabunin** [comment]
Can you please provide output of `pkg-config --cflags opencv` and `pkg-config --libs opencv` commands?
