### ISSUE TITLE
smiledetect.cpp

### ISSUE THREAD

**Issue by sturkmen72** [Itseez/opencv#5354]
i want to know if is there a need to rewrite this sample with new c++ api
https://github.com/Itseez/opencv/blob/master/samples/cpp/smiledetect.cpp

**Comment by StevenPuttemans** [comment]
Yep all samples should be redacted to the actual C++ interface. If you are up to it, go ahead, if you do not have time, make a list here with samples not changed yet and I will give you a hand!

**Comment by sturkmen72** [comment]
my initial work [here](https://github.com/Itseez/opencv/compare/master...sturkmen72:patch-2)

**Comment by StevenPuttemans** [comment]
want some help reviewing it? be sure to add the PR and not the branch comparison :)

**Comment by sturkmen72** [comment]
i thougt facedetect.cpp,smiledetect.cpp,ufacedetect.cpp must share same code parts except differences. checking it now.
please review when i make PR. thanks.

**Comment by sturkmen72** [comment]
@StevenPuttemans could you review it shortly. i will work on

**Comment by StevenPuttemans** [comment]
I will :)

**Comment by sturkmen72** [comment]
merged! ( thanks @StevenPuttemans for his guidance )

**Comment by StevenPuttemans** [comment]
You are welcome!
