### ISSUE TITLE
All Android samples are showing a black/blank camera _except_ for Native Activity, which is only in 2.4.x

### ISSUE THREAD

**Issue by johnagon** [Itseez/opencv#5374]
As per title, sorry I don't have time to fix this for you. All samples run fine (or have no need to be tested as MWE's) on my Lollipop phone.

The trouble comes with my backup phone which is running on build number A820_S150_Lambda_v2.4. That's a modded ROM from stock S150 API16. Which obviously I should try reverting back to before tearing up source code. It's ironic that Native Activity is working fine, is exactly what I want/need and yet was removed from the samples in the 3.0 release. It just works, and discourages me from flashing a stock ROM.

Also, though you might assume this already, the Color Blob Detector sample is responding to touch and showing the orange-yellow in the top left (after touch) and also a square to the left of that representing the color touched.

The logcat's are fine, the SDK manager is fine, either 3.0 or 2.4.10 have the same result in 2.4.x apk's. This appies to 2.4 and 3.0 samples.

**Comment by johnagon** [comment]
Two pictures of Color Blob Detect mostly not working, one of Native Activity fully working:

![screenshot_2015-09-21-11-54-14](https://cloud.githubusercontent.com/assets/14365653/9990255/c65fc93a-6057-11e5-9c93-76d975979838.png)
![screenshot_2015-09-21-11-54-21](https://cloud.githubusercontent.com/assets/14365653/9990253/c655692c-6057-11e5-9051-2edfc3ea7972.png)
![screenshot_2015-09-21-11-54-01-cropped](https://cloud.githubusercontent.com/assets/14365653/9990254/c65d4124-6057-11e5-8d4e-861575d16124.jpg)

**Comment by alalek** [comment]
Native camera support was dropped in 3.0, because there are no important benefits on modern Android devices.

> Also, though you might assume this already, the Color Blob Detector sample is responding to touch and showing the orange-yellow in the top left (after touch) and also a square to the left of that representing the color touched.

Does this mean that Camera API works and problem with drawing image?

**Comment by johnagon** [comment]
Thanks for the quick reply, spent the time trying to get the Native Activity in 3.0 :)

What I meant was that I expected it to be an easy diagnosis for you.

I have no experience with the Android camera API and hoped to begin with OpenCV directly. `onCameraFrame` was being called but the image is always black, I have a custom app where I save this to file where to verify.

The only way, on this phone, I can get the "camera view" to show other than black is when I try and change resolution when I get a quick glimpse of the camera. (My other phone has 2 cameras and I used this hook to call "recreate" without needing to change camera). Don't know if this phone has bad API, ROM, or camera.

**Comment by PhilLab** [comment]
Is camera access possible using the Android API (e.g. without any OpenCV dependencies)? The first download link of http://www.hasper.info/hello-world-for-android-computer-vision/ is a minimal example project for that.

**Comment by johnagon** [comment]
Yes, thanks for the code Phil, I can use the Android API without OpenCV no problem.

**Comment by johnagon** [comment]
Going by http://stackoverflow.com/a/7809300/5353361 I accept native support being dropped. It's copying byte buffers that has me worried, Specifically, that `GetByteArrayElements`  won't be copying data blocks,

*Since the returned array may be a copy of the original
array, changes made to the returned array will not necessarily
be reflected in the original array*

I doubt I could satisfy my curiosity by quickly examining the source.

Sorry if I've gone off topic with this, I have a second phone to get on with.

**Comment by johnagon** [comment]
No, thanks for the code Phil.

I updated my AS from Beta 4 to 1.4 RC1 and immediately it stopped working on the call:

```java
		camera = Camera.open();
```

I try stepping into with varying degrees of success. I've varied the targetSDK from 19 to 23 then down to 16 to try to better access this method

Here's the stack:

	E/Trace: error opening trace file: No such file or directory (2)
	E/AndroidRuntime: FATAL EXCEPTION: main
	E/AndroidRuntime: java.lang.RuntimeException: Fail to connect to camera service
	E/AndroidRuntime:     at android.hardware.Camera.native_setup(Native Method)
	E/AndroidRuntime:     at android.hardware.Camera.<init>(Camera.java:383)
	E/AndroidRuntime:     at android.hardware.Camera.open(Camera.java:360)
	E/AndroidRuntime:     at info.hasper.android.minimalcamera.MainActivity.surfaceChanged(MainActivity.java:42)
	E/AndroidRuntime:     at android.view.SurfaceView.updateWindow(SurfaceView.java:593)
	E/AndroidRuntime:     at android.view.SurfaceView.access$000(SurfaceView.java:83)
	E/AndroidRuntime:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
	E/AndroidRuntime:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:726)
	E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2105)
	E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
	E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4726)
	E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
	E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:567)
	E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:536)
	E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
	E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:615)
	E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
	E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:153)
	E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5022)
	E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
	E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
	E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
	E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
	E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by johnagon** [comment]
I'm trying to debug openCV, much easier than debugging a custom ROM.

     getHolder().unlockCanvasAndPost(canvas);

is where the screen gets blanked, I step through to it from 

                if (!mStopThread && mCameraFrameReady) {
                    mCameraFrameReady = false;
                    if (!mFrameChain[1 - mChainIdx].empty())
                        deliverAndDrawFrame(mCameraFrame[1 - mChainIdx]);
                }

and there are no errors, only `Log.d(TAG, "mStretch value: " + mScale);` gets called.

I was half expecting `if (!mFrameChain[1 - mChainIdx].empty())` not to get called (I missed the critical `!`) but it gets called and blanks my screen until I force a `recreate()` call where I get one frame then nothing.

**Comment by johnagon** [comment]
I gave up and ditched 4.1.2 it is apparent from OpenCV comments that it struggles and will soon be deprecated:

    // NOTE: The order of bitmap constructor and camera connection is important for android 4.1.x
    // Bitmap must be constructed before surface

I don't understand how that is possible and must be why the samples fail. ie:

    // NOTE: On Android 4.1.x the function must be called before SurfaceTextre constructor!
    protected void AllocateCache()
    {
        mCacheBitmap = Bitmap.createBitmap(mFrameWidth, mFrameHeight, Bitmap.Config.ARGB_8888);
    }

This is only called and callable through

    mCameraView.enableView();

Which, I am 90% sure is a method of the surface that mustn't exist yet. I suppose I could override and call the protected method directly, but I'm not that bothered anymore.

**Comment by johnagon** [comment]
![rtprofileopencv](https://cloud.githubusercontent.com/assets/14365653/14913520/84baa9c6-0dfb-11e6-9c8f-9b5884a857af.png)
Even with real time profiling my app is busy waiting almost as much as it's handling frames. I'm going native.

**Comment by tslater** [comment]
@alalek Where can I find information on deprecation? I'm using JavaCameraView, but getting all black. Is that deprecated in 3.1.x? I can't find anything on that here: https://docs.opencv.org/java/3.1.0/

**Comment by alalek** [comment]
About Android Native Camera is here: https://github.com/opencv/opencv/wiki/ChangeLog  (OpenCV 3.0 version)

> JavaCameraView

It is not deprecated by OpenCV team, but it uses Android Camera API. Currently Google pushes Camera 2 API in new Android versions and modern devices.
