### ISSUE TITLE
issue win8.1 missing setup variables for VS2013

### ISSUE THREAD

**Issue by FrankOcean11** [Itseez/opencv#5375]
im trying to use OpenCV Ver.3 and im not having any luck in setting this up,

**Comment by PhilLab** [comment]
You have to provide more information.

**Comment by FrankOcean11** [comment]
actually i think i just fixed it and really i dont see wtf is it i did diff as i did the same squat i did on the one i was having issues with, i think is cuz i did a whole new project? im not sure but as in right this second i just clicked run and the window popped up and closed real quick so i was unable to indentify the ver here is the source i input.

#include <iostream>
#include <opencv2/opencv.hpp>

void main()
{
  std::cout << "OpenCV Version: " << CV_VERSION << std::endl;
}

what can i do to make it stay till i enter return ?

**Comment by FrankOcean11** [comment]
and why is it that every time we use #include it deletes after post ?

**Comment by FrankOcean11** [comment]
#include <iostream
#include <opencv2/opencv.hpp

void main()
{
  std::cout << "OpenCV Version: " << CV_VERSION << std::endl;
}

**Comment by FrankOcean11** [comment]
this are some of the items i input into the vs2013 property for both debug and release 

$(OPENCV_DIR)\..\..\include
$(OPENCV_DIR)\lib
opencv_ts300.lib
opencv_world300.lib

**Comment by alalek** [comment]
General note: http://stackoverflow.com/questions/21257544/c-wait-for-user-input

OpenCV way: `cv::waitKey(0);`

BTW, Please close this issue, I don't see any problems with OpenCV here.

**Comment by FrankOcean11** [comment]
thanks!
