### ISSUE TITLE
Incorrect python docs for neural networks

### ISSUE THREAD

**Issue by Ruuttu** [Itseez/opencv#5411]
http://docs.opencv.org/modules/ml/doc/neural_networks.html?highlight=ann_mlp#cvann-mlp-create

"cv2.ANN_MLP.create"
-> 'module' object has no attribute 'ANN_MLP'

This is with python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32 
numpy 1.9.2 and cv2 3.0.0.

**Comment by berak** [comment]
@Ruuttu , with opencv3.0, all ml classes got moved to a cv2.ml submodule, so you have to use:

<pre>

    ann = cv2.ml.ANN_MLP_create()

>>> help(cv2.ml)
Help on module cv2.ml in cv2:

NAME
    cv2.ml

FILE
    (built-in)

FUNCTIONS
    ANN_MLP_create(...)
        ANN_MLP_create() -> retval

    Boost_create(...)
        Boost_create() -> retval

    DTrees_create(...)
        DTrees_create() -> retval

    ... and so on ...

</pre>

(i think, we can close this issue)
