### ISSUE TITLE
Issues to build opencv3 on Visual Studio 2015 (64bits)

### ISSUE THREAD

**Issue by h4k1m0u** [Itseez/opencv#5417]
Hi,

I have trouble to build `opencv3` on `Visual Studio 2015 (64bits)`.
Please note that I've kept the default values in `Cmake`; here is the output I get from `Cmake`: https://bpaste.net/show/46586f28f049

As I tried to build the `ALL_BUILD` project I get the following output (with many errors included): https://bpaste.net/show/b9b92e4906dd

I've spotted errors inside the previous output, of the kind: `fatal error C1001: An internal error has occurred in the compiler`.
I don't know if the errors are caused by `Visual Studio` or `OpenCV`?

**Comment by Dikay900** [comment]
You have the latest sourcecode from the master branch in this repo? If not please update to the current HEAD of the master branch.

**Comment by h4k1m0u** [comment]
@Dikay900 I've downloaded the master branch via HTTPS from Github.

**Comment by StevenPuttemans** [comment]
I just solved all the extra modules from crashing by deactivating the `ENABLE_PRECOMPILED_HEADERS` option in CMAKE. Then even the contributed modules build fine. Might wanna try that one?

**Comment by h4k1m0u** [comment]
@StevenPuttemans Thanks I will try it tonight (in 5/6 hours) and let you know if it worked or not.

**Comment by Dikay900** [comment]
For me the whole opencv code with all contrib modules enabled (except *world) compiles under windows 10 64 bit / VS2015 (Version 14.0.23107.0 D14REL) with `ENABLE_PRECOMPILED_HEADERS` enabled.

**Comment by StevenPuttemans** [comment]
Yeah for me too now. Had a version mismatch probably..

**Comment by h4k1m0u** [comment]
For me, it didn't work with and without `ENABLE_PRECOMPILED_HEADERS` on `Visual Studio 2015 64bits` (`Windows 7`). I still have the same kind of errors even after unchecking `ENABLE_PRECOMPILED_HEADERS`.

**Comment by StevenPuttemans** [comment]
It seems from the pastebin `fatal error C1001: An internal error has occurred in the compiler.` that somehow you are using a compiler that is crashing or incompatible with OpenCV. What compiler are you using?

**Comment by h4k1m0u** [comment]
@StevenPuttemans I'm using Visual Studio 2015 64 bits (Community edition).

**Comment by Dikay900** [comment]
@h4k1m0u can you please provide the version information of your Visual Studio?
Help > Info > Copy Info

**Comment by h4k1m0u** [comment]
@Dikay900 Copy info of my Visual Studio version:

Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA059
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA059
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA059
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

ViEmu for Visual Studio   3.6.0    
ViEmu: vi/vim emulation for Microsoft Visual Studio. (c) 2005-2015 Symnum Systems. Please visit     http://www.viemu.com for details.

**Comment by Dikay900** [comment]
This is strange since you should have the same version as I have.
I cannot reproduce such an internal error. If you have time maybe cleaning all up maybe help to secure that there is nothing dirty somewhere. (build folder, source folder, version mismatch)

**Comment by jaybo** [comment]
I'm pretty sure this is bug: https://github.com/Itseez/opencv/issues/5007 which was fixed June 17, 2015.  I had this same problem when downloading and building Release 3.0, and the problem went away when I cloned the current source tree from GitHub.

**Comment by StevenPuttemans** [comment]
:+1: then this can be closed down! :)
