### ISSUE TITLE
I keep getting an error while building opencv for ARM in visual studio 2015

### ISSUE THREAD

**Issue by MuhandJumah** [Itseez/opencv#5420]
So the problem is that everytime I try to build the solution in  [vs2015\WS\10.0\ARM]  I get 4 successful builds and 18 fails.

The errors I get are as follows:
'/Fl' requires an argument
Cannot open include file: 'jasper/jas_config.h': No such file or directory

And 85 other errors from that nature. I understand that it can't find jas_config.h and etc.. but where are they?

Thanks in advance

**Comment by alalek** [comment]
Mentioned header file is here: https://github.com/Itseez/opencv/tree/master/3rdparty/libjasper/jasper
so it is a part of OpenCV sources.

On this page you can see that only MSVS 2012-2013 were tested (there is no info about 2015): https://github.com/Microsoft/opencv/tree/winrt
Same info is here about MSVS versions: https://github.com/Itseez/opencv/tree/master/platforms/winrt

BTW, Also you can take a look here: https://github.com/Microsoft/opencv/tree/test-vs2015 and/or ask questions here about WinRT support with MSVS 2015: https://github.com/Microsoft/opencv/issues

**Comment by xhaffner** [comment]
Hi!

Did you solve this problem? I have the same...

**Comment by MuhandJumah** [comment]
?Hey Hi,

Not really, I actually moved on to Ubuntu and used openCV with Python.


Muhand Jumah
Adjunct/CLT
Computer Science Dept.
CSI\City University of New York
www.cs.csi.cuny.edu<http://www.cs.csi.cuny.edu/>
________________________________
