### ISSUE TITLE
MOG2 returns foreground for the entire first input image

### ISSUE THREAD

**Issue by YanaiA** [Itseez/opencv#5427]
In version 3.0, after initiating MOG2, and giving the first input image for learning, the output result image is all "true", but should be all "false".

Found someone who asked this question too:
http://askubuntu.com/questions/665722/peculiar-observations-with-opencv-backgroundsubtractormog2-module-opencv-3-0

**Comment by LorenaGdL** [comment]
Please, refer to this question in the Q&A forum: http://answers.opencv.org/question/69403/peculiar-observations-with-opencv-backgroundsubtractormog2-module-opencv-300-python-27x-ubuntu-1404/

**Comment by StevenPuttemans** [comment]
Like explained by @LorenaGdL in the Q&A topic, it is normal behaviour. You do not push anything to the background as long as the algorithm doesn't tell that it is background. This is how the technique was designed. I suggest closing down of this issue.
