### ISSUE TITLE
cuda::normalize without specifying output type (passing -1) returns strange output type.

### ISSUE THREAD

**Issue by panmari** [Itseez/opencv#5434]
When calling cuda::normalize with the following parameters

    cuda::normalize(resultGpu, resultGpu, 0, 1, NORM_MINMAX, -1, Mat() );

I get the as type of the output `7`, which is not valid for any conversions. Everything works fine if I specify the output type as follows:

       cuda::normalize(resultGpu, resultGpu, 0, 1, NORM_MINMAX, CV_32FC1, Mat() );

I'm relatively new to opencv, does the type `7` make any sense? How am I supposed to work with it if it's a valid value?

**Comment by jet47** [comment]
Fix : https://github.com/Itseez/opencv/pull/5436

**Comment by panmari** [comment]
Seems like this was merged into master, thanks @jet47 for your swift reply.
