### ISSUE TITLE
Linking of opencv binairies fails on gcc-5.2.1 (Ubuntu 15.10): DSO missing from command line

### ISSUE THREAD

**Issue by severin-lemaignan** [Itseez/opencv#5435]
Compiling opencv master (at commit d69b7c332aa6421) with CUDA enabled, the compilation fails when linking the first binary (either ``opencv_test_cudev`` if ``BUILD_TESTS`` is enabled and ``BUILD_EXAMPLES`` is disabled, or ``opencv_annotation`` if ``BUILD_EXAMPLES`` is enabled):

```
Linking CXX executable ../../../bin/opencv_test_cudev
/usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_reduction.cu.o: undefined reference to symbol '_ZNSo9_M_insertIdEERSoT_@@GLIBCXX_3.4.9'
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Tested on Ubuntu 15.10 with ``gcc-5.2.1``.

**Comment by severin-lemaignan** [comment]
Alright, this was due to `cmake` wrongly picking ``gcc`` instead of ``g++``. Closing.

**Comment by soulslicer** [comment]
How exactly did you solve this bug?

I had to set this flag to

-D CUDA_NVCC_FLAGS="-ccbin gcc-4.8"
