### ISSUE TITLE
Building with opencv_contrib using MinGW32

### ISSUE THREAD

**Issue by peter73421** [Itseez/opencv#5437]
Compiling OpenCV with Extra modules (opencv_contrib) using MinGW32 got error as

`
[ 54%] Building CXX object modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/compiler/importer.cc.obj
In file included from  C:\opencv\sources_contrib\modules\dnn\3rdparty\protobuf\src\google\protobuf\compiler\importer.cc:38:0:
c:\mingw\include\unistd.h:78:11: error: '_cdecl' does not name a type
 _EXTERN_C _cdecl __MINGW_NOTHROW
           ^
In file included from C:\opencv\sources_contrib\modules\dnn\3rdparty\protobuf\src\google\protobuf\compiler\importer.cc:38:0:
c:\mingw\include\unistd.h:104:1: error: '_cdecl' does not name a type
 _cdecl __MINGW_NOTHROW
 ^
c:\mingw\include\unistd.h: In function 'int nanosleep(const timespec*, timespec*)':
c:\mingw\include\unistd.h:114:51: error: '__mingw_sleep' was not declared in this scope
     ? (unsigned)(-1) : (unsigned)(period->tv_nsec));
                                                   ^
c:\mingw\include\unistd.h: At global scope:
c:\mingw\include\unistd.h:125:28: error: expected initializer before 'usleep'
 int _cdecl __MINGW_NOTHROW usleep( useconds_t )__MINGW_ATTRIB_DEPRECATED;
                            ^
c:\mingw\include\unistd.h: In function 'int usleep(useconds_t)':
c:\mingw\include\unistd.h:129:73: error: '__mingw_sleep' was not declared in this scope
 int usleep( useconds_t period ){ return __mingw_sleep( 0, 1000 * period ); }
                                                                         ^
c:\mingw\include\unistd.h: At global scope:
c:\mingw\include\unistd.h:138:33: error: expected initializer before 'sleep'
 unsigned _cdecl __MINGW_NOTHROW sleep( unsigned );
                                 ^
c:\mingw\include\unistd.h: In function 'unsigned int sleep(unsigned int)':
c:\mingw\include\unistd.h:142:68: error: '__mingw_sleep' was not declared in this scope
 unsigned sleep( unsigned period ){ return __mingw_sleep( period, 0 ); }
                                                                    ^
c:\mingw\include\unistd.h: At global scope:
c:\mingw\include\unistd.h:153:12: error: expected initializer before 'ftruncate'
 int _cdecl ftruncate( int, off_t );
            ^
In file included from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\cmath:44:0,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\random:38,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\bits\stl_algo.h:65,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\algorithm:62,
                 from C:\opencv\sources_contrib\modules\dnn\3rdparty\protobuf\src\google\protobuf\compiler\importer.cc:45:
c:\mingw\include\math.h: In function 'float hypotf(float, float)':
c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
 { return (float)(_hypot (x, y)); }
                              ^
modules\dnn\3rdparty\protobuf\CMakeFiles\libprotobuf.dir\build.make:62: recipe for target 'modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/compiler/importer.cc.obj' failed
mingw32-make[2]: *** [modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/compiler/importer.cc.obj] Error 1
CMakeFiles\Makefile2:5306: recipe for target 'modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all' failed
mingw32-make[1]: *** [modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2 
`

**Comment by mshabunin** [comment]
All problems regarding contrib modules should be reported as issues in opencv_contrib repository.

Looks like mingw32 is not being developed anymore, try to use mingw-w64 instead. Try to disable problematic module with cmake option: `-DBUILD_opencv_dnn=OFF`.
