### ISSUE TITLE
T-API for Android by default

### ISSUE THREAD

**Issue by PhilLab** [Itseez/opencv#5438]
The Android+OpenCL [tutorial](https://github.com/Itseez/opencv/blob/master/doc/tutorials/introduction/android_binary_package/android_ocl_intro.markdown) tutorial states 

> By default the OpenCL support (T-API) is disabled in OpenCV builds for Android OS (so it's absent in official packages as of version 3.0)

Is this to be changed? Considering the fact that not using the AndroidManager is said to be deprecated, the T-API is effectively also deprecated for Android.

**Comment by alalek** [comment]
Unfortunatelly, nowadays there are still many devices with poor OpenCL runtime quality released 1-2 years ago (similar problem is with desktops, but with less impact).
T-API is not provided by Java bindings, so OpenCL optimization is almost not used in Android apps (but there are some exceptions).
So OpenCL optimizations are not enabled by default on Android. If you need OpenCL, you can make custom Android builds with OpenCL support via `-DWITH_OPENCL=ON`.

**Comment by PhilLab** [comment]
@alalek thank you for commenting. Would it be an option to enable it for the *NDK development* by default? Developers using this kind of approach are targeting performance, used to device-specific pitfalls and would benefit from OpenCL. Looking at the stats from the tutorial, the speed-up is impressive!

**Comment by cudnn** [comment]
where can down ANDROID_OPENCL_SDK for opencv/samples/android/tutorial-4-opencl. I use 810 cpu

**Comment by PhilLab** [comment]
@alalek I would prefer the label RFC instead of question :smile: Do you agree?

**Comment by PhilLab** [comment]
Seems to be unsolvable because of device-specific opencl drivers :disappointed:
