### ISSUE TITLE
codec error while installing 3.0.0-alpha

### ISSUE THREAD

**Issue by line2sun** [Itseez/opencv#5450]
When installing version 3.0.0-alpha the module `opencv3.0/opencv-3.0.0-alpha/modules/python/src2/hdr_parser.py` returns `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position XX: ordinal not in range(128)`.

The error appears at the line 741: `linelist = list(f.readlines())`. 
My solution was to use the `codecs` library.

        ```
        import codecs
        ...
        f = codecs.open(hname, "r", encoding='utf-8')
        ```

**Comment by berak** [comment]
it is probably [this one](https://github.com/Itseez/opencv/issues/5253)

can you try again with github master branch ?

**Comment by StevenPuttemans** [comment]
In the meanwhile, do close this issue down, since it is probably not related to the current state of the library. More problems are best first reported at the [Q&A website](http://answers.opencv.org/questions/).
