### ISSUE TITLE
putText fails with empty std::string

### ISSUE THREAD

**Issue by dorian3d** [Itseez/opencv#5451]
`putText` throws a segmentation fault when an empty `std::string` is passed as the `text` argument. It doesn't happen with an "empty" char array:

```c++
cv::Mat im(640, 480, CV_8UC3);
std::cout << "a" << std::endl;
cv::putText(im, "", cv::Point(10, 30), cv::FONT_HERSHEY_PLAIN,
            1., cv::Scalar(255, 255, 255));
std::cout << "b" << std::endl;
cv::putText(im, std::string(""), cv::Point(10, 30), cv::FONT_HERSHEY_PLAIN,
            1., cv::Scalar(255, 255, 255));
std::cout << "c" << std::endl;
```

Output:

```
a
b
Segmentation fault (core dumped)
```

OpenCV version 3.0.0. GCC `g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`. Linux `3.16.0-50-generic x86_64`.

**Comment by berak** [comment]
@alalek, should the behaviour of cv::String get changed, so that assigning an empty std::string results in a empty, but valid cv::String (with a '\0' byte, but len 0)  , atm. it results in cstr==0, len==0.
