### ISSUE TITLE
opencv 3.0, Visual Studio reports leak from function: getCoreTlsData()

### ISSUE THREAD

**Issue by adamf88** [Itseez/opencv#5452]
From question asked on stackoverflow: http://stackoverflow.com/questions/32845535/opencv-3-0-visual-studio-memory-leak-detector-false-positive

If I enabled memory leaks detector in Visual Studio (to detect leaks in my application) I have always some additional memory leaks from OpenCV and it's very difficult to find out the real memory leak from my application.

The leak comes from function: opencv/modules/calib3d/src/stereobm.cpp file.
In function: StereoBMImpl->compute() we have statement:
if(ocl::useOpenCL() && disparr.isUMat() && params.textureThreshold == 0)

The function: ocl::useOpenCL invokes getCoreTlsData() and this function executes operator new but never deletes this object:
static TLSData<CoreTLSData> *value = new TLSData<CoreTLSData>();

I disabled OpenCL but this code is still executed and memory leak is also reported.

I suppose this error isn't dangerous because it's assignment to static object, but it makes very difficult to find out leaks in applications which links to OpenCV.

**Comment by alalek** [comment]
"new" is used here as workaround for "static initialization/desctruction order fiasco" C++ problem.
This leak is not a problem at all.
Try to mark somehow these cases as "False Positives" in MSVS.

P.S. `getCoreTlsData()` is used to store random number generator state. So disabling OpenCL does not help very much.

BTW, Current "master" branch contains different code, but it still uses "new":
```
TLSData<CoreTLSData>& getCoreTlsData()
{
    CV_SINGLETON_LAZY_INIT_REF(TLSData<CoreTLSData>, new TLSData<CoreTLSData>())
}
```

**Comment by davidlibbyFIT** [comment]
Is there any chance this can get re visited. We have an application and get a number of "Leaks" coming from 3.0+ of OpenCv Granted they are small, but very annoying and might mask other leaks in the app,
