### ISSUE TITLE
imread randomly returns empty matrix

### ISSUE THREAD

**Issue by automata** [Itseez/opencv#5463]
While trying to read some images, `imread` fails, returning a `Mat` with 0x0 as dimension (`mat.empty()` or `mat.data` give a way to test that and fallback to an error, as implemented in this [workaround](https://github.com/the-grid/gmr-saliency/commit/9499eec1a84e143530ddd0210cd4ad5aee722432)).

Followed some suggestions from places like http://stackoverflow.com/questions/7417637/imread-not-working-in-opencv but got no success.

**Comment by LorenaGdL** [comment]
Check the official Q&A forum: http://answers.opencv.org/questions/
In you do a search in the provided bar, you'll find plenty of posts about imread problems and ways to fix them. If after reviewing them you still got problems, post a question there (please, see FAQ before)

**Comment by StevenPuttemans** [comment]
The following code snippet is just confirmed to work on both 2.4 and 3.0 branch

<pre>
Mat image = imread("/path/to/image/file.png", 1);
if(image.empty()){
    cerr << "The image was not read correctly!" << endl;
    // ENABLE ONE OF THE FOLLOWING OPTIONS
    // If the check is inside a loop, then continue to the next image
    //continue;
    // If you want the software to stop then add this line
    return -1;
}
</pre>

**Comment by automata** [comment]
Thank you for the suggestions. Yes, that's a workaround to fail safe and I'm using it actually. I'll try Q&A forum suggestions as well. 

Closing for now.

**Comment by automata** [comment]
Turns out we were reading images without safe checking they were properly synced with fs. Using fsync seems to solve the issue: https://github.com/the-grid/gmr-saliency/commit/c8bd11cb2b56f3a409565d78e85ab01d16ace169.
