### ISSUE TITLE
FFMPEG VideoCapture/VideoWriter performance

### ISSUE THREAD

**Issue by sergiud** [Itseez/opencv#5464]
Is there a reason for using bicubic resampling in `CvCapture_FFMPEG::retrieveFrame`? (specifically, https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L772). Except color space conversion from RGB24 to BGR24, the method does not actually resample anything. Therefore in my opinion, instead of `SWS_BICUBIC` the flag should be either `SWS_AREA` or `SWS_FAST_BILINEAR`.

**Comment by sergiud** [comment]
The same goes for VideoWriter as well; see https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L1459.

**Comment by alalek** [comment]
Right, I also saw this. But there is src_size = dst_size and there is no scaling.
I hope it is not used at all in ffmpeg.

I found `unscaled` flag in ffmpeg:
https://github.com/FFmpeg/FFmpeg/blob/26e8895b7395ed180dcb7e30465058c45050b5e2/libswscale/utils.c#L1132

And code that forces `SWS_BICUBIC` in case of "zero" flag:
https://github.com/FFmpeg/FFmpeg/blob/26e8895b7395ed180dcb7e30465058c45050b5e2/libswscale/utils.c#L1170-L1190

In any case, you are free to change value of this flag and make some performance tests.
