### ISSUE TITLE
[OpenCV3.0] Test Core_UMat.getUMat fails on Android 

### ISSUE THREAD

**Issue by IvanovSergeyA** [Itseez/opencv#5465]
I use Android4.4 on my Lenovo Yoga Tablet2. 
OpenCV3.0 GIT hash:  dff9d2288b8bb47a486b01deaa8a16fe953e91b5
After I run opencv_test_core --gtest_filter=Core_UMat.getUMat, I have the following output:

Build type: release
Parallel framework: tbb
CPU features: mmx sse sse2 sse3
OpenCL Platforms: 
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics (OpenCL 1.2 )
Current OpenCL device: 
    Type = iGPU
    Name = Intel(R) HD Graphics
    Version = OpenCL 1.2 
    Compute units = 4
    Max work group size = 256
    Local memory size = 64 kB 
    Max memory allocation size = 136 MB 872 kB 409 B
    Double support = No
    Host unified memory = Yes
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 0
Note: Google Test filter = Core_UMat.getUMat
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Core_UMat
[ RUN      ] Core_UMat.getUMat
m: 
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9;
   2,   3,   4,   5,   6,   7,   8,   9,  10,  11;
   4,   5,   6,   7,   8,   9,  10,  11,  12,  13;
   6,   7,   8,   9,  10,  11,  12,  13,  14,  15;
   8,   9,  10,  11,  12,  13,  14,  15,  16,  17;
  10,  11,  12,  13,  14,  15,  16,  17,  18,  19;
  12,  13,  14,  15,  16,  17,  18,  19,  20,  21;
  14,  15,  16,  17,  18,  19,  20,  21,  22,  23;
  16,  17,  18,  19,  20,  21,  22,  23,  24,  25;
  18,  19,  20,  21,  22,  23,  24,  25,  26,  27]
ref: 
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9;
   2,  17,  17,  17,  17,  17,  17,  17,  17,  11;
   4,  17,  17,  17,  17,  17,  17,  17,  17,  13;
   6,  17,  17,  17,  17,  17,  17,  17,  17,  15;
   8,  17,  17,  17,  17,  17,  17,  17,  17,  17;
  10,  17,  17,  17,  17,  17,  17,  17,  17,  19;
  12,  17,  17,  17,  17,  17,  17,  17,  17,  21;
  14,  17,  17,  17,  17,  17,  17,  17,  17,  23;
  16,  17,  17,  17,  17,  17,  17,  17,  17,  25;
  18,  19,  20,  21,  22,  23,  24,  25,  26,  27]
Failure
Value of: err
  Actual: 14
Expected: 0.
Which is: 0
[  FAILED  ] Core_UMat.getUMat (172 ms)
[----------] 1 test from Core_UMat (172 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (173 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Core_UMat.getUMat

 1 FAILED TEST

**Comment by alalek** [comment]
Looks like there is problem with OpenCL runtime. Try to update drivers or disable OpenCL support.
