### ISSUE TITLE
[ML] problem with cv::ml::randMVNormal

### ISSUE THREAD

**Issue by amroamroamro** [Itseez/opencv#5469]
The [`randMVNormal`](http://docs.opencv.org/3.0.0/dd/ded/group__ml.html#gaf444266b05eeb29f24fc4fe6b6972c8d) function always throws an error (failed assertion). Here is a minimal example to reproduce the error:

```cpp
#include <iostream>
#include "opencv2/core.hpp"
#include "opencv2/ml.hpp"
using namespace std;
using namespace cv;
using namespace cv::ml;

int main()
{
    // generate nxd matrix of samples, X~N(mean,cov) 
    int n = 10;
    int d = 2;
    Mat mean = Mat::zeros(1, d, CV_32F);  // I tried both 1xd and dx1
    Mat cov = Mat::eye(d, d, CV_32F);
    Mat samples;
    randMVNormal(mean, cov, n, samples);
    cout << samples << endl;
    return 0;
}
```

> OpenCV Error: Assertion failed
> (C.type() == type && (((flags&GEMM_3_T) == 0 && C.rows == d_size.height && C.cols == d_size.width) || ((flags&GEMM_3_T) != 0 && C.rows == d_size.width && C.cols == d_size.height)))
> in cv::gemm, file C:\builds\master_PackSlave-win64-vc12-shared\opencv\modules\core\src\matmul.cpp, line 923

I think the arguments of [`gemm`](https://github.com/Itseez/opencv/blob/3.0.0/modules/core/src/matmul.cpp#L921) have the wrong dimensions. According to the [docs](http://docs.opencv.org/3.0.0/d2/de8/group__core__array.html#gacb6e64071dffe36434e1e7ee79e7cb35), it performs the following operation: `dst = src1.t()*src2 + src3.t()`.

Inside `randMVNormal`, it gets called with:

    src1 = samples.row(i)   // 1xd vector
    src2 = cholesky(cov)    // dxd matrix
    src3 = mean             // 1xd vector
    dst = samples.row(i)    // 1xd vector
    flags = GEMM_3_T

Note that `cv::ml::createConcentricSpheresTestSet` also throws similar error, because it uses `randMVNormal` internally.

---

Beside the above problem, I think there is another bug in `randMVNormal`. The matrix `samples` is initially filled with `randu(samples, 0., 1.)`. Shouldn't `randn` be used here instead?

**Comment by StevenPuttemans** [comment]
Are you up to supplying a pull request with the suggested fixes? That might speed up the process of getting it fixed!

**Comment by amroamroamro** [comment]
Ok. How about this version:

``` cpp
void randMVNormal(InputArray _mean, InputArray _cov, int nsamples, OutputArray _samples)
{
    // check mean vector and covariance matrix
    Mat mean = _mean.getMat(), cov = _cov.getMat();
    int dim = (int)mean.total();  // dimensionality
    CV_Assert(mean.rows == 1 || mean.cols == 1);
    CV_Assert(cov.rows == dim && cov.cols == dim);
    mean = mean.reshape(1,1);     // ensure a row vector

    // generate n-samples of the same dimension, from ~N(0,1)
    _samples.create(nsamples, dim, CV_32F);
    Mat samples = _samples.getMat();
    randn(samples, Scalar::all(0), Scalar::all(1));

    // decompose covariance using Cholesky: cov = utmat.t() * utmat
    // Note: cov must be square, symmetric, and positive semi-definite matrix
    Mat utmat;
    Cholesky(cov, utmat);

    // transform random numbers using specified mean and covariance
    //samples = samples * utmat + repeat(mean,nsamples,1);
    for(int i=0; i<nsamples; ++i) {
        Mat sample = samples.row(i);
        sample = sample * utmat + mean;
    }
}
```

I'm using matrix expressions to multiply instead of directly calling `cv::gemm` (simply because it's easier to read, I believe it will eventually call gemm as well).. I also I changed `randu` to `randn` as I previously mentioned.

**Comment by Dikay900** [comment]
@amroamroamro it is difficult to see here what you have changed.
Please create a pullrequest and link the pullrequest to this issue by commenting "#5469"
Then your fix will get reviewed.
https://github.com/Itseez/opencv/wiki/How_to_contribute#making-a-good-pull-request

**Comment by StevenPuttemans** [comment]
Thank you for the PR!
