### ISSUE TITLE
Compilation failure with non-GNU C libraries (non-portable code)

### ISSUE THREAD

**Issue by luaraneda** [Itseez/opencv#5476]
The problem is in the file "modules/core/src/parallel_pthreads.cpp", specifically between the lines 253 to 257:

	#ifndef PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP
	#define PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP PTHREAD_RECURSIVE_MUTEX_INITIALIZER
	#endif
	
	pthread_mutex_t ThreadManager::m_manager_access_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;

For what I can see, the code uses a recursive mutex from pthreads, but I don't really understand how a recursive mutex works to create a patch or pull request.
The problem lies in the use of the constants `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` and `PTHREAD_RECURSIVE_MUTEX_INITIALIZER`, which are defined in The GNU C Library (glibc), but they are not POSIX standard.
Because the the code is not standard, using others C libs that strictly follows POSIX guidelines, like musl libc, will result on a failed compilation.

One possible solution could be the one implemented in Alsa, where they have replaced the constant `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` with the constant `PTHREAD_ONCE_INIT` plus some initialization code. This way the entire code is portable across different C libraries.
You can view a patch in the following link:
https://build.netitwork.net/package/view_file/FairWind:12.0/alsa/0014-conf.c-use-portable-way-to-initialize-recursive-mute.patch?expand=1

Another recursive mutex related issue was recently opened, for a "compile problem on FreeBSD 10.2" [#5423](https://github.com/Itseez/opencv/issues/5423). I think both could be solved by changing the way recursive mutex are implemented.

**Comment by devernay** [comment]
OS X <= 10.6 is affected by this issue. 10.7 and later define `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP`

**Comment by alalek** [comment]
@luaraneda Does https://github.com/Itseez/opencv/pull/5765 patch work for you?

**Comment by luaraneda** [comment]
Yes, it's compiling fine now.
Thank you for the pull request!
