### ISSUE TITLE
Repeated/useless assignment in contours.cpp

### ISSUE THREAD

**Issue by Bovaz** [Itseez/opencv#5481]
Hello,

I am going through some of the source code as a learning exercise, and I noticed that in   
https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/contours.cpp  
in the method  
cvStartFindContours  
scanner-> is assigned twice:  
line 219: scanner->mode = mode;  
line 225: scanner->mode = (int) mode;

**Comment by PhilLab** [comment]
You can submit a pull request fixing this. Looks like a copy-paste bug to me

**Comment by Bovaz** [comment]
I am putting together a list of all similar things in the parts of the library I am looking at. THen I will do the pull request.

**Comment by StevenPuttemans** [comment]
:+1: great! Thank you for fixing stuff :)

**Comment by StevenPuttemans** [comment]
Also in this case, the one on line 225 can go, because mode is already defined as an integer so we do not need explicit conversion...

**Comment by aman11dhanpat** [comment]
Don't you think we can mark it as closed as PR is merged?
