### ISSUE TITLE
OpenCV3 build failing with contrib extension on Ubuntu 14.04

### ISSUE THREAD

**Issue by ahundt** [Itseez/opencv#5482]
I'm trying to build opencv3 with the contrib repository with linuxbrew with the standalone setup on Ubuntu 14.04, and it seems to be failing. I've recorded the relevant [gist-logs](https://gist.github.com/ee4c3b3ce43b67eedc82), which record the exact cmake command and debug output. I believe this is due to an issue with OpenCV rather than one with linuxbrew, since linuxbrew is simply a script that executes the normal CMake build. Nonetheless, I've created an [issue at the relevant homebrew repository as well](https://github.com/Homebrew/homebrew-science/issues/2846).

To reproduce the error from scratch create a vanilla ubuntu installation (I was using a VM with vmware tools) and run the following script from [ahundt/homebrew-robotics](https://github.com/ahundt/homebrew-robotics) which automates the linuxbrew setup and goes through opencv3 installation:

    bash <(curl -fsSL https://raw.githubusercontent.com/ahundt/homebrew-robotics/master/robonetracker.sh)

Here is the relevant CMake commands from the [gist-logs](https://gist.github.com/ee4c3b3ce43b67eedc82):

```
cmake
..
-DCMAKE_C_FLAGS_RELEASE=
-DCMAKE_CXX_FLAGS_RELEASE=
-DCMAKE_INSTALL_PREFIX=/home/hbr/.linuxbrew/Cellar/opencv3/3.0.0
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DCMAKE_BUILD_WITH_INSTALL_RPATH=1
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1
-DBUILD_JASPER=OFF
-DBUILD_JPEG=OFF
-DBUILD_TIFF=OFF
-DBUILD_OPENEXR=OFF
-DBUILD_PNG=OFF
-DBUILD_ZLIB=OFF
-DCMAKE_OSX_DEPLOYMENT_TARGET=
-DJPEG_INCLUDE_DIR=/home/hbr/.linuxbrew/opt/jpeg/include
-DJPEG_LIBRARY=/home/hbr/.linuxbrew/opt/jpeg/lib/libjpeg.so
-DBUILD_opencv_java=OFF
-DBUILD_opencv_python2=ON
-DBUILD_opencv_python3=OFF
-DWITH_1394=OFF
-DWITH_EIGEN=ON
-DWITH_FFMPEG=OFF
-DWITH_GPHOTO2=OFF
-DWITH_GSTREAMER=OFF
-DWITH_JASPER=OFF
-DWITH_OPENEXR=ON
-DWITH_OPENGL=OFF
-DWITH_QUICKTIME=OFF
-DWITH_QT=OFF
-DWITH_TBB=OFF
-DWITH_CUDA=OFF
-DOPENCV_EXTRA_MODULES_PATH=/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/opencv_contrib/modules
-DWITH_OPENCL=OFF
-DPYTHON2_EXECUTABLE=/home/hbr/.linuxbrew/bin/python
-DPYTHON2_LIBRARY=/libpython2.7.so
-DPYTHON2_INCLUDE_DIR=/home/hbr/.linuxbrew/Cellar/python/2.7.10_2/include/python2.7
```

The opencv3 step of the above script is failing, here is the error:
```
[100%] Built target opencv_test_stitching
[100%] Linking CXX executable ../../bin/opencv_perf_stitching
cd /tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild/modules/stitching && /home/hbr/.linuxbrew/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_stitching.dir/link.txt --verbose=1
/home/hbr/.linuxbrew/bin/g++-5  -std=c++11  -Os -w -pipe -march=core2    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden   -DNDEBUG   -L/home/hbr/.linuxbrew/lib -Wl,--dynamic-linker=/home/hbr/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/home/hbr/.linuxbrew/lib    CMakeFiles/opencv_perf_stitching.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/opencl/perf_warpers.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/opencl/perf_stitch.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/perf_stich.cpp.o  -o ../../bin/opencv_perf_stitching -rdynamic ../../lib/libopencv_ts.a ../../lib/libopencv_stitching.so.3.0.0 ../../lib/libopencv_hal.a ../../lib/libopencv_hal.a ../../lib/libopencv_hal.a ../../lib/libopencv_objdetect.so.3.0.0 ../../lib/libopencv_xfeatures2d.so.3.0.0 -ldl -lm -lpthread -lrt ../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a ../../lib/libopencv_shape.so.3.0.0 ../../lib/libopencv_video.so.3.0.0 ../../lib/libopencv_calib3d.so.3.0.0 ../../lib/libopencv_features2d.so.3.0.0 ../../lib/libopencv_flann.so.3.0.0 ../../lib/libopencv_ml.so.3.0.0 ../../lib/libopencv_highgui.so.3.0.0 ../../lib/libopencv_videoio.so.3.0.0 ../../lib/libopencv_imgcodecs.so.3.0.0 ../../lib/libopencv_imgproc.so.3.0.0 ../../lib/libopencv_core.so.3.0.0 ../../lib/libopencv_hal.a -ldl -lm -lpthread -lrt ../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a -Wl,-rpath,/home/hbr/.linuxbrew/Cellar/opencv3/3.0.0/lib 
make[2]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
[100%] Built target opencv_perf_stitching
make[2]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
CMakeFiles/Makefile2:13078: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
Makefile:152: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

```

**Comment by mshabunin** [comment]
Problem could be in path to PYTHON2_LIBRARY:
```
make[2]: *** No rule to make target '/libpython2.7.so', needed by 'lib/cv2.so'.  Stop.
```

**Comment by mshabunin** [comment]
This path is detected in homebrew-science/opencv3.rb:
```
py_lib = OS.linux? ? `python-config --configdir`.chomp : "#{py_prefix}/lib"
```
Probably something is wrong in the system configuration.

**Comment by ahundt** [comment]
I may be mistaken, but isn't that contradicted by the following cmake script lines?

```
-- Found PythonInterp: /home/hbr/.linuxbrew/bin/python (found suitable version "2.7.10", minimum required is "2.7") 
-- Found PythonLibs: /libpython2.7.so (found suitable exact version "2.7.10") 
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4", minimum required is "3.4") 
```

If cmake found it successfully why does it still fail subsequently? I'd expect if an incorrect path configuration is specified cmake should report the issue at configure time rather than `make` reporting it at compile time.

**Comment by ahundt** [comment]
I've been able to verify that this is a bug in the OpenCV3 cmake script. As you can see in the cmake command python3 is explicitly disabled:

```
-DBUILD_opencv_python3=OFF
```

Nonetheless, OpenCV is searching for python3, leading to eventual compilation failure. Can you reopen this issue or should I create a new one?

**Comment by ahundt** [comment]
@mshabunin Can you reopen this issue or should I create a new one?

**Comment by ahundt** [comment]
The following does work:

```
brew install opencv3 --with-contrib --c++11 --without-python3 --without-python -v
```

I believe there are two bugs here, one in homebrew-science opencv3.rb and one in the OpenCV3 cmake scripts.

**Comment by alalek** [comment]
Problem is still in the command line parameters of CMake, where "/libpython2.7.so" value is forced.
In this case these lines work:
https://github.com/Itseez/opencv/blob/bbff2884473f8eed2de0b40d50586bb45c9a6680/cmake/OpenCVDetectPython.cmake#L77-L80
and behavior from here:
https://github.com/Kitware/CMake/blob/19934b67e96c91f927a1887ce85a3e6b30b2f9a0/Modules/FindPythonLibs.cmake#L27-L32

> If cmake found it successfully why does it still fail subsequently

Most part of CMake command-line parameters work in the forced mode: this mean that autodetection with some part of checks are disabled in the case of passed values for these parameters. There are configuration flexibility on the one hand and possibility to shoot the leg yourself on the other hand.

So you get wrong results by passing wrong parameters for CMake via homebrew scripts. You need to find the reason of wrong command-line arguments. Take a look [here](https://github.com/Itseez/opencv/issues/5482#issuecomment-147407367). You need to fix path.

> `-DBUILD_opencv_python3=OFF`

It is wrong way also, because "python3" here is the name of OpenCV module (fullname is opencv_python3). Checks for python2/3 don't depend on this variable.


> The following does work

Yes, this disables python support in OpenCV (via homebrew).

**Comment by ahundt** [comment]
Thanks, that clears things up substantially.

Looking at the top CMakeLists.txt https://github.com/Itseez/opencv/blob/master/CMakeLists.txt#L1143 the variable does exist, it seems like a reasonable assumption when reading the code that setting `-DBUILD_opencv_python3=OFF` would turn off python3. Perhaps it should be updated to work that way here?

I've looked around some, including googling and using the search box in both the doxygen and sphinx opencv3.0 documentation, as well as the top level CMakeLists.txt itself, and there doesn't appear to be any documentation of this aspect of the build. Perhaps `OCV_OPTION` flags should be added for the `PYTHON3` and `PYTHON2` cases?


example `OCV_OPTION` flag:

    OCV_OPTION(INSTALL_PYTHON_EXAMPLES  "Install Python examples"   OFF )

**Comment by ahundt** [comment]
In other words, I believe there is a good reason the author of the homebrew formula made the error he did, and ideally the code could be modified reasonably easily to prevent that mistake and support that use case in a future release.

**Comment by IkramulMurad** [comment]
Hello,
I'm facing following error:
[ 85%] Linking CXX shared module ../../lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so
../../lib/libopencv_dpm.so.3.4.1: file not recognized: File truncated
collect2: error: ld returned 1 exit status
modules/python3/CMakeFiles/opencv_python3.dir/build.make:136: recipe for target 'lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so' failed
make[2]: *** [lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:23466: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Please help me to figure out the solution of this problem.
Thanks in advance
