### ISSUE TITLE
Operations on rectangles not supported in Java

### ISSUE THREAD

**Issue by johnagon** [Itseez/opencv#5488]
http://docs.opencv.org/java/2.4.2/org/opencv/core/Rect.html
and
http://docs.opencv.org/java/org/opencv/core/Rect.html

State:

    In addition to the class members, the following operations on rectangles are implemented:

    rect = rect +- point (shifting a rectangle by a certain offset)
    rect = rect +- size (expanding or shrinking a rectangle by a certain amount)
    rect += point, rect -= point, rect += size, rect -= size (augmenting operations)
    rect = rect1 & rect2 (rectangle intersection)
    rect = rect1 | rect2 (minimum area rectangle containing rect2 and rect3)
    rect &= rect1, rect |= rect1 (and the corresponding augmenting operations)
    rect == rect1, rect != rect1 (rectangle comparison) 

But I am unable to access them in Android Studio.

"Operator '|' cannot be applied to 'org.opencv.core.Rect', 'org.opencv.core.Rect'"

**Comment by mshabunin** [comment]
Java documentation for this class has been automatically generated from corresponding C++ documentation. Java does not support operator overloading, thus described operations are not possible.

To make overloaded operators from C++ available, additional functions should be implemented in the wrapper module. Or you can implement them in your code using public fields in the _Rect_ class.

**Comment by johnagon** [comment]
Oh, thanks. In my humble monoglot studio I appreciate any documentation at all.
