### ISSUE TITLE
There are not dll files in project sample FaceDetection

### ISSUE THREAD

**Issue by xinshouke** [Itseez/opencv#5492]
I want try the project sample FaceDetection using OpenCV3.0, but I found the below dll files was missing in opencv.props:opencv_core300.dll,opencv_imgcodecs300.dll... ... 
   So, the sample project doesn't work.
    My question is : the dll file name were like in the OpenCV2.0 folder; but they didn't exist in  OpenCV3.0?

**Comment by alalek** [comment]
> sample project

Please add more details about this project (especially, where did you get it from?)


BTW, Try to use opencv_world300.dll (.lib) with OpenCV 3.0 binary package, it is replacement for opencv_core/imgproc/etc.
