### ISSUE TITLE
add setTrackbarMin

### ISSUE THREAD

**Issue by nzjrs** [Itseez/opencv#5495]
Counterpart to setTrackbarMax as trackbars do not respect the minimum value (at least when accessing via the python bindings)

opencv 3 (gtk backend)

**Comment by StevenPuttemans** [comment]
Are you up to providing it yourself through a PR?

**Comment by aman11dhanpat** [comment]
I might look into this fix today.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by aman11dhanpat** [comment]
Hey @StevenPuttemans , how about closing this, as PR is merged now?

**Comment by StevenPuttemans** [comment]
@nzjrs can you close this down?

**Comment by nzjrs** [comment]
Thanks!
