### ISSUE TITLE
Generator "NMake Makefiles" produces buggy Makefile(s)

### ISSUE THREAD

**Issue by rwiesen** [Itseez/opencv#5496]
Platform: Windows (Windows 8.1 64bit, Visual Studio 2015 and Visual Studio 2010)
Version: Itseez/opencv@0d791189ee642add1b537b876d8f25fa236fa50a
CMake version: 3.3.2 (download)

Steps to reproduce:
- checkout to directory opencv
- create directory tmp as sibling of opencv
- change to directory tmp
- call 'cmake -G "NMake Makefiles" ..\opencv'
- call 'nmake'

Expected behavior:
- OpenCV is built

Observed behavior:
- nmake stops with an error (translated: path not found):

    [  2%] Linking C static library ..\lib\zlibd.lib
    Das System kann den angegebenen Pfad nicht finden.
    NMAKE : fatal error U1077: 'cd' : return code '0x1'
Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

This error is caused by a trailing backslash for a 'cd' command in the file "...\tmp\3rdparty\zlib\CMakeFiles\zlib.dir\build.make" (line 642 and others) that leads to lines being combined.

**Comment by StevenPuttemans** [comment]
Could you suggest a fix through a pull request? That will speed up the fixing!

**Comment by rwiesen** [comment]
No, unfortunately not, as I am an absolute beginner with CMake.

I can't even tell if the bug is in OpenCV or the CMake generator :-(

**Comment by alalek** [comment]
Try to use "Visual Studio" generators, they are faster than NMake (NMake provides poor support for parallel compilation).
You can refer to commands from our testing infrastructure:
http://pullrequest.opencv.org/buildbot/builders/precommit_windows64

**Comment by rwiesen** [comment]
Well, I know that the VS generator works - this is my current workaround... ;-)

Nevertheless, if "NMake Makefiles" is offered, it should work. I'd rather use nmake than devenv for automated builds.

**Comment by mshabunin** [comment]
I think it is a cmake problem, similar issue has been mentioned here: https://cmake.org/pipermail/cmake/2015-September/061484.html

As a workaround you can try to turn `CMAKE_USE_RELATIVE_PATHS` option OFF (this option is forced to ON in _opencv/CMakeLists.txt_). But I'd recommend to use VS generator as we do for our automated builds.

**Comment by MarianMMX** [comment]
1. Open CMakeLists.txt .
2. Go to line 70.
3. Comment (or delete):
#if(MSVC)
#  set(CMAKE_USE_RELATIVE_PATHS ON CACHE INTERNAL "" FORCE)
#endif()
4. delete the generated files and rerun cmake.

**Comment by happyLiMing** [comment]
I think it is a problem when you using the VC(cl.exe && nmake.exe).maybe there is some ENV you missed.
