### ISSUE TITLE
Update documentation links for version 3.0

### ISSUE THREAD

**Issue by luigidr** [Itseez/opencv#5526]
Hi,

on the OpenCV website, all the documentation links point to version 2.4.11 (i.e., to http://docs.opencv.org) instead of pointing to version 3.0 (i.e., http://docs.opencv.org/3.0.0).
To find the documentation of the latest version, you have to go to http://opencv.org/documentation.html or read the news about the OpenCV 3.0 release (http://opencv.org/opencv-3-0.html): both places indicates different links for the latest stable version.

Moreover, a link to the Javadocs (version 3.0) is missing from the website, even if they are present at http://docs.opencv.org/java/3.0.0/

I think that all these indications may be confusing for novice users that look for OpenCV 3.0 docs.

Could you update the links?

Thanks!

**Comment by StevenPuttemans** [comment]
I agree on this :) @alekcac could you take care of this, since you have access to the hosting?

**Comment by mshabunin** [comment]
First page now contains the list of all documentation versions located on the site: http://docs.opencv.org/
Considering the issue fixed.

**Comment by StevenPuttemans** [comment]
:+1:
