### ISSUE TITLE
Two bugs in  CvCaptureCAM_XIMEA::setProperty (Ximea driver wrapper).

### ISSUE THREAD

**Issue by hbadino** [Itseez/opencv#5527]
Bug 1:
Some properties of the camera can't be changed while acquiring images while others can be changed on the fly. For properties of the the former case, the right way to change them is to stop the acquisition (a call to xiStopAcquisition()), then change the property (xiSetProperty())and restart acquisition (xiStartAcquisition()).  One of those parameters is CV_CAP_PROP_XI_TRG_SOURCE. The current implementation in method CvCaptureCAM_XIMEA::setProperty of file cap_ximea.cpp is:

    case CV_CAP_PROP_XI_TRG_SOURCE    : mvret = xiSetParamInt( hmv, XI_PRM_TRG_SOURCE, ival); break;

while the right implementation would be something like:

    case CV_CAP_PROP_XI_TRG_SOURCE    : 
        {
            xiStopAcquisition(hmv);
            mvret = xiSetParamInt( hmv, XI_PRM_TRG_SOURCE, ival); 
            if (mvret == XI_OK)
                mvret = xiStartAcquisition(hmv);
            break;
        }

A proper fix of the bug should include all parameters that can not be changed without stopping acquisition but I don't have a list of those parameters. 

Bug 2:
The CvCaptureCAM_XIMEA::setProperty doesn't check if the camera has been opened and should return false if the handler is NULL.

Hernan

**Comment by StevenPuttemans** [comment]
I suggest that you provide a pull request with the suggested fixes? I have no camera using that driver interface to test it properly and it will be the fastest way to get the fixes included.

**Comment by jaybo** [comment]
This has been fixed by PR: #5635.
