### ISSUE TITLE
GpuMat hangs on cudaMalloc in constructor

### ISSUE THREAD

**Issue by alarconj** [Itseez/opencv#5528]
Uploading an image to the gpu hangs on cudaMalloc whenever the cudaimgproc or photo library is loaded. For example:

    1 #include "opencv2/core.hpp"
    2 #include "opencv2/highgui.hpp"
    3 #include "opencv2/photo.hpp"
    4 #include "opencv2/cudaimgproc.hpp"
    5
    6 int main()
    7 {
    8     cv::cuda::printCudaDeviceInfo(0);
    9     cv::Mat img = cv::imread("../img.jpg", 1);
    10    cv::cuda::GpuMat imgGpu(img);
    11    cv::edgePreservingFilter(img, img, 1, 60.0f, 0.4f);
    12    cv::namedWindow("Image", 0);
    13    cv::imshow("Image", img);
    14    cv::waitKey(0);
    15    cv::destroyAllWindows();
    16 }

In the previous code, the program freezes on line 10 and never returns. Debugging with visual studio shows that the program hangs indefinitely on cudaMalloc. Strangely this does not occur if line 11 is commented out. The same problem occurs if any of the cudaimgproc functions is called. Basically, so long as any function from cudaimgproc or photo is present in the code, cudaMalloc just hangs forever.

OpenCV version: Tag 3.0.0

The device info:

    Device 0: "Quadro K2200"
        CUDA Driver Version / Runtime Version          7.0 / 7.0
        CUDA Capability Major/Minor version number:    5.0

**Comment by jet47** [comment]
Make sure that OpenCV was built for your compute capabilty (`CUDA_ARCH_BIN` CMake flag). It not, CUDA might launch JIT compilation from PTX, which may take a long time.

**Comment by jet47** [comment]
Just use `-DCUDA_ARCH_BIN=5.0` and `-DCUDA_ARCH_PTX=""` to build OpenCV for your card architecture.

**Comment by alarconj** [comment]
Before I saw the last two posts I compiled OpenCV with `-DCUDA_ARCH_BIN=5.0` and `-DCUDA_ARCH_PTX="5.0"`, and this solved the problem. I guess I need to read more about JIT compilation, to understand what's going one here.
