### ISSUE TITLE
findcountours() application has stopped working .

### ISSUE THREAD

**Issue by zadannu** [Itseez/opencv#5530]
Hi,im using opencv 3.0 and i am using Visual Studio 2013 .Every time i call findcontours() my application crashes.I need some help if someone know what is happening .

Update: Other functions work fine but findcontours crash my aplication.

**Comment by mshabunin** [comment]
@zadannu, please provide minimal code example reproducing the crash. Try to build latest master branch OpenCV version ant test your application with it.

**Comment by StevenPuttemans** [comment]
I suggest moving this to http://answers.opencv.org/questions. The community will help you debug the problem, since the actual functions are working perfectly fine here.
