### ISSUE TITLE
python calls to fisheye calibration fail with exception (matrix dimension errors)

### ISSUE THREAD

**Issue by Algomorph** [Itseez/opencv#5534]
The following call succeeds in python:
```python
err1, K1, d1, rvecs, tvecs = cv2.calibrateCamera(objpoints, limgpoints, 
                                                       frame_dims, identity, blank, flags=flags,criteria = criteria)
```
The following call with identical objpoints and limgpoints parameters fails:
```python
err, K1, d1, tvecs, rvecs = cv2.fisheye.calibrate(objectPoints = objpoints, imagePoints = limgpoints, 
                                                          image_size = frame_dims, K=identity, D=blank2)
```
Firstly, objpoints has to be resized in python from ```(<num points in set>,3)``` to ```(<num points in set>, 1, 3)``` to pass the objectPoints.type() == CV_64FC3 check. That is not a bug but rather something counter-intuitive for the python wrapper specifically (this doesn't have to be done for the cv2.calibrateCamera, so current online examples don't do this).

Secondly, after the type of object points is correct, the follwing exception gets thrown:
```
cv2.error: ..../opencv/modules/core/src/matmul.cpp:900: error: (-215) a_size.width == len in function gemm
```
I have determined it occurs on (current) line 1337 in fisheye.cpp ```cv::internal::InitExtrinsics```. Relevant excerpt:
```C++
calcCovarMatrix(objectPoints, covObjectPoints, objectPointsMean, COVAR_NORMAL | COVAR_COLS);

Mat T = -R * objectPointsMean; //assertion failed here due to wrong dimensions of objectPointsMean
```

**Comment by Algomorph** [comment]
Transposing both object and image points to shapes (1, <num points in set> , 3) and (1, <num points in set> , 2), respectively, seems like a workaround for the above issue.
However, another bug manifests after this within this code segment:
```C++
    if (!rvecs.empty() && rvecs.kind()==_InputArray::STD_VECTOR_MAT)
    {
        int i;
        for( i = 0; i < (int)objectPoints.total(); i++ )
        {
            rvecs.getMat(i)=omc[i];
            tvecs.getMat(i)=Tc[i];
        }
    }
```
rvecs and tvecs at this point are empty, hence call to getMat(i) result in assertion failures.

**Comment by soupault** [comment]
Any news on the topic?

**Comment by christomaszewski** [comment]
I was able to get the fisheye calibration to work by applying the transformation Algomorph suggested and then initializing rvecs and tvecs to zero lists before the call to calibrate. There's a nice little wrapper that takes care of all this for you here: https://bitbucket.org/amitibo/pyfisheye
Props to the author!

**Comment by Algomorph** [comment]
Thanks for the workaround, @christomaszewski!

I think there's still some issue here that needs to be fixed within OpenCV... It should parallel the functionality of the "general" rational functions. Even there, currently, there are things that you need to initialize with 0 or identity from within python to get it to work, which shouldn't be the case.

I would also like to call into question the necessity of a whole separate fisheye namespace / submodule with functions that nearly mirror the general calib module functions. Why not make it just a flag to calibrate, stereoCalibrate, etc.? That's how we're switching between the older, 5-coefficient model and the newer rational model, isn't it? Why not follow the same structure? If we need to break up the code a little, that can be done in a more behind-the-scenes way. From a user's perspective, it just makes more sense to me to have a single set of functions. If anyone else this is worth to bring up for a discussion, I'll post it as a separate issue.

**Comment by kamrausch** [comment]
Has anybody figured out the formatting of the arrays (object points, and image points 1 and 2) for fisheye stereo calibrate? I am running into the same types of errors?

**Comment by philipptrenz** [comment]
@kamrausch Me too, see #11085
Did you find a workaround?

**Comment by bill2239** [comment]
did this resolve?
