### ISSUE TITLE
OpenCV 3.0.0 “configure” fails - ffmpeg download error

### ISSUE THREAD

**Issue by BenBenJones** [Itseez/opencv#5546]
Hi,

could you look into this issue? I posted it on stackoverflow, but received no helpful solutions...

http://stackoverflow.com/questions/32932915/opencv-3-0-0-configure-fails-ffmpeg-not-downloaded

best,
Ben

**Comment by alalek** [comment]
Actual problem is somewhere here: `Status=1;"unsupported protocol"`, what usually mean network issues.

There are some workarounds in case of network issues:
- disable FFMPEG (`cmake -DWITH_FFMPEG=OFF ...`), but OpenCV video/camera will not work in this case;
- manually download 3 files (opencv_ffmpeg.dll, opencv_ffmpeg_64.dll, ffmpeg_version.cmake) and put them into `3rdparty/ffmpeg`.
    - from [here](https://github.com/Itseez/opencv_3rdparty/tree/ffmpeg/master_20150703/ffmpeg) in RAW format
    - or from the link from SO answer (but link should include **commit** hash [8aeefc4efe3215de89d8c7e114ae6f7a6091b8eb](https://raw.githubusercontent.com/Itseez/opencv_3rdparty/8aeefc4efe3215de89d8c7e114ae6f7a6091b8eb/ffmpeg/opencv_ffmpeg.dll) instead of file hash)

**Comment by BenBenJones** [comment]
Is there a way to get a clue on what the network issues are?

**Comment by alalek** [comment]
You can try to use verbose mode of `curl` utility (this should be similar to CMake network requests in the most cases):
```
curl -v --request GET https://raw.githubusercontent.com/Itseez/opencv_3rdparty/8aeefc4efe3215de89d8c7e114ae6f7a6091b8eb/ffmpeg/ffmpeg_version.cmake
```

**Comment by FeanorLobelia** [comment]
I've been having this problem. I would guess that everybody on Windows trying to build OpenCV has.

Thanks for the links above! However, even when the ffmpeg dlls are downloaded CMake ignores them and tries to create its own download folder and the MD5 sum promptly fails, causing an error.

Not sure what the network issues are.

**Comment by alalek** [comment]
> MD5 sum promptly

Possible reasons of this is contents of file is "Forbidden"/"Not found" errors or  there is truncated data or empty file.

You may put "return()" statement before this code block to bypass any downloads (be sure that files are valid and available):
https://github.com/Itseez/opencv/blob/02c48ab7d698092239b90aaebc280812d9cdf618/cmake/OpenCVUtils.cmake#L849-L852

**Comment by FeanorLobelia** [comment]
Actually using the SO answer link with the commit hash worked for ffmpeg. Not sure why the RAW download didn't work.

Now I face the same problem with ippicv! It may be everything in the third party folder going awry. Not sure how to download ippicv from raw user git as in the SO answer for ffmpeg.

Excuse my lack of knowledge. I've never used Git properly so some of the technical stuff is going over my head.

**Comment by FeanorLobelia** [comment]
About putting in the "return()" statement, thanks. Will that affect all third party stuff?

**Comment by alalek** [comment]
At this moment only FFMPEG uses this download function (Windows only). IPPICV uses another implementation with archive unpacking.

**Comment by FeanorLobelia** [comment]
Right. But it's still the same error - 'unsupported protocol'?

**Comment by alalek** [comment]
What CMake version?

**Comment by FeanorLobelia** [comment]
It's 2.8.8. Is that the problem?

**Comment by BenBenJones** [comment]
I can donload the files using curl, but it does not work via chrome. Is there a reason for that?

**Comment by mshabunin** [comment]
Can it be caused by some antivirus restriction?

**Comment by alalek** [comment]
@FeanorLobelia Try to update CMake. We still use CMake 2.8.11 on some Windows slaves and it works fine. (One Linux machine uses Ubuntu 14.04 with CMake 2.8.7, but there is no FFMPEG download)

**Comment by rzr** [comment]
It looks like some cmake version are not supporting SSL and causing this issue. workaround is explained at : 

http://stackoverflow.com/questions/32749454/opencv-installation-error-ubuntu-14-04

**Comment by yirgagithub** [comment]
I was having the same problem i turn my extension off and turn off my anti-virus and it worked fine there was warning Local copy of opencv_ffmpeg.dll has invalid MD5 hash: but the 3 files downloaded successfully

**Comment by MiaoDX** [comment]
Note so sure, but I update cmake from 3.6.1 to 3.9.1 on my win 10, and the downloads are okay, (20170823).

**Comment by zakaria-chahboun** [comment]
## (OpenCV 3.2.0)

For Solve ***("CMake Error at cmake/OpenCVUtils.cmake:1043  (file): ... ")*** Error In Cmake
Follow This Steps:

[1] Go to:
"C:\\<b>[PATH_TO_YOUR_OPENCV]</b>\sources\3rdparty\ffmpeg\downloads"

[2] Add Three Folders :

	-First Folder Name (MD5): f081abd9d6ca7e425d340ce586f9c090
		put into : opencv_ffmpeg.dll

	-Second Folder Name (MD5): a423363a6eb76d362ca6c406c96c8db6
		put into : opencv_ffmpeg_64.dll 

	-Third Folder Name (MD5): 5346ae1854fc7aa569a722e85af480ec
		put into : ffmpeg_version.cmake

[3] Check if MD5 of dlls/files is correct ^^

-------- IMPORTANT --------
[!] ***With Other Version of OpenCV***, You Can Follow The Same Steps But With ***"Different" MD5 Hash***.
You Can Know The MD5 Hash Code For Each File In This Path:

[-1-] "C:\\<b>[PATH_TO_YOUR_OPENCV]</b>\sources\3rdparty\ffmpeg\ffmpeg.cmake"

Open it, And You Get *Informaions About All Things*.

-------- Manually Download --------
Go To *[-1-] Section*, And Find This Line :

***FFMPEG_BINARIES_COMMIT*** "2a19d0006415955c79431116e4634f04d5eb5a74"

And Get *MD5* For Your Version, For Example Here I'm Get *"2a19d0006415955c79431116e4634f04d5eb5a74"*.

Finally, Put This *MD5* In The Link Below, 
And Replace ***[MD5_CODE]*** With  Your MD5 Code ^^
Also Replace The Name Of *Each File* Of Required List To Download In <b><em>[FILE]</em></b>.

**`https://raw.githubusercontent.com/opencv/opencv_3rdparty/MD5_CODE]/ffmpeg/[FILE]`**

-------- Examples &#x1F49C;--------
*opencv_ffmpeg.dll:*

`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/opencv_ffmpeg.dll`

*opencv_ffmpeg_64.dll:*
`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/opencv_ffmpeg_64.dll`

*ffmpeg_version.cmake:*
`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/ffmpeg_version.cmake`

**Comment by alessandro-gentilini** [comment]
In my opinion, this issue is somewhat still relevant even with OpenCV 3.4.2.
My system has:
Windows 10
CMake 3.12.1

I downloaded OpenCV 3.4.2 and I tried to build it through cmake-gui.
After many minutes (in my opinion way too much minutes) I got this warning:

> FFMPEG: Download: opencv_ffmpeg.dll
> CMake Warning at cmake/OpenCVDownload.cmake:190 (message):
>   FFMPEG: Download failed: 28;"Timeout was reached"
> 
>   For details please refer to the download log file:
> 
>   C:/dev/opencv_build/CMakeDownloadLog.txt
> 
> Call Stack (most recent call first):
>   3rdparty/ffmpeg/ffmpeg.cmake:20 (ocv_download)
>   cmake/OpenCVFindLibsVideo.cmake:228 (download_win_ffmpeg)
>   CMakeLists.txt:633 (include)

and then the same for `opencv_ffmpeg_64.dll` and `ffmpeg.cmake`.
I followed the suggestion to refer to the log file `C:/dev/opencv_build/CMakeDownloadLog.txt` and I managed to fix by myself the issues: I manually downloaded the file and copied it to `.cache` folder.

As a final note: my very personal experience is that programmatically downloading a file from internet (`wget` or `cURL`) is very often very problematic in Windows behind a company firewall.

**Comment by mshabunin** [comment]
@alessandro-gentilini , please check the latest 3.4.3 release. We have added semi-manual fallback mechanism (#12124) - each failed download will be added to special script, e.g. `<build>/download_with_curl.sh` which can be modified if needed and executed manually. It will download and place all files to correct places. If you have Git for Windows, there is high probability that you also have Unix-compatible shell (git-shell) and curl tool. Unfortunately there is no special script for Windows (cmd or ps), but it is not too hard to add another variant - feel free to propose a PR.

**Comment by alessandro-gentilini** [comment]
@mshabunin It sounds very good! I'll give it a try! Thank you very much for your help.

**Comment by Meera-C** [comment]
To those who resolved this issue, I am using Cmake-gui 3.8.1 version (also tried 3.9 & 3.12) and Visual Studio 2017. I am getting the follwing error after 'Configure' button is pressed

```
CMake Warning at cmake/OpenCVDownload.cmake:193 (message):
  FFMPEG: Download failed: 5;"Couldn't resolve proxy name"

  For details please refer to the download log file:

  C:/OpenCV/CMakeDownloadLog.txt

Call Stack (most recent call first):
  3rdparty/ffmpeg/ffmpeg.cmake:20 (ocv_download)
  cmake/OpenCVFindLibsVideo.cmake:228 (download_win_ffmpeg)
  CMakeLists.txt:634 (include)


FFMPEG: Download: opencv_ffmpeg_64.dll
CMake Warning at cmake/OpenCVDownload.cmake:193 (message):
  FFMPEG: Download failed: 5;"Couldn't resolve proxy name"

  For details please refer to the download log file:

  C:/OpenCV/CMakeDownloadLog.txt

Call Stack (most recent call first):
  3rdparty/ffmpeg/ffmpeg.cmake:20 (ocv_download)
  cmake/OpenCVFindLibsVideo.cmake:228 (download_win_ffmpeg)
  CMakeLists.txt:634 (include)


FFMPEG: Download: ffmpeg_version.cmake
CMake Warning at cmake/OpenCVDownload.cmake:193 (message):
  FFMPEG: Download failed: 5;"Couldn't resolve proxy name"

  For details please refer to the download log file:

  C:/OpenCV/CMakeDownloadLog.txt

Call Stack (most recent call first):
  3rdparty/ffmpeg/ffmpeg.cmake:20 (ocv_download)
  cmake/OpenCVFindLibsVideo.cmake:228 (download_win_ffmpeg)
  CMakeLists.txt:634 (include)

IPPICV: Download: ippicv_2017u3_win_intel64_general_20180518.zip
CMake Warning at cmake/OpenCVDownload.cmake:193 (message):
  IPPICV: Download failed: 5;"Couldn't resolve proxy name"

  For details please refer to the download log file:

  C:/OpenCV/CMakeDownloadLog.txt

Call Stack (most recent call first):
  3rdparty/ippicv/ippicv.cmake:42 (ocv_download)
  cmake/OpenCVFindIPP.cmake:243 (download_ippicv)
  cmake/OpenCVFindLibsPerf.cmake:19 (include)
  CMakeLists.txt:635 (include)

```
I am attaching the 'C:/OpenCV/CMakeDownloadLog.txt' file.

Can some one please tell me what I have to do to resolve this. Where to manually download the files and place in which location?

[CMakeDownloadLog.txt](https://github.com/opencv/opencv/files/2383024/CMakeDownloadLog.txt)

**Comment by mshabunin** [comment]
@Meera-C , check `#cmake_download` lines in the log, they contains destination file name and resource URL.

**Comment by Meera-C** [comment]
```
#do_copy "opencv_ffmpeg_64.dll" "dc9c50e7b05482acc25d6ce0ac61bf1d" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll" "C:/OpenCV/3rdparty/ffmpeg"
#missing "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg_64.dll"
#cmake_download "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/dc9c50e7b05482acc25d6ce0ac61bf1d-opencv_ffmpeg_64.dll" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll"
# timeout on name lookup is not supported
# Curl_ipv4_resolve_r failed for proxy_emea.rsint.net
# Couldn't resolve proxy 'proxy_emea.rsint.net'
# Closing connection 0
```

In the above section, I have to download this 'https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll'  and place it in 'C:/OpenCV/3rdparty/ffmpeg'? Is that correct?

**Comment by Meera-C** [comment]
I downlaoded the files and still I am getting these errors

```
#use_cache "C:/Downloads/OPENCV/opencv-master/.cache"
#do_copy "opencv_ffmpeg.dll" "b8120c07962d591e2e9071a1bf566fd0" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll" "C:/OpenCV/3rdparty/ffmpeg"
#check_md5 "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg.dll"
#match_md5 "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg.dll" "b8120c07962d591e2e9071a1bf566fd0"
#do_copy "opencv_ffmpeg_64.dll" "dc9c50e7b05482acc25d6ce0ac61bf1d" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll" "C:/OpenCV/3rdparty/ffmpeg"
#check_md5 "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg_64.dll"
#match_md5 "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg_64.dll" "dc9c50e7b05482acc25d6ce0ac61bf1d"
#do_copy "ffmpeg_version.cmake" "3b90f67f4b429e77d3da36698cef700c" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/ffmpeg_version.cmake" "C:/OpenCV/3rdparty/ffmpeg"
#check_md5 "C:/OpenCV/3rdparty/ffmpeg/ffmpeg_version.cmake"
#mismatch_md5 "C:/OpenCV/3rdparty/ffmpeg/ffmpeg_version.cmake" "50a460534a0b8f70df9383f3e7fbe422"
#check_md5 "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/3b90f67f4b429e77d3da36698cef700c-ffmpeg_version.cmake"
#mismatch_md5 "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/3b90f67f4b429e77d3da36698cef700c-ffmpeg_version.cmake" "d41d8cd98f00b204e9800998ecf8427e"
#delete "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/3b90f67f4b429e77d3da36698cef700c-ffmpeg_version.cmake"
#cmake_download "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/3b90f67f4b429e77d3da36698cef700c-ffmpeg_version.cmake" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/ffmpeg_version.cmake"
# timeout on name lookup is not supported
# Curl_ipv4_resolve_r failed for 
# Couldn't resolve proxy '
# Closing connection 0
# 

#do_unpack "ippicv_2017u3_win_intel64_general_20180518.zip" "915ff92958089ede8ea532d3c4fe7187" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/bdb7bb85f34a8cb0d35e40a81f58da431aa1557a/ippicv/ippicv_2017u3_win_intel64_general_20180518.zip" "C:/OpenCV/3rdparty/ippicv"
#check_md5 "C:/Downloads/OPENCV/opencv-master/.cache/ippicv/915ff92958089ede8ea532d3c4fe7187-ippicv_2017u3_win_intel64_general_20180518.zip"
#mismatch_md5 "C:/Downloads/OPENCV/opencv-master/.cache/ippicv/915ff92958089ede8ea532d3c4fe7187-ippicv_2017u3_win_intel64_general_20180518.zip" "d41d8cd98f00b204e9800998ecf8427e"
#delete "C:/Downloads/OPENCV/opencv-master/.cache/ippicv/915ff92958089ede8ea532d3c4fe7187-ippicv_2017u3_win_intel64_general_20180518.zip"
#cmake_download "C:/Downloads/OPENCV/opencv-master/.cache/ippicv/915ff92958089ede8ea532d3c4fe7187-ippicv_2017u3_win_intel64_general_20180518.zip" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/bdb7bb85f34a8cb0d35e40a81f58da431aa1557a/ippicv/ippicv_2017u3_win_intel64_general_20180518.zip"
# timeout on name lookup is not supported
# Curl_ipv4_resolve_r failed for 
# Couldn't resolve proxy 
# Closing connection 0
# 

```
I have already dowloaded and placed the 'ffmpeg_version.cmake' and 'opencv_ffmpeg_64.dll' to the specified location from the url 'https://raw.githubusercontent.com/.....'

**Comment by mshabunin** [comment]
>In the above section, I have to download this 'https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll' and place it in 'C:/OpenCV/3rdparty/ffmpeg'? Is that correct?

No, you have to place it here: `C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/dc9c50e7b05482acc25d6ce0ac61bf1d-opencv_ffmpeg_64.dll`

**Comment by Meera-C** [comment]
I placed the 'opencv_ffmpeg.dll' from `"https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll"`  
in 
`C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/`

and deleted the 'dc9c50e7b05482acc25d6ce0ac61bf1d-opencv_ffmpeg_64.dll' which was already there. But, I am still getting the below error:

```
#use_cache "C:/Downloads/OPENCV/opencv-master/.cache"
#do_copy "opencv_ffmpeg.dll" "b8120c07962d591e2e9071a1bf566fd0" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll" "C:/OpenCV/3rdparty/ffmpeg"
#missing "C:/OpenCV/3rdparty/ffmpeg/opencv_ffmpeg.dll"
#cmake_download "C:/Downloads/OPENCV/opencv-master/.cache/ffmpeg/b8120c07962d591e2e9071a1bf566fd0-opencv_ffmpeg.dll" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll"
# timeout on name lookup is not supported
```
What am I doing wrong here?

**Comment by mshabunin** [comment]
@Meera-C , the file should be named exactly as written in the log: `dc9c50e7b05482acc25d6ce0ac61bf1d-opencv_ffmpeg_64.dll`. And you have to perform this operation it for all `#cmake_download` lines.

Please, ask a question on the [forum](answers.opencv.org), it is more appropriate place for troubleshooting.
