### ISSUE TITLE
findHomography leaves mask untouched in case of no inliers

### ISSUE THREAD

**Issue by PhilLab** [Itseez/opencv#5551]
The inlier mask is left untouched in case of no solution: [fundam.cpp#L411](https://github.com/Itseez/opencv/blob/0688bb61ed33d66d6e0a736b75824eafa40d4f78/modules/calib3d/src/fundam.cpp#L411)

This means that
* if we use an already populated mask as parameter (and this is allowed since the input values are completely ignored), the resulting mask stays the same which leads to the wrong conclusion
* if we pass an empty mask and afterwards want to check for each provided point if it was an inlier, we get an index-out-of-bounds exception.

The latter problem even happens in official OpenCV code: [global_motion.cpp#L506-L508](https://github.com/Itseez/opencv/blob/0688bb61ed33d66d6e0a736b75824eafa40d4f78/modules/videostab/src/global_motion.cpp#L506-L508).

I propose to change the function so that the mask is always set to the appropriate size (and zeroed if needed). Is this feasible?

**Comment by aman11dhanpat** [comment]
I'll pick this task if needed.
@Admin, can you mark this as bug?
