### ISSUE TITLE
Color image slicing in opencv 

### ISSUE THREAD

**Issue by Shashika007** [Itseez/opencv#5573]
I have tried to understood about color image slicing using by opencv. but i cound not get good results out of that. please, any one can help me to do color image slicing to identify and colour object different from background

**Comment by mshabunin** [comment]
@Shashika007, it is better to ask questions on forum: https://answers.opencv.org

**Comment by Shashika007** [comment]
@mshabunin . thanks !

**Comment by StevenPuttemans** [comment]
@mshabunin This can be closed down :)
