### ISSUE TITLE
Runtime error with bumblebee optirun dynamicuda opencv-2.4.11

### ISSUE THREAD

**Issue by Ingeborg87** [Itseez/opencv#5576]
Hi,

this is related to 

https://github.com/Itseez/opencv/issues/5557

I have installed their succesfully opencv-2.4.11 on OpenSUSE 13.2 on an optimus Laptop. I can compile programs successfully with Cuda 7.5 on a cuda 5.0 capable device. I need to run compiled programs with

optimus programname

Nevertheless i have  always to run Qt compiled programs outside of Qt with optirun to test but it won't even work. It throws out this runtimeerror ever and ever again with and without Qt.

OpenCV Error: No GPU support (The library is compiled without CUDA support) in mallocPitch, file /home/abuild/rpmbuild/BUILD/opencv-2.4.9/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp, line 126
Error: /home/abuild/rpmbuild/BUILD/opencv-2.4.9/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp:126: error: (-216) The library is compiled without CUDA support in function mallocPitch

Running programs without optirun returns me this error.

OpenCV Error: Gpu API call (no CUDA-capable device is detected) in mallocPitch, file /home/peter/programs/opencv-2.4.11/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp, line 1134
Error: /home/peter/programs/opencv-2.4.11/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp:1134: error: (-217) no CUDA-capable device is detected in function mallocPitch

There it points to 2.4.11 subdirectories.

The second thing i want to figure out is that it runs with 
primusrun program
but just with less performance..

This cuda related issues will kill me anytimes.

Thx Peter

**Comment by StevenPuttemans** [comment]
Why open up a new issue for completely the same problem?

**Comment by Ingeborg87** [comment]
It is a different problem and it is solved. This was a runtime error. The other one has had problems with the compilation especially the separated compilation. This here could be easely handled if you take a look whether not other older opencv libs are already installed. After deinstall and block the rpm package it works.
