### ISSUE TITLE
include\opencv2\core\mat.inl.hpp|666|undefined reference to `__atomic_fetch_add_4'|

### ISSUE THREAD

**Issue by Maple-Wang** [Itseez/opencv#5581]
||=== Build: Debug in wangfengtest (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `ZN2cv3Mat7releaseEv':|
D:\install\install\include\opencv2\core\mat.inl.hpp|666|undefined reference to `__atomic_fetch_add_4'|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by StevenPuttemans** [comment]
This is no bug, you are using prebuilt release libraries and you are your trying to run your application in debug mode. That won't work. If you want debug libraries, you need to built OpenCV yourself and use those.

**Comment by Maple-Wang** [comment]
I used OpenCV built by myself and use the default build method ，both debug and release can run on
the default mode.

**Comment by StevenPuttemans** [comment]
But still, you can then mismatch your includes with your build option, exactly what happens here. Be sure to include either the release or the debug libs to your project and not both!
