### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by larsmob** [Itseez/opencv#5593]
Windows 8.1, x64.
Extracted the prebuilt opencv3.0.0 found on your website and set up the paths. Installed numpy and opencv for Python3.5 from Cristoph Gohlke's WHLs.
On import cv2 it fails with "ImportError: DLL load failed [...]". Using Dependency Walker on the .pyd I found that several DLLs, MSVCP140.dll etc, were missing.
Installed the VC++ redistributable for VS2015 and the import works.

**Comment by alalek** [comment]
> Installed the VC++ redistributable
We prefer not to include this into OpenCV package.

**Comment by larsmob** [comment]
That's ok. The documentation should maybe mention this prerequisite.
