### ISSUE TITLE
Bug in solvePoly(): can't find roots of -x^2 + x^4 == 0 in OpenCV 2.4.9

### ISSUE THREAD

**Issue by egrossmann** [Itseez/opencv#5599]
Roots should be -1, +1 and 0 (double root).

Tested with something like:

  cv::Mat coeffsM (1, degree+1, CV_64FC1);
  coeffsM.at<double>(0,0) = 0;
  coeffsM.at<double>(0,1) = 0;
  coeffsM.at<double>(0,2) = -1;
  coeffsM.at<double>(0,3) = 0;
  coeffsM.at<double>(0,4) = 1;
  cv::Mat roots;
  double x = cv::solvePoly (coeffsM, roots);
  //  No roots!

Please let me know if you need more information.

I saw other odd behavior (but didn't document it, sorry).

  Thanks for providing OpenCV.

  Cheers,

  Etienne

From version.h:
#define CV_VERSION_EPOCH    2
#define CV_VERSION_MAJOR    4
#define CV_VERSION_MINOR    9
#define CV_VERSION_REVISION 0

**Comment by hoangviet1985** [comment]
I am working on the issue. Thanks for your report.

**Comment by Dikay900** [comment]
can be closed #5651 and #5605 was merged
