### ISSUE TITLE
Why "make" can't find libs???

### ISSUE THREAD

**Issue by happycharleswang** [Itseez/opencv#5606]
I am trying to build opencv on Ubuntu 14, and it stops at the java module.
it seems the make system can not find libs in /usr/lib
I have : 
/usr/lib/libtesseract.so
/usr/lib/liblept.so
But "make" just can't find them?!
What should I do? Thanks！

```
[ 78%] Building OpenCV Android library project
   [subant] No sub-builds to iterate on
BUILD SUCCESSFUL
Total time: 3 seconds
[ 78%] Linking CXX shared library ../../lib/armeabi-v7a/libopencv_java3.so
/home/charles/Programs/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ltesseract
/home/charles/Programs/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llept
```

**Comment by mshabunin** [comment]
@happycharleswang , please provide your cmake command and its output (as GitHub gist for example).

**Comment by happycharleswang** [comment]
I was building opencv4android on ubuntu, following this http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk

 The command I used is:
cd build_android_arm
cmake -DOPENCV_EXTRA_MODULES_PATH=/home/charles/Programs/opencv-3.0.0/opencv_contrib-3.0.0/modules -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_TOOLCHAIN_FILE=../android/android.toolchain.cmake $@ ../..

**Comment by happycharleswang** [comment]
more detailed outputs:




[ 90%] Built target opencv_perf_stitching
   [subant] No sub-builds to iterate on

BUILD SUCCESSFUL
Total time: 11 seconds
Scanning dependencies of target opencv_java
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/jni_part.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/utils.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/Mat.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/converters.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/__/core/misc/java/src/cpp/core_manual.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/__/features2d/misc/java/src/cpp/features2d_converters.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/core.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/imgproc.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/ml.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/photo.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/video.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/imgcodecs.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/videoio.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/objdetect.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/bioinspired.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/features2d.cpp.o
[ 90%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/calib3d.cpp.o
[ 90%] Linking CXX shared library ../../lib/armeabi-v7a/libopencv_java3.so
/home/charles/Programs/android-ndk/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ltesseract
/home/charles/Programs/android-ndk/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llept

**Comment by alalek** [comment]
@happycharleswang CMake output is log like this: http://pullrequest.opencv.org/buildbot/builders/precommit_android/builds/4481/steps/cmake/logs/stdio

Do you try to build from scratch (clean build directory)?

**Comment by happycharleswang** [comment]
CMake outputs file is here:
https://gist.github.com/happycharleswang/af716bc2db7475e2cb93

On line 194,     it shows Tesseract library is not found:
-- Tesseract:   NO

The cmake file (opencv_contrib/modules/text/FindTesseract.cmake) used to find Tesseract library is located in the  text module, its content:

# Tesseract OCR
unset(Tesseract_FOUND)
find_path(Tesseract_INCLUDE_DIR tesseract/baseapi.h
  HINTS
  /usr/include
  /usr/local/include)
find_library(Tesseract_LIBRARY NAMES tesseract
  HINTS
  /usr/lib
  /usr/local/lib)
find_library(Lept_LIBRARY NAMES lept
  HINTS
  /usr/lib
  /usr/local/lib)
set(Tesseract_LIBS ${Tesseract_LIBRARY} ${Lept_LIBRARY})
if(Tesseract_LIBS AND Tesseract_INCLUDE_DIR)
    set(Tesseract_FOUND 1)
endif()


It seems the above commands can not find anything. 
Tesseract_INCLUDE_DIR-NOTFOUND
Tesseract_LIBRARY-NOTFOUND
Lept_LIBRARY-NOTFOUND

however these libraries are indeed located at 
/usr/lib/libtesseract.so
/usr/lib/liblept.so
usr/include/tesseract

**Comment by happycharleswang** [comment]
To find out why opencv_contrib/modules/text/FindTesseract.cmake is not working, I made a simple test.
The content of CMakeLists.txt is:
include("FindTesseract.cmake")

And this works, it find tesseract successfully.

So, why a solo FindTesseract.cmake can find the lib files, and why it can't when it is invoked by in a tool chain (android.toolchain.cmake)?

**Comment by alalek** [comment]
These libraries in `/usr/lib` is for Ubuntu (your "host" system) only. They are unusable for Android ("target") build, so you don't have usable libraries for Android.
Case `host system != target system` is called cross-compilation and you should check this case exactly instead the simple `include("FindTesseract.cmake")` (you may check `CMAKE_CROSSCOMPILING` variable description [here](http://www.vtk.org/Wiki/CMake_Cross_Compiling)).

Does compilation work with `-DBUILD_opencv_text=OFF` additional CMake parameter?

You you need full functional text module, then you should find instructions how to build and run tesseract for Android (unfortunately I have no such experience). In general, after tesseract/llept build you should pass libraries and includes via CMake parameters (`-DTesseract_LIBRARY=/android/path/libtesseract.a -D...`).
BTW, static build is preferable for tesseract or you will have are problem how to install and load `libtesseract.so` on Android.

**Comment by happycharleswang** [comment]
thanks a lot @alalek ,  buid with -DBUILD_opencv_text=OFF works. 
However text module is what I need.
You are right, I'll go check tesseract lib for android.
