### ISSUE TITLE
split of a multidimensional matrix not working as in 2.4

### ISSUE THREAD

**Issue by SamDehaeck** [Itseez/opencv#5624]
Hello,

I have a 22x1024x1024 matrix with complex numbers (=> 2Channels). When I perform the splitting function in Opencv 2.4, I get a vector of 2 matrices with 22x1024x1024 elements as expected. When doing the same split in Opencv 3.0, I get 2 matrices of 22x1024 elements with dims =2. Converting the matrix to a 2D matrix with 22x1048576 first and then splitting does give a good result in Opencv 3.0.

Best regards,
Sam.

**Comment by hoangviet1985** [comment]
I just tested. I did not see the issue as you said. Are you sure the issues still exists?

**Comment by amroamroamro** [comment]
I have reported a similar issue before #5034.

There's an example attached you can run to see that `cv::split` is broken for ND-arrays.

**Comment by hoangviet1985** [comment]
I see that there are 2 versions of "split". The one with output "Mat*" is working well. The other has failed like you said.

**Comment by SamDehaeck** [comment]
Thank you very much for your fast response and fix.

**Comment by amroamroamro** [comment]
@hoangviet1985 I just tried it in 3.1.0 and it is working fine. Thanks :+1:
