### ISSUE TITLE
cv2.calcHist interprets image channel differently

### ISSUE THREAD

**Issue by Lautian** [Itseez/opencv#5625]
When I use (python binding) cv2.calcHist on a 3D matrix Img representing an image, calcHist interprets the first dimension as the channel dimension. 
I.e. calcHist used on channels [0] of a (5 x 4 x 3) matrix gives a histogram with a total of 12 counts instead of 20. Inspecting the histogram confirms that calcHist takes slice Img[0 , : , :] to calculate the histogram, where I would expect Img[: , : , 0]. When reading an image Img = cv2.imread(imgfile), the channel information is in the third dim: Img.shape = (400, 600, 3), and depicting Img[: , : , 0] shows it contains one channel of pixels. So it is not an issue of how cv2 expects a multi-channel image to be stored. 
Currently, if you simply use cv2.calcHist(img, channels = [0], ...), you get a histogram of the first row over all columns and channels, which is not what you would expect from the documentation.

cv2.calcHist: 
```python
cv2.calcHist(images, channels, mask, histSize, ranges[, hist[, accumulate]]) → hist
```
Code used for testing:

```python
imgname = '/home/beheerder/imgs/img1.jpg'
cvimg = cv2.imread(imgname)
cvimg.dtype
# =>
# dtype('uint8')
cvimg.shape
# =>
# (600, 600, 3)
testim = np.zeros((5, 4, 3), dtype = np.uint8)
testim[:1, :, 0] = 40
testim[:1, :1, 1] = 80
testim[0, :, :]
# =>
# array([[40, 80,  0],
#        [40,  0,  0],
#        [40,  0,  0],
#        [40,  0,  0]], dtype=uint8)
testim[:, :, 0]
# =>
# array([[40, 40, 40, 40],
#        [ 0,  0,  0,  0],
#        [ 0,  0,  0,  0],
#        [ 0,  0,  0,  0],
#        [ 0,  0,  0,  0]], dtype=uint8)

hist = cv2.calcHist(testim, [0], None, [2], [0, 100])
hist
# => 
#array([[ 11.],
#       [  1.]], dtype=float32)
# Fits with making a two-bin histogram of the slice testim[0, :, :],
# not the slice testim[:, :, 0]
histim = cv2.calcHist(cvimg, [0, 1], None, [2, 2], [0, 256, 0, 256])
np.sum(histim)
# => 1800.0
```

**Comment by mshabunin** [comment]
@Lautian , please note that calcHist accepts a list of images, try to call it like this:
```.py
hist = cv2.calcHist([testim], [0], None, [2], [0, 100])
```
You can find some additional information in [the tutorial](http://docs.opencv.org/master/d1/db7/tutorial_py_histogram_begins.html).

**Comment by Lautian** [comment]
That's the problem. The image was silently interpreted as a list of 2D slices, from each of which the first channel (column) is taken, giving the same histogram as for a slice testim[0 , : , :]
