### ISSUE TITLE
way to use in iPhone and iPad App

### ISSUE THREAD

**Issue by AtulPrakash007** [Itseez/opencv#5627]
I am newbie in the field of computer vision. I have gone through a lot of documentation and OpenCV docs. I tried to understand the algorithms also , even I also applied the FAST, SURF, SIFT, ORB and others for detecting key-points and descriptors and for match with the Image applied the BruteForce, FLANN (using Knnmatch also). They all are working fine for a single Image or a group of 10 Images. In the terms of iOS I stored the Images key-points and descriptors using the FIleManager in .yml format. and Later on fetch by using loop of number of count of Images to match one by one. When I tried to match with a 100 Images , it is taking approx 10 seconds to move through the whole loop. 

can it possible to use this architecture for matching Image. I am working on scenario where I have 1000 of Images and then when I will take a picture from camera , it will go through the whole Image and return the best identical Image.

**Comment by mshabunin** [comment]
@AtulPrakash007 , such questions better be asked on the users forum: http://answers.opencv.org

**Comment by AtulPrakash007** [comment]
I am agree with your concern. Actually I have seen the code of yours containing the file name matching_to_many_images.cpp . That's why I asked this question. So if you will help me in this concern , I am very thankful to you.
