### ISSUE TITLE
Fix of Bug #1784 causes erroneous checkIntegerRange() return

### ISSUE THREAD

**Issue by nilocFluid** [Itseez/opencv#5636]
In mathfuncs.cpp, checkIntegerRange() is maxVal inclusive, but the change to checkRange() for bug [#1784] (http://code.opencv.org/issues/1784) causes checkIntegerRange() to act maxVal exclusive :

    // see "Bug #1784
    int minVali = minVal<(-INT_MAX - 1) ? (-INT_MAX - 1) : cvFloor(minVal);
    int maxVali = maxVal>INT_MAX ? INT_MAX : cvCeil(maxVal) - 1; // checkIntegerRang() use inclusive maxVal

Subtracting 1 from cvCeil(maxVal) causes checkIntegerRange() to return false if a value is equivalent to maxVal.

**Comment by alalek** [comment]
@vpisarev Is this test valid?
https://github.com/Itseez/opencv/blob/d19897b734aab68d19d784f53836b48ed6098a34/modules/core/test/test_math.cpp#L2533-L2534

**Comment by alalek** [comment]
Well, test is valid, because maxVal is "exclusive" (see docs):

> maxVal - **exclusive** upper boundary of valid values range
 
Also,

> return false if a value is equivalent to maxVal.

It is fine. Valid values are `[minVal; maxVal)`.

**Comment by nilocFluid** [comment]
but checkIntegerRange() is maxVal inclusive

**Comment by alalek** [comment]
Could you provide a testcase which fails? (like above, for example)

**Comment by nilocFluid** [comment]
Lets say we have an array of length 10 (10 rows) and depth < CV_32F called `samples`.

We want to create a TrainData object with :

    cv::ml::TrainData::create(InputArray samples, 
							int layout, 
							InputArray responses, 
							InputArray varIdx = noArray(), 
							InputArray 	sampleIdx = noArray(), 
							InputArray 	sampleWeights = noArray(), 
							InputArray 	varType = noArray() 
							)	

The above function calls `TrainDataImpl::setData()`, which passes `(samples.rows - 1)` as `maxVal` in it's call to checkRange :

    CV_Assert( (sampleIdx.checkVector(1, CV_32S, true) > 0 &&
                       checkRange(sampleIdx, true, 0, 0, nsamples-1)) ||
                       sampleIdx.checkVector(1, CV_8U, true) == nsamples );

So, `maxVal == 9` inside `checkRange()`.  Then `checkRange()` passes `(cvCeil(maxVal) - 1)` as `maxVal` to `checkIntegerRange()` : 
    
    if (depth < CV_32F)
    {
        // see "Bug #1784"
        int minVali = minVal<(-INT_MAX - 1) ? (-INT_MAX - 1) : cvFloor(minVal);
        int maxVali = maxVal>INT_MAX ? INT_MAX : cvCeil(maxVal) - 1; // checkIntegerRang() use inclusive maxVal

        (check_range_functions[depth])(src, badPt, minVali, maxVali, badValue);
    }

Now, `maxVal == 8` inside `checkIntegerRange()`.  If the array `sampleIdx` contains `9`, `checkRange()` will return false, which causes the assertion in `TrainDataImpl::setData()` to fail.

**Comment by alalek** [comment]
Documentation of `checkRange` says, that `maxVal` parameter is "**exclusive** upper boundary of valid values range".
So check for elements is (by definition from docs): "minVal <= element[i] < maxVal" (there are `<=` and `<`). So `checkRange({1,2,3,9,5,4}, true, NULL, 0, 9)` returns false because relation `elem[3] < maxVal` is failed. But `checkRange({1,2,3,9,5,4}, true, NULL, 0, 9+1)` or `checkRange({1,2,3,9,5,4}, true, NULL, 0, 9 + 0.1f)` return true as expected.

I believe for your task you can try to use `cv::inRange`.

**Comment by nilocFluid** [comment]
I see your point.  From the point of view of `checkRange` everything is behaving appropriately.  

However, if `checkRange` is behaving appropriately, then `TrainDataImpl::setData()` isn't using `checkRange` appropriately.  In the case I illustrated above `9` is a valid index.  The range being checked should be [0,10), but because the `maxVal` parameter to `checkRange` is `nsamples - 1` the range being checked is [0,9), which is inappropriate.  

Should I change the title of this issue?

**Comment by alalek** [comment]
I believe, new ticket about ml code will be fine.

**Comment by alalek** [comment]
Problem in ML module has been fixed in #5783
