### ISSUE TITLE
Add build/ to .gitignore

### ISSUE THREAD

**Issue by comdiv** [Itseez/opencv#5637]
On windows it created by compiler and trys to sneak into commits

**Comment by ilya-lavrenov** [comment]
It's wrong. Just don't build in source tree.

**Comment by comdiv** [comment]
ok will keep my .gitignore as temporal

**Comment by alalek** [comment]
http://stackoverflow.com/questions/7335420/global-git-ignore

**Comment by comdiv** [comment]
Oh it's just my local fail to keep build path in checkout directory. Much simpler to fix it with Assume Not Modified mark on local .gitignore and keep it in mind rather than globalize fail.
