### ISSUE TITLE
issue with imencode in python

### ISSUE THREAD

**Issue by wangyongliang** [Itseez/opencv#5647]
opencv 2.4， python 2.7
#data is numpy ndarray
data = cv2.imencode("jpeg", data)

this code throw exception:
OpenCV Error: Unspecified error (could not find encoder for the specified extension) in imencode, file /home/wangyongliang/opencv-2.4.7/modules/highgui/src/loadsave.cpp, line 415
/home/wangyongliang/opencv-2.4.7/modules/highgui/src/loadsave.cpp:415: error: (-2) could not find encoder for the specified extension in function imencode

but imwrite is ok:
cv2.imwrite("test.jpg", text)

**Comment by ramanraja** [comment]
I also face the same issue. Not sure why this question has been labeled as invalid and closed.

**Comment by acust** [comment]
@ramanraja 
There are two things wrong with this issue

1. `cv2.imwrite()` returns a tuple, the above code would not even put the encoded image data into the 'data' value
2. `jpeg` is an invalid parameter for `cv2.imwrite()`, doing `retval, data = cv2.imencode(".jpg", data)` would be the correct way

**Comment by fredguth** [comment]
I just want to leave a comment here that despite this issue being closed, the  documentation (https://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html) is causing this confusion.

So:
img = cv2.imread('myfile.jpg',cv2.IMREAD_COLOR)
pngimg = cv2.imencode('.png', img)
jpgimg =  cv2.imencode('.jpg', img)
bmpimg = cv2.imencode('.bmp', img)
etc...
