### ISSUE TITLE
VideoWriter generates vertically flipped video with the MSMF backend on Windows 7, 64bit

### ISSUE THREAD

**Issue by mbarann** [Itseez/opencv#5648]
The cv::VideoWriter() on Windows 7, 64bit, creates vertically flipped videos when using the Microsoft Media Foundation backend. We have used the H264 fourcc and mp4 container.

To verify that the problem is not in our code, we created the video also using the Video for Windows backend with the MSVC fourcc and avi container. The resulting video was not vertically flipped.

**Comment by mbarann** [comment]
Here is a patch that makes CvVideoWriter_MSMF::WriteFrame() copy the frames  in the correct order. The ARM case is unchanged, because we could not test it. But it has probably the same problem.

Index: cap_msmf.cpp
===================================================================
--- cap_msmf.cpp	(revision 5490)
+++ cap_msmf.cpp	(revision 5491)
@@ -4371,9 +4371,9 @@
 #else
         hr = MFCopyImage(
             pData,                      // Destination buffer.
-            cbWidth,                    // Destination stride.
-            (BYTE*)videoFrameBuffer,    // First row in source image.
-            cbWidth,                    // Source stride.
+            cbWidth,                   // Destination stride.
+            ((BYTE*)videoFrameBuffer) + (videoHeight-1)*cbWidth,    // First row in source image.
+            -cbWidth,                    // Source stride.
             cbWidth,                    // Image width in bytes.
             videoHeight                 // Image height in pixels.
             );

**Comment by StevenPuttemans** [comment]
Are you up to supplying a PR with the suggested fix? Details on how to do so can be found [here](https://github.com/Itseez/opencv/wiki/How_to_contribute). Thanks in advance!

**Comment by mbarann** [comment]
I hope I have created the PR correctly.

**Comment by StevenPuttemans** [comment]
Thank you for the pull request. Keep an eye out at the following page: http://pullrequest.opencv.org/#/summary/ and see if any of the buildbots turn red. If so you will need to address any issues that arise.

**Comment by StevenPuttemans** [comment]
Since PR is being merged, you can close this down!
