### ISSUE TITLE
AKAZE detectAndCompute tries to convert from color to gray and gets exception.

### ISSUE THREAD

**Issue by MikeUnverferth** [Itseez/opencv#5656]
In akaze.cpp the detectAndCompute function is checking img.type() != CV_8UC1 and treating as color to convert to gray. It throws an exception if the input is 16-bit unsigned I believe this should be doing a different check, such as (img.channels() !=1) as 16U and 32F types are clearly supported based on the lines following.

**Comment by Dikay900** [comment]
can be closed, PR was merged
