### ISSUE TITLE
Error in cap_mjepg_decode.cpp

### ISSUE THREAD

**Issue by LaurentBerger** [Itseez/opencv#5668]
at line https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_mjpeg_decoder.cpp#L557
It should be m_height = avi_hdr.dwHeight ; instead of m_height = avi_hdr.dwWidth;

**Comment by PhilLab** [comment]
@LaurentBerger: thanks for reporting. this issue can be closed
