### ISSUE TITLE
v3.0 on linux: undefined reference to `cv::Mat::

### ISSUE THREAD

**Issue by n8bar** [Itseez/opencv#5683]
v3.0 on linux:  cameradatafeed.cpp:676: error: undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'

**Comment by StevenPuttemans** [comment]
You linker settings are probably incorrect. With problems like this, you will get helped much faster at http://answers.opencv.org/questions!

**Comment by mshabunin** [comment]
There is no `cameradatafeed.cpp` file in OpenCV 3.0.
