### ISSUE TITLE
recent opencv 3.0 dev on android , load opencv_java3.so crash

### ISSUE THREAD

**Issue by xylcbd** [Itseez/opencv#5684]
commit id : 8b554d3c2dffc5616b5099517386b4d722d82640

when executing <code>System.loadLibrary("opencv_java3");</code> , the tutorial4-opencl sample app crashed,

crash log:
<code>
11-20 10:11:39.628 18556-18593/org.opencv.samples.tutorial4 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 18593 (GLThread 457)
</code>

**Comment by xylcbd** [comment]
the android.mk

<code>
LOCAL_PATH := $(call my-dir)

# add OpenCV
include $(CLEAR_VARS)
OPENCV_INSTALL_MODULES:=on
#OPENCV_LIB_TYPE:=STATIC
ifdef OPENCV_ANDROID_SDK
  ifneq ("","$(wildcard $(OPENCV_ANDROID_SDK)/OpenCV.mk)")
    include ${OPENCV_ANDROID_SDK}/OpenCV.mk
  else
    include ${OPENCV_ANDROID_SDK}/sdk/native/jni/OpenCV.mk
  endif
else
  include ../../sdk/native/jni/OpenCV.mk
endif

ifndef OPENCL_SDK
  $(error Specify OPENCL_SDK to Android OpenCL SDK location)
endif

# add OpenCL
LOCAL_C_INCLUDES+= $(OPENCL_SDK)/include
LOCAL_LDLIBS 	+= -L$(OPENCL_SDK)/lib/$(TARGET_ARCH_ABI) -lOpenCL

LOCAL_MODULE    := JNIpart
LOCAL_SRC_FILES := jni.c CLprocessor.cpp
#LOCAL_CFLAGS 	+= -fopenmp
#LOCAL_LDFLAGS 	+= -fopenmp
LOCAL_LDLIBS    += -llog -lGLESv2 -lEGL
include $(BUILD_SHARED_LIBRARY)
</code>

**Comment by xylcbd** [comment]
I attempted to link with static lib , it throws link error ,

<code>
D:/opensource/opencv/build_mini/install/sdk/native/jni/../libs/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'GOMP_parallel'
</code>

**Comment by mshabunin** [comment]
Where do you get OpenCV android library? Do you build it yourself? What cmake parameters do you use?

**Comment by alalek** [comment]
Looks like it is not actual anymore
