### ISSUE TITLE
Doc: Possible discrepancy for cvtColor RGB2Luv 

### ISSUE THREAD

**Issue by PkLab** [Itseez/opencv#5689]
The [doc](http://docs.opencv.org/3.0.0/de/d25/imgproc_color_conversions.html) for cvtColor RGB ? CIE L*u*v*  doesn't look like the [code](https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/color.cpp#L5563)

The doc: `L = 116Y ^(1/3)`
The code: `L = 116Y''   -16`
may be should be clarified also:
```
[R'G'B']<-[spline interpolation]·[RGB]
[X'Y'Z']<-[CIED65 XYZ conversion matrix]·[R'G'B']
Y''<-[spline interpolation]·Y'
```
Spline interpolation operates some tricks on code but using the formula as is in the doc and comparing the 2 `L` you will have difference.

Test code
```cpp
	cv::Mat_<cv::Vec3f> bgr(1, 1, cv::Vec3f(0.7, 0.7, 0.8));
	cv::Mat_<cv::Vec3f> xyz(1, 1, cv::Vec3f(0.f, 0.f, 0.f));
	cv::Mat_<cv::Vec3f> luv(1, 1, cv::Vec3f(0.f, 0.f, 0.f));
	cv::Mat_<cv::Vec3f> lab(1, 1, cv::Vec3f(0.f, 0.f, 0.f));

	cv::cvtColor(bgr, xyz, CV_BGR2XYZ);
	cv::cvtColor(bgr, luv, CV_BGR2Luv);
	cv::cvtColor(bgr, lab, CV_BGR2Lab);

	clog << "BGR:\t" << bgr << endl;
	clog << "XYZ:\t" << xyz << endl;
	clog << "Luv:\t" << luv << endl;
	clog << "Lab:\t" << lab << endl;
	clog << endl;

	float Y, L;
	Y = xyz(0, 0)[1];
	L = 116.0 * pow(Y, 1 / 3.0);

	clog << "      L(Y):\t" << L << endl;
	clog << " L(Y) - 16:\t" << L - 16 << endl;
	L = luv(0, 0)[0];
	clog << "L from Luv:\t" << L << endl;
	L = lab(0, 0)[0];
	clog << "L from Lab:\t" << L << endl;
```
Output
```txt
BGR:	[0.69999999, 0.69999999, 0.80000001]
XYZ:	[0.70656455, 0.7212671, 0.76406127]
Luv:	[74.896202, 15.300271, 3.3003368]
Lab:	[74.896194, 9.1452894, 3.3699393]

      L(Y):	104.03  << as the doc for RGB2Luv
 L(Y) - 16:	88.0295 << as the doc for RGB2Lab
L from Luv:	74.8962
L from Lab:	74.8962
```

**Comment by h12345jack** [comment]
Wow,I met [the problem](http://answers.opencv.org/question/76503/may-i-ask-why-i-get-the-wrong-answer-about-rgb2luv/?answer=76549#post-id-76549) a few days ago. 
I use cv2.  mytest is  [199,187,187] ,
matlab:
```
function luvim = rgb2luv_im(im)

if size(im,3) ~= 3
    error('im must have three color channels');
end
if ~isa(im,'float')
    im = im2single(im);
end
if (max(im(:)) > 1)
    im = im./255;
end

XYZ = [.4125 .3576 .1804; .2125 .7154 .0721; .0193 .1192 .9502];
Yn = 1.0;
Lt = .008856;
Up = 0.19784977571475;
Vp = 0.46834507665248;
imsiz = size(im);
im = permute(im,[3 1 2]);
im = reshape(im,[3 prod(imsiz(1:2))]);
xyz = reshape((XYZ*im)',imsiz);
x = xyz(:,:,1);
y = xyz(:,:,2);
z = xyz(:,:,3);

l0 = y./Yn;
l = l0;
l(l0>Lt) = 116.*(l0(l0>Lt).^(1/3)) - 16;
l(l0<=Lt) = 903.3*l0(l0<=Lt);
c = x + 15*y + 3 * z;
u = 4*ones(imsiz(1:2),class(im));
v = (9/15)*ones(imsiz(1:2),class(im));
u(c~=0) = 4*x(c~=0)./c(c~=0);
v(c~=0) = 9*y(c~=0)./c(c~=0);

u = 13*l.*(u-Up);
v = 13*l.*(v-Vp);

luvim = cat(3,l,u,v);
```
if use cv2 make rgb2xyz than xyz2luv by myself.
```
    x=im_xyz[0]
    y=im_xyz[1]
    z=im_xyz[2]
    L=116.0*y**(1./3)-16 if y > 0.008856 else 903.3*y
    Un_prime = 0.19784977571475; 
    Vn_prime = 0.46834507665248;
    u_prime=0
    v_prime=0
    constant=(x+15.0*y+3.0*z)
    if constant!=0:
        u_prime = 4.0*x/constant
        v_prime = 9.0*y/constant
    u=13.0*L*(u_prime-Un_prime)
    v=13.0*L*(v_prime-Vn_prime)
    return np.array([L,u,v]) 
```
the result of L is 89 , but if you use rgb2luv , the result is [76.84296417, 6.9851861 , 1.50677502],
oh kill me!
then i try a photo 
![pic1](https://cloud.githubusercontent.com/assets/11959047/11462814/34cdb052-9754-11e5-8a39-1f9983623eb4.jpg)
compare to the photoshop
![14483495131024](https://cloud.githubusercontent.com/assets/11959047/11462803/0161e6b6-9754-11e5-8846-b8f39581bc47.jpg)
and the matlab
![14483672436409](https://cloud.githubusercontent.com/assets/11959047/11462810/1b43f092-9754-11e5-98c2-fc500799d76f.jpg)
and the opencv rgb2luv
![f123](https://cloud.githubusercontent.com/assets/11959047/11462901/a186a126-9755-11e5-8055-8c24a098baaf.png)

why photoshop is similar to the result of opencv?

**Comment by PkLab** [comment]
Already answered! Becuase matlab code `Yn=1.0` is a simpification, maybe your conversion function is unofficial, just an user file from FileExcange (http://www.mathworks.com/matlabcentral/fileexchange/19406-3d-stereo-disparity/content/lankton_stereo/msseg/RGB2Luv.m)?  

It looks OpenCV, like photoshop, uses more accurate conversion to encode values based on human perception: `L = splineinterpolation(Y,LabCbrtTab...`

I think issue is just related to the doc.

**Comment by h12345jack** [comment]
i know it.is not official.but it is the same with the doc. so i feel confuzed with the result when compared to the result of opencv. i agree with the doc problem, hope it can be more clear.

**Comment by PkLab** [comment]
Pleae note that the [code](https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/color.cpp#L5577) operates someting different from the doc
```cpp
//The (new) doc
L = 116 * Y^(1/3) - 16 
//The code: L = 116 * Yi -16
L0 = splineInterpolate(Y*LabCbrtTabScale, LabCbrtTab, LAB_CBRT_TAB_SIZE);
L = 116 * L0 - 16;
//where L0 <> Y ^(1/3)
```
You can see the difference using my test code and its previous output
```
Y from BGR2XYZ = 0.7212671
L = 116 * Y^(1/3) - 16 = 88.092
L from  BGR2Luv = 74.8962
```

This is the same for BGR2Lab

**Comment by iperov** [comment]
same for BGR2LAB , output is differs from official doc and from https://ru.wikipedia.org/wiki/LAB
