### ISSUE TITLE
 RELATIVE_PATH OpenCVGenConfig.cmake error on 3.0

### ISSUE THREAD

**Issue by fakkoweb** [Itseez/opencv#5690]
I get this error while configuring:
```
CMake Error at cmake/OpenCVGenConfig.cmake:114 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  ../../opencv/share/OpenCV/
Call Stack (most recent call first):
  CMakeLists.txt:658 (include)
```
I call it from inside root source directory on command line 
```
cmake . -Bbuild -DOGRE_USE_BOOST=1 -DWITH_TBB=1 -DWITH_CUDA=1 -DCMAKE_INSTALL_PREFIX:PATH=../../opencv/
```
I want to compile in subfolder /build and then install it on a folder outside the root source folder. Everything works fine with 2.4

I had to disable `WITH_IPP` to configure with no errors.

**Comment by mshabunin** [comment]
Try to pass install path without explicit type specifier: `-DCMAKE_INSTALL_PREFIX=../../opencv/` or provide absolute path: `-DCMAKE_INSTALL_PREFIX:PATH=<some-path>/opencv`

Not sure why it works this way, following is the related section of [cmake documentation]:(https://cmake.org/cmake/help/v3.4/manual/cmake.1.html)
`If the :<type> portion is given it must be one of the types specified by the set() command documentation for its CACHE signature. If the :<type> portion is omitted the entry will be created with no type if it does not exist with a type already. If a command in the project sets the type to PATH or FILEPATH then the <value> will be converted to an absolute path.`

**Comment by alalek** [comment]
Not enough details to reproduce problem
