### ISSUE TITLE
Error importing cv2 after making opencv 3 for anaconda python 3

### ISSUE THREAD

**Issue by 121onto** [Itseez/opencv#5693]
In case anyone else is stuck with this issue.  I was getting the following error after installing opencv 3 for python 3 (I am using an anaconda env for my python 3 install):

```{bash}
ImportError                               Traceback (most recent call last)
<ipython-input-1-72fbbcfe2587> in <module>()
----> 1 import cv2

ImportError: dlopen(/my/home/directory/anaconda/envs/python3/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so, 2): Library not loaded: lib/libopencv_reg.3.0.dylib
  Referenced from: /my/home/directory/anaconda/envs/python3/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so
  Reason: image not found
```

I fixed this problem by adding the following environment variables:

```{bash}
export ANACONDA_HOME=$HOME/anaconda
export DYLD_FALLBACK_LIBRARY_PATH=$ANACONDA_HOME/envs/python3/lib
```

**Comment by alalek** [comment]
Looks like, it is build/install configuration issue of python package manager (Python binding should be build via static linkage with OpenCV modules or there are a lot of issues with RPATH and so on).
We don't maintain anaconda builds and we can't fix there anything, so it is not the right place for fixes request.
1) answers.opencv.org (similar topics via google search: "anaconda site:answers.opencv.org")
2) Add issue somewhere here: https://github.com/conda/conda-recipes/tree/master/opencv (but there is OpenCV 2.4.9 only)
3) check custom conda builds via links from this issue: #5224
