### ISSUE TITLE
Why imwrite's result is different from the original Mat object?

### ISSUE THREAD

**Issue by AmNotGod** [Itseez/opencv#5695]
Hey, guys.
I get a problem. I try to use imwrite to save a Mat object as an image file, then, I use imread to read the file into another Mat object. It is surprising that the two Mat objects are not totally the same, some pixels are not equal!

How can I solve this problem? I need to ensure that the two Mat objects are the same. 
Thanks!

**Comment by alalek** [comment]
Do you want something like cv::FileStorage to serialize Mat data?
What type is used in Mat (CV_8UC3 or other)?
What format is used for image (JPEG is not lossless)?

**Comment by AmNotGod** [comment]
The type I used in Mat is default(may be CV_8UC3 ?)
The format I used for image is jpg.

I want to save a Mat object as a jpg file and if I read the jpg file as a Mat object, the pixles need to be the same as the original one.That 's all I want.
Thanks.

**Comment by AmNotGod** [comment]
Hey, I think I have got the answer. 
The jpg format will compress the original Mat object which causes the result  file be different from the original Mat object.
Thanks, again!

**Comment by prtsh** [comment]
You can adjust jpeg compression quality by using CV_IMWRITE_JPEG_QUALITY parameter while calling imwrite. By default it's 95. 

If quality parameter is kept at 100, quantization loss can be avoided.There will be some loss in fixed point DCT, but imread output image should be very close to the corresponding input image of imwrite.

In case you want exact match, try .png or .bmp filename extension while using imwrite.  

Please check imread documentation for more information.

**Comment by AmNotGod** [comment]
That's very helpful, thank you!
