### ISSUE TITLE
opencl has no impact on the performance of face detection

### ISSUE THREAD

**Issue by anguoyang** [Itseez/opencv#5697]
Hi, all,

I have compiled opencv 3.0 with opencl(WITH_OPENCL), and also compiled and run a face detection sample, without any error, however, there is no difference no matter I using TAPI/UMAT or NOT.
Here is my source code(using UMAT):
int main()
{

	VideoCapture cap("subway.avi"); // open the video file for reading

	if (!cap.isOpened())  // if not success, exit program
	{
		cout << "Cannot open the video file" << endl;
		return -1;
	}

	namedWindow("MyVideo", CV_WINDOW_NORMAL); //create a window called "MyVideo"

	// Load Face cascade (.xml file)
	CascadeClassifier face_cascade;
	face_cascade.load("haarcascade_frontalface_alt2.xml");
	while (1)
	{
		Mat frame;

		bool bSuccess = cap.read(frame); // read a new frame from video

		if (!bSuccess) //if not success, break loop
		{
			cout << "Cannot read the frame from video file" << endl;
			break;
		}

		UMat umat;
		umat = frame.getUMat(ACCESS_READ);

		imshow("MyVideo", umat); //show the frame in "MyVideo" window

		// Detect faces
		std::vector<Rect> faces;
		face_cascade.detectMultiScale(umat, faces, 1.1, 2, 0 | CV_HAAR_SCALE_IMAGE, Size(30, 30));

		// Draw circles on the detected faces
		for (int i = 0; i < faces.size(); i++)
		{
			Point center(faces[i].x + faces[i].width*0.5, faces[i].y + faces[i].height*0.5);
			ellipse(umat, center, Size(faces[i].width*0.5, faces[i].height*0.5), 0, 0, 360, Scalar(255, 0, 255), 4, 8, 0);
		}

		imshow("Detected Face", umat);

		if (waitKey(30) == 27) //wait for 'esc' key press for 30 ms. If 'esc' key is pressed, break loop
		{
			cout << "esc key is pressed by user" << endl;
			break;
		}
	}

	return 0;
}

Could you please help me to find out the reason? thanks a lot.

My display card is Intel Iris HD graphics, and there is no error when running my sample, but the speed is very very very slow!!! btw, the input video:"subway.avi" is with 1080P resolution.

**Comment by alalek** [comment]
Instead of Mat/UMat try to use `cv::setUseOpenCL(bool flag)`

**Comment by anguoyang** [comment]
thanks alalek, is there any samples on how to use it, does "cv::setUseOpenCL" is all that I need to do with opencl?

**Comment by prtsh** [comment]
Hi anguoyang, I think all intel iris graphic card have openCl support, at least 1.1 or 1.2.

Just to make sure that the drivers are not obsolete, you can install latest drivers from intel website -
https://software.intel.com/en-us/articles/opencl-drivers

**Comment by mshabunin** [comment]
@anguoyang , check [this](https://github.com/Itseez/opencv/blob/master/samples/tapi/pyrlk_optical_flow.cpp) sample and some other in the [samples/tapi](https://github.com/Itseez/opencv/tree/master/samples/tapi) folder.

**Comment by EUA** [comment]
Well, I think this bug is valid.

I just tried via Python 3.7 + OpenCV 4.0 
Code is here:
https://pastebin.com/D5T1DgV6

I tried to capture from my webcam, 1280x720 @10 fps and it takes %46 of my Ryzen1700 while **OpenCL is enabled**. Well, the same percentage CPU usage while OpenCL is disabled.

This means **face_cascade.detectMultiScale** does not support OpenCL in my opinion.

**Comment by alalek** [comment]
`opencv_version --opencl` should provide detailed information about OpenCL.

**Comment by EUA** [comment]
I don't think if there are a problem on my OpenCL installation.
I test via Mesa Gallium OpenCL. Now testing with AMD-OpenCL library with same amount of CPU load.

> opencv_version --opencl
> 4.0.1
> OpenCL Platforms: 
>     AMD Accelerated Parallel Processing
>         dGPU: Ellesmere (OpenCL 1.2 AMD-APP (2766.4))
> Current OpenCL device: 
>     Type = dGPU
>     Name = Ellesmere
>     Version = OpenCL 1.2 AMD-APP (2766.4)
>     Driver version = 2766.4
>     Address bits = 64
>     Compute units = 32
>     ...

**Comment by EUA** [comment]
**I found the issue.**

Even if **cv2.ocl.useOpenCL()** returns true by default,
_Before declare CascadeClassifier variable_, we need to set **cv2.ocl.setUseOpenCL(true)**

Moving code 

`face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")`

below `cv2.ocl.setUseOpenCL(True)` line fix the issue.

Thanks.

**Comment by rajhlinux** [comment]
I also find the same problem with the CPU being used at 100% with OpenCL being used for the "ufacedetect.cpp" sample. Why is it so slow running with OpenCL being used with the help of GPU? 

I have a decent AMD Radeon RX 580 GPU.

**Comment by rajhlinux** [comment]
> **I found the issue.**
> 
> Even if **cv2.ocl.useOpenCL()** returns true by default, _Before declare CascadeClassifier variable_, we need to set **cv2.ocl.setUseOpenCL(true)**
> 
> Moving code
> 
> `face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")`
> 
> below `cv2.ocl.setUseOpenCL(True)` line fix the issue.
> 
> Thanks.

Can you give example how to do it in c++?

Here is the code from opencv's samples T-API folder for "ufacedetect.cpp":

```
#include "opencv2/objdetect.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/core/ocl.hpp"
#include <iostream>

using namespace std;
using namespace cv;

// ./ufacedetect --cascade=/home/user/opencv/data/haarcascades/haarcascade_frontalface_alt.xml /dev/video5 --scale=1.3

static void help()
{
    cout << "\nThis program demonstrates the cascade recognizer. Now you can use Haar or LBP features.\n"
            "This classifier can recognize many kinds of rigid objects, once the appropriate classifier is trained.\n"
            "It's most known use is for faces.\n"
            "Usage:\n"
            "./ufacedetect [--cascade=<cascade_path> this is the primary trained classifier such as frontal face]\n"
               "   [--nested-cascade[=nested_cascade_path this an optional secondary classifier such as eyes]]\n"
               "   [--scale=<image scale greater or equal to 1, try 1.3 for example>]\n"
               "   [--try-flip]\n"
               "   [filename|camera_index]\n\n"
            "see facedetect.cmd for one call:\n"
            "./ufacedetect --cascade=\"../../data/haarcascades/haarcascade_frontalface_alt.xml\" --nested-cascade=\"../../data/haarcascades/haarcascade_eye_tree_eyeglasses.xml\" --scale=1.3\n\n"
            "During execution:\n\tHit any key to quit.\n"
            "\tUsing OpenCV version " << CV_VERSION << "\n" << endl;
}

void detectAndDraw( UMat& img, Mat& canvas, CascadeClassifier& cascade,
                    CascadeClassifier& nestedCascade,
                    double scale, bool tryflip );

int main( int argc, const char** argv )
{
    VideoCapture capture;
    UMat frame, image;
    Mat canvas;

    string inputName;
    bool tryflip;

    CascadeClassifier cascade, nestedCascade;
    double scale;

    cv::CommandLineParser parser(argc, argv,
        "{cascade|data/haarcascades/haarcascade_frontalface_alt.xml|}"
        "{nested-cascade|data/haarcascades/haarcascade_eye_tree_eyeglasses.xml|}"
        "{help h ||}{scale|1|}{try-flip||}{@filename||}"
    );
    if (parser.has("help"))
    {
        help();
        return 0;
    }
    string cascadeName = samples::findFile(parser.get<string>("cascade"));
    string nestedCascadeName = samples::findFileOrKeep(parser.get<string>("nested-cascade"));
    scale = parser.get<double>("scale");
    tryflip = parser.has("try-flip");
    inputName = parser.get<string>("@filename");
    if ( !parser.check())
    {
        parser.printErrors();
        help();
        return -1;
    }

    if ( !nestedCascade.load( nestedCascadeName ) )
        cerr << "WARNING: Could not load classifier cascade for nested objects: " << nestedCascadeName << endl;
    if( !cascade.load( cascadeName ) )
    {
        cerr << "ERROR: Could not load classifier cascade: " << cascadeName << endl;
        help();
        return -1;
    }

    cout << "old cascade: " << (cascade.isOldFormatCascade() ? "TRUE" : "FALSE") << endl;

    if( inputName.empty() || (isdigit(inputName[0]) && inputName.size() == 1) )
    {
        int camera = inputName.empty() ? 0 : inputName[0] - '0';
        if(!capture.open(camera))
            cout << "Capture from camera #" <<  camera << " didn't work" << endl;
    }
    else
    {
        inputName = samples::findFileOrKeep(inputName);
        imread(inputName, IMREAD_COLOR).copyTo(image);
        if( image.empty() )
        {
            if(!capture.open( inputName ))
                cout << "Could not read " << inputName << endl;
        }
    }

    if( capture.isOpened() )
    {
        cout << "Video capturing has been started ..." << endl;
        for(;;)
        {
            capture >> frame;
            if( frame.empty() )
                break;

            detectAndDraw( frame, canvas, cascade, nestedCascade, scale, tryflip );

            char c = (char)waitKey(10);
            if( c == 27 || c == 'q' || c == 'Q' )
                break;
        }
    }
    else
    {
        cout << "Detecting face(s) in " << inputName << endl;
        if( !image.empty() )
        {
            detectAndDraw( image, canvas, cascade, nestedCascade, scale, tryflip );
            waitKey(0);
        }
        else if( !inputName.empty() )
        {
            /* assume it is a text file containing the
            list of the image filenames to be processed - one per line */
            FILE* f = fopen( inputName.c_str(), "rt" );
            if( f )
            {
                char buf[1000+1];
                while( fgets( buf, 1000, f ) )
                {
                    int len = (int)strlen(buf);
                    while( len > 0 && isspace(buf[len-1]) )
                        len--;
                    buf[len] = '\0';
                    cout << "file " << buf << endl;
                    imread(samples::findFile(buf), IMREAD_COLOR).copyTo(image);
                    if( !image.empty() )
                    {
                        detectAndDraw( image, canvas, cascade, nestedCascade, scale, tryflip );
                        char c = (char)waitKey(0);
                        if( c == 27 || c == 'q' || c == 'Q' )
                            break;
                    }
                    else
                    {
                        cerr << "Aw snap, couldn't read image " << buf << endl;
                    }
                }
                fclose(f);
            }
        }
    }

    return 0;
}

void detectAndDraw( UMat& img, Mat& canvas, CascadeClassifier& cascade,
                    CascadeClassifier& nestedCascade,
                    double scale, bool tryflip )
{
    double t = 0;
    vector<Rect> faces, faces2;
    const static Scalar colors[] =
    {
        Scalar(255,0,0),
        Scalar(255,128,0),
        Scalar(255,255,0),
        Scalar(0,255,0),
        Scalar(0,128,255),
        Scalar(0,255,255),
        Scalar(0,0,255),
        Scalar(255,0,255)
    };
    static UMat gray, smallImg;

    t = (double)getTickCount();

    cvtColor( img, gray, COLOR_BGR2GRAY );
    double fx = 1 / scale;
    resize( gray, smallImg, Size(), fx, fx, INTER_LINEAR_EXACT );
    equalizeHist( smallImg, smallImg );

    cascade.detectMultiScale( smallImg, faces,
        1.1, 3, 0
        //|CASCADE_FIND_BIGGEST_OBJECT
        //|CASCADE_DO_ROUGH_SEARCH
        |CASCADE_SCALE_IMAGE,
        Size(30, 30) );
    if( tryflip )
    {
        flip(smallImg, smallImg, 1);
        cascade.detectMultiScale( smallImg, faces2,
                                 1.1, 2, 0
                                 //|CASCADE_FIND_BIGGEST_OBJECT
                                 //|CASCADE_DO_ROUGH_SEARCH
                                 |CASCADE_SCALE_IMAGE,
                                 Size(30, 30) );
        for( vector<Rect>::const_iterator r = faces2.begin(); r != faces2.end(); ++r )
        {
            faces.push_back(Rect(smallImg.cols - r->x - r->width, r->y, r->width, r->height));
        }
    }
    t = (double)getTickCount() - t;
    img.copyTo(canvas);

    double fps = getTickFrequency()/t;
    static double avgfps = 0;
    static int nframes = 0;
    nframes++;
    double alpha = nframes > 50 ? 0.01 : 1./nframes;
    avgfps = avgfps*(1-alpha) + fps*alpha;

    putText(canvas, cv::format("OpenCL: %s, fps: %.1f", ocl::useOpenCL() ? "ON" : "OFF", avgfps), Point(50, 30),
            FONT_HERSHEY_SIMPLEX, 0.8, Scalar(0,255,0), 2);

    for ( size_t i = 0; i < faces.size(); i++ )
    {
        Rect r = faces[i];
        vector<Rect> nestedObjects;
        Point center;
        Scalar color = colors[i%8];
        int radius;

        double aspect_ratio = (double)r.width/r.height;
        if( 0.75 < aspect_ratio && aspect_ratio < 1.3 )
        {
            center.x = cvRound((r.x + r.width*0.5)*scale);
            center.y = cvRound((r.y + r.height*0.5)*scale);
            radius = cvRound((r.width + r.height)*0.25*scale);
            circle( canvas, center, radius, color, 3, 8, 0 );
        }
        else
            rectangle( canvas, Point(cvRound(r.x*scale), cvRound(r.y*scale)),
                       Point(cvRound((r.x + r.width-1)*scale), cvRound((r.y + r.height-1)*scale)),
                       color, 3, 8, 0);
        if( nestedCascade.empty() )
            continue;
        UMat smallImgROI = smallImg(r);
        nestedCascade.detectMultiScale( smallImgROI, nestedObjects,
            1.1, 2, 0
            //|CASCADE_FIND_BIGGEST_OBJECT
            //|CASCADE_DO_ROUGH_SEARCH
            //|CASCADE_DO_CANNY_PRUNING
            |CASCADE_SCALE_IMAGE,
            Size(30, 30) );

        for ( size_t j = 0; j < nestedObjects.size(); j++ )
        {
            Rect nr = nestedObjects[j];
            center.x = cvRound((r.x + nr.x + nr.width*0.5)*scale);
            center.y = cvRound((r.y + nr.y + nr.height*0.5)*scale);
            radius = cvRound((nr.width + nr.height)*0.25*scale);
            circle( canvas, center, radius, color, 3, 8, 0 );
        }
    }
    imshow( "result", canvas );
}
```
I am able to view that the "OpenCL=ON" is displayed on the rendered window. So I know OpenCL is working utilizing my AMD GPU. However it makes no difference in off loading the CPU, CPU is still being used at 100%.

**Comment by Xnoopeex** [comment]
I have found a solution on Windows machines.
The problem might be windows internal powermanagement. 
In Windows Graphics Settings I added my Application.exe and forced it to use the internal Intel GPU. 
After that the facedetection was offloaded to my Intel GPU (75% utilization) and the CPU usage dropped from 65% to 20%.
(intel  i5-11400H)
I have noticed, that the framerate dropped by about 50% using the Intel GPU.
I think that could be a pipline issue between GPU and CPU, but not sure.

Here is my code:
`#include <opencv2/objdetect.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/core/ocl.hpp>
#include <iostream>

using namespace cv;
using namespace std;

int main(int argc, char** argv)
{
    ocl::setUseOpenCL(true);
    if (!cv::ocl::haveOpenCL())
    {
        std::cout << "OpenCL is not available..." << std::endl;
        //return;
    }

    cv::ocl::Context context;
    if (!context.create(cv::ocl::Device::TYPE_ALL))
    {
        std::cout << "Failed creating the context..." << std::endl;
        //return;
    }

    std::cout << context.ndevices() << " GPU devices are detected." << std::endl; //This bit provides an overview of the OpenCL devices you have in your computer
    for (int i = 0; i < context.ndevices(); i++)
    {
        cv::ocl::Device device = context.device(i);
        std::cout << "name:              " << device.name() << std::endl;
        std::cout << "available:         " << device.available() << std::endl;
        std::cout << "imageSupport:      " << device.imageSupport() << std::endl;
        std::cout << "OpenCL_C_Version:  " << device.OpenCL_C_Version() << std::endl;
        std::cout << std::endl;
    }
    // Load the cascades
    CascadeClassifier face_cascade;
    CascadeClassifier eye_cascade;
    face_cascade.load("C:/opencv/sources/data/haarcascades/haarcascade_frontalface_default.xml");
    eye_cascade.load("C:/opencv/sources/data/haarcascades/haarcascade_eye.xml");

    // Open the webcam
    VideoCapture webcam(0); // 0 is the index of the default webcam
    if (!webcam.isOpened()) {
        cerr << "Failed to open webcam" << endl;
        return 1;
    }
    int64 t1, t2, recog=0;
    int frames = 0;
    double proc_time=0;
    double fps=0;


    while (true) {

        cv::UMat frame = cv::UMat(cv::Size(1280, 720), CV_8UC3, cv::USAGE_ALLOCATE_DEVICE_MEMORY);

        //cv::Mat frame;
        
        // Read a frame from the webcam
        webcam.read(frame);

        t1 = getTickCount();
        // Convert the frame to grayscale
        
        cv::UMat grey = cv::UMat(cv::Size(1280, 720), CV_8UC1, cv::USAGE_ALLOCATE_DEVICE_MEMORY);
        cvtColor(frame,grey, COLOR_BGR2GRAY);

        //cv::Mat grey;
        //cvtColor(frame,grey, COLOR_BGR2GRAY);

        // Detect faces
        vector<Rect> faces;
        vector<Rect> eyes;
        face_cascade.detectMultiScale(grey, faces, 1.1, 2, 0, cv::Size(30, 30));
        eye_cascade.detectMultiScale(grey, eyes, 1.1, 2, 0 | cv::CASCADE_SCALE_IMAGE, cv::Size(30, 30));
        for (size_t i = 0; i < faces.size(); i++)
        {
            rectangle(frame, faces[i], Scalar(255, 255, 255), 2);
            recog++;
        }
        for (size_t i = 0; i < eyes.size(); i++)
        {
            rectangle(frame, eyes[i], Scalar(0, 0, 255), 2);
            recog++;
        }

        t2 = getTickCount();

        proc_time += (t2 - t1) / getTickFrequency();

        // Show the frame
        imshow("Webcam", frame);

        frames++;
        if (frames % 60 == 0) {
            fps = 60.0 /proc_time;
            proc_time = 0;
            cout << "FPS: " << fps << endl;
            cout << "Recogs: " << recog << endl;
        }

        // Exit the loop if the user presses 'q'
        if (waitKey(1) == 'q') {
            break;
        }
    }

    return 0;
}`
