### ISSUE TITLE
Error while building Release with BUILD_TBB flag activated

### ISSUE THREAD

**Issue by djebm2** [Itseez/opencv#5706]
Linking CXX shared library ../../lib/libtbb.so
/usr/bin/ld: cannot open output file ../../lib/libtbb.so: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libtbb.so] Error 1
make[1]: *** [3rdparty/tbb/CMakeFiles/tbb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by djebm2** [comment]
Linking CXX static library ../../lib/libopencv_hal_pch_dephelp.a
/usr/bin/ar: ../../lib/libopencv_ts_pch_dephelp.a: No such file or directory
[ 10%] /make[2]: *** [lib/libopencv_ts_pch_dephelp.a] Error 1usr/bin/ld: cannot
 open output file ../../lib/libtbb.so: No such file or directory
make[1]: Built target IlmImf
*** [modules/ts/CMakeFiles/opencv_ts_pch_dephelp.dir/all] Error 2
collect2: error: ld returned 1 exit status
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [lib/libtbb.so] Error 1
make[1]: *** [3rdparty/tbb/CMakeFiles/tbb.dir/all] Error 2

**Comment by alalek** [comment]
Can't reproduce on Linux with latest master branch.
1) Use the latest master
2) Build from scratch (cleanup build directory)
3) Check #5041 where TBB issues have been fixed.

**Comment by mshabunin** [comment]
@djebm2 , feel free to reopen the issue if you could reproduce the issue with the latest master branch (or 2.4 branch). Please provide more information about OpenCV version and platform being used.
