### ISSUE TITLE
OpenCL HOG Object detect assigns the wrong SIMD size.

### ISSUE THREAD

**Issue by ajbernal** [Itseez/opencv#5710]
In the classification of descriptor histograms function each kernel variation depends on preprocessor directives to specify the kernel SIMDness. The value is passed to the kernel as a compilation a flag named `WAVE_SIZE`. The value of `WAVE_SIZE` is then calculated by compiling each kernel twice. 

The first time assumes no SIMD size to build the kernel and then it calls  `getWorkGroupInfo(CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE)` to to find it.
The second time it  passes the previous SIMD size (`WAVE_SIZE`) as a compilation flag but know the kernel has changed and it's possible that the compiler will choose a different SIMD size for the new kernel that contradicts the previous value. 

Since the SIMD preferred size depends upon vendor implementation, we can't guarantee that the SIMDness would remain constant if the kernel changes. 

This issue happens on the following kernels:
- classify_hists_180_kernel
- classify_hists_252_kernel
- classify_hists_kernel
- normalize_hists_kernel -> reduce_smem 

Called from the following functions:
- ocl_classify_hists
- ocl_normalize_hists

**Comment by alalek** [comment]
Hi,

1) Similar 2-step compilation have been used as a workaround for OpenCL compilers/runtime, which are unable to run compiled kernels or run code very inefficiently due some GPU resource limitation (VGPR and others): these kernels is large enough and there are many variables. So this 2 step strategy is used to get more effective code which can be launched:
a) build kernel#1 with default parameters.
b) ask optimal parameters for kernel#1 and apply these parameters to kernel#2.
It is a trick, but it works.
An another (but similar) approach have been added for filtering code ( [2.4 branch](https://github.com/Itseez/opencv/commit/7b0f018a740ac9c8b10f08cc6b35a26b1e0f9d3d#diff-f5164f2518dfe19a99215c7e5ef61ec3) - there were issue with successfully compiled kernels which were unable to run with required workgroup size)

> we can't guarantee that the SIMDness would remain constant if the kernel changes.
I agree here, but I don't know other better solutions at this moment (without a large performance impact, like to check all range of possible WAVE_SIZE values and SIMDness in all cases and to select "the best" value).

2) Do you have a suggestion with fix something here? Does this workaround not work somewhere on some cases?

**Comment by ajbernal** [comment]
My thoughts, here:
* I'm not against compiling the kernel twice and I think that it will definitely help dealing with different platforms/vendors. But I haven't really thought about a general solution.
* The solution for this specific case is pretty simple. In order to guarantee SIMDness we should compile the kernel with SIMD32 since it's the highest size optimized in the kernel without the use of barriers. 
  * If the  compiler then decides to build the first kernel using SIMD16 and we pass that value to the next build, we're safe because there's a barrier that guarantees the execution order between different hardware threads (even if it decides to build the second kernel using SIMD32).
  * If the compiler builds the first kernel using SIMD32 the second will use SIMD32 as well, so no issues here.

I have a fix in place and I can submit a pull request to address this specific case but we may want to check if we're doing the same somewhere else.
