### ISSUE TITLE
FlannBasedMatcher add single

### ISSUE THREAD

**Issue by dropfen** [Itseez/opencv#5711]
Hi, I wonder how could I add a single Descriptor set to a trained Matcher, with the common interface. Because the docs says, that you have to pass in a vector. 

So I need to pass a vector with a single descriptor, right? Ok, then my question is, which imageIdx will have the matches related to this descriptor?

**Comment by mshabunin** [comment]
@dropfen , the Q&A forum is more appropriate place for questions: http://answers.opencv.org/
