### ISSUE TITLE
demosaicing on 16bit files (EA or bilinear) gives black file

### ISSUE THREAD

**Issue by ArkadiuszRaj** [Itseez/opencv#5719]
I have written simple app that catches data from stdin (imdecode), runs demosaicing function and do simple statistic analysis.

`op@sh:~$ make; dcraw -D -4 -t 0 -c canong9x.CR2 | worker  -d EA,GR  - `
`[100%] Built target worker`
`Received data file (5536x3693x1 16-bits)`
`Demosaicing`
 `min max mean stddev`
`0.0000     0.0000     0.0000     0.0000   `
`0.0000     0.0000     0.0000     0.0000   `
`0.0000     0.0000     0.0000     0.0000 `  

Zeros only, black file, when written to PNG or using imshow - black image is visible.
However switching dcraw to produce 8bpp data makes everything working.

`op@sh:~$ make; dcraw -D -t 0 -c canong9x.CR2 | worker  -d EA,GR  - `
`[100%] Built target worker`
`Received data file (5536x3693x1 8-bits)`
`Demosaicing`
`min max mean stddev`
`171.0000   255.0000     208.9201     11.9695   `
`172.0000   255.0000     225.6286     15.9104 `
`169.0000   255.0000     196.4580     8.0409`
`174.0000   255.0000     217.3052     13.5734`

Tested using EA & bilinear algo. 

I am using OpenCV 3

`op@sh:~$ pkg-config --modversion opencv`
`3.0.0`

**Comment by alalek** [comment]
What is "min max mean stddev" **before** demosaicing?

`imshow` may not work well with 16-bit data. Try to use cv::FileStorage to check contents.

**Comment by ArkadiuszRaj** [comment]
Well, to use imshow I am normalizing data... Anyway - when no demosaicing is started, only one channel (as expected) is available for analyze:

`1947.0000  8340.0000  3110.9690   574.0365`

(in previous message secont printout represens RGBY decomposition (Y is created internally using cvtColor)

**Comment by alalek** [comment]
Thanks! So it is not 16-bit `imdecode` problem.

Looks like that some code paths (include 16-bit) are dropped into this ["zero" stub](https://github.com/Itseez/opencv/blob/ddf82d0b154873510802ef75c53e628cd7b2cb13/modules/imgproc/src/demosaicing.cpp#L56-L79).

**Comment by ArkadiuszRaj** [comment]
cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 4096 KB
physical id	: 0
siblings	: 3
core id		: 0
cpu cores	: 3
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl pni cx16 x2apic hypervisor lahf_lm
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by alalek** [comment]
@ArkadiuszRaj 
Could you add a `bayer.type()` value:
```
Mat bayer;
if(src.channels() == 1) {
    bayer = src.clone();
    std::cout << bayer.type() << std::endl; // add this line
    demosaicing(bayer, src, code);
}
```

**Comment by ArkadiuszRaj** [comment]
Hello,

Due to other reasons I had to reinstall comp, which resulting in downloading & compiling fresh OpenCV from repository head. Then I realised the previously mentioned issue disappeared. 
Gray, bilinear & EA methods works with 16 bit data as expected. VNG also, but with 8 bits only (no surprise).

I believe  ticket can be closed.

**Comment by alalek** [comment]
Thanks for update!

BTW, "Zero stub" is an optimized code path: all is fine there, fallback path is available and works. I were not able to reproduce problem several days ago.
