### ISSUE TITLE
cuda::HOG instability bug in release mode

### ISSUE THREAD

**Issue by GabrieleDalmazzone** [Itseez/opencv#5721]
Hello,
I have found that the opencv cuda HOG implementation is non deterministic:
if you write a code where you perform HOG features extraction a thousand of times in a loop, you will see that the returned descriptors are not always the same (about 3 to 5 times over 1000 they are different).
This doesn't happen in debug mode (with -g -G compilation flags).
I have found that the instability originates from the cuda-kernel: normalize_hists_kernel_many_blocks.

SOLUTION:
there is a race condition in calling reduce_smem kernel.
In order to fix this a __syncthreads() has to be added before the second call of reduce_smem.
But I have no answer to the question: why not before the first call too???

Hope this can help

**Comment by jet47** [comment]
Hello,

Thank you for your investigation. Could you create a pull request with your fix?

**Comment by GabrieleDalmazzone** [comment]
I think I have completed the pull-request procedure.
By

**Comment by mshabunin** [comment]
@GabrieleDalmazzone , you've merged the fix to your fork, not to OpenCV mainline. Please create pull request to Itseez/OpenCV repository: https://github.com/Itseez/opencv/compare/master...GabrieleDalmazzone:GabrieleDalmazzone-patch-1
