### ISSUE TITLE
Indefinite hang when connecting to a rtsp stream

### ISSUE THREAD

**Issue by peters** [Itseez/opencv#5730]
Built latest version from `HEAD` with ffmpeg support enabled on Windows 10.

When you connect to a rtsp stream and the resource (read: the streaming server) is unavailable an indefinite hang on Windows is observed.

I've done some initial research and if you want to handle transient connection issues you need to specify a interrupt callback as per [documentation](https://ffmpeg.org/doxygen/2.7/structAVFormatContext.html#a5b37acfe4024d92ee510064e80920b40) before `avformat_open_input` is called.

Digging through their bug tracker i found a related [issue](https://trac.ffmpeg.org/ticket/2694) submitted about two years ago.

Repo:

```c++
auto vc = new cv::VideoCapture();
auto success = vc->open("rstp://192.168.1.200/media/video1");
// -- indefinite hang
```

**Comment by peters** [comment]
Attaching with a debugger shows that the hang is located at https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg.cpp#L201 which again refers to https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L582

I built ffmpeg using this [docker container](https://github.com/Itseez/opencv_3rdparty/tree/ffmpeg/master) but i'm unsure how to generate a pdb for the generated dll.

**Comment by peters** [comment]
According to this [article](http://plagatux.es/2012/08/skipping-blocking-libav-functions-with-interruption-callbacks/) you have to supply an interrupt callback, otherwise you'll be stuck since the socket will block indefinitely.

I did a quick test by adding the callback (5 second timeout) where the timestamp value is updated everytime we are able to read a frame from the stream.

**Comment by peters** [comment]
@mshabunin Is it possible to hire a opencv developer (from the foundation) or make a donation in order to get a fix landed for this issue?

**Comment by vpisarev** [comment]
Hi @peters, unfortunately, right now we do not have a working mechanism for handling individual bug reports on commercial basis. We either do more or less big projects (a few man-months at least), or let community fix the bug and accept the patches in the form of pull requests, or fix the bugs ourselves "for free" when we can reproduce it and when it's critical for our own projects. In this particular case I believe all we can do in the short term is to integrate a patch from community.

**Comment by peters** [comment]
That's understandable, thanks for letting me know :)

**Comment by peters** [comment]
This also applies if the stream goes away (network interruption) when you are connected.

**Comment by peters** [comment]
@alalek @vpisarev I just posted a 500$ bounty https://www.bountysource.com/issues/28757855-indefinite-hang-when-connecting-to-a-rtsp-stream. Would you be so kind to see if anyone on your team would like to claim it on their spare time?

If they don't have the time is it appropiate to advertise the bounty on your mailinglist?

The fix _SHOULD_ be fairly trivial according to this comment https://github.com/Itseez/opencv/issues/5730#issuecomment-161107510.

**Comment by Maroc-OS** [comment]
> I did a quick test by adding the callback (5 second timeout) where the timestamp value is updated everytime we are able to read a frame from the stream. 

What was the test patch you added!

let me see if i can help on this if it will not toke time.

**Comment by peters** [comment]
@Maroc-OS Thanks for the interest in fixing this issue, but I just landed a PR which resolves this issue.

**Comment by Maroc-OS** [comment]
:) anytime @peters and good work

**Comment by peters** [comment]
Thanks :dancers:

**Comment by alikanarya** [comment]
Hi Peter,
is it possible to change timeout value without changing it inside the source?
I am using opencv_ffmeg.dll.
Can I access it as a property or via function?
Otherwise I have to change the timeout value in source and build the dll again.
Thanks

**Comment by alikanarya** [comment]
hi, i changed the timeout property inside the source but nothing changed.
infact i was building opencv using cmake. afterthat i noticed that this building takes ffmeg prebuilt binaries hence my code change isnt compiled via this method.
So how can i rebuild opencv_ffmeg.dll?

**Comment by alalek** [comment]
> So how can i rebuild opencv_ffmeg.dll?

You need any Linux (Ubuntu is OK) with installed git/[docker](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/).
Clone repository and run [build_update.sh script](https://github.com/opencv/opencv_3rdparty/blob/ffmpeg/master/build_update.sh):
```
git clone -b ffmpeg/master --depth=100 --recursive https://github.com/opencv/opencv_3rdparty.git
cd opencv_3rdparty
./build_update.sh
```
In case of custom OpenCV build (your case) you need to use `BUILD_SKIP_OPENCV_UPDATE=1` environment variable (before you should commit your changes into "opencv" sub-directory):
```
BUILD_SKIP_OPENCV_UPDATE=1 ./build_update.sh
```

**Comment by alikanarya** [comment]
Thanks Alex,
I am building on debian. I didnt clone the opencv but already copied the source package under the opencv folder of your structure.
Infact, the things were going good but "make" arised 
"Error: openh264 not found by pkg-config" message.
And docker isnt installed on my system. Is the docker compulsory and what about the message above?
