### ISSUE TITLE
Build OpenCV for Android

### ISSUE THREAD

**Issue by manjia** [Itseez/opencv#5736]
Hello, I'm looking for a way to compile the OpenCV sources for Android architectures.
I tried with any single tutorial and guide existing on the internet including this one: http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk but I got no luck. 
I also noticed that each one guide I found comes out with a custom, undocumented solution.
Can you please provide a straightforward way to do that?

Thanks in advance.

**Comment by alalek** [comment]
Questions should go to http://answers.opencv.org

I believe something from this link should help:
http://pullrequest.opencv.org/buildbot/waterfall?tag=os-Android
(requirement of Android SDK/NDK is assumed)

**Comment by manjia** [comment]
I'll ask in answers then,
The link you provided wasn't helpful but thanks anyway

**Comment by manjia** [comment]
I'll ask in answers then,
The link you provided wasn't helpful but thanks anyway
