### ISSUE TITLE
Inverse cv::linearPolar transform causes missing patch in output

### ISSUE THREAD

**Issue by ejoebstl** [Itseez/opencv#5764]
I'm trying apply an inverse linear polar transform to some quadratic images:

![in](https://cloud.githubusercontent.com/assets/1852126/11653532/c98645fe-9d96-11e5-81ee-029d33ab2371.png)

The result, I'd expect is the following (done using Photoshop):

![expected](https://cloud.githubusercontent.com/assets/1852126/11653548/ddf1c8f6-9d96-11e5-92aa-932e367fefc2.png)

However, the result I get from OpenCV's linearPolar function is the following:

![result](https://cloud.githubusercontent.com/assets/1852126/11653554/e76a6fbe-9d96-11e5-8b79-2b612cb41a4e.jpg)

Some part of the image is missing and can be noticed as a black slice.

Minimal code to reproduce: 

```
int main(int argc, char** argv) {
    assert(argc == 3);

    Mat pol;
    Mat in = imread(argv[1]);

    // In case input is not quadratic. 
    resize(in, in, Size(in.rows, in.rows));

    // This is just for orienting the output. It can be left out - the bug still occurs. 
    in = in.t();
    flip(in, in, -1);

    linearPolar(in, pol, 
        Point2f(in.cols / 2, in.rows / 2), (in.rows / 2), 
        CV_WARP_FILL_OUTLIERS | CV_INTER_LINEAR | CV_WARP_INVERSE_MAP);

    imwrite(argv[2], pol);
    
    return 0;
}
````

Any help in tracking this one would be appreciated. The related code (```cvLinearPolar```and ```cvCartToPolar```) is somewhat hard to read.

**Comment by kautilyavc** [comment]
I am new to development in Opencv.Can you please tell me where the said pieces of code(cvLinearPolar&cvCartToPolar) are located in the imgproc directory?I found their function declaration in imgproc_c.h but I am unable to find the function definition.

**Comment by Dikay900** [comment]
You can find
`CV_IMPL
void cvLinearPolar( const CvArr* srcarr, CvArr* dstarr,
            CvPoint2D32f center, double maxRadius, int flags )` in imgproc/src/imgwarp.cpp:6598 (eof)

**Comment by ythej** [comment]
@kautilya-vc , Are you still working on this bug ?? If not, I would like to work on this. Please update :)

Thanks.

**Comment by kautilya-vc** [comment]
@ythej ,I am still working on this. I will update here incase I am unable to solve it.
Thanks

**Comment by Aravind-Suresh** [comment]
@kautilya-vc, Are you still working on this bug? If not, I am willing to fix this. Thanks :)

**Comment by kautilya-vc** [comment]
@Aravind-Suresh Please go ahead.Really sorry for the delay in response.
