### ISSUE TITLE
`cv::cuda::createContinuous`effectively ignores its `cols` argument

### ISSUE THREAD

**Issue by dotdash** [Itseez/opencv#5780]
In 1db4afac6aa52be3e158a5fdc03572ee0d51baf1 `createContinuous` was made generic and it now uses `reshape` instead of setting `rows` and `cols` directly. But `reshape` only takes a `rows` parameter, and calculates an appropriate number of `cols`. This means that the result of `createContinuous` may have a different number of columns than requested.

This breaks, for example, the repeated use of a single `cv::cuda::Convolution` instance on images of varying sizes, because the persistent buffers don't get resized correctly.

A quick fix would be to change the area check in `createContinuousImpl` from `obj.size().area() < area` to `obj.size().area() != area`, but that would of course introduce more reallocations than strictly necessary.

**Comment by jet47** [comment]
https://github.com/Itseez/opencv/pull/5781
