### ISSUE TITLE
HDR example produces images with inverted colors

### ISSUE THREAD

**Issue by pkondratyuk** [Itseez/opencv#5787]
Running the HDR tutorial code from current OpenCV master produces hdr images with inverted colors (i.e., black is white, green is cyan, etc.).

The issue seems to be in the MergeDebevec() call. MergeMartens() works as it should, the colors are normal.

More specifically, the output of the hdr tutorial is as follows:
file "hdr.hdr" - inverted colors
file "ldr.png" - inverted colors (since it is produced from the hdr data)
file "fusion.png" - normal colors

OpenCV was compiled with Visual Studio 2010 x64.

**Comment by alalek** [comment]
I have this ldr.png:
![ldr](https://cloud.githubusercontent.com/assets/4981219/11975899/7eff3ef2-a983-11e5-8089-43c03640632e.png)

"white is white" here.

hdr.hdr looks fine also (checked via luminance-hdr program)

**Comment by oomdik** [comment]
I agree with @pkondratyuk - the result posted at http://docs.opencv.org/3.1.0/d3/db7/tutorial_hdr_imaging.html#gsc.tab=0 looks like 
![ldr](https://cloud.githubusercontent.com/assets/460704/14637764/bafbb428-0633-11e6-9d41-3b74e080a0d6.png), and as posted above this is not the result you get with that code.
