### ISSUE TITLE
CascadeClassifier.detectMultiScale crash on Mac OSX

### ISSUE THREAD

**Issue by mrdebug** [Itseez/opencv#5791]
unable to run the sample program facedetect.cpp on Mac OSX (On Linux and Windows works). You will have a crash. See the crash report

Thread 0 Crashed:: Dispatch queue: opencl_runtime
0   libsystem_kernel.dylib        	0x00007fff95a4e002 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9972c5c5 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8c8666e7 abort + 129
3   libGPUSupportMercury.dylib    	0x00007fff994bce5c gpusGenerateCrashLog + 158
4   com.apple.AMDRadeonX3000GLDriver	0x00000001068454fc 0x106820000 + 152828
5   libGPUSupportMercury.dylib    	0x00007fff994bd818 gpusQueueSubmitDataBuffers + 162
6   com.apple.AMDRadeonX3000GLDriver	0x000000010687098c 0x106820000 + 330124
7   com.apple.AMDRadeonX3000GLDriver	0x0000000106870872 0x106820000 + 329842
8   com.apple.AMDRadeonX3000GLDriver	0x0000000106870c36 gldFinishQueue + 41
9   com.apple.opencl              	0x00007fff9aee7b86 0x7fff9aee6000 + 7046
10  com.apple.opencl              	0x00007fff9aee8058 0x7fff9aee6000 + 8280
11  com.apple.opencl              	0x00007fff9af06358 0x7fff9aee6000 + 131928
12  com.apple.opencl              	0x00007fff9af099b8 0x7fff9aee6000 + 145848
13  libdispatch.dylib             	0x00007fff9472733f _dispatch_client_callout + 8
14  libdispatch.dylib             	0x00007fff94728926 _dispatch_barrier_sync_f_invoke + 74
15  com.apple.opencl              	0x00007fff9af09834 0x7fff9aee6000 + 145460
16  com.apple.opencl              	0x00007fff9af05430 0x7fff9aee6000 + 128048
17  com.apple.opencl              	0x00007fff9aefa777 clEnqueueReadBuffer + 817
18  libopencv_core.3.0.dylib      	0x0000000101e19c13 cv::ocl::OpenCLAllocator::map(cv::UMatData*, int) const + 451
19  libopencv_core.3.0.dylib      	0x0000000101e7dd30 cv::UMat::getMat(int) const + 48
20  libopencv_objdetect.3.0.dylib 	0x000000010341fd4f cv::CascadeClassifierImpl::ocl_detectMultiScaleNoGrouping(std::__1::vector<float, std::__1::allocator<float> > const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&) + 3151
21  libopencv_objdetect.3.0.dylib 	0x0000000103420a46 cv::CascadeClassifierImpl::detectMultiScaleNoGrouping(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<double, std::__1::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, bool) + 2086
22  libopencv_objdetect.3.0.dylib 	0x0000000103421925 cv::CascadeClassifierImpl::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<double, std::__1::allocator<double> >&, double, int, int, cv::Size_<int>, cv::Size_<int>, bool) + 565
23  libopencv_objdetect.3.0.dylib 	0x0000000103422055 cv::CascadeClassifierImpl::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>) + 117
24  libopencv_objdetect.3.0.dylib 	0x0000000103424486 cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>) + 214
25  ssssss.untitled               	0x0000000101a49c9b detectAndDraw(cv::Mat&, cv::CascadeClassifier&, cv::CascadeClassifier&, double, bool) + 1259
26  ssssss.untitled               	0x0000000101a48a43 main + 7107
27  libdyld.dylib                 	0x00007fff8c32d5ad start + 1

**Comment by alalek** [comment]
> 17 com.apple.opencl 0x00007fff9aefa777 clEnqueueReadBuffer + 817
> 18 libopencv_core.3.0.dylib 0x0000000101e19c13 cv::ocl::OpenCLAllocator::map(cv::UMatData*, int) const + 451

Looks like it is related to OpenCL problem.
Try to build without OpenCL support or disable OpenCV via environmnt variables (OPENCV_OPENCV_DEVICE=disabled or OPENCV_OPENCV_RUNTIME=invalid)
