### ISSUE TITLE
A bug about 'vector' might exsists in VC14.

### ISSUE THREAD

**Issue by Vargnatt** [Itseez/opencv#5794]
I rebuilt OpenCV 3.0 (master branch on Dec 12th) libs for Visual Studio 2015 in windows 10 a couple of days ago. And I wrote a function about operation on contours involving  "vector< vector < Point> >" , which works  properly on OpenCV 3.0 + VS 2013. However, it crushes in VS 2015, showing "Unhandled exception at 0x6F433472 (ucrtbase.dll) in testProj.exe: An invalid parameter was passed to a function that considers invalid parameters fatal."

I checked call stack and step my scripts, finding that such exception is thrown when deleting "vector< vector < Point> >". Either destroying a vector object when breaking out of a function or simply using method " .clear()"  and " .erase()" does such error recurs. But testing vector< Mat > and some other types like vector < Rect > throws no exception. The function called when crush is "deallocate()" in xmemory0.

As the function does work on other machines and the test for other types is fine, I think it would not be a coding error or configuration mistake. I did some search  and saw equivalent issues like http://answers.opencv.org/question/74771/findcontours-exception/

So I wonder how to fix it.

Regards.

**Comment by alalek** [comment]
We have regular test runs with MSVS 2015, and don't see similar problems.

Try to get build/run commands from our builders: http://pullrequest.opencv.org/#/summary/opencv
Also you may provide a pull request with failed reproducer of this problem (via [simple test](https://github.com/Itseez/opencv/blob/46ada3886fa490e279274182aa8f5fc65740fc21/modules/core/test/test_utils.cpp#L18-L29)) and our buildbot will check (try to run) them.

**Comment by alalek** [comment]
Minimal reproducer (with input data) is still required.

**Comment by sanme98** [comment]
I found a similar issue in VC14(2015) but no problem after changed to VC12(2013).
