### ISSUE TITLE
convertiong a ROI into grayscale is not working in android

### ISSUE THREAD

**Issue by AmnahSaleem** [Itseez/opencv#5822]
Here is my code, i am not able to covert the mouth region into grayscale please help me...i have tried everything available on internet

			Mat innerWindow = mRgba.submat(moutharea);
	Imgproc.cvtColor(innerWindow, innerWindow,Imgproc.COLOR_RGB2GRAY);		
	Imgproc.threshold( innerWindow,  innerWindow,70, 255,Imgproc.THRESH_BINARY);

**Comment by sturkmen72** [comment]
try

    Mat innerWindow = mGray.submat(moutharea);
    //Imgproc.cvtColor(innerWindow, innerWindow,Imgproc.COLOR_RGB2GRAY);      
    Imgproc.threshold( innerWindow,  innerWindow,70, 255,Imgproc.THRESH_BINARY);

**Comment by alalek** [comment]
`cvtColor` call is wrong as mentioned @sturkmen72. You can't replace RGBA (not RGB) 4-channel image pixels with gray 1-channel pixels.

Something like this may help:
```
for (...) {
    ...
    Mat innerWindow = mRgba.submat(moutharea);
    Mat grayRoi;
    Imgproc.cvtColor(innerWindow, grayRoi, Imgproc.COLOR_RGBA2GRAY);
    Imgproc.threshold(grayRoi,  grayRoi, 70, 255, Imgproc.THRESH_BINARY);
    Imgproc.cvtColor(grayRoi, innerWindow, Imgproc.COLOR_GRAY2RGBA);
}
```

**Comment by AmnahSaleem** [comment]
it works :+1:  it doesn't show  moutharea in grayscale because of the reason @alalek  mentioned but it is working for further processing.
I think  mention this point should be mention in OpenCv 3.0 documentation as well. As many people are confused because of this.
