### ISSUE TITLE
Documentation ORB (Oriented FAST and Rotated BRIEF)

### ISSUE THREAD

**Issue by Perif** [Itseez/opencv#5831]
The documentation of the ORB is missing a small update in the example code due to the API change in opencv 3: http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_feature2d/py_orb/py_orb.html

    # Initiate STAR detector
    orb = cv2.ORB()

should be 

    # Initiate STAR detector
    orb = cv2.ORB_create()

See : 
- https://stackoverflow.com/questions/31630559/attributeerror-module-object-has-no-attribute-orb
- https://stackoverflow.com/questions/19523803/cv2-orb-and-cv2-sift-not-defined

**Comment by alalek** [comment]
This problem was already fixed in master: http://docs.opencv.org/master/d1/d89/tutorial_py_orb.html
