### ISSUE TITLE
FaceDetection sample Project is not working in android studio...  couldn't find "libdetection_based_tracker.so

### ISSUE THREAD

**Issue by AmnahSaleem** [Itseez/opencv#5837]
Please help the users in this Problem... many users are facing this problem in running face detection code in android studio...

Please provide some tutorial so that user can run it on Android studio...
 Error :

FATAL EXCEPTION: main Process: org.opencv.samples.opencv3_facedetection, PID: 19095 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.opencv.samples.opencv3_facedetection-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libdetection_based_tracker.so

**Comment by alalek** [comment]
There is no OpenCV support for Android Studio, see this issue #5003

**Comment by lxdatgithub** [comment]
Add this code to the openCVSamplefacedetection build.gradle, in my case ,it works.
```   
    externalNativeBuild {
            ndkBuild {
                path 'src/main/jni/Android.mk'
            }
        }
```
In this case , the environment is **android studio 2.2.3 , opencv 3.2.0**.

In the new verison of android studio, the cpp support is so sweet. You **right click** the any directory in your project,like "cpp" or so-called "jni" directory in your project, that will a option "Link C++ Projects with Gradle" ,click it and choose ndk-build, then point to your **Android.mk** which is in "cpp" directory(/home/user/AndroidStudioProjects/face-detection/openCVSamplefacedetection/src/main/jni). That add the code above to the build.gradle. Lukily , you can also choose cmake if you have CMakeList.txt file.

By the way , you would better export the OPENCV_ANDROID_SDK to the sys variable before compiling the opencv sample project, like below:

```export OPENCV_ANDROID_SDK=/home/user/AndroidStudioProjects/OpenCV-android-sdk```

**Comment by JorgeOsorio97** [comment]
@lxdatgithub 
I tried adding your code to my build.gradle but I am already using path in Cmake to cmake list 
```
externalNativeBuild {  
    cmake {
        path "CMakeLists.txt"
    }
    ndkBuild {
        path "main/cpp/Android.mk"
    }
} 
```
but i got this error: 
`More than one externalNativeBuild path specified`
