### ISSUE TITLE
Broken Link in python tutorial

### ISSUE THREAD

**Issue by crobertsbmw** [Itseez/opencv#5838]
On this page of the documentation, http://docs.opencv.org/3.0-last-rst/doc/py_tutorials/py_gui/py_video_display/py_video_display.html#display-video, half way down, there is a link with the text "Property Identifier" that takes me to a 404 (http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_video.html#videocapture-get).

**Comment by alalek** [comment]
RST documentation was deprecated and not maintained anymore in OpenCV 3.0+.
Tutorial with broken link is [here](http://docs.opencv.org/master/dd/d43/tutorial_py_video_display.html) at this moment.

BTW, cross-branch links should gone away.
