### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by morrysa7** [Itseez/opencv#5841]
Hi,

I had some cpp scripts which used to work! I changed my Ubuntu and therefore I installed the opencv from git. Now when I make the same files I receive this error:

g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -fPIE  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/local/include -o main.o main.cpp
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -fPIE  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/local/include -o dbscan.o dbscan.cpp
g++ -m64 -Wl,-O1 -o opticalFlowVideo main.o dbscan.o   `pkg-config --libs opencv libavformat libavcodec libswscale libavutil` 
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status
make: *** [opticalFlowVideo] Error 1

The same scrit still works on my older system with an older branch of Opencv.

This is my system specifications:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

And this is my opencv libs:

pkg-config --libs opencv
-L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_cudawarping -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn -lopencv_dpm -lopencv_fuzzy -lopencv_hdf -lopencv_line_descriptor -lopencv_optflow -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_rgbd -lopencv_viz -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lippicv -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_imgproc -lopencv_cudaarithm -lopencv_core -lopencv_cudev  

Thanks in advance

**Comment by Aravind-Suresh** [comment]
@morrysa7 I think ippicv library is not installed properly. Just download the source from http://sourceforge.net/projects/opencvlibrary/files/3rdparty/ippicv/ and install. If that doesn't work try making opencv again.

Make sure you don't get any error regarding ippicv while making. If you get one, put the ippicv source under opencv/3rdparty folder and make again.

I had the same problem before and I did something like this.

**Comment by alalek** [comment]
Just remove `-lippicv` from `opencv.pc` file in case of shared libraries (default) or add `-L<path to ippicv.a>` into linker command.
This problem was fixed in the latest master.

**Comment by morrysa7** [comment]
Thanks a lot
This solved the whole issue....
:dancer:

**Comment by xMoad** [comment]
Thanks you so much, i've been working on this all day

**Comment by rgborges** [comment]
Thanks very much I've solved my problem

**Comment by Jargon4072** [comment]
thanks it worked for me
