### ISSUE TITLE
Python-Binding mechanism

### ISSUE THREAD

**Issue by autosquid** [Itseez/opencv#5844]
I read the binding code under `modules/python/src2`, and I want to apply the mechanism in my own project. Is that possible and any hints on how to?

**Comment by alalek** [comment]
It is wrong place to ask "How to use Python". Anyway all OpenCV Python-related code and scripts are open and you can use it under BSD licence.

If you just want to use OpenCV python bindings, you should refer to "OpenCV-Python tutorials" [here](http://docs.opencv.org/master/).

**Comment by autosquid** [comment]
@alalek  no, I am not asking about "(how) to use OpenCV python bindings". I am asking how to re-use the binding mechanism. I.E. I want to reuse the `gen2.py` and `hdr_parser.py` in MY OWN project.

**Comment by autosquid** [comment]
@alaek  I do not think is issue should be closed now. you have a clear mis-interpretation of my question.

**Comment by alalek** [comment]
Your question is not related to OpenCV bugs/features, so it is closed.
