### ISSUE TITLE
Build fails after pulling 3.1

### ISSUE THREAD

**Issue by themightyoarfish** [Itseez/opencv#5851]
I just pulled [the master branch] (https://github.com/Itseez/opencv/commit/4cfe2b4deaf8d67013b27a4446ea6c3c902ce056) and attempted to recompile, but received this error during configuring
```
CMake Error at samples/gpu/CMakeLists.txt:100 (list):
  list sub-command REMOVE_ITEM requires list to be present
```

I then deleted the entire build directory and cmake caches and started from scratch, which gave me this
```
CMake Error at 3rdparty/ippicv/downloader.cmake:99 (message):
  ICV: Failed to unpack ICV package from /Volumes/Macintosh
  HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/downloads/macosx-4ff1fde9a7cfdfe7250bfcd8334e0f2f/ippicv_macosx_20151201.tgz
  to /Volumes/Macintosh
  HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/unpack with error
  1
Call Stack (most recent call first):
  3rdparty/ippicv/downloader.cmake:110 (_icv_downloader)
  cmake/OpenCVFindIPP.cmake:237 (include)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:537 (include)
```
The system is OSX 10.10.4 on which I successfully compiled previous versions.
Can anyone reproduce this?

**Comment by alalek** [comment]
Please add `cmake --version`

**Comment by themightyoarfish** [comment]
@alalek `cmake version 3.3.2`

**Comment by alalek** [comment]
Does "Macintosh HD" include space in the name?

Does this work?
```
mkdir -p "/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/unpack"
cd "/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/unpack"
cmake -E tar xz "/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/downloads/macosx-4ff1fde9a7cfdfe7250bfcd8334e0f2f/ippicv_macosx_20151201.tgz"
```

**Comment by themightyoarfish** [comment]
Yes, there is a space after `Macintosh` as is standard on OSX. The result of these commands is
```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/opencv/3rdparty/ippicv/downloads/macosx-4ff1fde9a7cfdfe7250bfcd8334e0f2f/ippicv_macosx_20151201.tgz
```

**Comment by alalek** [comment]
1) Spaces and/or unicode symbols in the base path cause a lot of problems. These unusual cases are not tested and may not work at all.
2) This is very strange. How did you get CMake? Try to get .dmg package and install it from [here](https://cmake.org/download/)

**Comment by themightyoarfish** [comment]
In installed it with macports.

**Comment by alalek** [comment]
Related question without answer (OS is Windows, not Mac OSX):
http://answers.opencv.org/question/74746/problem-extracting-ippicv_zip/

Unfortunately, I can't reproduce this issue, our Mac builder works fine.
Current temporary workaround: try to disable IPP (`cmake -DWITH_IPP=OFF .`)

**Comment by themightyoarfish** [comment]
I manually deleted the `3rdparty/ippicv/unpack/ippicv_osx` directory (strangely, I had to `sudo` it otherwise I got a denied permission error, might be a reason why extraction by cmake did not work) and then ran configure again, and now it passes without errors.

**Comment by alalek** [comment]
Looks like there is nothing to fix in OpenCV

**Comment by fake-name** [comment]
I'm encountering this issue when building OpenCV 3.1.0 on a Ubuntu 14.04 x64 system, so I think the root cause assumed so far is not correct.

**Comment by fake-name** [comment]
The above is with opencv and opencv_contrib cloned in ~/, and each repo checked out to 3.1.0

**Comment by alalek** [comment]
@fake-name Could you open a new issue please?

**Comment by fake-name** [comment]
@alalek  - Why? It's the same error in the output.

**Comment by alalek** [comment]
You are right! But there are described 2 problems, that is bad practice actually (one issue - one problem).
After reading of the first 5 messages it is not clear what your problem is still here (there was discussed another question).

**Comment by victorhcm** [comment]
I was facing this same issue. Make sure to disable `INSTALL_C_EXAMPLES` if you're compiling OpenCV 3.1.0:

```bash
cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=ON \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
	-D BUILD_EXAMPLES=ON ..
```

Source: [PyImageSearch][1]

[1]: http://www.pyimagesearch.com/2015/06/22/install-opencv-3-0-and-python-2-7-on-ubuntu/

**Comment by izus13** [comment]
Hi,

I am having the same issue as listed above by fake-name, my cmake output is exactly the same and has 3 config errors relating to not being able to find the following 3 files linux/videodev.h , sys/videoio.h , ffmpeg/avformat.h.   I am also running Ubuntu 14.4 on x64 system.  All listed dependencies on opencv site are installed.  I realise this post is closed but was wondering if there is a solution to this.

**Comment by izus13** [comment]
All OK, I found the problem - sorted out.

**Comment by ScottHavird** [comment]
izus13, what solved your problem? I am having the same issue. Thanks

**Comment by izus13** [comment]
Hi Scot,

As it turned out, it was my fault, the path to the Opencv-contrib package was incorrect so it could not find those header files.  Once I figured that out, it all built without any further issues.

Hope that helps,
Suzana
________________________________

**Comment by ScottHavird** [comment]
Thanks Suzana!

**Comment by DSLituiev** [comment]
Hi, I am still having this issue. I checked out 3.1.0 and running following on Ubuntu14:


cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=OFF \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D BUILD_EXAMPLES=ON ..

Then I am getting

```
...
CMake Warning at 3rdparty/ippicv/downloader.cmake:56 (message):
  ICV: Local copy of ICV package has invalid MD5 hash:
  09273fbe1fd9e7738fc49f16a79e1cd8 (expected:
  808b791a6eac9ed78d32a7666804320e)
Call Stack (most recent call first):
  3rdparty/ippicv/downloader.cmake:110 (_icv_downloader)
  cmake/OpenCVFindIPP.cmake:237 (include)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:537 (include)

-- ICV: Downloading ippicv_linux_20151201.tgz...
CMake Error at 3rdparty/ippicv/downloader.cmake:73 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/dima/external/opencv/3rdparty/ippicv/downloads/linux-808b791a6eac9ed78d32a7666804320e/ippicv_linux_20151201.tgz]
      expected hash: [808b791a6eac9ed78d32a7666804320e]
        actual hash: [09273fbe1fd9e7738fc49f16a79e1cd8]

Call Stack (most recent call first):
  3rdparty/ippicv/downloader.cmake:110 (_icv_downloader)
  cmake/OpenCVFindIPP.cmake:237 (include)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:537 (include)


CMake Error at 3rdparty/ippicv/downloader.cmake:77 (message):
  ICV: Failed to download ICV package: ippicv_linux_20151201.tgz.
  Status=18;"Transferred a partial file"
Call Stack (most recent call first):
  3rdparty/ippicv/downloader.cmake:110 (_icv_downloader)
  cmake/OpenCVFindIPP.cmake:237 (include)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:537 (include)


-- Configuring incomplete, errors occurred!
See also "/home/dima/external/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/home/dima/external/opencv/build/CMakeFiles/CMakeError.log".
```

Do you guys know any fix?

**Comment by alalek** [comment]
@DSLituiev Take a look [here](https://github.com/Itseez/opencv/issues?utf8=%E2%9C%93&q=is%3Aissue+hash+mismatch)
