### ISSUE TITLE
/usr/bin/ld: cannot find -lippicv

### ISSUE THREAD

**Issue by clarkk** [Itseez/opencv#5852]
When compiling some code I get this

```
# g++ txtbin-03.1.cpp -o txtbin `pkg-config opencv --cflags --libs`
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status
```

When compiling with `opencv 2.4` it works (opencv installed with apt-get)

Installing opencv
```
# apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
# apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
# cd /var/bin && git clone https://github.com/Itseez/opencv.git && cd opencv
# cmake . && make -j2 && make install 
```

**Comment by alalek** [comment]
Thanks for report!
Dependency from `ippicv` is wrong here and it should be removed.
Workaround: try to use `cmake -DINSTALL_CREATE_DISTRIB=ON .`

**Comment by clarkk** [comment]
If you compile like this is looks like it works

`cmake -DWITH_IPP=ON . && make -j $(nproc) && make install`

**Comment by Vishruit** [comment]
Wrongly associated library path!
`find` /usr/local/ -name `"libippicv*"`
Add the path returned to the LIBS path or you can symlink libippicv.a to /usr/local/lib 
[Source ](https://iotmakerblog.wordpress.com/category/computer-vision/)

**Comment by zimenglan-sysu-512** [comment]
hi @Vishruit,
i follow ur way to `ln -s`, it works.
thanks.
