### ISSUE TITLE
opencv_perf_features2d fails

### ISSUE THREAD

**Issue by photoszzt** [Itseez/opencv#5863]
When I run the perf tests on opencv-3.1.0, the features2d perf test fails:
```
[  FAILED  ] agast_detect.detect/0, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_5_8)
[  FAILED  ] agast_detect.detect/1, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12d)
[  FAILED  ] agast_detect.detect/2, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12s)
[  FAILED  ] agast_detect.detect/3, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", OAST_9_16)
[  FAILED  ] agast_detect.detect/4, where GetParam() = ("stitching/a3.png", AGAST_5_8)
[  FAILED  ] agast_detect.detect/5, where GetParam() = ("stitching/a3.png", AGAST_7_12d)
[  FAILED  ] agast_detect.detect/6, where GetParam() = ("stitching/a3.png", AGAST_7_12s)
[  FAILED  ] agast_detect.detect/7, where GetParam() = ("stitching/a3.png", OAST_9_16)
```
The problem is the actual rows are 10 times as the expected rows. 

The detail test logs: 
```
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 2977
Expected: expect_rows
Which is: 229
Argument "points-pt" has unexpected number of rows

params    = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_5_8)
termination reason:  unknown
bytesIn   =     540000
bytesOut  =          0
samples   =         13 of 100
outliers  =          1
frequency = 1000000000
min       =    1235726 = 1.24ms
median    =    1239048 = 1.24ms
gmean     =    1244751 = 1.24ms
gstddev   = 0.01064570 = 0.08ms for 97% dispersion interval
mean      =    1244816 = 1.24ms
stddev    =      13396 = 0.01ms
[  FAILED  ] agast_detect.detect/0, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_5_8) (41 ms)
[ RUN      ] agast_detect.detect/1
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 6520
Expected: expect_rows
Which is: 652
Argument "points-pt" has unexpected number of rows

params    = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12d)
termination reason:  unknown
bytesIn   =     540000
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1514853 = 1.51ms
median    =    1537149 = 1.54ms
gmean     =    1539759 = 1.54ms
gstddev   = 0.01363964 = 0.13ms for 97% dispersion interval
mean      =    1539888 = 1.54ms
stddev    =      21071 = 0.02ms
[  FAILED  ] agast_detect.detect/1, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12d) (36 ms)
[ RUN      ] agast_detect.detect/2
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 7060
Expected: expect_rows
Which is: 706
Argument "points-pt" has unexpected number of rows

params    = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12s)
termination reason:  unknown
bytesIn   =     540000
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1472958 = 1.47ms
median    =    1489972 = 1.49ms
gmean     =    1499683 = 1.50ms
gstddev   = 0.01969603 = 0.18ms for 97% dispersion interval
mean      =    1499948 = 1.50ms
stddev    =      30100 = 0.03ms
[  FAILED  ] agast_detect.detect/2, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", AGAST_7_12s) (35 ms)
[ RUN      ] agast_detect.detect/3
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 6490
Expected: expect_rows
Which is: 649
Argument "points-pt" has unexpected number of rows

params    = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", OAST_9_16)
termination reason:  unknown
bytesIn   =     540000
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1695402 = 1.70ms
median    =    1708442 = 1.71ms
gmean     =    1713296 = 1.71ms
gstddev   = 0.01143532 = 0.12ms for 97% dispersion interval
mean      =    1713398 = 1.71ms
stddev    =      19775 = 0.02ms
[  FAILED  ] agast_detect.detect/3, where GetParam() = ("cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png", OAST_9_16) (38 ms)
[ RUN      ] agast_detect.detect/4
/home/zhitingz/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 900
Expected: expect_rows
Which is: 90
Argument "points-pt" has unexpected number of rows

params    = ("stitching/a3.png", AGAST_5_8)
termination reason:  unknown
bytesIn   =     460800
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =     961582 = 0.96ms
median    =     966828 = 0.97ms
gmean     =     971178 = 0.97ms
gstddev   = 0.01144556 = 0.07ms for 97% dispersion interval
mean      =     971235 = 0.97ms
stddev    =      11195 = 0.01ms
[  FAILED  ] agast_detect.detect/4, where GetParam() = ("stitching/a3.png", AGAST_5_8) (27 ms)
[ RUN      ] agast_detect.detect/5
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 8710
Expected: expect_rows
Which is: 871
Argument "points-pt" has unexpected number of rows

params    = ("stitching/a3.png", AGAST_7_12d)
termination reason:  unknown
bytesIn   =     460800
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1478922 = 1.48ms
median    =    1501354 = 1.50ms
gmean     =    1512031 = 1.51ms
gstddev   = 0.02125847 = 0.19ms for 97% dispersion interval
mean      =    1512342 = 1.51ms
stddev    =      32652 = 0.03ms
[  FAILED  ] agast_detect.detect/5, where GetParam() = ("stitching/a3.png", AGAST_7_12d) (33 ms)
[ RUN      ] agast_detect.detect/6
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 8510
Expected: expect_rows
Which is: 851
Argument "points-pt" has unexpected number of rows

params    = ("stitching/a3.png", AGAST_7_12s)
termination reason:  unknown
bytesIn   =     460800
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1420835 = 1.42ms
median    =    1450404 = 1.45ms
gmean     =    1445571 = 1.45ms
gstddev   = 0.01071659 = 0.09ms for 97% dispersion interval
mean      =    1445645 = 1.45ms
stddev    =      15476 = 0.02ms
[  FAILED  ] agast_detect.detect/6, where GetParam() = ("stitching/a3.png", AGAST_7_12s) (32 ms)
[ RUN      ] agast_detect.detect/7
~/Downloads/opencv-3.1.0/modules/ts/src/ts_perf.cpp:370: Failure
Value of: actual.size.p[0]
  Actual: 8950
Expected: expect_rows
Which is: 895
Argument "points-pt" has unexpected number of rows

params    = ("stitching/a3.png", OAST_9_16)
termination reason:  unknown
bytesIn   =     460800
bytesOut  =          0
samples   =         10 of 100
outliers  =          0
frequency = 1000000000
min       =    1839543 = 1.84ms
median    =    1851260 = 1.85ms
gmean     =    1852928 = 1.85ms
gstddev   = 0.00918888 = 0.10ms for 97% dispersion interval
mean      =    1852999 = 1.85ms
stddev    =      17187 = 0.02ms
[  FAILED  ] agast_detect.detect/7, where GetParam() = ("stitching/a3.png", OAST_9_16) (36 ms)
[----------] 8 tests from agast_detect (278 ms total)
```

**Comment by alalek** [comment]
We have regular test runs on our buildbot and don't see this issue. Also "testdata" should be updated to same version (opencv_extra repo)

**Comment by photoszzt** [comment]
This is my configure. I am using the 3.1.0 testdata. I also tried using the master of opencv and opencv_extra cloned from git repo and they all have the same failure. I'm building it using Ubuntu 14.04 LTS. 

-- General configuration for OpenCV 3.1.0 =====================================
--   Version control:               unknown
-- 
--   Platform:
--     Host:                        Linux 3.13.0-73-generic x86_64
--     CMake:                       2.8.12.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
-- 
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /usr/bin/c++  (ver 4.8.4)
--     C++ flags (Release):         -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      
--     Linker flags (Debug):        
--     Precompiled headers:         YES
--     Extra dependencies:          /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libtiff.so /usr/lib/x86_64-linux-gnu/libjasper.so /usr/lib/x86_64-linux-gnu/libjpeg.so gtk-3 gdk-3 atk-1.0 gio-2.0 pangocairo-1.0 gdk_pixbuf-2.0 cairo-gobject pango-1.0 cairo gobject-2.0 gthread-2.0 glib-2.0 stdc++ dl m pthread rt
--     3rdparty dependencies:       libwebp
-- 
--   OpenCV modules:
--     To be built:                 core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3 viz
-- 
--   GUI: 
--     QT:                          NO
--     GTK+ 3.x:                    YES (ver 3.10.8)
--     GThread :                    YES (ver 2.40.2)
--     GtkGlExt:                    NO
--     OpenGL support:              NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.2.50)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 - 4.0.3)
--     JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
--     OpenEXR:                     NO
--     GDAL:                        NO
-- 
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      NO
--       codec:                     NO
--       format:                    NO
--       util:                      NO
--       swscale:                   NO
--       resample:                  NO
--       gentoo-style:              NO
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     UniCap:                      NO
--     UniCap ucil:                 NO
--     V4L/V4L2:                    NO/NO
--     XIMEA:                       NO
--     Xine:                        NO
--     gPhoto2:                     NO
-- 
--   Parallel framework:            pthreads
-- 
--   Other third-party libraries:
--     Use IPP:                     NO
--     Use IPP Async:               NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Eigen:                   NO
--     Use Cuda:                    NO
--     Use OpenCL:                  NO
--     Use custom HAL:              NO
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
--     Libraries:                   NO
--     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)
--     packages path:               lib/python2.7/dist-packages
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:
--     ant:                         /usr/bin/ant (ver 1.9.3)
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:                        Matlab not found or implicitly disabled
-- 
--   Documentation:
--     Doxygen:                     NO
--     PlantUML:                    NO
-- 
--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           YES
--     C/C++ Examples:              NO
-- 
--   Install path:                  /usr/local
-- 
--   cvconfig.h is in:              /home/zhitingz/Downloads/opencv-3.1.0_build
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhitingz/Downloads/opencv-3.1.0_build

**Comment by photoszzt** [comment]
The cmake configure I am using is: 

cmake -DBUILD_SHARED_LIBS=OFF \
           -DWITH_FFMPEG=OFF \
           -DWITH_OPENEXR=OFF \
           -DWITH_CUDA=OFF \
           -DWITH_OPENCL=OFF \
           -DWITH_1394=OFF \
           -DWITH_V4L=OFF \
           -DWITH_IPP=OFF \
           -DWITH_PTHREADS_PF=ON \
           -DWITH_GDAL=OFF \
           -DBUILD_opencv_java=OFF

**Comment by alalek** [comment]
Thanks for update!
Looks like performance test or AGAST implementation don't allow to call detection multiple times.

Could you run test with `--perf_min_samples=1 --perf_force_samples=1` parameters?

```
Actual: 6520
Expected ... 652
samples = 10 of 100
```
Seems that keypoints are not cleared and collected again and again.

**Comment by photoszzt** [comment]
Yes. I can run test with --perf_min_samples=1 --perf_force_samples=1 successfully.
