### ISSUE TITLE
OpenCV 3.1.0 simple VideoCapture and waitKey crashes after a while on OS X 10.11.2

### ISSUE THREAD

**Issue by mahiuchun** [Itseez/opencv#5874]
OpenCV 3.1.0 is installed through `brew install opencv3 --with-contirb --with-qt5` and the following program crashes after a while:
```c++
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/videoio.hpp>

int main(int argc, const char * argv[]) {
    cv::VideoCapture cap(0);
    cv::Mat frame;
    while (cap.read(frame)) {
        imshow("Frame", frame);
        if (cv::waitKey(1) == 'q') {
            break;
        }
    }
    return 0;
}
```

The stack trace is the following:
```
2015-12-24 09:54:22.297 basic-capture[86100:4481590] -[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x103600680
2015-12-24 09:54:22.313 basic-capture[86100:4481590] An uncaught exception was raised
2015-12-24 09:54:22.313 basic-capture[86100:4481590] -[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x103600680
2015-12-24 09:54:22.313 basic-capture[86100:4481590] (
	0   CoreFoundation                      0x00007fff95766ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff90699f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff95769b9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff956a2601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff956a2188 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00007fff9c7d385b __NSFireTimer + 95
	6   CoreFoundation                      0x00007fff956acbc4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	7   CoreFoundation                      0x00007fff956ac853 __CFRunLoopDoTimer + 1075
	8   CoreFoundation                      0x00007fff9572ae6a __CFRunLoopDoTimers + 298
	9   CoreFoundation                      0x00007fff95667cd1 __CFRunLoopRun + 1841
	10  CoreFoundation                      0x00007fff95667338 CFRunLoopRunSpecific + 296
	11  HIToolbox                           0x00007fff8f2f3935 RunCurrentEventLoopInMode + 235
	12  HIToolbox                           0x00007fff8f2f3677 ReceiveNextEventCommon + 184
	13  HIToolbox                           0x00007fff8f2f35af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	14  AppKit                              0x00007fff967d10ee _DPSNextEvent + 1067
	15  AppKit                              0x00007fff96b9d943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	16  libqcocoa.dylib                     0x000000010555ae5a _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 1034
	17  libopencv_highgui.3.1.dylib         0x000000010083c596 cvWaitKey + 178
	18  basic-capture                       0x0000000100001666 main + 246
	19  libdyld.dylib                       0x00007fff8a0335ad start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
2015-12-24 09:54:22.314 basic-capture[86100:4481590] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x103600680'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff95766ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff90699f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff95769b9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff956a2601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff956a2188 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00007fff9c7d385b __NSFireTimer + 95
	6   CoreFoundation                      0x00007fff956acbc4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	7   CoreFoundation                      0x00007fff956ac853 __CFRunLoopDoTimer + 1075
	8   CoreFoundation                      0x00007fff9572ae6a __CFRunLoopDoTimers + 298
	9   CoreFoundation                      0x00007fff95667cd1 __CFRunLoopRun + 1841
	10  CoreFoundation                      0x00007fff95667338 CFRunLoopRunSpecific + 296
	11  HIToolbox                           0x00007fff8f2f3935 RunCurrentEventLoopInMode + 235
	12  HIToolbox                           0x00007fff8f2f3677 ReceiveNextEventCommon + 184
	13  HIToolbox                           0x00007fff8f2f35af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	14  AppKit                              0x00007fff967d10ee _DPSNextEvent + 1067
	15  AppKit                              0x00007fff96b9d943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	16  libqcocoa.dylib                     0x000000010555ae5a _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 1034
	17  libopencv_highgui.3.1.dylib         0x000000010083c596 cvWaitKey + 178
	18  basic-capture                       0x0000000100001666 main + 246
	19  libdyld.dylib                       0x00007fff8a0335ad start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ahundt** [comment]
I can confirm issues with waitkey crashing frequently on OS X.

**Comment by alalek** [comment]
Please add result of `cv::getBuildInformation()`

**Comment by mahiuchun** [comment]
Attached
[buildInfo.txt](https://github.com/Itseez/opencv/files/73536/buildInfo.txt)

**Comment by alalek** [comment]
Thanks!
QT backend is used here for UI interaction.
Are you able to reproduce this problem with Cocoa backend?

**Comment by kesinger** [comment]
I'm seeing a similar problem with a similar program and what I thought was the Cocoa backend.   A slightly censored file is attached with the output from cv::getBuildInformation() and the stacktraces. 

One thing I noticed is when I step through in a debugger is I get breakpoints triggered at constant locations in cap_qtkit.mm.  Line 335 always triggers twice, then line 299 triggers twice, then 435 triggers once, then the program works as intended.

[buildinfo.txt](https://github.com/Itseez/opencv/files/79240/buildinfo.txt)

**Comment by alalek** [comment]
@kesinger Thanks for information! QT framework is not used in your build, but problem is still here.

Looks like, both QTKit capture + cv::waitKey are required to reproduce this bug.

**Comment by Tobiasgeek** [comment]
Hi,

I am also have the same issue, but I'm not using the QT framework. My program is just plain simple c++ running on Xcode.

The error occurs after a couple of minutes my video capture c++ program. I even tried on a simple video capture program, and it repeats the same error.

[openCV-error.txt](https://github.com/Itseez/opencv/files/85380/openCV-error.txt)

[openCV-config.txt](https://github.com/Itseez/opencv/files/85379/openCV-config.txt)

**Comment by gbumgard** [comment]
Same install as OP, same stack trace, same problem. I did not see this in OpenCV 3.0. However, I also upgraded to 10.11 (El Capitan) near same time (which now I regret - SIP in OS X complicated the build process for latest versions of OpenCV+CUDA/cuDNN+Caffe w/Python2.7).

**Comment by Tobiasgeek** [comment]
I'm using Yosemite 10.10, and I just downgraded to 3.0.0 and works pretty good. I need to run the program for longer period of time to see. But at the moment everything seems fine.

**Comment by gbumgard** [comment]
Reverting to 3.0 also solved the problem for me under OSX 10.11.

**Comment by BuiltInParris** [comment]
Also experiencing this problem with OpenCV 3.1.0, OSX version 10.11.2.

**Comment by mron** [comment]
Same  problem with OpenCV 3.1.0, OSX version 10.11.2. Not using cv::waitKey().

**Comment by mron** [comment]
Same problem with OpenCV 3.0.0, OSX version 10.11.2. Not using cv::waitKey(). Should I be?
-[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x60800007e980

**Comment by mron** [comment]
Found this in: "opencv-3.1.0/modules/videoio/src/cap_qtkit.mm"
....
bool CvCaptureCAM::grabFrame(double timeOut)
// Create a dummy timer so that runUntilDate does not exit immediately:
[NSTimer scheduledTimerWithTimeInterval:100 target:capture selector:@selector(doFireTimer:) userInfo:nil repeats:YES];

This looks like it runs about 100sec then looks for doFireTimer.
I can't find doFilreTimer().

**Comment by rtielking** [comment]
I can confirm consistent crash exactly 100 seconds after starting my program.  I also have OS X 10.11.2 and OpenCV 3.1.0 using the VideoCapture class.

**Comment by mron** [comment]
This code doesn't make sense to me:
...
    [NSTimer scheduledTimerWithTimeInterval:100 target:nil selector:@selector(doFireTimer:) userInfo:nil repeats:YES];
    while (![capture updateImage] && (total += sleepTime)<=timeOut) {
        [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:sleepTime]];
    }
...

The first line : " [NSTimer scheduledTimerWithTimeInterval ... " adds a timer to the current run loop, which isn't created until the while loop is executed. The "while" loop creates run loops to act essentially like sleep(). I don't think run loops act that way.  [NSThread sleepForTimeInterval:] might work if there is a separate thread running. Also, if the timer is needed, it should be invalidated when no longer needed, and fixed so it references a valid object.

**Comment by alalek** [comment]
There is a patch for file cap_qtkit.mm between OpenCV 3.0.0 and OpenCV 3.1.0:
https://github.com/Itseez/opencv/commit/e8bf4417ef7afbebf08283eb50147c12e1bf7b03#diff-2a81486ed8ebf4c35433ebaa5f2c5e75
Could someone revert this fix for cap_qtkit.mm and re-check this problem?
`target:capture` --> `target:nil`

@mron Could you try to use dummy cv::waitKey call (OpenCV 3.0.0):
```
void main(...)
{
    cv::waitKey(1);
    ... your code without waitKey ...
}
```

**Comment by mron** [comment]
I'm very new to opencv and github, so please bear with me. I did try putting the waitKey() call in. The timer still fires and crashes. Changing "nil" to "capture" will not help unless a "doFireTimer:" method is added to the capture's ( CaptureDelegate? ) class. I'm also new to objc.. sorry.

**Comment by jackyliang** [comment]
@rtielking did you fix this? I timed the code, and it crashes in exactly 100 seconds.

**Comment by rtielking** [comment]
yes i was able to fix the crash at 100sec by commenting out the following line

[NSTimer scheduledTimerWithTimeInterval:100 target:capture selector:@selector(doFireTimer:) userInfo:nil repeats:YES];

in the /modules/videoio/src/cap_qtkit.mm file and recompiling

**Comment by jackyliang** [comment]
@rtielking I believe I installed OpenCV through Homebrew + Luarocks - how would I recompile it manually?

**Comment by rtielking** [comment]
Download the source at https://github.com/Itseez/opencv/archive/3.1.0.zip
and extract the source code.  Install XCode from Apple's App Store so you will have the developer tools you need.  Find the line I mentioned above and comment it out.  Then open a terminal and cd to the directory where you extracted the source code and run the following commands:

brew install cmake
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE ..
make -j4
sudo make install

Then it should work for you on the mac.

**Comment by jackyliang** [comment]
@rtielking following these instructions should theoretically allow my program to know which OpenCV version to use right? Should I remove my existing OpenCV installation first?

**Comment by rtielking** [comment]
Might be a good idea to remove existing installation first just to be sure.  I always built from source, so don't know where brew puts things when it installs.

**Comment by jackyliang** [comment]
@rtielking I compiled it.. commented out the line with the `100`.. Then re-compiled it using the build instructions. However, the crash still happened at the 100 mark =/ I am also not 100% sure if the old installation is gone even though I deleted that folder.

**Comment by mron** [comment]
I was able to recompile with the line commented out. The crashes have stopped.

**Comment by cedricve** [comment]
Having the same issue

**Comment by shawnsnyder** [comment]
Same issue here.  Reverting to 3.0....

**Comment by alalek** [comment]
Could someone check this fix: #6051?

**Comment by rtielking** [comment]
i'll check

**Comment by rtielking** [comment]
I have verified that 3.1.0 crashes at 100 seconds on El Capitan 10.11.3 and fix #6051 fixed the crash issue.  Thanks.

**Comment by cedricve** [comment]
Still crashes after applying patch on Yosemite.

**Comment by MikemanGit** [comment]
Could someone tell me exactly how to apply this patch ? (sorry for the now question)

**Comment by mron** [comment]
I don’t understand github enough to help. I just changed my local copy.
Sorry,
Ron

**Comment by MikemanGit** [comment]
I also changed the local copy, but didn't solved the problem. How did you recompile the file ? Or what steps do you took exactly to fix this ? Sorry for all the questions, but I need it for my theses. Thanks anyway !

**Comment by mron** [comment]
You have to tell Xcode to delete the cached versions of the library. I'm not sitting at the computer now, so I can't tell you how. It has to do with deleting "derived data". You can look it up. It took me a few tries to get rid of it properly. When I get home I'll look at how I did it. Xcode has so many layers, I don't remember off hand.

Ron

**Comment by shawnsnyder** [comment]
@MikemanGit  hi Mike, this lovely person made a pretty great tutorial on rebuilding opencv with Make. 
http://blogs.wcode.org/2014/10/howto-install-build-and-use-opencv-macosx-10-10/
like mron said, you will want to make sure your xcode project isn't holding on to any residual libs.  inside your project after you install a fresh opencv, go to window -> projects and click delete on your derived data.  afterwards you will want to 'clean' your project with product -> clean.  
side note, videocapture.read() with webcams has a pretty nasty mem leak on osx 10.11 that seems to still exist in the master branch.  if your camera reading needs to happen for a long time, you might want to stick to opencv2

**Comment by FredFG** [comment]
I had a similar problem. If you have previously build OpenCV version 2 you need to deleted the old dylibs (dynamic libraries) before you "make install".
1--Using terminal, go to  /usr/local/lib
2-- run ls -la
3-- you should see the older dylibs such as "highgui.2.4..." etc.
Remove all the "old" dylibs (anything with version 2...... etc)
It's actually easier to remove ALL the OpenCv and libdc1394 dylibs.

CMake will re-install them.

**Comment by MikemanGit** [comment]
Managed to fix it, thanks guys !

**Comment by ottogutierrez** [comment]
Thank you for your help! this worked perfect

**Comment by mateuszmikusz** [comment]
If you use Homebrew, you can also do `brew install --HEAD opencv3` to get the newest release from the GitHub repository which consists of the above mentioned fix (probably uninstall the previous version first). Keep in mind though that this is installing the newest code base which is not stable and may introduce other bugs.

**Comment by LukasKalinski** [comment]
Same error and same stack trace here. Did the following:
**brew remove opencv3** (effectively cleaned everything and Xcode immediately noticed it)
**brew cleanup**
**brew install --HEAD opencv3**
(might be unstable, but hopefully more stable than current 3.1)

**Comment by Ghifarahadian** [comment]
Hi guys. Thank you for all the advices. I reinstall the opencv yet I still have the problem.

Im running Yosemite version 10.10.5 and I also install opencv_contrib. Any suggestions? Or perhaps downgrading is the only way to go. How to downgrade it? Thank you

**Comment by mron** [comment]
I’m not familiar with github enough to help. Maybe send a more descriptive message about your install procedure and someone with more understanding can help.

**Comment by Ghifarahadian** [comment]
I am using this (https://github.com/Itseez/opencv_contrib) to install. Oh and initially i use this (https://www.youtube.com/watch?v=U49CVY8yOxw) to install openCV 3.1.0 on Mac. I am not sure whether the openCV installed this way is removed when using `brew remove opencv3`

**Comment by geraldstanje** [comment]
hi, is this issue already solved?

**Comment by zhonghh** [comment]
Same problem, after a few captures the opencv crashes. I am using python bindings in Mac. This makes video capture unusable. I have to rely on some other frameworks to do the job.

**Comment by casparwylie** [comment]
any fixes for python bindings ? Deleting derived data is irrelevant in this case unfortunately.. cheers.

**Comment by hndr91** [comment]
I have same problem in Sierra 10.12. v3.1.0 installed from anaconda

**Comment by mron** [comment]
There was a very simple fix that was never folded into the main branch. Look back into the bug history and you'll find it.

Ron

**Comment by jkearse3** [comment]
Having this same problem on OSX 10.10.5. Any update on the fix?

**Comment by mron** [comment]
Wow,
It was never folded in?

Ron

**Comment by susanbhattarai** [comment]
Having the same problem on OSX 10.11.5 . I am using the python interface for opencv2

**Comment by jkearse3** [comment]
Bumping the issue. By any chance could this be reopened so that a fix can happen to the repo?

**Comment by mron** [comment]
I know this was “fixed” over a year ago. I didn’t know github and how it works to pursue getting the fix folded into the main line of the code.
Ron

**Comment by nuksss** [comment]
I use Anaconda for Python and Opencv on my Mac. How shall I recompile if that's the case?

**Comment by mron** [comment]
How did you download OpenCV?

Ron

**Comment by alexscluk** [comment]
in anaconda prompt, type in:

_conda install -c menpo opencv3_

according to this website:

[https://anaconda.org/menpo/opencv3](https://anaconda.org/menpo/opencv3)

**Comment by ahundt** [comment]
I created https://github.com/opencv/opencv/issues/8931 so hopefully it can actually be fixed. :-)

**Comment by mron** [comment]
I hope so!
Thanks.

Ron

**Comment by ShangxuanWu** [comment]
This issue still occurs. OSX 10.12.5 with python 2.7.13 and python-opencv2

**Comment by htzy** [comment]
me too.
2017-09-20 23:20:24.579 python2.7[17999:2038663] -[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x7facf99ed4f0

**Comment by vasyaivanov** [comment]
Is someone looking at this issue?
Or at least, how can we install OpenCV 3.0? It seams brew or Pycharm can see only 3.1 and above.
Thanks.

**Comment by ahundt** [comment]
If you're still having this problem with the latest release say so on #8931
