### ISSUE TITLE
FaceRecognizer::predict(...) could provide more than one match

### ISSUE THREAD

**Issue by ptheofan** [Itseez/opencv#5885]
FaceRecognizer::predict at the moment returns a result for a single best match. It would be really nice if we could provide a maxCount of possible matches and get a list of labels and scores (currently returns only 1). 

Extending the existing classes is always an option but given that a lot of people use java or python bindings and with the class internals not being exposed there the only option is to extend the class in cpp, compile the bindings, etc. so it would make sense to actually have it by default?

According to http://answers.opencv.org/question/3494/adding-new-method-in-facerecognizer/ this is something quite a few people have been searching for.

**Comment by mshabunin** [comment]
The _face_ module is part of opencv_contrib repository and it has own issue tracker.

BTW, take a look at the related PR: https://github.com/Itseez/opencv_contrib/pull/465, feel free to comment.
