### ISSUE TITLE
opencv/cmake/OpenCVDetectOpenCL.cmake - alternative OPENCL_INCLUDE_DIR

### ISSUE THREAD

**Issue by mpekalski** [Itseez/opencv#5886]
I was trying to compile OpenCV using AMDAPPSDK-3.0 for OpenCL part, but it was failing all the time on providing cmake with OPENCL_INCLUDE_DIR.

In **opencv/cmake/OpenCVDetectOpenCL.cmake** lines 7-11
```
else(APPLE)
  set(OPENCL_FOUND YES)
  set(HAVE_OPENCL_STATIC OFF)
  set(OPENCL_INCLUDE_DIR "${OpenCV_SOURCE_DIR}/3rdparty/include/opencl/1.2")
endif(APPLE)
```
override variable **OPENCL_INCLUDE_DIR** so it is not possible to set a different include dir than the one provided by the package. So the line 23
```
CMAKE_FLAGS "-DINCLUDE_DIRECTORIES:STRING=${OPENCL_INCLUDE_DIR}"
```

After commenting the line 
```
set(OPENCL_INCLUDE_DIR "${OpenCV_SOURCE_DIR}/3rdparty/include/opencl/1.2")
```
everything went fine.

**Comment by alalek** [comment]
There is "WITH_OPENCL" option that enables/disables this automatic detection. So you can try this:
```
cmake -DWITH_OPENCL=OFF -DHAVE_OPENCL=ON =DHAVE_OPENCL_STATIC=ON -DOPENCL_LIBRARIES=... -DOPENCL_INCLUDE_DIRS=... 
```

**Comment by mpekalski** [comment]
Thanks, it worked. I did not think about having HAVE_OPENCL=ON and WITH_OPENCL=OFF at once. When I used those it worked, I mean it changed the libraries.

One as probably one would like to use clBLAS and clFFT he has to remember about but setting
```
-DWITH_OPENCLAMDFFT=ON 
-DHAVE_CLAMDFFT=ON
-DCLAMDFFT_ROOT_DIR=...
-DCLAMDFFT_INCLUDE_DIR=...
```
and
```
-DWITH_OPENCLAMDBLAS=ON
-DHAVE_CLAMDBLAS=ON
-DCLAMDBLAS_ROOT=...
-DCLAMDBLAS_INCLUDE_DIR=...
```

**Comment by mpekalski** [comment]
I did not think about using WITH_OPENCL=OFF and HAVE_OPENCL=ON, it is not that intuitive but clever. 

I do not know if it is an issue but in your solution include path is not listed in the summary:

```
--   OpenCL:
--     Version:                     dynamic
--     Include path:
--     libraries:                   /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
--     Use AMDFFT:                  YES
--     Use AMDBLAS:                 YES
```

with my solution all CL* include dirs get listed
```
--   OpenCL:
--     Version:                     dynamic
--     Include path:                /opt/AMDAPPSDK-3.0/include /opt/cfFFT/include /opt/clBLAS/include
--     libraries:                   /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
--     Use AMDFFT:                  YES
--     Use AMDBLAS:                 YES
-- 
```
