### ISSUE TITLE
loading SVM model not supported in python

### ISSUE THREAD

**Issue by DarwinsBuddy** [Itseez/opencv#5891]
I'm using OpenCV 3.0-beta and it seems that, according to my experience with the ml python module and various sites (e.g. http://answers.opencv.org/question/75077/opencv-300-python-svmload-is-missing/), the possiblity to load a serialized and stored svm from disk is not properly wrapped in the python bindings.

The issue could be related to #4969 or even be the same.

Is there someone currently working on this issue?

**Comment by DarwinsBuddy** [comment]
I wanted to provide a fix for this issue, but unfortunately the automatic build failed simply for differing ABI definitions. This is an intended solution, since I wrapped 2 functions for the python API.
I'm new to contributing to this project. I appreciate anyone, who helps me out and shows me what documentation I haven't read to fix this issue.

**Comment by gat3way** [comment]
Please do the same for ANN_MLP as it is affected by the same issue.
