### ISSUE TITLE
cmake gui cannot download necessary files

### ISSUE THREAD

**Issue by ardeal** [Itseez/opencv#5895]
I am trying to configure opencv 3.1.0 with cmake gui on Windows 8.1 and Visual studio 2013. 
during configuring, sever files cannot be downloaded from your server, such as:
Downloading ffmpeg_version.cmake...
  https://raw.githubusercontent.com/Itseez/opencv_3rdparty/8aeefc4efe3215de89d8c7e114ae6f7a6091b8eb/ffmpeg/ffmpeg_version.cmake

it seems that cmake cannot connect to the server without proxy.

Can you provide solution for my issue?

![image](https://cloud.githubusercontent.com/assets/6227348/12027819/0fe10e22-ae08-11e5-9237-d37ff67379ee.png)

**Comment by alalek** [comment]
Download these files manually or disable these dependencies: `-DWITH_IPP=OFF -DWITH_FFMPEG=OFF` via CMake parameters.

**Comment by ddurgaprasad** [comment]
Could you provide the link for download ?

**Comment by alalek** [comment]
3 files (2x `.dll` + `.cmake`) is needed from here:
https://github.com/Itseez/opencv_3rdparty/tree/ffmpeg/master_20150703/ffmpeg

**Comment by yirgagithub** [comment]
Turn off any extension and your anti-virus this worked for me
