### ISSUE TITLE
OpenCV 3.1.0 CvCascadeImageReader::NegReader::create() has a bug

### ISSUE THREAD

**Issue by YonatanSimson** [Itseez/opencv#5896]
dirname is not initialized. What i think the developer meant to do was:

    string dirname, str;//dirname - was not in use
    std::ifstream file(_filename.c_str());

    dirname = GetDirName(_filename);

    if ( !file.is_open() )
        return false;

    while( !file.eof() )
    {
        std::getline(file, str);
        if (str.empty()) break;
        if (str.at(0) == '#' ) continue; /* comment */
        imgFilenames.push_back(dirname + str);//append file name to directory
    }
    file.close();

For windows my function for getting the dirname is:

    inline std::string GetDirName(std::string filePath)
    {
    	//Get GT filename
    	char drive[_MAX_DRIVE];
    	char dir[_MAX_DIR];
    	char fname[_MAX_FNAME];
    	char ext[_MAX_EXT];
        _splitpath_s( filePath.c_str(), drive, dir, fname, ext);
               
        return std::string (drive) + std::string (dir);
    }

**Comment by StevenPuttemans** [comment]
I am afraid that the variable is still old code which was not deleted. It is not used anywhere else in code so just adding functionality for it seems useless. I suggest removing it with a PR, if you are up to it, else I will do it for you!

**Comment by pranavg189** [comment]
Hi, i want to work on this pull request....any ideas on how to approach this bug...?

**Comment by pranavg189** [comment]
I have made the necessary changes....please review it....

**Comment by YonatanSimson** [comment]
Looks fine to me.
