### ISSUE TITLE
cvtColor COLOR_BGRA2GRAY does not work correctly

### ISSUE THREAD

**Issue by Motherboard** [Itseez/opencv#5898]
When converting an BGRA image to a grayscale one, the Alpha channel has to be taken into account, i.e. render the color intensity wherever the Alpha channel is 255, and fade to white for any different value.
The current implementation just ignores the alpha channel completely, which makes some images render incorrectly.

**Comment by ejoebstl** [comment]
I'd disagree. Using the alpha channel to change the color like you describe just assumes white as background color.

While this might be useful for your use-case, it's probably not for a general purpose function.

**Comment by Motherboard** [comment]
It is what matlab does... Some ARGB images encode the image on the alpha channel and use the RGB with color blobs or rectangles.
Currently, loading such an image would result in something that does not even resemble the intended rendering regardless of background color.

It would be a nice option to specify the background color and fade to that, but with no background color specified, white would be a good default to be consistent with most image viewers and Matlab.

**Comment by alalek** [comment]
You should make alpha-blending yourself with wanted background color/image to RGB/RGBx image. And after that call `cvtColor` where alpha channel is not used.
