### ISSUE TITLE
Brightness and Contrast

### ISSUE THREAD

**Issue by CoderSquirrel** [Itseez/opencv#5900]
Hi, i'm using opencv at my last year project, for the default image processing i have i was using GIMP, to find the right contrast that i need to my image, i found that the value must be set as 40, in a scale of  -127 to 127. But in opencv, follow the exemple found at the docs, its values goes only to 1 to 3, alpha value (gain). 
I'm quite new at image processing and i'm struggling at it.
Do you guys know what i'm missing to get the range of -127 to 127 like gimp to set the contrast?

**Comment by alalek** [comment]
This is not a good place to ask questions. Please use more appropriate platform for this: http://answers.opencv.org/
