### ISSUE TITLE
FFMPEG latest: cv2.VideoWriter.write not working

### ISSUE THREAD

**Issue by dista** [Itseez/opencv#5903]
latest master version:

```
commit 8d79285d027ecee2da7a74f8ea01f0476fcbabb5
Merge: 5fa6423 96654f0
Author: Alexander Alekhin <alexander.alekhin@itseez.com>
Date:   Thu Dec 24 10:08:58 2015 +0000

    Merge pull request #5840 from paroj:v4ldefault
````

I use python, and try following code:

```
import cv2 
import sys 
import json
import os


video_capture = cv2.VideoCapture('http://10.33.0.68/channels/preview/1/flv:500k')

fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while True:
    ret, frame = video_capture.read()

    print ret 

    out.write(frame)
```

upstream is an http/flv,   the problem is the generated output.avi is always 5.6KB
```
-rw-r--r-- 1 root root 5.6K Dec 31 11:54 output.avi
```
I assume it is avi header.

the opencv is build with ffmpeg & python.  

ffmpeg is the lasted master version:
```
commit 780c4223a54396c3b352608002428fae7f378996
Author: Paul B Mahol <onemda@gmail.com>
Date:   Sun Dec 13 12:56:30 2015 +0100

    avfilter/af_sofalizer: remove reorder hack
    
    Signed-off-by: Paul B Mahol <onemda@gmail.com>

```

**Comment by alalek** [comment]
There is no chance to chase for latest ffmpeg code. Try to use stable (and better tested) ffmpeg releases.

**Comment by dista** [comment]
I tried ffmpeg-2.8.4, but still not working,
my ffmpeg configure command:
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --enable-gpl --enable-nonfree --enable-libfreetype --enable-libx264 --enable-pic --disable-static --enable-shared
```

**Comment by dista** [comment]
Figured out how to make it work.

After change  `out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))`
to `out = cv2.VideoWriter('output.avi',fourcc, 20.0, (1280, 720))`

it can output data correctly. 

1280 * 720 is the input http/flv's image size.

I think the document should be improved.

**Comment by alalek** [comment]
Invalid frames were dropped in this case, because you specified wrong resolution for output video.
