### ISSUE TITLE
[IMGPROC] drawMarker with triangle-up marker type

### ISSUE THREAD

**Issue by amroamroamro** [Itseez/opencv#5905]
The [`cv::drawMarker`](http://docs.opencv.org/3.1.0/d6/d6e/group__imgproc__draw.html#ga482fa7b0f578fcdd8a174904592a6250) function draws the wrong shape for the [`cv::MARKER_TRIANGLE_UP`](http://docs.opencv.org/3.1.0/d6/d6e/group__imgproc__draw.html#ga0ad87faebef1039ec957737ecc633b7b) marker.

Here is an example using OpenCV 3.1.0 Python bindings (of course the same happens from C++):
``` py
import numpy as np
import cv2

markers = [
    cv2.MARKER_CROSS,
    cv2.MARKER_TILTED_CROSS,
    cv2.MARKER_STAR,
    cv2.MARKER_DIAMOND,
    cv2.MARKER_SQUARE,
    cv2.MARKER_TRIANGLE_UP,
    cv2.MARKER_TRIANGLE_DOWN
]

img = np.zeros((100,400,3), dtype=np.uint8)
x = 50
for mt in markers:
    img = cv2.drawMarker(img, (x,50), (0,0,255),
        markerType=mt, markerSize=30, thickness=2, line_type=cv2.LINE_AA)
    x += 50

cv2.imshow('Draw Marker', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

![drawmarker](https://cloud.githubusercontent.com/assets/83908/12069015/87bd3236-b024-11e5-9b04-594cc08ecb54.png)

(notice the next-to-last shape, which should be a triangle pointing upward △).

**Comment by StevenPuttemans** [comment]
Thanks for reporting! A typo on my side it seems!
