### ISSUE TITLE
ConvexityDefects function is not detecting the points correctly 

### ISSUE THREAD

**Issue by farhadzamanpolok** [Itseez/opencv#5908]
![capture](https://cloud.githubusercontent.com/assets/9360179/12070860/021bf25e-b0b8-11e5-84e0-cff23a9dd13a.PNG)

**Comment by LaurentBerger** [comment]
can you post original image

**Comment by alalek** [comment]
or dump 11 points of the original contour

**Comment by farhadzamanpolok** [comment]
![main](https://cloud.githubusercontent.com/assets/9360179/12073261/c27f6594-b13f-11e5-9d43-115e9b4075e7.jpg)

![contours](https://cloud.githubusercontent.com/assets/9360179/12073264/d08e1158-b13f-11e5-9088-0b625efa528d.jpg)
![convexhull](https://cloud.githubusercontent.com/assets/9360179/12073266/dc0c9392-b13f-11e5-88d1-a8c4d1973f7b.jpg)

![all](https://cloud.githubusercontent.com/assets/9360179/12073268/e8166460-b13f-11e5-8c77-549221aae7bf.jpg)

**Comment by farhadzamanpolok** [comment]
It is the second point. Clockwise.  I think dumping is not a perfect solution.  V2.4.9 the detection is perfect. When i uploaded to v3 it is giving me this error

**Comment by farhadzamanpolok** [comment]
See this video. I done this using v2.4.9 

https://m.youtube.com/watch?v=cIfZFZTe4W8

**Comment by LaurentBerger** [comment]
At https://github.com/Itseez/opencv/blob/7e50d3e5712812e386074c689524a2de0d5df842/modules/imgproc/src/convhull.cpp#L305 may be add j=hcurr; can help to solve this problem

**Comment by farhadzamanpolok** [comment]
Yes. Now it's working fine.

**Comment by SPANInspectionSystems** [comment]
has this issue been solved in opencv3.3?
