### ISSUE TITLE
OpenCV in static in opencv_ffmpeg310_64.dll

### ISSUE THREAD

**Issue by LaurentBerger** [Itseez/opencv#5920]
Hi,

I have build opencv 3.1.0 in static with VS 2013 and I still need opencv_ffmpeg310_64.dll in path to load video file. Is it good or I have built opencv in wrong way?

Thanks for your answer

**Comment by alalek** [comment]
There are a licensing issues: `opencv_ffmpeg310_64.dll` is LGPL. See readme files in `3rdparty/ffmpeg`.

**Comment by LaurentBerger** [comment]
Thanks for your anwser
