### ISSUE TITLE
Undistort Python binding

### ISSUE THREAD

**Issue by kerkilchoi** [Itseez/opencv#5928]
I am trying to use OpenCV3's fisheye lens undistortion. I am using python 2.7 binding for OpenCV 3.1 (w/ contrib), and on Mac OS X (El Capitan). 

A relevant code snippet is 
```
K = np.array([[785.909, 0., 1035.3], [0., 785.909, 985.95], [0., 0., 1.]], dtype=np.float32)
D = np.array([0.01212,-0.0123,0.0202,-0.00444], dtype=np.float32)
undistorted = cv2.fisheye.undistortImage(distorted_image, K, D)
```
This results in an error, pasted below.  
```
error                                     Traceback (most recent call last)
<ipython-input-16-8a4aac76a841> in <module>()
      1 undistorted = np.empty(shape=gray.shape)
----> 2 undistorted = cv2.fisheye.undistortImage(gray, K, D)

error: /tmp/opencv320160105-72493-1cyibez/opencv-3.1.0/modules/calib3d/src/fisheye.cpp:409: error: (-215) (P.depth() == CV_32F || P.depth() == CV_64F) && (R.depth() == CV_32F || R.depth() == CV_64F) in function initUndistortRectifyMap
```

Since the inputs P and R for the undistortImage function are optional (according to its function signature), I am a bit confused about what causes this error/exception. I passed None for the optional arguments, which didn't solve the problem. 

If anyone could provide a hint on what this is about and how this should be fixed/handled, it would be greatly appreciated.

**Comment by soupault** [comment]
I'm getting the same error on Python 3.5 for both Arch Linux x64 () and Windows 7 x64 platforms.

**Comment by smidm** [comment]
You have to specify also Knew parameter. See a working example https://github.com/smidm/opencv-python-fisheye-example/blob/master/fisheye_example.py 

This should be noted in the documentation or fixed to work without Knew.

**Comment by soupault** [comment]
@smidm thanks! The solution worked for me. I'll work on the PR in the free time.

**Comment by kerkilchoi** [comment]
Thanks. It works good. As pointed out, documentation of this would be very helpful.

**Comment by zhangweilion** [comment]
Thanks  to  smidm

**Comment by Flock1** [comment]
I have camera coordinates and distortion coefficients for a camera that took an image from testing and hence, I don't have access to it. I just have the matrices and the distorted image, don't even know if it's fisheye distortion. Can someone help me what should I do in this case?

**Comment by smidm** [comment]
@Flock1 There are many models for camera distortion. You should find out what model was used in calibration and use some code implementing the model for undistorting your images. If you are lucky, the code for your model is implemented in OpenCV. If it's not and you won't be able to find out anything about the model, you can fit the OpenCV model by making stright lines in your images actually straight (see [Devernay, Frederic, and Olivier Faugeras. "Straight lines have to be straight." Machine vision and applications (2001)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.18.7064&rep=rep1&type=pdf))
