### ISSUE TITLE
MSER detection segfaults

### ISSUE THREAD

**Issue by sanchom** [Itseez/opencv#5932]
Running this code: https://gist.github.com/sanchom/6fac623bd31188fdb2f9 on the attached image causes a segfault.

![segfaulter](https://cloud.githubusercontent.com/assets/742889/12184911/fb37bb14-b54c-11e5-8f45-bba100692795.png)

**Comment by StevenPuttemans** [comment]
Excuse me, but a segmentation fault is not an error. In most cases, when running in debug mode the actual error is printed just above, if not, start debugging the code and see where exactly it goes wrong. Print out the dimensions of your image, ...

**Comment by cbalint13** [comment]
@sanchom ,

* Can post a sample code that reproduce the segfault ?

**Comment by sanchom** [comment]
#include <vector>

    #include "opencv2/opencv.hpp"

    int main(int argc, char** argv) {
      cv::Ptr<cv::MSER> mser_extractor = cv::MSER::create();
      cv::Mat gray_image = cv::imread("segfaulter.png", cv::IMREAD_GRAYSCALE);
    
      std::vector<std::vector<cv::Point> > msers;
      std::vector<cv::Rect> boxes;
      mser_extractor->detectRegions(gray_image, msers, boxes);

      return 0;
    }

**Comment by kunalgrover05** [comment]
Doesn't throw any errors for me, tested on repository version.

**Comment by Aravind-Suresh** [comment]
@sanchom

It doesn't throw any error for me. Try debugging and finding the reason for the seg fault. If you get stuck up, post the error/debug logs.

**Comment by mshabunin** [comment]
@sanchom , please provide more information about your system configuration, OpenCV version and build options (for OpenCV and test application).
