### ISSUE TITLE
im getting a make error with persistence.hpp

### ISSUE THREAD

**Issue by kostasl** [Itseez/opencv#5935]
Hi,
I get a compile error with persistence.hpp using opencv3 with cmake
cmake -D WITH_EIGEN=OFF -D WITH_QT=ON -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local .

I noticed someone had reported the problem before:
https://github.com/Itseez/opencv/issues/5664

In my case I get :
```
usr/local/include/opencv2/core/persistence.hpp:1107:27:   required from 'cv::FileNodeIterator& cv::operator>>(cv::FileNodeIterator&, std::vector<_RealType>&) [with _Tp = std::basic_string<char>]'
/usr/local/include/opencv2/core/persistence.hpp:1130:8:   required from 'void cv::operator>>(const cv::FileNode&, std::vector<_RealType>&) [with _Tp = std::basic_string<char>]'
../Control/InputGenerator.cpp:62:27:   required from here
/usr/local/include/opencv2/core/persistence.hpp:793:41: error: no matching function for call to 'read(cv::FileNode, __gnu_cxx::__alloc_traits<std::allocator<std::basic_string<char> > >::value_type&, std::basic_string<char>)'
                 read(**it, vec[i], _Tp());
```
through an operator >> call you end up calling 
```
read( const FileNode& node, std::vector<_Tp>& vec, const std::vector<_Tp>& default_value = std::vector<_Tp>() )
```
 where if  _Tp is std:string,  then a required version of a read function such like the one existing for uchar in persistence.hpp:
```
static inline
void read(const FileNode& node, uchar& value, uchar default_value)
```
does not exists for  function with parameters of std:string type like it exists for a few types like uchar above.

Yet if you look in opencv 2.4.12
this function existed in core/operations.hpp and it had an std:string overload.

Perhaps this is  a bug, where an overload of read() function for std:string has been missed?

Thanks,
Kostas

**Comment by alalek** [comment]
Please add some sample code to reproduce this problem

**Comment by kostasl** [comment]
yes, indeed.  I have reverted to using the old library instead of 3.0.
Below I extracted the lines below, which used to give the compilation error:

```
 const std::string path = 'Some Path to a yml file containing key-value pairs';

 std::vector<std::string> imgPaths;

  cv::FileStorage fs = cv::FileStorage(path, cv::FileStorage::READ, "UTF-8");
 
//The line below hit the missing read() function
  fs["imgNames"] >> imgPaths;

'''

**Comment by alalek** [comment]
Use `cv::String` instead of `std::string` (there are some issues with `std::string`, so public interfaces migrated to `cv::String`):
```
std::vector<cv::String> imgPaths;
```

**Comment by kostasl** [comment]
OK, that worked thank you.
 Had to convert the code to vector<cv::String> and solved the problem - additionally had to link against the opencv_imgcodecs for imread to work now.

Cheers,
K.
