### ISSUE TITLE
Compiling OpenCV with Beignet OpenCL

### ISSUE THREAD

**Issue by soulslicer** [Itseez/opencv#5938]
I've installed Beignet succesfully and have made it pass all tests and CLINFO indicates 20 work units etc. However, when I try to compile OpenCV, it says in Cmake that:

the include path is:
"/home/raaj/opencv/3rdparty/include/opencl/1.2"

When it should be:
/usr/local/include/CL/

How can I work around this? Is this a issue?

**Comment by alalek** [comment]
There is no problem if your OpenCL implementation is Khronos OpenCL 1.2 compatible (conformant). Dynamic loading is used by default.

To switch on your custom OpenCL run CMake (in the clean build dir) with these variables passed via command-line:
- disabled OpenCL auto detection: `WITH_OPENCL=OFF`
- `HAVE_OPENCL=ON`
- `HAVE_OPENCL_STATIC=ON`
- `OPENCL_LIBRARIES=path`
- `OPENCL_INCLUDE_DIRS=path`

**Comment by soulslicer** [comment]
Are you or anyone familiar with what those entries should be for Beignet? Especially Opencl_libraries. Beignet seems to install .so files to multiple locations

**Comment by soulslicer** [comment]
Thanks, I got it to work now.
