### ISSUE TITLE
DenseOpticalFlow missing functions

### ISSUE THREAD

**Issue by soulslicer** [Itseez/opencv#5939]
http://docs.opencv.org/master/dc/d47/classcv_1_1DualTVL1OpticalFlow.html#gsc.tab=0

```
cv::Ptr<cv::DenseOpticalFlow> alg = cv::createOptFlow_DualTVL1();
    alg->setTheta(0.125);
```

The following code gives:

```
/home/linux/cl/test.cpp:119:10: error: ‘class cv::DenseOpticalFlow’ has no member named ‘setTheta’
     alg->setTheta(0.125);
```

**Comment by berak** [comment]
DenseOpticalFlow is the base class for DualTVL1OpticalFlow, it does not have any of those member functions.

please instead use: 

    cv::Ptr<cv::DualTVL1OpticalFlow> alg = cv::createOptFlow_DualTVL1();
    alg->setTheta(0.125);
