### ISSUE TITLE
Precompiled header: created and used with different settings of -fpic

### ISSUE THREAD

**Issue by caraffi** [Itseez/opencv#5944]
OpenCV 3.1
Cross compiling Windows->android
Using android-ndk-r10e (32bit)
Standalone toolchain gcc 4.9 targeting API19
Enabling precompiled headers
Building static libraries (also applies for shared libraries)
Building using ninja, and defining environment variable ANDROID_STANDALONE_TOOLCHAIN

A long list of warnings like the following are displayed:
cc1plus.exe: warning: /OpenCV3_1/opencv/build_android/modules/features2d/test_precomp.hpp.gch/opencv_test_features2d_Release.gch: created and used with different settings of -fpic

**Comment by caraffi** [comment]
Compiling with mingw/gcc 4.9.2 Windows->Windows 32bit, I get instead (basically for every file compiled) the warning:
warning: -fPIC ignored for target (all code is position independent).

**Comment by alalek** [comment]
Precompiled headers feature is disabled in case of any cross-compilation

**Comment by caraffi** [comment]
Do you mean from now on? Because the behaviour I tested is that while cross compiling the precompiled header are enabled by default in the cmake gui.

**Comment by alalek** [comment]
Clear CMake cache (CMakeCache.txt) or disable `ENABLE_PRECOMPILED_HEADERS=OFF`.

Change is added [here](https://github.com/Itseez/opencv/commit/c8ff7a486735f45f9dd4060111b71957c78142c6#diff-af3b638bc2a3e6c650974192a53c7291)

**Comment by caraffi** [comment]
Ok, thanks for having handled this!

2016-01-21 19:59 GMT+01:00 Alexander Alekhin <notifications@github.com>:

> Clear CMake cache (CMakeCache.txt) or disable
> ENABLE_PRECOMPILED_HEADERS=OFF.
>
> Change is added here
> <https://github.com/Itseez/opencv/commit/c8ff7a486735f45f9dd4060111b71957c78142c6#diff-af3b638bc2a3e6c650974192a53c7291>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv/issues/5944#issuecomment-173674101>.
>



-- 
  Ing. Claudio Caraffi, PhD
   E-Mail: claudio.caraffi@gmail.com
