### ISSUE TITLE
where can down ANDROID_OPENCL_SDK for opencv/samples/android/tutorial-4-opencl.

### ISSUE THREAD

**Issue by cudnn** [Itseez/opencv#5950]
I use  z3 810 cpu ～ I have down https://developer.qualcomm.com/software/adreno-gpu-sdk/tools but can't fined sdk suitable,could you sent yours sdk to  me ;
My email is 332644854@qq.com

**Comment by alalek** [comment]
You should provide GPU specification, not CPU. See https://en.wikipedia.org/wiki/Adreno for Qualcomm SoCs. GPU is "Adreno 430" for "Snapdragon 810".

Try download something from here: https://developer.qualcomm.com/software/adreno-gpu-sdk/tools

**Comment by cudnn** [comment]
I have down https://developer.qualcomm.com/software/adreno-gpu-sdk/tools  but can't fined sdk  suitable

**Comment by cudnn** [comment]
Can sent your ANDROID_OPENCL_SDK to me

**Comment by cudnn** [comment]
My email is 332644854@qq.com

**Comment by anonym24** [comment]
To download sdk for Adreno registration is required, I registered but won't able to log in, it always says about 5 minutes but I waited much longer

Can someone send me that archive?

> Sorry, unrecognized username or password. If this is a new account, please allow 5 minutes after email validation for account to become active. If you have not received an account validation email, please check your spam folder.
