### ISSUE TITLE
Writing numpy object data to image file

### ISSUE THREAD

**Issue by anmoluppal** [Itseez/opencv#5951]
I recently tried loading a ndarray using `cv2.imdecode`, and got a `np.ndarray` object, But when I was trying exactly opposite approach of the same, I am not getting expected outputs. I used `cv2.imencode(".png", image)` but it returns me a `np.ndarray` object and not the expected binary string or file object, How can I convert `np.ndarray` to a binary string which I can directly use to write to a `.png` image as:

    with open("img.png", "w") as f:
        f.write(binary_string)

**Comment by Wizlem** [comment]
You can easily convert numpy arrays to strings - http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.tostring.html

If you are just working with files, you can use cv2.imread and cv2.imwrite.

**Comment by Dikay900** [comment]
could be closed i think since imread returns a file object as requested by the author of the issue.

Please reopen if there are any more problems reading an image.
