### ISSUE TITLE
Compiling OpenCV with Windows Intel OpenCL

### ISSUE THREAD

**Issue by soulslicer** [Itseez/opencv#5957]
Good day,

I am having issues compiling OpenCV 3.1.0 with the Intel Windows OpenCL SDK 2.0. I have set my CMAKE Options as such:

WITH_OPENCL=OFF
HAVE_OPENCL=ON
HAVE_OPENCL_STATIC=ON
OPENCL_LIBRARIES=C:/Program Files (x86)/Intel/OpenCL SDK/5.3/lib/x64/OpenCL.lib
OPENCL_INCLUDE_DIRS=C:/Program Files (x86)/Intel/OpenCL SDK/5.3/include/

It seems to give warnings saying that clCreateCommandQueue and clEnqueueTask was declared deprecated. Is this an issue of 1.2 vs 2.0?

**Comment by alalek** [comment]
Looks like some things were changed in Windows SDK or MSVS compiler.
Just disable Direct3D support via CMake parameter: `-DWITH_DIRECTX=OFF`.

OpenCL 2.0 deprecates some calls of OpenCL 1.1/1.2. You can ignore these messages.

Also OpenCL 2.0 support is not well tested. So you should build and run OpenCV tests to pass some basic checks.

**Comment by soulslicer** [comment]
I now have issues with Eigen and OpenCL and OpenMP, getting this error where I would get an Internal Compiler Error:

http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1096
