### ISSUE TITLE
OpenCV Error: Assertion failed (The data should normally be NULL!)

### ISSUE THREAD

**Issue by hmischel** [Itseez/opencv#5958]
This looks to be an issue with opencv and python 2.7 using the Flann sub modules

C:\Python27\python.exe C:/canming/flann.py
OpenCV Error: Assertion failed (The data should normally be NULL!) in NumpyAllocator::allocate, file C:\opencv\sources\modules\python\src2\cv2.cpp, line 163
Traceback (most recent call last):
  File "C:/canming/flann.py", line 22, in <module>
    matches =  flann.knnMatch(des1,des2,k=2)
cv2.error: C:\opencv\sources\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate

Process finished with exit code 1

**Comment by alalek** [comment]
duplicate #5667
