### ISSUE TITLE
Matrix transpose after convertPointsFromHomogeneous is erroneous

### ISSUE THREAD

**Issue by spainer** [Itseez/opencv#5959]
Transposing the resulting matrix from convertPointsFromHomogeneous gives wrong dimensions of the matrix. The code

```cpp
Mat m(2, 4, CV_32F);
m.at<float>(0, 0) = 1;
m.at<float>(0, 1) = 2;
m.at<float>(0, 2) = 3;
m.at<float>(0, 3) = 2;
m.at<float>(1, 0) = 1;
m.at<float>(1, 1) = 2;
m.at<float>(1, 2) = 3;
m.at<float>(1, 3) = 1;
cout << "m = " << m << endl;

Mat m2;
convertPointsFromHomogeneous(m, m2);
cout << "m2 = " << m2 << endl;
Mat m3 = m2.t();
cout << "m3 = " << m3 << endl;
```

gives the output

> m = [1, 2, 3, 2;
> 1, 2, 3, 1]
> m2 = [0.5, 1, 1.5;
>  1, 2, 3]
> m3 = [0.5, 1, 1.5, 1, 2, 3]

As *m2* is 2x3, one would expect *m3* to be 3x2, instead it is 1x6.

**Comment by pi-squared** [comment]
convertPointsFromHomogeneous will output an array of Point3f or Point2f objects. So it looks like *m2* is a 2x3 matrix but it is infact 2x1, so when it is transposed it will give you a 1x2 matrix of Point3f which is what you see. If you want to do it as a matrix transpose, you could reshape it to single-channel before. 
So: `Mat m3 = m2.reshape(1).t();`

**Comment by spainer** [comment]
Thanks for the clarification, I also printed the matrix dimensions and you are right.
