### ISSUE TITLE
In static build, enabled but not found Webp causes undefined references

### ISSUE THREAD

**Issue by caraffi** [Itseez/opencv#5960]
In static build, if WITH_WEBP is ticked (default value) but WEP_INCLUDE_DIR is not found, there will be undefined references when trying to linking to the produced libopencv_imgcodecs310.a library:

libopencv_imgcodecs310.a(grfmt_webp.cpp.obj):grfmt_webp.cpp:(.text$_ZNK2cv11WebPDecoder14checkSignatureERKNS_6StringE+0x39): undefined reference to `WebPGetFeaturesInternal'

libopencv_imgcodecs310.a(grfmt_webp.cpp.obj):grfmt_webp.cpp:(.text$_ZN2cv11WebPDecoder8readDataERNS_3MatE+0x14c): undefined reference to `WebPDecodeBGRInto'

libopencv_imgcodecs310.a(grfmt_webp.cpp.obj): bad reloc address 0x14c in section `.text$_ZN2cv11WebPDecoder8readDataERNS_3MatE'

(Workaround: manually disable WITH_WEBP)

CMake output:
[...]
  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver 0.3.1)
[...]

**Comment by alalek** [comment]
Please add more details, because we can't reproduce this problem. You can take a look on the one of our static Windows build with WebP: http://pullrequest.opencv.org/buildbot/builders/precommit_windows_ten/builds/520

**Comment by caraffi** [comment]
Sorry for not mentioning this: The error doesn't happen at build time, but when linking the library to another project. So if you link an external application to libopencv_imgcodecs310.a you should see the error.

**Comment by alalek** [comment]
In case of static link you should specify all 3rdparty libraries (like libwebp.a, libz.a/libzip.a, etc). Do you add them into linker list?

You may want to use CMake to do this automatically, check this [example](https://github.com/Itseez/opencv/blob/3.1.0/samples/cpp/example_cmake/CMakeLists.txt)

**Comment by caraffi** [comment]
I don't think this is the problem: When no WEBP support is available, at the beginning of grfmt_webp.cpp `#ifdef HAVE_WEBP`  should give false and the file should not be compiled, so that there's no trace of the call to WebPGetFeaturesInternal and WebPDecodeBGRInto. So the problem seems to me that HAVE_WEBP is somehow defined by mistake somewhere.

**Comment by caraffi** [comment]
Thanks for the clarification! I had missed a new library libwebp.a exists now. Sorry, my bad!
