### ISSUE TITLE
No CvSVM.get_default_grid function exists in Java wrapper

### ISSUE THREAD

**Issue by Motherboard** [Itseez/opencv#5966]
This function is said to exist by the documentation...

**Comment by mshabunin** [comment]
Neither the [documentation for 2.4.11](http://docs.opencv.org/java/2.4.11/org/opencv/ml/CvSVM.html) nor the [documentation for 3.1.0](http://docs.opencv.org/java/3.1.0/org/opencv/ml/SVM.html) do not mention this method.

Please, add link to errorneous documentation and provide exact OpenCV version. Feel free to reopen the issue if you have more information.

**Comment by Motherboard** [comment]
In the page you linked to (2.4.11) under train_auto:

"Trains an SVM with optimal parameters.

The method trains the SVM model automatically by choosing the optimal parameters C, gamma, p, nu, coef0, degree from "CvSVMParams". Parameters are considered optimal when the cross-validation estimate of the test set error is minimal.

If there is no need to optimize a parameter, the corresponding grid step should be set to any value less than or equal to 1. For example, to avoid optimization in gamma, set gamma_grid.step = 0, gamma_grid.min_val, gamma_grid.max_val as arbitrary numbers. In this case, the value params.gamma is taken for gamma.

And, finally, if the optimization in a parameter is required but the corresponding grid is unknown, you may call the function "CvSVM.get_default_grid". To generate a grid, for example, for gamma, call CvSVM.get_default_grid(CvSVM.GAMMA)."

**Comment by mshabunin** [comment]
@Motherboard , this documentation has been automatically generated from the [main documentation article](http://docs.opencv.org/2.4.11/modules/ml/doc/support_vector_machines.html#cvsvm-train-auto) and can contain mistakes. The function `get_default_grid` is not actually wrapped in Java.

If you really need this method, I can mark this issue as "Feature Request", or you can create grids in Java manually using same parameters as in the corresponding [C++ code](https://github.com/Itseez/opencv/blob/68eab8ea00c01ddbe3dbc3a69af1c1e8fe63ccf9/modules/ml/src/svm.cpp#L365).
