### ISSUE TITLE
Can not build opencv-3.1.0 for iOS

### ISSUE THREAD

**Issue by aussiDavid** [Itseez/opencv#5997]
I followed the instructions here: http://docs.opencv.org/2.4/doc/tutorials/introduction/ios_install/ios_install.html

Here is the output from running the build script.
[build_ios.txt](https://github.com/Itseez/opencv/files/97373/build_ios.txt)

Thanks in advance.

**Comment by StevenPuttemans** [comment]
This page is mainly for issues with current implementation that have been proven to exist. For getting debug help on your installation, add the question at answers.opencv.org/questions, where you will get help much faster.

**Comment by alalek** [comment]
Unfortunately, I have no idea that is going wrong with your build.
We have similar [build](http://pullrequest.opencv.org/buildbot/builders/master_iOS-mac/builds/173/steps/build%20framework/logs/stdio) on our build machine that works fine.
You may check provided output and compare it.

BTW, we don't use `ln -s` command for a few years.

**Comment by aussiDavid** [comment]
Moved to opencv questions: http://answers.opencv.org/question/84712/can-not-build-opencv-310-for-ios/

Thanks.
