### ISSUE TITLE
rtsp problem with java

### ISSUE THREAD

**Issue by ferrusqui** [Itseez/opencv#5998]
Hi,

I'm trying (using java) to get the h264 stream coming from an IP camera via RTSP:

jdk1.8.0_45
my OS is windows 7.
I'm using opencv 3.1.0

I'm not able to open the stream.

This is my code:

//        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        System.load("D:\\opencv_3.1.0\\opencv\\build\\java\\x64\\opencv_java310.dll");

        VideoCapture camera = new VideoCapture();

        camera.open("rtsp://xxxx:yyyy@zzzz@192.168.1.10/onvif/profile2/media.smp");
        
        if (camera.isOpened()) 
        {
            System.out.println("Video is captured");
        }
        else
        {
            System.out.println("Video is not captured");
        }

Clearly I have always the output "Video is not captured".

Where is my mistake?

Thanks

**Comment by alalek** [comment]
There is a possible problem with implicit loading of opencv_ffmpeg310_64.dll. You need to put it into `PATH` (environment variable) locations or near `opencv_java310.dll`.
