### ISSUE TITLE
build_framework.py , should we add -Wno-implicit-function-declaration flag ?

### ISSUE THREAD

**Issue by rezacute** [Itseez/opencv#6011]
I was unable to build opencv with contrib modules, the root cause was implicit function declaration.
I solved it by adding `-Wno-implicit-function-declaration` on the build_framework.py .
Is this known problem ? Can i submit PR to address this problem ?

**Comment by alalek** [comment]
It is just a warning, real problem is not here.
I have this with contrib build:
```
    <...>clang++  <...> opencv_waldboost_detector
ld: library not found for -lopencv_core
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
