### ISSUE TITLE
extended detectMultiscale fails when reject levels are requested

### ISSUE THREAD

**Issue by pixelou** [Itseez/opencv#6022]
When weights and rejection levels are requested, [detectMultiscale](http://docs.opencv.org/3.1.0/da/dd5/classcv_1_1BaseCascadeClassifier.html#afa5ead715ec7c9cf0ef71f210ba7715f) is abnormally slow and eventually returns one square detection at the center of the image.

Tested with 3.1.0.r107.g1cd3c6f. It also failed with one of the earlier revisions of `3.1.0`.

Bug has been confirmed by another tester on [answers.opencv.org](http://answers.opencv.org/question/84605/detectmultiscale-fails-when-weights-are-requested/?answer=85636#post-id-85636) who has reported that it is working mostly correctly on `2.4` (more detections than the basic detectMultiScale).

Minimal working example: (the image I used is available [here](https://pbs.twimg.com/media/BhxWutnCEAAtEQ6.jpg))

```cpp
#include <iostream>
#include <string>
#include <vector>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

const string opencvDir = "/usr/share/opencv/haarcascades/";
const string WindowName = "Oscars";

int main() {
    CascadeClassifier faceCascade;
    if (!faceCascade.load(opencvDir + "/haarcascade_frontalface_alt2.xml")) {
        cerr << "failed to load cascade features" << endl;
        return -1;
    }

    Mat im = imread("oscar.jpg");
    Mat gray(im.cols, im.rows, CV_8U);
    cvtColor(im, gray, cv::COLOR_BGR2GRAY);

    double scaleFactor = 1.2;
    int minNeighbors = 2;
    int flags = 0;
    Size minSize = Size(50, 50);
    Size maxSize = Size(150, 150);
    bool outputRejectLevels = true;
    vector<Rect> objects;
    vector<int> rejectLevels;
    std::vector<double> levelWeights;

    // Broken version
    faceCascade.detectMultiScale(gray, objects, rejectLevels, levelWeights,
        scaleFactor, minNeighbors, flags,
        minSize, maxSize, outputRejectLevels);

    Mat preview = im.clone();
    for (Rect obj : objects)
            rectangle(preview, obj, Scalar(255, 0, 0));

    namedWindow(WindowName, WINDOW_AUTOSIZE);   
    imshow(WindowName, preview);
    waitKey(0);

    objects.clear();
    rejectLevels.clear();
    levelWeights.clear();

    // Working version
    faceCascade.detectMultiScale(gray, objects, scaleFactor, minNeighbors, 
        flags, minSize, maxSize);

    preview = im.clone();
    for (Rect obj : objects)
            rectangle(preview, obj, Scalar(255, 0, 0));
    namedWindow(WindowName, WINDOW_AUTOSIZE);   
    imshow(WindowName, preview);
    waitKey(0);

    return 0;    
}
```

**Comment by StevenPuttemans** [comment]
I confirm that this bug exists, as readable in the Q&A post!

**Comment by StevenPuttemans** [comment]
@Dikay900 I guess this might have something to do with this earlier bug and the [proposed fix](https://github.com/Itseez/opencv/issues/5347). Could you check if it works at your side?

**Comment by StevenPuttemans** [comment]
I just let the software run for a plain hour with the number of neighbors set at 0. Given at the following input image

![faces](https://cloud.githubusercontent.com/assets/4621239/12644105/d3fbaa90-c5c0-11e5-8b28-115f8ffab9fd.jpg)

the result is as follows

![screenshot from 2016-01-28 12 53 41](https://cloud.githubusercontent.com/assets/4621239/12644089/b1d4db3a-c5c0-11e5-951b-13f26a5f5d2e.png)

I am now trying the parameter at 1 to see if the algorithm does actually something usefull, because it seems now that it detects faces in every image location. If that is so, the error must be in the evaluation of features or in the calculation of the stage thresholds.

**Comment by StevenPuttemans** [comment]
**_Second update:_**

Tried to take a look at the fact if older models where the cause. But even a newly trained model, trained this morning, doesn't work and keeps running very long.

**Comment by Dikay900** [comment]
So with the reverted line of #5362 it works again as expected?

**Comment by StevenPuttemans** [comment]
These tests are done using the latest master branch, which is older than that PR. You are suggesting to revert that line and try again?

**Comment by Dikay900** [comment]
yes but if the tests are older anyway than it has nothing to do with this line right? I just want to check that before digging deeper.

**Comment by StevenPuttemans** [comment]
I will check out in a second :) I will report back in minute or 5!

**Comment by StevenPuttemans** [comment]
Good and bad news.

1. GOOD: I got it working by reverting back that line
2. BAD: we will have to get back to that PR and try to define a solution for adding the fix and ensuring that the extended function still works. For now I will just revert the line through a PR!

RESULT NOW WITH `facemodel.detectMultiScale(temp, faces, rejectLevels, levelWeights, 1.1, 1, 0, Size(), Size(), true);`

![screenshot from 2016-02-04 13 14 49](https://cloud.githubusercontent.com/assets/4621239/12814721/869fd45c-cb41-11e5-9a11-b6f8f94c9662.png)

**Comment by Dikay900** [comment]
then can you open that pr reverting that commit simple as that?
We can then not solve the other issue but this is due to ABI_Compatibility in general.

**Comment by StevenPuttemans** [comment]
I have no access to PRs so I need to actually submit one also :D I guess @alalek or @vpisarev will take care of the new one and push it in. Then I guess leaving it as it is is still the best way to go. In the near future we might be able to start up a discussion group on an improved cascade classifier interface and make a clone in the contrib repo for that?

**Comment by Dikay900** [comment]
yes that was my intention it has to be an own PR.
Yes you are right since the abi is now enforced we need to get a proper interface ourself in the contrib repo if needed.
Maybe i will start this on march since we need a beginning for this anyway. Currently i've got no time doing something here.

**Comment by StevenPuttemans** [comment]
Same for me :D Stuff I would like to add, since I desperately need it for my PhD
1) Making a general feature selection interface. Because limiting it to HAAR and LBP only seems a waste of the power
2) Adding a better detection certainty calculation, because the numberOfNeighbours and the weights are both not the best and most correct options

**Comment by ahmadi219** [comment]
**Hi, 
im using Code:**
face_cascade.detectMultiScale(graySacleFrame, faces,rejectLevels,levelWeights,1.1, 2, 0|CASCADE_SCALE_IMAGE, Size(30, 30), Size(80, 80),true);
**but it return some noise detection around me  but cant detect my big face in front of webcam :D** 
what is Solution? im using OpenCv 3.0.0

**Comment by StevenPuttemans** [comment]
But what is the size of your face? If it is larger than 80x80 pixels it will not get detected ...
