### ISSUE TITLE
setUseOpenCL() no longer accessible

### ISSUE THREAD

**Issue by StevenPuttemans** [Itseez/opencv#6024]
The function `setUseOpenCL(false)` was one of the only ways to explicitly tell your OpenCV code to ignore every OpenCL call it passes. However in the latest master branch I am trying the following code

```
#include <iostream>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main()
{
    ocl::setUseOpenCL(false);
    cout << "Hello world!" << endl;
    return 0;
}
```

However when trying to compile it says that the ocl namespace is not available, but my libs are built with OpenCL support. Adding `#include "opencv2/ocl/ocl.hpp"` leads to very strange errors in the ocl.hpp header.

Could anyone confirm this doesn't work anymore?

**Comment by alalek** [comment]
There are "tapi" [samples](https://github.com/Itseez/opencv/tree/master/samples/tapi). Are they work for you?

P.S. `#include "opencv2/core/ocl.hpp"` for master branch

**Comment by StevenPuttemans** [comment]
ow it could be that I am indeed looking for the wrong include. Lemme see try those examples out.

**Comment by StevenPuttemans** [comment]
using `#include "opencv2/core/ocl.hpp"` did the trick. In my opinion it is maybe quite weird that `#include "opencv2/ocl/ocl.hpp"` still exists in master branch?

**Comment by alalek** [comment]
> It is maybe quite weird that #include "opencv2/ocl/ocl.hpp" still exists in master branch
None

I believe it is coming from some OpenCV 2.4 installation. Refer https://github.com/Itseez/opencv/issues/5989#issuecomment-172796508 how to debug includes:
```
$ g++ -E -x c++ - -v -I /home/alalek/projects/opencv_build/install/include \
    <<< '#include "opencv2/ocl/ocl.hpp"' | grep  "# 1 .*opencv2.*1"
...
# 1 "/usr/include/opencv2/ocl/ocl.hpp" 1 3 4
...
```

Compiler fallback to system includes of OpenCV 2.4.
