### ISSUE TITLE
build succeeds, import fails: missing libswscale.so.2

### ISSUE THREAD

**Issue by BMaxV** [Itseez/opencv#6031]
Hello, I tried building opencv today and it's not importing because

ImportError: libswscale.so.2: cannot open shared object file: No such file or directory

I think I followed the build instructions to the letter, they're not that long after all. It says the dependencies are all installed, but libswscale.so.2 isn't there apparently. So where do I get  libswscale.so.2?

Thanks for any help.

**Comment by alalek** [comment]
Dig to direction of ffmpeg/libav: swscale is from there.

**Comment by alalek** [comment]
There is useful commands:
- `ldd <binary file>` (Linux)
- `otool -L <binary_file>` (Mac)

**Comment by BMaxV** [comment]
Ok so following the trail there is a whole bunch of libscale .so's installed, including

libswscale.so
libswscale.so.3
libswscale.so.3.0.0

but they're version 3 I assume? Then maybe they were correctly installed as newest lib of their name. Could the problem be solved by updating a reference or do I really have to look for the presumably older version 2?

**Comment by alalek** [comment]
Try to build OpenCV from scratch (clean build directory). CMake should not configure build with wrong versions (if you don't hack them and force wrong files directly or to use custom ffmpeg builds).

**Comment by BMaxV** [comment]
But that's what I did in the first place? I pretty much copy pasted these install instructions here:

http://docs.opencv.org/3.0-beta/doc/tutorials/introduction/linux_install/linux_install.html

I got the code from github too.

**Comment by alalek** [comment]
We can't reproduce this problem. Linux nightly build works fine and pass tests: http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV-lin64/builds/598

To debug your case please provide cmake/build logs (parts of logs with "swscale", run "make" with `VERBOSE=1`), output of `ldd cv2.so` command.

**Comment by BMaxV** [comment]
Oh ok I'm so sorry, I think I missed doing the make install, of course it wouldn't find it then. Sorry to have taken your time. Thank you for your help though (and the software of course)!
