### ISSUE TITLE
Same old error. Can someone help. I'm new to VS 2015 

### ISSUE THREAD

**Issue by Sandeepkriss** [Itseez/opencv#6043]
Hi, I'm using VS 2015. I'm running opencv simple program, but it giving error. Please look at the link below and suggest an solution. Thanks for your time
![vs 2015 error](https://cloud.githubusercontent.com/assets/16983194/12714526/bcb035be-c8ee-11e5-8453-43145baade4c.jpg)

I'm thinking that additional dependence are missing but i could not figure it out. I'm new to VS & opencv.

**Comment by alalek** [comment]
Some introduction tutorials are here:
http://docs.opencv.org/2.4/doc/tutorials/introduction/table_of_content_introduction/table_of_content_introduction.html#table-of-content-introduction

This question must go to http://answers.opencv.org
