### ISSUE TITLE
utility.hpp file bool 'check' is Apple macro 'check' from AssertMacros.h. How to work around or fix?

### ISSUE THREAD

**Issue by jmbapps** [Itseez/opencv#6047]
There is a line of code in the OpenCV 3.1 utility.hpp the tries to create a bool check() const;. It occurs when you #include opencv2/core.hpp. Unfortunately this causes the error 'Expected member name or ';' after declaration specifiers. Since Apple uses 'check' in their AssertMacros.h,.
#ifndef check
#define check(assertion)  __Check(assertion)
#endif

opencv 3.1, El Capitan 10.11.3, Xcode 7.2.

**Comment by alalek** [comment]
```
#include "apple headers"
#undef check
#include "opencv headers"
```

**Comment by jmbapps** [comment]
Thx for the suggestion, but Apple has that macro for a reason.  I tried that already and it just creates more errors with the ViewController.o file.  It needs to be fixed on opencv's framework.  Call the macro cvcheck.  Simple.

**Comment by alalek** [comment]
There is no "check" macro in OpenCV. It is just normal method name.

Workaround #2:
```
#include "apple headers"
#undef check
#include "opencv headers"
#define check(assertion) __Check(assertion) # restore APPLE "check()" macro
```

You can also try "__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0"

**Comment by alalek** [comment]
https://opensource.apple.com/source/CarbonHeaders/CarbonHeaders-18.1/AssertMacros.h
> For time immemorial, Mac OS X has defined version of most of these macros without the __ prefix, which could collide with similarly named functions or macros in user code, including new functionality in Boost and the C++ standard library.
> A future release of Mac OS X will no longer do this, and will require that clients move to the new macros as defined above.

So Apple's "check()" macro is deprecated and should not be used anymore.

**Comment by jmbapps** [comment]
True there is not a macro in opencv, it is a bool that uses the same name as the Apple macro.

**Comment by mdejong** [comment]
I ran into quite a few problems with this method named check() and was able to work around the problem like this:

#include <opencv2/opencv.hpp> // Include OpenCV before any Foundation headers
#import <Foundation/Foundation.h>
#import <XCTest/XCTest.h>
...

As long as the opencv.hpp header is included *BEFORE* any apple foundation headers then the compilation works. But, this method in OpenCV really should just be changed from "check" to anything else like "check2" or whatever would avoid the problem.

**Comment by jmbapps** [comment]
Thank you for the help.  I agree, the bool should be renamed to help matters.

**Comment by jmbapps** [comment]
It still says the utility.hpp does nothing, but it us just a warning now.  Maybe you should fix this...just my opinion.  Get rid of useless files!

**Comment by mshabunin** [comment]
@jmbapps , what do you mean? File `utility.hpp` is used in many places. Method `CommandLineParser::check` is called in several C++ sample apps to validate command line arguments.

**Comment by jmbapps** [comment]
Thank you for the explanation, but I can read the comments.  Ahem, and I quote.... Returns true if error occured while accessing the parameters (bad conversion, missing arguments,
    etc.). Call @ref printErrors to print error messages list.
Here is what I get.
opencv2/core/utility.hpp
utility.hpp:729:5: Declaration does not declare anything.

Thank you for your help.

**Comment by alalek** [comment]
This mean that `check` is still defined to something wrong somewhere in your build setup.
For example, try to find and remove:
- `-Dcheck=` from command-line options
- `#define check` lines

**Comment by jmbapps** [comment]
The comments above fully explain what is going on.  Apple Macro check is conflicting with utility.hpp bool check.  If you import the opencv file before the Foundation.h then it works, but with the above warning.  All you guys would have to do is rename this bool to cvcheck or something similar, but as you said...wontfix.  So be it.  I have it running so I do not care....until the next version.  ;o)

**Comment by mshabunin** [comment]
@jmbapps , unfortunately we can not rename this method because it will break source and binary compatibility with previous versions. As I see, the best way to reduce potential inconveniences is to add a `#warning` statement in the beginning of the `utility.hpp` explaining the cause of the problem and a suggesting a way to avoid it. Feel free to provide pull request.
