### ISSUE TITLE
cv::ocl::useOpenCL() is not thread safe

### ISSUE THREAD

**Issue by Mitsuhiko-Matsukawa** [Itseez/opencv#6056]
cv:: ocl::useOpenCL() is called from cv::remap() but it's not thread safe,
so I can't use cv::remap() in the parallel section.
If I call cv:: ocl::useOpenCL() at the beginning of my program, cv::remap() works well.

I think this is a same issue of #5882 but it has not fixed in 3.1.0 yet.

**Comment by alalek** [comment]
How we can reproduce this problem?
- specify OS / HW
- add OpenCV build configuration via getBuildInformation()
- add some minimal reproducer sample
- stack traces / other useful logs

**Comment by Mitsuhiko-Matsukawa** [comment]
Windows10Pro x64
GeForceGTX 680
OpenCV3.1.0
Visual Studio Premium 2013 Update 5
[BuildInformation.txt](https://github.com/Itseez/opencv/files/115362/BuildInformation.txt)
![error_trace](https://cloud.githubusercontent.com/assets/17040347/12777761/de971876-ca99-11e5-9b96-328cc75eb988.PNG)

**Comment by alalek** [comment]
Thanks for update!

Could you add result of this statement:
```
std::cout << cv::ocl::useOpenCL() << std::endl;
```
(replace commented out code)

**Comment by Mitsuhiko-Matsukawa** [comment]
I have already attached it.
https://github.com/Itseez/opencv/files/115362/BuildInformation.txt
Thanks.

**Comment by Mitsuhiko-Matsukawa** [comment]
Sorry, I tried this code, but there is no output.
std::cout << cv::ocl::useOpenCL() << std::endl;

If I comment out this code, the exception occurs.
If I don't comment out, it works well without any output.

**Comment by alalek** [comment]
`useOpenCL()` returns "bool" result. What is value here (true/false)?

**Comment by Mitsuhiko-Matsukawa** [comment]
It returns true.

**Comment by alalek** [comment]
Thanks!
Could you also check OpenCV with this patch: #6057?

**Comment by Mitsuhiko-Matsukawa** [comment]
Thanks but it still has a problem.

`initialized = true;`

This code should be after handle is set.
I have changed below and it works well

```
static void* WinGetProcAddress(const char* name)
{
    static bool initialized = false;
    static HMODULE handle = NULL;
    if (!handle && !initialized)
    {
        cv::AutoLock lock(cv::getInitializationMutex());
        if(!initialized)
        {
            // initialized = true;  // this code is a problem
            handle = GetModuleHandleA("OpenCL.dll");
            if (!handle)
            {
                const char* path = "OpenCL.dll";
                const char* envPath = getenv("OPENCV_OPENCL_RUNTIME");
                if (envPath)
                    path = envPath;
                handle = LoadLibraryA(path);
                if (!handle)
                {
                    if (envPath)
                        fprintf(stderr, ERROR_MSG_CANT_LOAD);
                }
                else if (GetProcAddress(handle, OPENCL_FUNC_TO_CHECK_1_1) == NULL)
                {
                    fprintf(stderr, ERROR_MSG_INVALID_VERSION);
                    handle = NULL;
                }
            }
            initialized = true;  // move here
        }   
    }
    if (!handle)
        return NULL;
    return (void*)GetProcAddress(handle, name);
}
```

**Comment by alalek** [comment]
Thanks! Right, patch is updated.

**Comment by Mitsuhiko-Matsukawa** [comment]
I have checked, it works well, thank you so much!
