### ISSUE TITLE
Option for logging disabling on Android

### ISSUE THREAD

**Issue by PhilLab** [Itseez/opencv#6064]
The Android camera views pollute the log with multiple messages per frame, e.g.:

    D/JavaCameraView: Preview Frame received. Frame size: 1382400
    D/CameraBridge: mStretch value: 1.0
    D/FpsMeter: 6,27 FPS@1280x720
 Not only would disabling them via an option make the log more understandable but also the performance should increase.

**Comment by alalek** [comment]
There is `BuildConfig.DEBUG` build constant in Android code (not sure about normal Java)
http://stackoverflow.com/a/8050835

What is about messages filtering (without verbose/debug messages)?

**Comment by pranavg189** [comment]
I would like to work on this feature...any idea on where to start ?

**Comment by PhilLab** [comment]
Create your own logging class with the same interface as the official android.util.Log class:

    class Log {
        public static int w(String tag, String msg) {
             if(mLoggingEnabled) {
                 Log.w(tag, msg)
             }
        }
        public static void enableLogging(boolean enabled) {
              mLoggingEnabled = enabled
        }
        //...............
    }

And then replace all calls to ``android.util.Log.*`` with this class (e.g. by replacing the include command)

Additionally, the call to ``Log.enableLogging()`` could be delegated also from the OpenCV manager class

**Comment by pranavg189** [comment]
Thanks @PhilLab for the insight :) you mean that we create the same exact interface which is given in android.util.Log...customize it....and replace all the calls from original one to custom one...but where should we store the new Log interface that we will be creating..?

**Comment by pranavg189** [comment]
should the new Log class be placed in the package **org.opencv.engine.manager**

**Comment by PhilLab** [comment]
I would place it into org.opencv.engine

**Comment by alalek** [comment]
I believe package name should be `org.opencv.android`. Files are located [here](https://github.com/Itseez/opencv/tree/3.1.0/modules/java/generator/src/java)

**Comment by alalek** [comment]
I'm not sure that this should be done in OpenCV.
Please refer to Android documentation how to configure logging: http://developer.android.com/reference/android/util/Log.html#isLoggable(java.lang.String, int)

**Comment by PhilLab** [comment]
@alalek: thanks for evaluating! Actually, ``isLoggable`` seems like a way too expensive function, c.f. [__android_log_level](https://github.com/android/platform_system_core/blob/7a106f7c1220fc749ca137675ac7b4c915418f47/liblog/log_is_loggable.c#L92-L251) which is called by [__android_log_is_loggable](https://github.com/android/platform_system_core/blob/7a106f7c1220fc749ca137675ac7b4c915418f47/liblog/log_is_loggable.c#L253-L257), again which is called by ``android_util_Log_isLoggable``, the native backend of said function.

The information by Google about logging is actually quite contradicting: It says in the documentation of [Log](http://developer.android.com/reference/android/util/Log.html):
 >  Verbose should never be compiled into an application except during development. Debug logs are compiled in but stripped at runtime

This is obviously not true - when looking at the logs of released apps, verbose and debug logging still appear. In the [release guide](http://developer.android.com/tools/publishing/preparing.html#releaseready)

 > You can deactivate logging by removing calls to Log methods in your source files

On stackoverflow, lots of people advise [writing](http://stackoverflow.com/a/10026228
) [a](http://stackoverflow.com/a/4959362) [logging](http://stackoverflow.com/a/2019597) [wrapper](http://stackoverflow.com/a/4128456) or even [proguard](http://stackoverflow.com/a/2466662). Now I am confused

**Comment by alalek** [comment]
Some configuration options are described on provided link:
> You can change the default level by setting a system property: 'setprop log.tag.<YOUR_LOG_TAG> <LEVEL>' Where level is either VERBOSE, DEBUG, INFO, WARN, ERROR, ASSERT, or SUPPRESS. SUPPRESS will turn off all logging for your tag. You can also create a local.prop file that with the following in it: 'log.tag.<YOUR_LOG_TAG>=<LEVEL>' and place that in /data/local.prop.

But I didn't try to play with them.

**Comment by PhilLab** [comment]
This is only possible via the adb shell: ``adb shell setprop log.tag.<YOUR_LOG_TAG> <LEVEL>``- Setting it in code with ``System.setProperty("log.tag.JavaCameraView", "ERROR");`` won't have any effect. Writing the local.prop file is only possible with root rights on newer devices ([link](http://stackoverflow.com/a/18556839)). So this approach might work for developer devices but is not feasible for end users. I seriously don't get how Google wants us to use the logging feature.

**Comment by pranavg189** [comment]
I think we should try setting different configuration options directly from within opencv as @alalek suggested...there must be some way of setting the logging features from within the code....

**Comment by alalek** [comment]
We have some discussion on our meeting about this issue:
- we don't want to add functionality not related to computer vision into OpenCV. So the "Log" wrapper class is not preferable way for us. We don't want to make another log4j.
- we believe approach with `if(BuildConfig.DEBUG)` condition and proper message level setup (verbose/debug) should work fine.

**Comment by PhilLab** [comment]
Thanks for merging @alalek! If you had time for discussing it in the meeting again, here would be one addition:
The problem I see with commits like said #6397 is that we have to manually change every Log statement, the code gets harder to read and future code additions might forget the wrapping. Having a slim Log class which just adds a ``BuildConfig.DEBUG`` around all log levels below ``INFO`` would mean that we just have to replace ``import android.util.Log;`` with ``import org.opencv.Log;`` and are done. We could even configure Proguard to strip those methods completely.

**Closing it for now**
