### ISSUE TITLE
No module named 'cv2' in opencv-3.1

### ISSUE THREAD

**Issue by vinllen** [Itseez/opencv#6071]
I have python-2.7 and python-3.4 in my Mac, when i switch python version to 3.4, and install opencv-3.1, it looks like `cv2` module cannot work in my computer:
```
Python 3.4.0 (default, Feb  5 2016, 19:51:52)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
>>>
```
But it works well when my python version is 2.7.

**Comment by alalek** [comment]
Questions must go to http://answers.opencv.org
OpenCV Python binding for Python2 and Python3.x are different. You need to build both with installed build requirements.

There is nothing to fix in OpenCV (only bugs / features are tracked here). Closing.
