### ISSUE TITLE
Undefined references after building on Ubuntu

### ISSUE THREAD

**Issue by Gbear605** [Itseez/opencv#6076]
I had OpenCV version 2.4.12 running fine on my computer. I then built and installed version 3.1.0. Now when I compile, I get
```
/tmp/ccjxY4XG.o: In function `cvPointFrom32f':
/usr/local/include/opencv2/core/types_c.h:929: undefined reference to `cvRound'
/usr/local/include/opencv2/core/types_c.h:930: undefined reference to `cvRound'
/tmp/ccjxY4XG.o: In function `cvReadInt':
/usr/local/include/opencv2/core/core_c.h:2318: undefined reference to `cvRound'
/tmp/ccjxY4XG.o: In function `cvEllipseBox':
/usr/local/include/opencv2/imgproc/imgproc_c.h:1041: undefined reference to `cvRound'
/usr/local/include/opencv2/imgproc/imgproc_c.h:1042: undefined reference to `cvRound'
collect2: error: ld returned 1 exit status
```

I am compiling the following code.c file:
```
#include "opencv2/highgui/highgui_c.h"
#include <stdio.h>
int main(int argc, char* argv[])
{
      return 0;
}
```
I am compiling it using 
```
gcc -ggdb `pkg-config opencv --cflags --libs` camera.c -o camera `pkg-config --libs opencv`
```

I am on a Jetson TK1, which has an ARM cpu. It is running Ubuntu 14.04.

I installed 3.1.0 by 

```
wget https://github.com/Itseez/opencv/archive/3.1.0.zip
unzip 3.1.0.zip
cd opencv-3.1.0
mkdir build
cd build
cmake -DWITH_CUDA=ON -DCUDA_ARCH_BIN="3.2" -DCUDA_ARCH_PTX="" -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF ..
sudo make -j4 install
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/" >> ~/.bashrc
source ~/.bashrc
```

**Comment by alalek** [comment]
1) Try to add `#include <opencv2/highgui.hpp>` before "c" header

2) Add output: `pkg-config opencv --cflags --libs`
You may try to specify `PKG_CONFIG_PATH` environment variable to point into /usr/local/... path for OpenCV 3.1

3) You can also debug included headers and check that there is no mix of 2.4/3.1 headers:
```
gcc++ -E -x c++ - -v `pkg-config opencv --cflags --libs` \
    <<< '#include "opencv2/opencv.hpp"' | grep  "# 1 .*opencv2.*1"
```

**Comment by Gbear605** [comment]
Adding `#include <opencv2/highgui.hpp>` fixed my problem.

**Comment by charlie5** [comment]
#include <opencv2/core/fast_math.hpp>      // Works for me on archlinux.

**Comment by suryaprakaz** [comment]
How do I add #include <opencv2/highgui.hpp> when I am using OpenCV C bindings? Will there not be a language clash?
