### ISSUE TITLE
buildInfo file Enhancement Request.

### ISSUE THREAD

**Issue by FredFG** [Itseez/opencv#6089]
It would be useful if the "buildInfo" file contained the data/time of the build.
This would isolate this important information from the date of generating the buildInfo file which might be a significant time later.

**Comment by alalek** [comment]
More useful thing is VCS revision (Git commit hash), refer to `getBuildInformation()`

**Comment by pranavg189** [comment]
Can i get an idea on how this buildinfo file is created......how to proceed on that using `getBuildInformation()`

**Comment by alalek** [comment]
@FredFG @pranavg189 Could you take a look on #6090?
Added build info entries are available [here](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/5375/steps/cmake/logs/stdio)
