### ISSUE TITLE
custom_hal.hpp not found

### ISSUE THREAD

**Issue by ABeekhub** [Itseez/opencv#6098]
just reporting, while trying to compile opencv from git on opensuse i got this error:
```
~/opencv/modules/core/src/hal_replacement.hpp:226:10: fatal error: 'custom_hal.hpp' file not found
#include "custom_hal.hpp"
         ^
1 error generated.
```
I found this file in the same folder: 
`~/opencv/modules/core/src/hal_replacement.hpp`

When I symlinked it to custom_hal.hpp in the same folder it continued compiling.

gr
Arno

**Comment by mshabunin** [comment]
File `custom_hal.hpp` should've been generated by cmake in your build directory. Please check whether your source folder has any changed files by running `git status` and `git describe`. Please try to build OpenCV from scratch in empty out-of-source build directory.

**Comment by ABeekhub** [comment]
Hi mshabunin,

As you wrote I started from scratch and everything compiled fine.

thanks for the reply and the hint.

gr
Arno

**Comment by dozyc** [comment]
I had the same problem, I think because I moved my build directory from one place to another. Even after regenerating in CMake I got this error. I had to trash the build directory completely then Configure/Generate. Kind of annoying but it worked out.

**Comment by patrikhuber** [comment]
I would like to re-open this, there is definitely a bug, and I can reproduce it. I'm on newest master as of today, clean tree, and I'm doing an out-of-source tree.

How to reproduce:

If you leave OPENCV_CONFIG_FILE_INCLUDE_DIR on the default value (which is the build directory, let's say `C:/opencv-git/build`), everything works fine. However if you change it to something else, for example the install directory, outside your build directory, like `C:/opencv-git/install`, then you get: `fatal error C1083: Cannot open include file: 'custom_hal.hpp': No such file or directory`.

Is `cvconfig.h` meant to go outside the build directory? If yes, something needs to be fixed. If no, the user should be prevented of doing so, to avoid the custom_hal.hpp error.

**Comment by mshabunin** [comment]
@patrikhuber , why do you change `OPENCV_CONFIG_FILE_INCLUDE_DIR`? Can you add more details about your usage model?

**Comment by patrikhuber** [comment]
@mshabunin: Well I thought it should go into the INSTALL dir. Maybe I'm wrong about that? I changed it since cmake-gui exposes it as an option that can be changed. If it is not supposed to go outside the build directory and OpenCV doesn't compile when it's changed, then maybe the user shouldn't be allowed to change it?

My usage model is the following: Completely separate source, build and install trees, all next to each other:

```
opencv/    # sources
build/
install/
```

**Comment by mshabunin** [comment]
@patrikhuber , looks like this option should not be changed. I ran 
```.sh
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ../opencv
make install
``` 
and it worked well. `cvconfig.h` is located in the `install/include/opencv2` folder.

**Comment by patrikhuber** [comment]
@mshabunin You're right! So it seems to me like the best course of action would be to remove `OPENCV_CONFIG_FILE_INCLUDE_DIR` from the options that are exposed to cmake-gui, to prevent users to easily change it?

**Comment by alalek** [comment]
You see here CMake "cache" variables. There is a problem: CMake doesn't support variables with global scope, so using of "cache" variables is just workaround for missing global variables support.
Just ignore these unknown variables, touching them is always on your own risk (non-standard combinations are not supported well or just break your build).

**Comment by patrikhuber** [comment]
Hmm I see. The problem is knowing which ones are "unknown" and which ones are not, as they look exactly the same in cmake-gui. So you don't know which variables you are "allowed" to touch and which are "unsupported".

**Comment by alexcohn** [comment]
See https://github.com/opencv/opencv/commit/0c4d5ffecd1585b0aa57cedfdfba0dd46d8f6041. It looks like the same argument may be applied to **custom_hal.hpp**, too. I find it polluting in the _root_ **${CMAKE_BINARY_DIR}**. Probably the headers **cv_cpu_config.h**, **cvconfig.h**, **opencv2/cvconfig.h** and **opencv2/opencv_modules.hpp** should be stored elsewhere, too. At least, for this latter quartet, overriding **OPENCV_CONFIG_FILE_INCLUDE_DIR** works (but this causes **custom_hal.hpp** to get lost, as @patrikhuber [found](https://github.com/opencv/opencv/issues/6098#issuecomment-265000441)).

**Comment by eninyo** [comment]
so what is the default OPENCV_CONFIG_FILE_INCLUDE_DIR?
i have the putput to "build" directory. 
i though to set this to: build\install
setting it to install (same level as build) dodn't work. the custom_hal.hpp file is missing :-(
so now i don't know what it was...
