### ISSUE TITLE
Reading disconnected camera returns true (3.1)

### ISSUE THREAD

**Issue by oprospero** [Itseez/opencv#6107]
I have no problems opening and reading frame from a usb camera. However when disconnecting the read function will always return true. This occurs on Opencv 3.x but not on 2.4.x

Affects:
Windows:
Opencv 3.1
Opencv 3.0
Linux:
Opencv 3.1
Opencv 3.0

Works on
Windows:
Opencv 2.4.8
Linux:
Opencv 2.4.9

Test Code
```
int main() {
 int device = 0;
 VideoCapture cap(device);
 cap.open()

 if (cap.open()){
  while (1) {
   Mat frame;
   bool ret = cap.read(frame);
   if (ret)
    imshow(frame);
   else
    break;
  }
 }

}
```

Possible related tickets:
https://github.com/Itseez/opencv/issues

**Comment by alalek** [comment]
Duplicate #5746
