### ISSUE TITLE
drawMarker Parameters order in docs.opencv.org

### ISSUE THREAD

**Issue by Vovochka777** [Itseez/opencv#6110]
http://docs.opencv.org/3.1.0/d6/d6e/group__imgproc__draw.html#ga482fa7b0f578fcdd8a174904592a6250

markerType and color in wrong order.

**Comment by rahulchhabra07** [comment]
I have started working on this. Will keep you updated on the progress.
Thanks.

**Comment by rahulchhabra07** [comment]
Done here: https://github.com/Itseez/opencv/commit/232f564011cad27fbde05fd713a04a6b38945bfd.
Please have a look and let me know if this is fine.

**Comment by sturkmen72** [comment]
it seems good. you should open a pull request.

**Comment by rahulchhabra07** [comment]
I have opened the Pull Request and it has passed required builds. Please merge it.
