### ISSUE TITLE
Could anyone check the performance of the function **findCircleGrid** on the following testing images?

### ISSUE THREAD

**Issue by an2tong** [Itseez/opencv#6115]
Hi,

I am trying to test the function **findCircleGrid**. For most cases, it can work very well. But when I test the following images, it always return false. I posted a detailed problem description in Stackoverflow: http://stackoverflow.com/questions/35397595/opencv2-4-11-findcirclegrid

Can you please help to check this problem. Thank you in advance!

**Comment by alalek** [comment]
http://answers.opencv.org
