### ISSUE TITLE
why cv2.cvtColor is too slow?

### ISSUE THREAD

**Issue by tornadomeet** [Itseez/opencv#6123]
hello,all,
 i found cv2.cvtColor is very slow(both test with opencv3.0 and opencv3.1) in python, so i test it with the code: 
```python
import time, cv2
img = cv2.imread('det.jpg')
tic = time.time()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
toc = time.time()
print "time is: ", toc-tic, "s"
```
and it output: ```time is:  23.2596108913 s```
the size of det.jpg is 550*367
what's wrong with this? thanks~

**Comment by alalek** [comment]
I believe you measure OpenCL kernels compilation. Try to disable OpenCL.

**Comment by tornadomeet** [comment]
@alalek cool! i rebuild opencv which disable OpenCL, then it is normal now, the output now is: ``time is:  0.00453495979309 s```, thanks very much!
in order to help others with build options, i paste my cmake here:
```
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/home/work/wuwei/tools/opencv3.1 -DWITH_OPENCL=OFF -DINSTALL_C_EXAMPLES=ON -DINSTALL_PYTHON_EXAMPLES=ON  -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.1.0/modules -DBUILD_EXAMPLES=ON ..
```

**Comment by alalek** [comment]
Actually real OpenCL optimization code path should not work for this code, but OpenCL bootstrapping code works (load OpenCL runtime and select OpenCL device).

**Comment by StevenPuttemans** [comment]
@alalek is there any way that to disable the OpenCL bootstrapping code when you do not want it to be loaded to avoid problems exactly like these. Since he is not using UMats there should be no loading of OpenCL code at all right?

**Comment by alalek** [comment]
At this moment, a code near `CV_OCL_RUN` assumes that calls `cv::ocl::useOpenCL()` are very light, but it doesn't (due OpenCL bootstraping problem for the first call).
@StevenPuttemans Could you open a new issue?
