### ISSUE TITLE
libopencv_java3.so is 64-bit instead of 32-bit Android/Eclipse error

### ISSUE THREAD

**Issue by Wababa** [Itseez/opencv#6124]
Hi,
I am trying to build an App using OpenCV and NDK. The app works fine on my Nexus 5 but when I try it on my Samsung Galaxy S6 I get a message that OpenCV could not be initialized correctly and on the logcat I get the error 

>  E/art(3895): dlopen("/data/app/org.opencv.engine-1/lib/arm64/libopencv_java3.so", RTLD_LAZY) failed: dlopen failed: "/data/app/org.opencv.engine-1/lib/arm64/libopencv_java3.so" is 64-bit instead of 32-bit

Browsing through StackOverflow I figured that this error could be resolved including the library in the apk. So I tried including opencv placing

> OPENCV_CAMERA_MODULES:=on
OPENCV_INSTALL_MODULES:=on

in the Android.mk and loading OpenCV with: 

> static {
    if (!OpenCVLoader.initDebug()) {
        // Handle initialization error
    }
}

like stated in the opencv tutorial [page](http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.html) 
but I couldn't get it to load OpenCV.
Here is my Android.mk and Application.mk
 Android.mk

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

OPENCV_CAMERA_MODULES:=on
OPENCV_INSTALL_MODULES:=on

include /Users/ben/Downloads/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk

LOCAL_MODULE    := native gray
LOCAL_SRC_FILES := jni_part.cpp 
LOCAL_LDLIBS +=  -llog -ldl
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -llog 
 
include $(BUILD_SHARED_LIBRARY)
```

Application.mk 

```
APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -fexceptions
APP_ABI := armeabi-v7a
APP_PLATFORM := android-9
```
Thank you ;)

**Comment by mshabunin** [comment]
Did you try to build with `APP_ABI := arm64-v8a` ?

**Comment by alalek** [comment]
OpenCV Android Manager doesn't support this configuration (there is 64-bit ARM CPU detected, so 64-bit library loaded).
You need to build your app with OpenCV directly (include into APK "libs"): suggestions from SO should work fine, just check "libs" dir.
Also you can check this [OpenCV initialization pattern](https://github.com/Itseez/opencv/blob/3.1.0/samples/android/face-detection/src/org/opencv/samples/facedetect/FdActivity.java#L144-L150)

P.S. Also you should remove "OpenCV Manager" from this phone.

Related #5862

**Comment by Wababa** [comment]
Wow, that was an easy fix. Actually changing the APP_ABI worked. Thank you so much @mshabunin :D

**Comment by gaochunchun** [comment]
good.

**Comment by ShreyashPromact** [comment]
@Wababa  where you have changed `APP_ABI` ? I can't see that in code.
