### ISSUE TITLE
cv::cuda::reduce to row and to col produce row vectors

### ISSUE THREAD

**Issue by dtmoodie** [Itseez/opencv#6126]
cv::cuda::redeuce's documentation states that:
Dimension index along which the matrix is reduced. 0 means that the matrix is reduced to a single row. 1 means that the matrix is reduced to a single column.

However that is not correct.  As can be seen [here](https://github.com/Itseez/opencv/blob/master/modules/cudev/include/opencv2/cudev/grid/reduce_to_vec.hpp) for both gridReduceToRow and gridReduceToCol, a row vector is created.

**Comment by Aravind-Suresh** [comment]
I will work on this.

**Comment by jet47** [comment]
A row vector is used to create contiguous matrix, so that 1D indexing can be used.
