### ISSUE TITLE
Content missing in the OpenCV-Python Tutorials/Mathematical Tools in OpenCV

### ISSUE THREAD

**Issue by ptar543** [Itseez/opencv#6127]
The content of "OpenCV 3.0.0-dev documentation » OpenCV-Python Tutorials » Core Operations » Mathematical Tools in OpenCV" seems to be missing now.
Please help.

**Comment by alalek** [comment]
Any link?

P.S. "3.0.0-dev" documentation is not actual anymore. The latest version is "3.1.0-dev"

**Comment by ptar543** [comment]
http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_core/py_maths_tools/py_maths_tools.html#mathematical-tools

Thank you!

**Comment by StevenPuttemans** [comment]
Actually that page does not exist anymore

http://docs.opencv.org/master/d7/d16/tutorial_py_table_of_contents_core.html#gsc.tab=0

But I am guessing you need arithmetic operations? Take a look here:

http://docs.opencv.org/master/d0/d86/tutorial_py_image_arithmetics.html#gsc.tab=0

**Comment by alalek** [comment]
Thanks Steven!

**Comment by scweiser** [comment]
So there are no more tutorials for more advanced image mathematical tools?  I've been going through the tutorials, but the one section I needed most was use of PCA/SVD for images and videos.

**Comment by StevenPuttemans** [comment]
Euh wait, why would the image mathematical tools be gone? They are still fully operational inside OpenCV. 

There is still a tutorial on PCA: http://docs.opencv.org/master/d1/dee/tutorial_introduction_to_pca.html
There is also still documentation on SVD: http://docs.opencv.org/master/df/df7/classcv_1_1SVD.html#details

**Comment by scweiser** [comment]
Thanks!  I'm more interested in seeing how to use it in python / some tutorials for that, but the C documentation is helpful..  I'm not seeing any PCA/SVD modules in the python cv2 module though.

`>>> cv2.SVD()`
`AttributeError: module 'cv2' has no attribute 'SVD'`

For now I'm using python-sklearn for PCA, but in the future we'd like to use OpenCV for PCA/SVD.

**Comment by StevenPuttemans** [comment]
Actually I am guessing there must be some extra namespace, because all the [PCA functions](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L1900) have CV_EXPORTS_W prefixes which ports them to the Python wrappers.

@berak, got any clue where the SVD and PCA are inside Python wrappers?

**Comment by berak** [comment]
@StevenPuttemans , the PCA and SVD *Objects* are not exposed to python(or java), but the PCACompute(), SVDecomp(), etc. *functions* are useable from python (same functionality, i'd say)

**Comment by scweiser** [comment]
Ok, got it.  Thanks so much!
