### ISSUE TITLE
A misstake in fisheye camera model documentation

### ISSUE THREAD

**Issue by Nandiin** [Itseez/opencv#6128]
In the "Detailed Description" Section of [this page] (http://docs.opencv.org/master/db/d58/group__calib3d__fisheye.html#gsc.tab=0), it says 

_x' = (theta_d / r) x
y' = (theta_d / r) y_

but I think it should be

_x' = (theta_d / r) a
y' = (theta_d / r) b_

since

_a = x / z
b = y / z_

I have checked the source code and it supports my understanding above.

please check it out.

**Comment by Aravind-Suresh** [comment]
Can I fix this documentation?

**Comment by Aravind-Suresh** [comment]
Is this fine?

https://github.com/Aravind-Suresh/opencv-1/commit/f6d0c89fcaa1d2d2e5986bd71ae12a5f1b12eeea

**Comment by Aravind-Suresh** [comment]
Is this documentation fine? If yes, I will make a pull request.

https://github.com/Aravind-Suresh/opencv-1/commit/f6d0c89fcaa1d2d2e5986bd71ae12a5f1b12eeea
