### ISSUE TITLE
Docs: Incomplete description of applyColorMap() parameters

### ISSUE THREAD

**Issue by lvv** [Itseez/opencv#6149]
applyColorMap function have two features:

- input image must have depth of CV_8U only
- If input image have different depth, applyColorMap silently returns (in second parameter)  unmodified input image.  

I personally consider both of above as bugs, but this is only my own sense of style.   Submitted issue is about the fact that non of the above features are reflected in docs.   

These features are described in  colormap.cpp:148, but not in RST docs.

**Comment by lvv** [comment]
I've submitted fix at https://github.com/Itseez/opencv/pull/6150

**Comment by sturkmen72** [comment]
this can be closed down
