### ISSUE TITLE
using movie or file instead of camera

### ISSUE THREAD

**Issue by adamib** [Itseez/opencv#6151]
Can you please advice on how to use Lucas optical flow to detect motion for movie file instead of the webcam? so I don't want to click (or use the mouse_down function)

thanks

**Comment by Aravind-Suresh** [comment]
Have a look into this: http://docs.opencv.org/master/d7/d8b/tutorial_py_lucas_kanade.html#gsc.tab=0

**Comment by adamib** [comment]
thanks
