### ISSUE TITLE
ConvexityDefects function does not detect points correctly

### ISSUE THREAD

**Issue by cvguy** [Itseez/opencv#6155]
I'm using the version 3.1.0, the version 2.4.9 works fine.
There is a line that crosses the hand that shouldn't be there.
![captura](https://cloud.githubusercontent.com/assets/17393664/13206390/47310eac-d8fd-11e5-81e4-338893dac68f.PNG)
The original image:
![a](https://cloud.githubusercontent.com/assets/17393664/13206399/6301830a-d8fd-11e5-9ef1-05f1f8fa7ade.jpg)
It is important to note, that I have tried the fix #5914 for the issue #5908 compiled the binaries and tried with that fix, but that doesnt' fix my problem.
These are the points returned:
266.0 112.0 277.0 174.0
226.0 168.0 232.0 172.0
229.0 179.0 249.0 192.0
248.0 210.0 256.0 201.0
258.0 215.0 261.0 200.0
286.0 223.0 289.0 217.0
318.0 223.0 322.0 190.0
351.0 166.0 348.0 160.0
351.0 156.0 320.0 169.0
327.0 121.0 248.0 210.0
326.0 120.0 310.0 152.0
299.0 107.0 284.0 142.0

**Comment by devkicks** [comment]
Hi, 
Just wondering, have you tried ConvexityDefects with a different image? The image in example above seems to have two "blobs" - try using a different image or selecting the blobs using findContours

**Comment by cvguy** [comment]
Yes, I am already selecting the biggest contour, however with version 2.4.9 it works correctly.

**Comment by cvguy** [comment]
Another image that produces the same result.
![1](https://cloud.githubusercontent.com/assets/17393664/13216178/7e0faaca-d95a-11e5-91f4-6b7d7dc973a3.jpg)
![captura2](https://cloud.githubusercontent.com/assets/17393664/13216184/90439f26-d95a-11e5-92e5-16570a355528.PNG)

**Comment by cvguy** [comment]
Code that produces the error:
[HSL.txt](https://github.com/Itseez/opencv/files/140503/HSL.txt)
[Window.txt](https://github.com/Itseez/opencv/files/140504/Window.txt)
[Main.txt](https://github.com/Itseez/opencv/files/140505/Main.txt)

**Comment by sturkmen72** [comment]
i used [ a test code](https://github.com/sturkmen72/opencv_samples/blob/master/convexityDefects_sample.cpp) and see no problem with convexityDefects function
![result](https://cloud.githubusercontent.com/assets/12151541/13217988/2c5d24ae-d96f-11e5-8140-845f1d1ce335.png)
![result1](https://cloud.githubusercontent.com/assets/12151541/13217994/393c6ca2-d96f-11e5-8172-d2aa79a22eb6.png)

**Comment by cvguy** [comment]
I managed to solve the problem somehow, by doing some erosion and dilation, thus avoiding the line crossing.
Probably there are some non-visible pixels that altered the result.
It still is quite weird that @sturkmen72 managed to get it right using the c version, but using the java wrapper it doesnt' work, and need to do the workaround mentioned above (erode/dilate).
Thank you all for answering.

**Comment by cvguy** [comment]
By the way, the full dump of the points returned of the first image is:
Start 266.0 112.0 End 226.0 168.0Farthest PT 277.0 174.0
Start 226.0 168.0 End 229.0 179.0Farthest PT 232.0 172.0
Start 229.0 179.0 End 248.0 210.0Farthest PT 249.0 192.0
Start 248.0 210.0 End 258.0 215.0Farthest PT 256.0 201.0
Start 258.0 215.0 End 286.0 223.0Farthest PT 261.0 200.0
Start 286.0 223.0 End 318.0 223.0Farthest PT 289.0 217.0
Start 318.0 223.0 End 351.0 166.0Farthest PT 322.0 190.0
Start 351.0 166.0 End 351.0 156.0Farthest PT 348.0 160.0
Start 351.0 156.0 End 327.0 121.0Farthest PT 320.0 169.0
Start 327.0 121.0 End 326.0 120.0Farthest PT 248.0 210.0
Start 326.0 120.0 End 299.0 107.0Farthest PT 310.0 152.0
Start 299.0 107.0 End 266.0 112.0Farthest PT 284.0 142.0

Being the "Start 327.0 121.0 End 326.0 120.0Farthest PT 248.0 210.0" the one that crosses the hand and shouldnt' be there.

In case someone wants to compare them.

**Comment by cvguy** [comment]
As expected, erode/dilate doesn't fix the problem in all cases.
The problem continues to appear, still I think that convexityDefects returns an additional convexity that shouldn't be there.

**Comment by devkicks** [comment]
There seems to some logical mistake in your code. I have always used OpenCV with C++ so cant check your code in depth. However here is my suggestion what you should do. Divide your algorithm into few steps and check if output of each step is what you expect it to be. My best bet is that there is a logical mistake where you select the biggest blob. If you look at the first figure its combining the convexity defect points with another blob. Here is what general steps there should be in your code.

1. Load a binary image
2. Find contours --> findContours function in C++
3. Find the biggest blob using -> contourArea (note that contour area is different from the number of points in a contour).
4. Select the biggest blog ad use it with [approxPolyDP](http://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#approxpolydp) to approximate polygonal curves - this step also acts as denoising the noise you might have in the contour.
5. apply convexHull and convexityDefects

I hope this helps you. If you can provide source code , I will see if I have sometime on the next weekend to look at it.

**Comment by cvguy** [comment]
Thank you so much, I will try that.

**Comment by devkicks** [comment]
![segcolor_35](https://cloud.githubusercontent.com/assets/3410225/13255335/a1bb66ba-da3d-11e5-9c1c-e05257ff3a8b.png)

Check your code on this image - it has only one blob

**Comment by cvguy** [comment]
Yes, with that one it works perfectly, i will try what you suggested and comment the results.

**Comment by cvguy** [comment]
Now it works, i did it step by step as @devkicks suggested, apparently step 4 (approxPolyDp) is mandatory, otherwise it doesn't work, whenever I don't do that step, additional lines are created.
Thank you all.

**Comment by devkicks** [comment]
can someone please mark this as closed since the problem was solved. Thanks
