### ISSUE TITLE
Unable to open VideoCapture: "VIDIOC_QUERYCTRL: Inappropriate ioctl for device‏"

### ISSUE THREAD

**Issue by shadow1runner** [Itseez/opencv#6157]
Hi,

I want to use the following video grabber (output from `lsusb`):
```
Bus 003 Device 005: ID 1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]
````
It works out of the box on both Ubuntu 14.04 and 15.10 using VLC (by opening it as capture device).

However, the following sample program yields the error (on stderr) `VIDIOC_QUERYCTRL: Inappropriate ioctl for device‏`
```
#include "opencv2/opencv.hpp"

int main(int, char**)
{
    cv::VideoCapture cap(1);
    // unable to read frames etc.
}
```

I was able to reproduce this behavior on:
   * OpenCV 3.1
   * master (177aef05b6b5e0b31143fd84ff66f44cd1295688)

I also tried with the official Ubuntu packages coming in (the quite old) `v2.4.8` where the error does _not_ occur.

Any ideas?
Thanks in advance!

**Comment by mshabunin** [comment]
Please compare output of `cv::getBuildInformation()` from 3.1 and 2.4.8, especially the part starting with `--   Video I/O:` and provide results here. Probably you need to install additional development packages to enable this functionality when building OpenCV from sources.

**Comment by alalek** [comment]
> cv::VideoCapture cap(1);

What is about `cv::VideoCapture cap(0);`?

Add output of this command:
```
ls -al /dev/video*
```

**Comment by shadow1runner** [comment]
@mshabunin

`3.1-dev`:
```
 Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  YES (ver 2.2.1)
    FFMPEG:                      YES
      codec:                     YES (ver 54.35.0)
      format:                    YES (ver 54.20.4)
      util:                      YES (ver 52.3.0)
      swscale:                   YES (ver 2.1.1)
      resample:                  NO
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    NO/YES
    XIMEA:                       NO
    Xine:                        NO
    gPhoto2:                     NO
```

`2.4.8`:
```
Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  YES (ver 2.2.1)
    FFMPEG:                      YES
      codec:                     YES (ver 54.35.0)
      format:                    YES (ver 54.20.3)
      util:                      YES (ver 52.3.0)
      swscale:                   YES (ver 2.1.1)
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    Using libv4l (ver 1.0.1)
    XIMEA:                       NO
    Xine:                        NO
```

So according to that it comes down to `V4L/V4L2:                    NO/YES (nok)` <-> `V4L/V4L2:                    Using libv4l (ver 1.0.1) (ok)`. Could that be?

Here is the full output for each: 
[Buildinfo-3.1-dev.txt](https://github.com/Itseez/opencv/files/145195/Buildinfo-3.1-dev.txt)
[BuildInfo-2.4.8.txt](https://github.com/Itseez/opencv/files/145196/BuildInfo-2.4.8.txt)

Thanks

**Comment by shadow1runner** [comment]
@alalek:
`cap(0)` is my (internal) webcam on my notebook. I've tried the same on two different machine (one without any camera and then the notebook), both yielding the same result.

Notebook:
```~$ ls -al /dev/video*
crw-rw----+ 1 root video 81, 0 Feb 24 19:07 /dev/video0
crw-rw----+ 1 root video 81, 1 Feb 24 19:34 /dev/video1
```

**Comment by alalek** [comment]
Does internal webcam work? Or problem is same? We need to understand a source of this problem.

Could you try to install `libv4l-dev` package and rerun OpenCV CMake configuration?

**Comment by shadow1runner** [comment]
Yes, the internal camera works without any problems, it's just this framegrabber that makes problems.

I did as you suggested (`sudo apt-get install libv4l-0 libv4l-dev`), reran `cmake` and `sudo make install` and rebuilt my program. The output is still the same though:
```
  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  YES (ver 2.2.1)
    FFMPEG:                      YES
      codec:                     YES (ver 54.35.0)
      format:                    YES (ver 54.20.4)
      util:                      YES (ver 52.3.0)
      swscale:                   YES (ver 2.1.1)
      resample:                  NO
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    NO/YES
    XIMEA:                       NO
    Xine:                        NO
    gPhoto2:                     NO
```

**Comment by alalek** [comment]
Please try to run: `cmake -DWITH_LIBV4L=ON .` in the build directory

**Comment by shadow1runner** [comment]
@alalek yeash, I've played around with cmake a bit, see my update above. I've just pulled the latest changes and am building it again, I don't think it will make any difference to Update 2 above though.

**Comment by shadow1runner** [comment]
@alalek I have messed sth up on the previous try, by redoing the whole process I now get:
```
V4L/V4L2:                    Using libv4l1 (ver 1.0.1) / libv4l2 (ver 1.0.1)
```
and it works :-).

So to summarize the steps necessary for fixing this issue:
  * `sudo apt-get install libv4l-dev`
  *  `cmake -DWITH_LIBV4L=ON ..` (or similar, it's important to have the `WITH_LIBV4L` enabled
  *  `make && sudo make install`

So it's not a bug in master after all (, so I hope it's fine if I close it). 
Thank you very much for your help, @alalek, @mshabunin.

**Comment by Abhinavpndy** [comment]
Hi ..Ran these all command and completed successfully in Ubuntu 16 but if I am running my code in Eclipse, can any one help me to link that with Eclipse or how Eclipse can knows that we have done these changes ??

BTW facing error : Unable to stop the stream: Inappropriate ioctl for device
2018-01-27 19:50:48 ERROR VideoEventGenerator:52 - Error opening cameraId vid-01 with url=../sample-video/sample.mp4.Set correct file path or url in camera.url key of property file.

Please guide and thanks in advance..

**Comment by IvyGongoogle** [comment]
try to rebuild your opencv by adding `-D WITH_LIBV4L=ON`:

```
cd opencv
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=./local -D WITH_LIBV4L=ON ..
make -j
make install
```

**Comment by selamie** [comment]
Hi, 

I installed opencv on a processor running debian via sudo apt-get install python3-opencv and ran into the same error. Is there anyway to enable WITH_LIBV4L in that configuration, or should I uninstall and re-install from source?

**Comment by hamza-995** [comment]
I am trying to connect Raspberr pi v2 Camer to jetson nano via csi slot and when i try to feed this device in ros 
i get following error:
[ERROR] [1674907779.479409762]: Couldn't query v4l fps! error 25, Inappropriate ioctl for device
