### ISSUE TITLE
opencv.pc wrong library path for lippicv

### ISSUE THREAD

**Issue by Maya-BF** [Itseez/opencv#6163]
I installed opencv 3.1with homebrew. 
When compiling there is an error showing that the library lippicv is not found.

> ld: library not found for -lippicv
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

The file opencv.pc includes the library lippicv under the wrong path **{exec_prefix}/lib** when it's under **{exec_prefix}/share/share/OpenCV/3rdparty/lib**

**Comment by alalek** [comment]
Duplicate #5852
