### ISSUE TITLE
Array bounds warning while building source

### ISSUE THREAD

**Issue by huntrar** [Itseez/opencv#6164]
During CMake build on most recent master (https://github.com/Itseez/opencv/tree/177aef05b6b5e0b31143fd84ff66f44cd1295688)

`[ 33%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/contours.cpp.o
/home/huntrar/opencv/modules/imgproc/src/contours.cpp: In function ‘CvSeq* cvFindNextContour(CvContourScanner)’:
/home/huntrar/opencv/modules/imgproc/src/contours.cpp:837:37: warning: array subscript is above array bounds [-Warray-bounds]
                 i4 = i3 + deltas[++s];
                                     ^
/home/huntrar/opencv/modules/imgproc/src/contours.cpp:651:37: warning: array subscript is above array bounds [-Warray-bounds]
                 i4 = i3 + deltas[++s];
                                     ^
/home/huntrar/opencv/modules/imgproc/src/contours.cpp:555:37: warning: array subscript is above array bounds [-Warray-bounds]
                 i4 = i3 + deltas[++s];
                                     ^
/home/huntrar/opencv/modules/imgproc/src/contours.cpp:920:37: warning: array subscript is above array bounds [-Warray-bounds]
                 i4 = i3 + deltas[++s];
                                     ^
/home/huntrar/opencv/modules/imgproc/src/contours.cpp:731:37: warning: array subscript is above array bounds [-Warray-bounds]
                 i4 = i3 + deltas[++s];
                                     ^
`

**Comment by alalek** [comment]
Please report only real confirmed bugs with minimal problem reproducers (reproducer with memory corruption in this case).
Dumping warnings from compilers or static analyzers is not a good practice.

BTW, this warning is buggy in GCC 4.8.

**Comment by huntrar** [comment]
Oops, thanks for the heads up.
