### ISSUE TITLE
OpenCV 2.4 with FFMPEG 3.0.

### ISSUE THREAD

**Issue by dpo** [Itseez/opencv#6179]
I'm one of the maintainers of [Homebrew/Science](https://github.com/Homebrew/homebrew-science). We're getting reports that OpenCV 2.4 doesn't build with FFMPEG 3.0. The error is as in https://github.com/Itseez/opencv/issues/5762.

Looking at what you've done in OpenCV3, I prepared [this patch](https://gist.githubusercontent.com/dpo/c459b13eec0dc38d87a6). I'm no expert on either OpenCV or FFMPEG. Does the patch look complete to you? If so, feel free to merge it in for future releases.

Thanks.

**Comment by alokrajiv** [comment]
I'm still facing the issue. I've done `brew update` and `brew uninstall ffmpeg`. then tried `brew install opencv --with-ffmpeg`. still same error!

**Comment by mshabunin** [comment]
@alokrajiv , the fix has not been released yet. You have to build OpenCV by yourself using latest 2.4 branch revision or wait for OpenCV 2.4.13 and corresponding brew update.
AFAIK, brew has `--HEAD` option which allows you to install latest version from repository.

**Comment by alokrajiv** [comment]
@mshabunin solved. thanx.
