### ISSUE TITLE
OpenCV 2.4 with VTK 7

### ISSUE THREAD

**Issue by dpo** [Itseez/opencv#6180]
Configuring with `-DWITH_VTK=ON` fails with VTK7. The message is
```
  Requested modules not available:

    vtkRenderingOpenGL
```
Any ideas?

**Comment by hyuce** [comment]
When I use `-DWITH_VTK=ON` fails with VTK7
my message is `VTK support:                 NO`
Also python(3) libs in python(3) binding cannot be found.
my platform is OSX 10.11.3

**Comment by chengguo1987** [comment]
vtkRenderingOpenGL was replaced by vtkRenderingOpenGL2 in VTK 7.
So you can edit cmake/OpenCVDetectionVTK.cmake.

At line 6, change "vtkRenderingOpenGL" to "vtkRenderingOpenGL2".

**Comment by HaziqRazali** [comment]
Can u tell me where cmake/OpenCVDetectionVTK.cmake. is located ? I cant seem to find that file. I am having the same problems

**Comment by mannyglover** [comment]
@HaziqRazali, @chengguo1987 meant "OpenCVDetectVTK.cmake", not "OpenCVDetectionVTK.cmake".  I was also confused that "this file was missing".
