### ISSUE TITLE
Compilation fails on Raspbian Jessie

### ISSUE THREAD

**Issue by sonium0** [Itseez/opencv#6184]
The make process terminates with the following message:

[ 17%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o
/mnt/usbdrive/opencv-3.1.0/modules/imgcodecs/src/grfmt_webp.cpp: In member function ‘virtual bool cv::WebPEncoder::write(const cv::Mat&, const std::vector<int>&)’:
/mnt/usbdrive/opencv-3.1.0/modules/imgcodecs/src/grfmt_webp.cpp:258:93: error: ‘WebPEncodeLosslessBGR’ was not declared in this scope
/mnt/usbdrive/opencv-3.1.0/modules/imgcodecs/src/grfmt_webp.cpp:262:94: error: ‘WebPEncodeLosslessBGRA’ was not declared in this scope
modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:238: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o' failed
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o] Error 1
CMakeFiles/Makefile2:4829: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liuct** [comment]
I got the same issue on Ubuntu 12.04, i can confirm i have libwebp  installed.

**Comment by alalek** [comment]
Try to disable Webp support: `cmake -DWITH_WEBP=OFF <...>` or force usage of [provided webp sources](https://github.com/Itseez/opencv/tree/3.1.0/3rdparty/libwebp) `cmake -DBUILD_WEBP=ON`

You can also provide more information, like CMake output about WEBP:
```
WEBP:                        build (ver 0.3.1)
```

**Comment by sonium0** [comment]
Yes, this works

**Comment by liuct** [comment]
thanks a lot, the workaround also works for me.

**Comment by shangwenyao** [comment]
thank you so much! -DWITH_WEBP=OFF solve my issue as well.
