### ISSUE TITLE
Machine learning bindings for python not matching doc

### ISSUE THREAD

**Issue by kobbe** [Itseez/opencv#6188]
I have discovered that the machine learning library have moved in the python bindings from being directly in cv2 to cv2.ml. This change is nowhere to be found in the tutorials or the documentation of any of the functions. Example http://docs.opencv.org/3.0-last-rst/doc/py_tutorials/py_ml/py_svm/py_svm_opencv/py_svm_opencv.html?highlight=svm

OpenCV 3.0+ is affected

**Comment by alalek** [comment]
Documentation on this link is not supported anymore: `Last updated on Dec 30, 2014`
OpenCV migrated on doxygen generator, support for separate documentation via `.rst` is removed.

**Comment by kobbe** [comment]
How does that help me? How do I know how to call the functions? Is there no documentation for python and the machine learning library? 

It would maybe be a good idea to at least inform users that the documentation is not up to date and invalid. Any user searching for svm in opencv will come to that site and of course assume that it is indeed valid, there is nothing that ways it is not. A banner at the top of the page would be good.

**Comment by berak** [comment]
kobbe, have a look here: http://docs.opencv.org/ref/master/d6/d00/tutorial_py_root.html

**Comment by kobbe** [comment]
@berak, those tutorials also use the old bindings. http://docs.opencv.org/ref/master/dd/d3b/tutorial_py_svm_opencv.html#gsc.tab=0

**Comment by alalek** [comment]
Take a look on "digits" samples: https://github.com/Itseez/opencv/tree/master/samples/python

**Comment by berak** [comment]
kobbe, you're right, (just fixing that)

**Comment by kobbe** [comment]
@alalek Nice!
