### ISSUE TITLE
Opencv 2.4 FTBFS with GCC6 (with patch)

### ISSUE THREAD

**Issue by sergiomb2** [Itseez/opencv#6195]
From https://bugzilla.redhat.com/show_bug.cgi?id=1307821
Yaakov Selkowitz send this:  [Fix-FTBFS-with-GCC-6-1307821.txt] 
(https://github.com/Itseez/opencv/files/153849/Fix-FTBFS-with-GCC-6-1307821.txt)
( https://bugzilla.redhat.com/attachment.cgi?id=1131801 ) 
```
/builddir/build/BUILD/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:969:30: error: the compiler can assume that the address of 'annotate_img' will never be NULL [-Werror=address]
             if (&annotate_img!=NULL) {
                 ~~~~~~~~~~~~~^~~
/builddir/build/BUILD/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1016:34: error: the compiler can assume that the address of 'annotate_img' will never be NULL [-Werror=address]
                 if (&annotate_img!=NULL) {
                     ~~~~~~~~~~~~~^~~
/builddir/build/BUILD/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1111:25: error: the compiler can assume that the address of 'orientation_img' will never be NULL [-Werror=address]
     if (&orientation_img!=NULL) {
         ~~~~~~~~~~~~~~~~^~~
```

Upstream fix (among other unrelated changes): https://github.com/Itseez/opencv/commit/eebd4cad665f4f1270ca58bb13e9708e130f9b30 .

Please apply the fix on branch 2.4 and preferentially also do one new tag or release :-) .
Thanks.

**Comment by alalek** [comment]
Referred commit is on 2.4 [branch](https://github.com/Itseez/opencv/blob/8a09d95eab3fdb06bd9f402be1e59cf7d8b932b1/modules/contrib/src/chamfermatching.cpp#L969) ([2.4 link](https://github.com/Itseez/opencv/blob/2.4/modules/contrib/src/chamfermatching.cpp#L969)).

Just wait for 2.4.13 release.

**Comment by sergiomb2** [comment]
OK thanks , for me this issue is fixed

**Comment by kaisark** [comment]
The opencv 2.4.8 build failed with error below. For those on compiler 6, should we check out the 2.4.13 branch to avoid the build issue? Is there a work-around???

gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1) 

Thanks.


/home/pi/opencv/modules/contrib/src/chamfermatching.cpp: In member function ‘void cv::ChamferMatcher::Matching::computeDistanceTransform(cv::Mat&, cv::Mat&, cv::Mat&, float, float, float)’:
/home/pi/opencv/modules/contrib/src/chamfermatching.cpp:969:30: error: the compiler can assume that the address of ‘annotate_img’ will never be NULL [-Werror=address]
             if (&annotate_img!=NULL) {

**Comment by Abanoub-G** [comment]
Hi @sergiomb2 ,
                            I'm facing the same problem here. Can you please share how you solved?

**Comment by sergiomb2** [comment]
https://src.fedoraproject.org/rpms/opencv/blob/f24/f/opencv-2.4.12.3-gcc6.patch

does it help ?

**Comment by mahesh2492** [comment]
Does anyone have a solution? I am having the same issue. 
Thanks
