### ISSUE TITLE
Threading performance issue with OpenCV 3.1

### ISSUE THREAD

**Issue by cwilkens** [Itseez/opencv#6196]
I'm trying to poll a basic webcam and display the image in a window in C++. I'm using Visual Studio 2015 on Windows 7 x64. I built OpenCV, and have additional dependencies of libusb and this code: [https://github.com/inspirit/PS3EYEDriver](https://github.com/inspirit/PS3EYEDriver)

I request the camera at 640x480 60fps. When I try to do cv::cvtColor with CV_YUV2BGR_YUY2, it struggles to achieve 35 fps and prints a large number of "payload error" (debug prints from PS3EYEDriver). 
If I convert to grayscale (CV_YUV2GRAY_YUY2) then there's no issue and it reports working at 60 fps, with minimal to none "payload error" prints.

I looked into the source and noticed the color conversion CV_YUV2BGR_YUY2 uses parallel_for_, while the grayscale conversion doesn't. I'm not sure if I built OpenCV wrong (there were no errors) or if I'm doing something wrong elsewhere, or if this is a legitimate bug.

results of getBuildInformation():

> General configuration for OpenCV 3.1.0-dev =====================================
> 
>   Version control:               unknown
> 
>   Platform:
>     Timestamp:                   2016-03-02T00:46:08Z
>     Host:                        Windows 6.1.7601 AMD64
>     CMake:                       3.4.1
>     CMake generator:             Visual Studio 14 2015 Win64
>     CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild
> .exe
>     MSVC:                        1900
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio
> 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.23506.0)
>     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE
> _NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigob
> j /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP8  /MD /O2 /Ob2 /D NDEBUG  /Zi
>     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE
> _NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigob
> j /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP8  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
>     C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio
> 14.0/VC/bin/x86_amd64/cl.exe
>     C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRE
> CATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi
> /MP8  /MD /O2 /Ob2 /D NDEBUG  /Zi
>     C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRE
> CATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi
> /MP8  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
>     Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
>     Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL
>     Precompiled headers:         YES
>     Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32 vfw32
>     3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper I
> lmImf
> 
>   OpenCV modules:
>     To be built:                 core flann imgproc ml photo video imgcodecs sha
> pe videoio highgui objdetect superres ts features2d calib3d stitching videostab
>     Disabled:                    world
>     Disabled by dependency:      -
>     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d
> cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarp
> ing cudev java python2 python3 viz
> 
>   Windows RT support:            NO
> 
>   GUI:
>     QT:                          NO
>     Win32 UI:                    YES
>     OpenGL support:              NO
>     VTK support:                 NO
> 
>   Media I/O:
>     ZLib:                        build (ver 1.2.8)
>     JPEG:                        build (ver 90)
>     WEBP:                        build (ver 0.3.1)
>     PNG:                         build (ver 1.6.19)
>     TIFF:                        build (ver 42 - 4.0.2)
>     JPEG 2000:                   build (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
>     GDAL:                        NO
> 
>   Video I/O:
>     Video for Windows:           YES
>     DC1394 1.x:                  NO
>     DC1394 2.x:                  NO
>     FFMPEG:                      YES (prebuilt binaries)
>       codec:                     YES (ver 56.41.100)
>       format:                    YES (ver 56.36.101)
>       util:                      YES (ver 54.27.100)
>       swscale:                   YES (ver 3.1.101)
>       resample:                  NO
>       gentoo-style:              YES
>     GStreamer:                   NO
>     OpenNI:                      NO
>     OpenNI PrimeSensor Modules:  NO
>     OpenNI2:                     NO
>     PvAPI:                       NO
>     GigEVisionSDK:               NO
>     DirectShow:                  YES
>     Media Foundation:            NO
>     XIMEA:                       NO
>     Intel PerC:                  NO
> 
>   Parallel framework:            Concurrency
> 
>   Other third-party libraries:
>     Use IPP:                     9.0.1 [9.0.1]
>          at:                     C:/opencv/3rdparty/ippicv/unpack/ippicv_win
>     Use IPP Async:               NO
>     Use Eigen:                   NO
>     Use Cuda:                    NO
>     Use OpenCL:                  YES
>     Use custom HAL:              NO
> 
>   OpenCL:                        <Dynamic loading of OpenCL library>
>     Include path:                C:/opencv/3rdparty/include/opencl/1.2
>     Use AMDFFT:                  NO
>     Use AMDBLAS:                 NO
> 
>   Python 2:
>     Interpreter:                 C:/Python27/python.exe (ver 2.7.11)
> 
>   Python 3:
>     Interpreter:                 NO
> 
>   Python (for build):            C:/Python27/python.exe
> 
>   Java:
>     ant:                         NO
>     JNI:                         NO
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Matlab:                        Matlab not found or implicitly disabled
> 
>   Documentation:
>     Doxygen:                     NO
>     PlantUML:                    NO
> 
>   Tests and samples:
>     Tests:                       YES
>     Performance tests:           YES
>     C/C++ Examples:              NO
> 
>   Install path:                  C:/opencv/mybuild/install
> 
>   cvconfig.h is in:              C:/opencv/mybuild
> 
> 

The core of my program is just getting the frame from the camera, converting the color space, and displaying the image:

	
	
	cv::Mat image(ctx.eye->getHeight(), ctx.eye->getWidth(), CV_8UC2);
	cv::Mat frame;
	cv::namedWindow("image");
	for (;;)
	{
		uint8_t* new_pixels = ctx.eye->getFrame();

		clock_t now_ticks = clock();
		ctx.last_frames++;
		if (now_ticks - ctx.last_ticks > 1000)
		{
			printf("FPS: %.2f\n", 1000 * ctx.last_frames / (float)(now_ticks - ctx.last_ticks));
			ctx.last_ticks = now_ticks;
			ctx.last_frames = 0;
		}

		memcpy(image.data, new_pixels, ctx.eye->getRowBytes() * ctx.eye->getHeight());
		free(new_pixels);

		cv::cvtColor(image, frame, CV_YUV2BGR_YUY2);
		//cv::cvtColor(image, frame, CV_YUV2GRAY_YUY2);

		imshow("image", frame);

		if (cv::waitKey(1) >= 0)
			break;
	}

I'm not sure what to do next in terms of debugging this issue, and I'm not super knowledgeable about threading, but if you have pointers I'll gladly investigate more.

**Comment by alalek** [comment]
> Performance tests: YES

Please investigate problem via performance tests

**Comment by mshabunin** [comment]
You can reduce number of threads or disable them completely using function: `void cv::setNumThreads(int nthreads)`.

**Comment by cwilkens** [comment]
Ok. There definitely seems to be something wrong with my build. I ran the tests by right-clicking -> Build on the RUN_TESTS project in the VS 2015 solution. I let it run for a couple hours before cancelling, and this was the output:

```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug x64 ------
1>  Test project C:/opencv/mybuild
1>        Start  1: opencv_test_core
1>   1/37 Test  #1: opencv_test_core .................***Failed  727.12 sec
1>        Start  2: opencv_perf_core
1>   2/37 Test  #2: opencv_perf_core .................   Passed  2034.97 sec
1>        Start  3: opencv_sanity_core
1>   3/37 Test  #3: opencv_sanity_core ...............***Failed  970.31 sec
1>        Start  4: opencv_test_flann
1>   4/37 Test  #4: opencv_test_flann ................   Passed    0.16 sec
1>        Start  5: opencv_test_imgproc
1>   5/37 Test  #5: opencv_test_imgproc ..............***Exception: Other545.21 sec
1>        Start  6: opencv_perf_imgproc
1>   6/37 Test  #6: opencv_perf_imgproc ..............***Failed  4346.31 sec
1>        Start  7: opencv_sanity_imgproc
1>   7/37 Test  #7: opencv_sanity_imgproc ............***Failed  935.46 sec
1>        Start  8: opencv_test_ml
1>   8/37 Test  #8: opencv_test_ml ...................***Exception: Other 61.71 sec
1>        Start  9: opencv_test_photo
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): warning MSB5021: "cmd" and its child processes are being terminated in order to cancel the build.
1>A task was canceled.
1>A task was canceled.
Build has been canceled.
```

The test-reports\accuracy\opencv_test_core.xml file reports 921 failures.
[paste of opencv_test_core.xml](https://gist.github.com/cwilkens/c6542305ed403012004b)

My local changeset that I built from is [https://github.com/Itseez/opencv/commit/cb012010c61584705930b039212a2206ef282c33](https://github.com/Itseez/opencv/commit/cb012010c61584705930b039212a2206ef282c33)

I used cmake-gui to configure and generate the solution, and then built with VS 2015 Community edition.
ALL_BUILD project, Debug x64 and Release x64, then INSTALL project, Debug x64 and Release x64. I didn't have any issues compiling, though I think there were some warnings - I'd have to rebuild to see what they were.

**Comment by alalek** [comment]
Looks like used OpenCL runtime is broken.
Try to disable OpenCL support (`cmake -DWITH_OPENCL=OFF ...` and rebuild) or switch to another OpenCL device (environment variable: `OPENCV_OPENCL_DEVICE=:GPU:1`).

**Comment by cwilkens** [comment]
I disabled OpenCL (unchecking WITH_OPENCL in cmake) and rebuilt, then re-ran the tests.
```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug x64 ------
1>  Test project C:/opencv/mybuild
1>        Start  1: opencv_test_core
1>   1/37 Test  #1: opencv_test_core .................***Failed  499.57 sec
1>        Start  2: opencv_perf_core
1>   2/37 Test  #2: opencv_perf_core .................   Passed  1037.04 sec
1>        Start  3: opencv_sanity_core
1>   3/37 Test  #3: opencv_sanity_core ...............***Failed  282.32 sec
1>        Start  4: opencv_test_flann
1>   4/37 Test  #4: opencv_test_flann ................   Passed    0.01 sec
1>        Start  5: opencv_test_imgproc
1>   5/37 Test  #5: opencv_test_imgproc ..............***Failed  433.48 sec
1>        Start  6: opencv_perf_imgproc
1>   6/37 Test  #6: opencv_perf_imgproc ..............***Failed  2698.33 sec
1>        Start  7: opencv_sanity_imgproc
1>   7/37 Test  #7: opencv_sanity_imgproc ............***Failed  208.12 sec
1>        Start  8: opencv_test_ml
1>   8/37 Test  #8: opencv_test_ml ...................***Failed   20.77 sec
1>        Start  9: opencv_test_photo
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): warning MSB5021: "cmd" and its child processes are being terminated in order to cancel the build.
1>A task was canceled.
1>A task was canceled.
Build has been canceled.
```
This time opencv_test_core.xml only shows one failure:

```
    <testcase name="accuracy" status="run" time="0" classname="Core_globbing">
      <failure message="C:\opencv\modules\core\test\test_io.cpp:552&#x0A;Expected: (lenas.size()) &gt; (pngLenas.size()), actual: 0 vs 0" type=""><![CDATA[C:\opencv\modules\core\test\test_io.cpp:552
Expected: (lenas.size()) > (pngLenas.size()), actual: 0 vs 0]]></failure>
    </testcase>
```
I'm assuming I don't have some sort of test data set up properly, especially considering 90% of opencv_sanity_core failed with this output:

```
<testcase name="absdiffScalar/13" value_param="(1280x720, 16SC3)" status="run" time="0.235" classname="Size_MatType_absdiffScalar">
      <failure message="C:\opencv\modules\ts\src\ts_perf.cpp:615&#x0A;Failed&#x0A;  No regression data for c argument" type=""><![CDATA[C:\opencv\modules\ts\src\ts_perf.cpp:615
Failed
  No regression data for c argument]]></failure>
    </testcase>
```
If there's some information/documentation on how to set up the data for the tests and run them, I'll try them again.

Anyway, I tried the new OpenCL-less .lib files in my project, and had the same performance issues as before. I tried messing around with `cv::setNumThreads` (the docs say 0 is disable, but that 1 is disable for the Concurrency backend, so I tried a few different values).

So, I have my program printing the frames per second once a second. Standard output (with the debug prints from the libusb wrapper) with the color conversion to BGR looks like this:

```
payload error
payload error
payload error
FPS: 37.40
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 30.98
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 36.93
payload error
payload error
payload error
```

Standard output with the color conversion to grayscale:
```
FPS: 59.76
FPS: 60.28
FPS: 60.04
FPS: 60.04
FPS: 59.98
FPS: 60.04
FPS: 60.04
FPS: 59.98
FPS: 60.04
FPS: 59.98
```

Standard output with color conversion to BGR and `cv::setNumThreads(0)`: (same output with setting to 1)
```
FPS: 32.07
FPS: 32.04
FPS: 31.65
FPS: 32.04
FPS: 32.04
FPS: 31.97
FPS: 31.94
FPS: 31.97
FPS: 31.90
FPS: 31.62
```

Standard output with color conversion to BGR and `cv::setNumThreads(2)`:
```
FPS: 58.19
payload error
FPS: 59.00
payload error
payload error
FPS: 57.14
FPS: 57.83
FPS: 59.17
payload error
payload error
FPS: 58.07
payload error
FPS: 59.17
FPS: 58.42
FPS: 59.06
FPS: 59.06
payload error
payload error
FPS: 57.39
```

Standard output with `cv::setNumThreads(3)` is similar:

```
FPS: 58.53
payload error
FPS: 58.71
FPS: 59.82
payload error
payload error
FPS: 57.88
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 54.73
payload error
payload error
payload error
FPS: 57.03
payload error
FPS: 59.06
payload error
FPS: 59.00
payload error
payload error
payload error
FPS: 57.09
payload error
payload error
```

`cv::setNumThreads(4)` seems to start the breakdown in performance:
```
payload error
payload error
FPS: 54.21
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 39.33
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 49.21
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
FPS: 51.18
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
payload error
```

My processor is an Intel i7-5700HQ, which has 8 logical cores. Trying `cv::setNumThreads(8)` replicates the output of not setting the number of threads (excessive "payload error" and an FPS of approximately 30).


Could the threading backend be an issue? Is there a way to build OpenCV with a backend that's not Microsoft Concurrency?

**Comment by alalek** [comment]
Test data: http://answers.opencv.org/question/4542/can-not-find-data-files-for-test-programs/

**Comment by cwilkens** [comment]
Ok, with the build with OpenCL disabled, and test data set up, this is a full test run:

```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug x64 ------
1>  Test project C:/opencv/mybuild
1>        Start  1: opencv_test_core
1>   1/37 Test  #1: opencv_test_core .................   Passed  505.94 sec
1>        Start  2: opencv_perf_core
1>   2/37 Test  #2: opencv_perf_core .................   Passed  1142.80 sec
1>        Start  3: opencv_sanity_core
1>   3/37 Test  #3: opencv_sanity_core ...............   Passed  288.05 sec
1>        Start  4: opencv_test_flann
1>   4/37 Test  #4: opencv_test_flann ................   Passed    0.01 sec
1>        Start  5: opencv_test_imgproc
1>   5/37 Test  #5: opencv_test_imgproc ..............   Passed  453.80 sec
1>        Start  6: opencv_perf_imgproc
1>   6/37 Test  #6: opencv_perf_imgproc ..............   Passed  2782.25 sec
1>        Start  7: opencv_sanity_imgproc
1>   7/37 Test  #7: opencv_sanity_imgproc ............   Passed  232.86 sec
1>        Start  8: opencv_test_ml
1>   8/37 Test  #8: opencv_test_ml ...................   Passed  346.95 sec
1>        Start  9: opencv_test_photo
1>   9/37 Test  #9: opencv_test_photo ................   Passed  409.74 sec
1>        Start 10: opencv_perf_photo
1>  10/37 Test #10: opencv_perf_photo ................   Passed    8.94 sec
1>        Start 11: opencv_sanity_photo
1>  11/37 Test #11: opencv_sanity_photo ..............   Passed    1.07 sec
1>        Start 12: opencv_test_video
1>  12/37 Test #12: opencv_test_video ................   Passed   18.62 sec
1>        Start 13: opencv_perf_video
1>  13/37 Test #13: opencv_perf_video ................   Passed  362.94 sec
1>        Start 14: opencv_sanity_video
1>  14/37 Test #14: opencv_sanity_video ..............   Passed   26.18 sec
1>        Start 15: opencv_test_imgcodecs
1>  15/37 Test #15: opencv_test_imgcodecs ............   Passed   84.03 sec
1>        Start 16: opencv_perf_imgcodecs
1>  16/37 Test #16: opencv_perf_imgcodecs ............   Passed    0.19 sec
1>        Start 17: opencv_sanity_imgcodecs
1>  17/37 Test #17: opencv_sanity_imgcodecs ..........   Passed    0.06 sec
1>        Start 18: opencv_test_shape
1>  18/37 Test #18: opencv_test_shape ................   Passed  15190.23 sec
1>        Start 19: opencv_test_videoio
1>  19/37 Test #19: opencv_test_videoio ..............   Passed   51.26 sec
1>        Start 20: opencv_perf_videoio
1>  20/37 Test #20: opencv_perf_videoio ..............   Passed    0.66 sec
1>        Start 21: opencv_sanity_videoio
1>  21/37 Test #21: opencv_sanity_videoio ............   Passed    0.11 sec
1>        Start 22: opencv_test_highgui
1>  22/37 Test #22: opencv_test_highgui ..............   Passed    0.59 sec
1>        Start 23: opencv_test_objdetect
1>  23/37 Test #23: opencv_test_objdetect ............   Passed   35.33 sec
1>        Start 24: opencv_perf_objdetect
1>  24/37 Test #24: opencv_perf_objdetect ............   Passed    0.09 sec
1>        Start 25: opencv_sanity_objdetect
1>  25/37 Test #25: opencv_sanity_objdetect ..........   Passed    0.05 sec
1>        Start 26: opencv_test_superres
1>  26/37 Test #26: opencv_test_superres .............   Passed   14.15 sec
1>        Start 27: opencv_perf_superres
1>  27/37 Test #27: opencv_perf_superres .............   Passed   72.72 sec
1>        Start 28: opencv_sanity_superres
1>  28/37 Test #28: opencv_sanity_superres ...........   Passed   22.20 sec
1>        Start 29: opencv_test_features2d
1>  29/37 Test #29: opencv_test_features2d ...........***Failed  288.62 sec
1>        Start 30: opencv_perf_features2d
1>  30/37 Test #30: opencv_perf_features2d ...........***Failed   53.45 sec
1>        Start 31: opencv_sanity_features2d
1>  31/37 Test #31: opencv_sanity_features2d .........***Failed    5.83 sec
1>        Start 32: opencv_test_calib3d
1>  32/37 Test #32: opencv_test_calib3d ..............   Passed  672.49 sec
1>        Start 33: opencv_perf_calib3d
1>  33/37 Test #33: opencv_perf_calib3d ..............   Passed  708.98 sec
1>        Start 34: opencv_sanity_calib3d
1>  34/37 Test #34: opencv_sanity_calib3d ............   Passed   69.05 sec
1>        Start 35: opencv_test_stitching
1>  35/37 Test #35: opencv_test_stitching ............   Passed    0.11 sec
1>        Start 36: opencv_perf_stitching
1>  36/37 Test #36: opencv_perf_stitching ............   Passed  1277.93 sec
1>        Start 37: opencv_sanity_stitching
1>  37/37 Test #37: opencv_sanity_stitching ..........   Passed  120.89 sec
1>
1>  92% tests passed, 3 tests failed out of 37
1>
1>  Label Time Summary:
1>  Accuracy             = 18071.89 sec (15 tests)
1>  Main                 = 25249.19 sec (37 tests)
1>  Performance          = 6410.95 sec (11 tests)
1>  Sanity               = 766.35 sec (11 tests)
1>  opencv_calib3d       = 1450.52 sec (3 tests)
1>  opencv_core          = 1936.79 sec (3 tests)
1>  opencv_features2d    = 347.90 sec (3 tests)
1>  opencv_flann         =   0.01 sec (1 test)
1>  opencv_highgui       =   0.59 sec (1 test)
1>  opencv_imgcodecs     =  84.28 sec (3 tests)
1>  opencv_imgproc       = 3468.91 sec (3 tests)
1>  opencv_ml            = 346.95 sec (1 test)
1>  opencv_objdetect     =  35.47 sec (3 tests)
1>  opencv_photo         = 419.76 sec (3 tests)
1>  opencv_shape         = 15190.23 sec (1 test)
1>  opencv_stitching     = 1398.93 sec (3 tests)
1>  opencv_superres      = 109.08 sec (3 tests)
1>  opencv_video         = 407.75 sec (3 tests)
1>  opencv_videoio       =  52.03 sec (3 tests)
1>
1>  Total Test time (real) = 25249.30 sec
1>
1>  The following tests FAILED:
1>  	 29 - opencv_test_features2d (Failed)
1>  	 30 - opencv_perf_features2d (Failed)
1>  	 31 - opencv_sanity_features2d (Failed)
1>  Errors while running CTest
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files (x86)\CMake\bin\ctest.exe" --force-new-ctest-process -C Debug
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 8.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

So even with the features2d failures, it doesn't look like any tests catch this issue (since my code doesn't use features2d), if it's a bug strictly related to OpenCV. Or it could be something weird between the libraries I'm using/how I built them/how I built my project. 

Is there a way for me to build OpenCV with a different threading backend? How else can I debug this issue?

**Comment by alalek** [comment]
Try to grab frames from video file instead of camera.

About performance tests I mean to measure performance via OpenCV performance measuring framework (possible with adding of new test for your image size).
Something like this (but without `--check` parameter and with `--gtest_filter=*cvtColor*` parameter to skip useless tests):
http://pullrequest.opencv.org/buildbot/builders/master-mac/builds/613/steps/perf_imgproc/logs/stdio
```
[ RUN      ] Size_CvtMode_cvtColor8u.cvtColor8u/356
[ PERFSTAT ]    (samples = 1, mean = 4.92, median = 4.92, stddev = 0.00 (0.0%))
[ VALUE    ] 	(1920x1080, COLOR_YUV2BGR)
[       OK ] Size_CvtMode_cvtColor8u.cvtColor8u/356 (42 ms)
[ RUN      ] Size_CvtMode_cvtColor8u.cvtColor8u/357
[ PERFSTAT ]    (samples = 1, mean = 4.94, median = 4.94, stddev = 0.00 (0.0%))
[ VALUE    ] 	(1920x1080, COLOR_YUV2RGB)
[       OK ] Size_CvtMode_cvtColor8u.cvtColor8u/357 (43 ms)
[ RUN      ] Size_CvtMode_cvtColor8u.cvtColor8u/358
[ PERFSTAT ]    (samples = 1, mean = 5.89, median = 5.89, stddev = 0.00 (0.0%))
[ VALUE    ] 	(1920x1080, CX_YUV2BGRA)
[       OK ] Size_CvtMode_cvtColor8u.cvtColor8u/358 (50 ms)
[ RUN      ] Size_CvtMode_cvtColor8u.cvtColor8u/359
[ PERFSTAT ]    (samples = 1, mean = 6.31, median = 6.31, stddev = 0.00 (0.0%))
[ VALUE    ] 	(1920x1080, CX_YUV2RGBA)
[       OK ] Size_CvtMode_cvtColor8u.cvtColor8u/359 (50 ms)
```

**Comment by cwilkens** [comment]
Ran the performance tests. [Paste of xml file.](https://gist.github.com/cwilkens/3cdd465e2a9ff9f784db)

The relevant test output in the console:
```
[ RUN      ] Size_CvtMode2_cvtColorYUV420.cvtColorYUV420/22
[ PERFSTAT ]    (samples = 100, mean = 0.97, median = 0.97, stddev = 0.06 (5.9%))
[ VALUE    ]    (640x480, COLOR_YUV2BGR_YUY2)
[       OK ] Size_CvtMode2_cvtColorYUV420.cvtColorYUV420/22 (798 ms)
```
The camera is 640x480 at 60 fps and I'm using that exact color constant in my code. I'm assuming it's 798 ms total, for all 100 samples, in which case there should be no problem with the performance of the conversion itself.

I'm working on trying to grab frames from a video file. I can't open a raw file of YUV data using openCV, so I'm trying to convert from RGB to YUV and then back, but I'm hitting errors so I'm still working on it.

**Comment by cwilkens** [comment]
Okay, I got it pulling from a video file, this was my loop:

```
	while(myfile.read(frame_3ch))
	{
		clock_t now_ticks = clock();
		ctx.last_frames++;
		if (now_ticks - ctx.last_ticks > 1000)
		{
			printf("FPS: %.2f\n", 1000 * ctx.last_frames / (float)(now_ticks - ctx.last_ticks));
			ctx.last_ticks = now_ticks;
			ctx.last_frames = 0;
		}

		std::vector<cv::Mat> channels(3);
		cv::split(frame_3ch, channels);
		channels.pop_back();
		cv::merge(channels, frame_2ch);

		cv::cvtColor(frame_2ch, frame, CV_YUV2BGR_YUY2);

		imshow("image", frame);

		if (cv::waitKey(1) >= 0)
			break;
	}
```

With `cv::setNumThreads(0)`, the above would report 16 fps. I then tried running a Release build, and it reported 64 fps. 
I switched back to my code for the webcam: 
`cv::setNumThreads(8)`, Release build: 
```
FPS: 60.04
FPS: 59.98
payload error
FPS: 59.06
FPS: 60.04
FPS: 60.04
FPS: 59.98
FPS: 60.04
```
`cv::setNumThreads(8)`, Debug build still reports 30 fps with a massive amount of `payload error`.

So I figured out how to use my profiler.
8 threads, Debug build, 30 fps:
![debug_8threads_30fps_payloaderrors](https://cloud.githubusercontent.com/assets/1930495/13801103/c9e7161e-eafc-11e5-9cc2-cb4aeff9f532.PNG)

8 threads, Release build, 60 fps:
![release_8threads_60fps](https://cloud.githubusercontent.com/assets/1930495/13801110/d8217c74-eafc-11e5-8941-0aeaa1bf34f8.PNG)

`cv::setNumThreads(0)`, Debug build, 16 fps (but no `payload error`):
![debug_0numthreads_16fps](https://cloud.githubusercontent.com/assets/1930495/13801123/f72345b2-eafc-11e5-869c-777c7853d902.PNG)

`cv::setNumThreads(0)`, Release build, 60 fps:
![release_0numthreads_60fps](https://cloud.githubusercontent.com/assets/1930495/13801140/16704ec4-eafd-11e5-93fd-324b2ee569a6.PNG)

So the obvious difference is that in a Debug build, the majority of time is spent in cvtYUV422toRGB(), but only because it calls into std::max which has it's time eaten up by std::_Debug_lt()

So std::_Debug_lt() is slow, but I'm not sure why. I doubt this is openCV's issue but if there's a workaround/way to fix it, that would be nice.

**Comment by alalek** [comment]
> std::_Debug_lt() is slow, but I'm not sure why

Because it is Debug build (with disabled compiler optimizations and enabled additional checks).

There is still nothing to change in OpenCV. `std::max` [usage](https://github.com/Itseez/opencv/blob/3.1.0/modules/imgproc/src/color.cpp#L6542-L6547) is valid.

BTW, Code for `_Debug_lt` implementation (found via google):
```
    template<class _Ty1, class _Ty2> inline
    bool _Debug_lt(const _Ty1& _Left, const _Ty2& _Right,
        _Dbfile_t _File, _Dbline_t _Line)
    {   // test if _Left < _Right and operator< is strict weak ordering
        if (!(_Left < _Right))
            return (false);
        else if (_Right < _Left)
            _DEBUG_ERROR2("invalid operator<", _File, _Line);
        return (true);
    }

...

    template<class _Ty> inline
    const _Ty& (max)(const _Ty& _Left, const _Ty& _Right)
    {   // return larger of _Left and _Right
        return (_DEBUG_LT(_Left, _Right) ? _Right : _Left);
    }
```
