### ISSUE TITLE
Rebuild library for android 

### ISSUE THREAD

**Issue by nnthero001** [Itseez/opencv#6202]
I using opencv in my application, 
I using OpenCVLoader (not OpeCvmanager) with methods: 
Utils.bitmapToMat,
Utils.matToBitmap
Imgproc.adaptiveThreshold
Imgproc.cvtColor, 
Imgproc.GaussianBlur

My apk size large than 30M, 
I want to rebuild the library only with the method above.
I how to start.  Please help me. Thank.

**Comment by alalek** [comment]
http://answers.opencv.org
