### ISSUE TITLE
tutorial_code\features2D\AKAZE_tracking : missing header

### ISSUE THREAD

**Issue by philippefoubert** [Itseez/opencv#6209]
**The `<opencv2/tracking.hpp>` header** included in opencv\samples\cpp\tutorial_code\features2D\AKAZE_tracking\planar_tracking.cpp **is missing**.

I am working with the code from head OpenCV 3.1.0-dev (Version control: 3.1.0-639-gfdd20d7-dirty).

Regards,
    Philippe.

**Comment by alalek** [comment]
Right, this header is from opencv_contrib

**Comment by renu285** [comment]
Can I contribute to this by adding the appropriate header file
