### ISSUE TITLE
Testing opencv_test_objdetect fails

### ISSUE THREAD

**Issue by gunshi** [Itseez/opencv#6211]
- OpenCV version: 3.1
- Host OS: Mac OS X 10.11.2

Upon running opencv_test_objdetect from the bin folder I get: 

```
CTEST_FULL_OUTPUT
OpenCV version: 3.1.0-dev
OpenCV VCS version: 3.1.0-223-g9ebbfc7
Build type: release
Parallel framework: gcd
CPU features: mmx sse sse2 sse3
OpenCL is disabled
[==========] Running 9 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Objdetect_HOGDetectorReadWrite
[ RUN      ] Objdetect_HOGDetectorReadWrite.regression
/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/test/test_cascadeandhog.cpp:527: Failure
Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] Objdetect_HOGDetectorReadWrite.regression (12 ms)
[----------] 1 test from Objdetect_HOGDetectorReadWrite (12 ms total)

[----------] 2 tests from Objdetect_CascadeDetector
[ RUN      ] Objdetect_CascadeDetector.regression
/Users/gunshigupta/Desktop/incept/opencv/modules/ts/src/ts.cpp:518: Failure
Failed

	failure reason: Invalid test data
	test case #-1
	seed: ffffffffffffffff
-----------------------------------
	LOG:
validation file is not determined or not correct
-----------------------------------

[  FAILED  ] Objdetect_CascadeDetector.regression (16 ms)
[ RUN      ] Objdetect_CascadeDetector.small_img
0. cascadeandhog/cascades/haarcascade_frontalface_alt.xml
unknown file: Failure
C++ exception with description "/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/src/cascadedetect.cpp:1639: error: (-215) !empty() in function detectMultiScale
" thrown in the test body.
[  FAILED  ] Objdetect_CascadeDetector.small_img (55 ms)
[----------] 2 tests from Objdetect_CascadeDetector (71 ms total)

[----------] 1 test from Objdetect_HOGDetector
[ RUN      ] Objdetect_HOGDetector.regression
/Users/gunshigupta/Desktop/incept/opencv/modules/ts/src/ts.cpp:518: Failure
Failed

	failure reason: Invalid test data
	test case #-1
	seed: ffffffffffffffff
-----------------------------------
	LOG:
validation file is not determined or not correct
-----------------------------------

[  FAILED  ] Objdetect_HOGDetector.regression (0 ms)
[----------] 1 test from Objdetect_HOGDetector (0 ms total)

[----------] 1 test from Objdetect_HOGDetector_Strict
[ RUN      ] Objdetect_HOGDetector_Strict.accuracy
[       OK ] Objdetect_HOGDetector_Strict.accuracy (1803 ms)
[----------] 1 test from Objdetect_HOGDetector_Strict (1803 ms total)

[----------] 4 tests from OCL_ObjDetect/HOG
[ RUN      ] OCL_ObjDetect/HOG.GetDescriptors/0
/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/test/opencl/test_hogdetector.cpp:73: Failure
Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] OCL_ObjDetect/HOG.GetDescriptors/0, where GetParam() = (64x128, 8UC1) (1 ms)
[ RUN      ] OCL_ObjDetect/HOG.GetDescriptors/1
/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/test/opencl/test_hogdetector.cpp:73: Failure
Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] OCL_ObjDetect/HOG.GetDescriptors/1, where GetParam() = (48x96, 8UC1) (0 ms)
[ RUN      ] OCL_ObjDetect/HOG.Detect/0
/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/test/opencl/test_hogdetector.cpp:73: Failure
Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] OCL_ObjDetect/HOG.Detect/0, where GetParam() = (64x128, 8UC1) (0 ms)
[ RUN      ] OCL_ObjDetect/HOG.Detect/1
/Users/gunshigupta/Desktop/incept/opencv/modules/objdetect/test/opencl/test_hogdetector.cpp:73: Failure
Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] OCL_ObjDetect/HOG.Detect/1, where GetParam() = (48x96, 8UC1) (0 ms)
[----------] 4 tests from OCL_ObjDetect/HOG (1 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 5 test cases ran. (1887 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] Objdetect_HOGDetectorReadWrite.regression
[  FAILED  ] Objdetect_CascadeDetector.regression
[  FAILED  ] Objdetect_CascadeDetector.small_img
[  FAILED  ] Objdetect_HOGDetector.regression
[  FAILED  ] OCL_ObjDetect/HOG.GetDescriptors/0, where GetParam() = (64x128, 8UC1)
[  FAILED  ] OCL_ObjDetect/HOG.GetDescriptors/1, where GetParam() = (48x96, 8UC1)
[  FAILED  ] OCL_ObjDetect/HOG.Detect/0, where GetParam() = (64x128, 8UC1)
[  FAILED  ] OCL_ObjDetect/HOG.Detect/1, where GetParam() = (48x96, 8UC1)

 8 FAILED TESTS
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Additionally I notice that there is no cascadeandhog folder in the build directory, however it is referenced as such:

>     String root = cvtest::TS::ptr()->get_data_path() + "cascadeandhog/cascades/";

in  test_cascadeandhog.cpp's TEST function.

Result of getbuildinformation():

> General configuration for OpenCV 3.1.0-dev =====================================
>   Version control:               3.1.0-224-g9cbfc44
> 
>   Platform:
>     Timestamp:                   2016-03-04T18:32:42Z
>     Host:                        Darwin 15.2.0 x86_64
>     CMake:                       3.4.1
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               Release
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 7.0.2.7000181)
>     C++ flags (Release):         -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
>     C++ flags (Debug):           -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
>     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
>     C flags (Release):           -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
>     C flags (Debug):             -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
>     Linker flags (Release):
>     Linker flags (Debug):
>     Precompiled headers:         NO
>     Extra dependencies:          -framework OpenCL /usr/local/lib/libwebp.dylib avcodec avformat avutil swscale avresample /usr/lib/libbz2.dylib -framework VideoDecodeAcceleration bz2 -framework QTKit -framework QuartzCore -framework AppKit vtkRenderingOpenGL vtkImagingHybrid vtkIOImage vtkCommonDataModel vtkCommonMath vtkCommonCore vtksys vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkDICOMParser vtkIOCore /usr/lib/libz.dylib vtkmetaio /usr/local/lib/libjpeg.dylib /usr/local/lib/libpng.dylib /usr/local/lib/libtiff.dylib vtkImagingCore vtkRenderingCore vtkCommonColor vtkFiltersExtraction vtkFiltersCore vtkFiltersGeneral vtkCommonComputationalGeometry vtkFiltersStatistics vtkImagingFourier vtkalglib vtkFiltersGeometry vtkFiltersSources vtkInteractionStyle vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOGeometry vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkftgl vtkIOExport vtkRenderingAnnotation vtkImagingColor vtkRenderingContext2D vtkRenderingGL2PS vtkRenderingContextOpenGL vtkgl2ps vtkRenderingLabel -framework Cocoa
>     3rdparty dependencies:       libjpeg libpng libtiff libjasper IlmImf lib
> 
>   OpenCV modules:
>     To be built:                 core flann imgproc ml photo video viz imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab
>     Disabled:                    world
>     Disabled by dependency:      -
>     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3
> 
>   GUI: 
>     QT:                          NO
>     Cocoa:                       YES
>     OpenGL support:              NO
>     VTK support:                 YES (ver 6.3.0)
> 
>   Media I/O: 
>     ZLib:                        build (ver 1.2.8)
>     JPEG:                        build (ver 90)
>     WEBP:                        /usr/local/lib/libwebp.dylib (ver encoder: 0x0202)
>     PNG:                         build (ver 1.6.19)
>     TIFF:                        build (ver 42 - 4.0.2)
>     JPEG 2000:                   build (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
>     GDAL:                        NO
> 
>   Video I/O:
>     DC1394 1.x:                  NO
>     DC1394 2.x:                  NO
>     FFMPEG:                      YES
>       codec:                     YES (ver 56.60.100)
>       format:                    YES (ver 56.40.101)
>       util:                      YES (ver 54.31.100)
>       swscale:                   YES (ver 3.1.101)
>       resample:                  YES (ver 2.1.0)
>       gentoo-style:              YES
>     GStreamer:                   NO
>     OpenNI:                      NO
>     OpenNI PrimeSensor Modules:  NO
>     OpenNI2:                     NO
>     PvAPI:                       NO
>     GigEVisionSDK:               NO
>     QuickTime:                   NO
>     QTKit:                       YES
>     V4L/V4L2:                    NO/NO
>     XIMEA:                       NO
>     gPhoto2:                     NO
> 
>   Parallel framework:            GCD
> 
>   Other third-party libraries:
>     Use IPP:                     9.0.1 [9.0.1]
>          at:                     /Users/gunshigupta/Desktop/opencv/3rdparty/ippicv/unpack/ippicv_osx
>     Use IPP Async:               NO
>     Use VA:                      NO
>     Use Intel VA-API/OpenCL:     NO
>     Use Eigen:                   YES (ver 3.2.6)
>     Use Cuda:                    NO
>     Use OpenCL:                  YES
>     Use custom HAL:              NO
> 
>   OpenCL:                        <Link with OpenCL library>
>     Link libraries:              -framework OpenCL
>     Use AMDFFT:                  NO
>     Use AMDBLAS:                 NO
> 
>   Python 2:
>     Interpreter:                 /usr/local/bin/python2.7 (ver 2.7.11)
> 
>   Python 3:
>     Interpreter:                 /usr/local/bin/python3 (ver 3.5.1)
> 
>   Python (for build):            /usr/local/bin/python2.7
> 
>   Java:
>     ant:                         NO
>     JNI:                         /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Matlab:                        Matlab not found or implicitly disabled
> 
>   Documentation:
>     Doxygen:                     NO
>     PlantUML:                    NO
> 
>   Tests and samples:
>     Tests:                       YES
>     Performance tests:           YES
>     C/C++ Examples:              NO
> 
>   Install path:                  /usr/local
> 
>   cvconfig.h is in:              /Users/gunshigupta/Desktop/cvbuild

**Comment by alalek** [comment]
I believe you need `opencv_extra` repo and `OPENCV_TEST_DATA_PATH` environment variable
