### ISSUE TITLE
Loop body not executed

### ISSUE THREAD

**Issue by sturkmen72** [Itseez/opencv#6212]
Code Analysis feature of Visual Studio says : "Loop body not executed" for some part of the code from [matx.hpp](https://github.com/Itseez/opencv/blob/3.1.0/modules/core/include/opencv2/core/matx.hpp#L505)
for example:
```
template<typename _Tp, int m, int n> inline
Matx<_Tp, m, n>::Matx(_Tp v0, _Tp v1)
{
    CV_StaticAssert(channels >= 2, "Matx should have at least 2 elements.");
    val[0] = v0; val[1] = v1;
    for(int i = 2; i < channels; i++) val[i] = _Tp(0);
}
```
please review

**Comment by alalek** [comment]
Is it says 2 times (or more, but "channels" value is 1,2)?
I believe It is just template specialization processing for some "unexpected" values (like many warning, like "dead code" or condition "is constant"). So there is nothing to fix really (fix will be ugly copy-paste, but wait ... this larger code block is already a bunch of copy-paste stuff).

Is there available some kind of "suppression" file for this tool?


BTW, I see here problem with naming consistence: there is very strange `channels` name for number of total elements (`Matx33f` with channels=9):
```
    enum { depth    = DataType<_Tp>::depth,
           rows     = m,
           cols     = n,
           channels = rows*cols,
           type     = CV_MAKETYPE(depth, channels),
           shortdim = (m < n ? m : n)
         };
```
But it is too legacy and there no way to fix it now.

**Comment by sturkmen72** [comment]
Thanks for the explanation.
