### ISSUE TITLE
Unable to run and install OpenCV on Xcode 7

### ISSUE THREAD

**Issue by dddppp** [Itseez/opencv#6216]
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

- OpenCV version: 3.x
- Host OS:  Mac OS X 10.11.3 
- Target OS: iOS 9.2

### In which part of the OpenCV library you got the issue?
Examples:
I am unable to run the examples using Xcode 6.4 or Xcode 7.. 

Any idea on how I can get them to work?

These are the sort of messages I get:

![screen shot 2016-03-07 at 11 48 36](https://cloud.githubusercontent.com/assets/653958/13568668/b202d2fc-e45a-11e5-908c-37d1c3ae63d8.png)

**Comment by alalek** [comment]
Only actual bugs or feature requests should be filled here. For questions use Q/A forum: http://answers.opencv.org

Anyway, it is just wrong migration of your app from OpenCV 2.4. In OpenCV 3.x `ios.h` is moved from `highgui` module to `imgcodecs`.
