### ISSUE TITLE
Handle Bad Images

### ISSUE THREAD

**Issue by shivz69** [Itseez/opencv#6223]
- OpenCV version: 3.0
- Host OS: Windows 7
- Visual Studio 2012 Express

### In which part of the OpenCV library you got the issue?
Examples:
- imgcodecs

### Expected behaviour
- Program was supposed to handle corrupt images without crashing.

### Actual behaviour
- Program crashes giving the following error:
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in cv::imdecode_, file C:\builds\master_PackSlave-win32-vc12-shared\opencv\modules\imgcodecs\src\loadsave.cpp, line 470

### Additional description
- Using libcurl to get images from a website and use opencv to do image processing on the images.

### Code example to reproduce the issue / Steps to reproduce the issue
NB. Please use libcurl library otherwise this will not compile.
```
#include <stdio.h>
#include <curl/curl.h>
#include <string> 
#include <iostream>
#include <vector> 
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

//curl writefunction to be passed as a parameter
size_t write_data(char *ptr, size_t size, size_t nmemb, void *userdata) {
    ostringstream *stream = (ostringstream*)userdata;
    size_t count = size * nmemb;
    stream->write(ptr, count);
    return count;
}

//function to retrieve the image as Cv::Mat data type
cv::Mat curlImg()
{
	CURL *curl;
	CURLcode res;
	ostringstream stream;
	curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_URL, "http://www.cars.co.za/images/pictures/general/graphic_sellyourcar.png"); //the img url
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_data); // pass the writefunction
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, &stream); // pass the stream ptr when the writefunction is called
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 1); // timeout if curl_easy hangs, use min time for best performance
	res = curl_easy_perform(curl); // start curl
	string output = stream.str(); // convert the stream into a string
	curl_easy_cleanup(curl); // cleanup
	vector<char> data = vector<char>( output.begin(), output.end() ); //convert string into a vector
	Mat data_mat = Mat(data); // create the cv::Mat datatype from the vector
	Mat image = imdecode(data_mat,1); //read an image from memory buffer
	return image;
}
int main(void)
{
	namedWindow( "Image output", CV_WINDOW_AUTOSIZE );
	while (1)
	{
		Mat image = curlImg();
		imshow("Image output",image); //display image
		cvWaitKey(1);
		//cv::destroyWindow("Image output");
	}
}

**Comment by alalek** [comment]
> OpenCV Error: Assertion failed

It is just C++ exception (it is not termination assertion). You should handle it via `try-catch` yourself.

Related more general problem is out of main scope of OpenCV.
OpenCV usually uses 3rdparty libraries to read images which may contain some bugs and crash (for example, #5849).
Also if you have some reliable imaging library you can use it to load image data and fill `cv::Mat` values directly.

**Comment by berak** [comment]
this is not an opencv library issue, you curl code is (seriously) broken.

please close this issue, ask again on answers.opencv.org (where this should have gone in the 1st place), and you'll get an answer.
