### ISSUE TITLE
opencv2/core/core.hpp: No such file or directory

### ISSUE THREAD

**Issue by younas-bangash** [Itseez/opencv#6233]
I am trying to build tutorial2Example but when i try to run the code i face opencv2/core/core.hpp: No such file or directory error

**Comment by alalek** [comment]
http://docs.opencv.org/master/df/d65/tutorial_table_of_content_introduction.html

**Comment by younas-bangash** [comment]
Thanks for link it solve my problem little bit i am try to build  Tutorial2Activity in Android Studio but when i try to run the project i got the following error
`java.lang.UnsatisfiedLinkError: Couldn't load mixed_sample: findLibrary returned null`

**Comment by alalek** [comment]
Android Studio is not supported "from the box" yet: #5003

**Comment by younas-bangash** [comment]
I successfully integrate the tutorial2example with android studio 
Now i have create new c file and add module name in the android.mk file but .so file is not generate for this file due to which library is not loading can u please help me regarding that
