### ISSUE TITLE
Failed ASSERTION createBackgroundSubtractorMOG2().apply() for pictures

### ISSUE THREAD

**Issue by bw4sz** [Itseez/opencv#6250]
Migrated from [separate issue](https://github.com/Itseez/opencv/issues/4871#issuecomment-195961172) as requested by @alalek 

### Please state the information for your system
- OpenCV version: 3.1.0 dev
- Host OS: Windows 10
- Compiler & CMake: GCC 5.3 & CMake 3.5

### In which part of the OpenCV library you got the issue?
Examples:
- background subtraction (bgsegm)

### Expected behavior
Apply each frame to the background
### Actual behavior
Throws failed memory assertion if frame size is large

### Additional description

Here is a simple example of trying to create a background model from pictures, not video. This only occurs when using pictures from file, not when using cv2.videocapture from a video file to read frames. It fails on the very first position in the loop. Once they are numpy arrays, what does it matter? 

Looking at memory, it does rise, but certainly does not spike dramatically. 

I've tried smaller photos (shape~ (1920,2560,3) and i get the error after 3 photos. 

### Code example to reproduce the issue / Steps to reproduce the issue

    import cv2 
    import glob
    import os
    import cv2.bgsegm
    
    
    #File formats
    ext="C:/Users/Ben/Desktop/pics2/*.jpg"
    
    #Create mog
    b=cv2.createBackgroundSubtractorMOG2()
    
    #Find photos
    jpgs=[]
    jpgs.extend(glob.glob(ext))
    
    #Read in photos and add to background
    for x in jpgs:
        current_image=cv2.imread(x)
        print("Photo size is %s" % str(current_image.shape))
        b.apply(current_image)        
    
Returns:
    
    Photo size is (2992, 5152, 3)
    OpenCV Error: Insufficient memory (Failed to allocate 1541478400 bytes) in OutOfMemoryError, file C:\opencv\source\opencv\modules\core\src\alloc.cpp, line 52
    OpenCV Error: Assertion failed (u != 0) in create, file C:\opencv\source\opencv\modules\core\src\matrix.cpp, line 432

**Comment by bw4sz** [comment]
I am currently responding to comment

"Please add cv2.setBreakOnError(True) in after import cv2. Application should crash on assertion, then attach debugger (do you have MS Visual Studio or WinGDB?) and get "call stack" from there." 

Although it does not appear that cv2.setBreakOnError is exposed to python.
```

import cv2
cv2.setBreakonError()
Traceback (most recent call last):
  Python Shell, prompt 4, line 1
AttributeError: 'module' object has no attribute 'setBreakonError'
```

Regardless, i am currently attempting to capture c++ exception using my installation of codeblocks.

**Comment by alalek** [comment]
Right, `setBreakonError` is not exported via bindings.

**Comment by sturkmen72** [comment]
@alalek i tried to find out the problem. with Visual Studio x64 i could not reproduce the error.
tested on CodeBlocks x86 and reproduced the same error.
this line try to create a Mat with rows=1, cols=716.636.160 and fail.
`bgmodel.create( 1, frameSize.height*frameSize.width*nmixtures*(2 + 2*nchannels), CV_32F );`
https://github.com/Itseez/opencv_contrib/blob/master/modules/bgsegm/src/bgfg_gaussmix.cpp#L121

with Visual Studio x64 i can run the code below but with CodeBlocks x86 i can't.
`Mat m(20000, 100000, CV_32F);`

**Comment by sturkmen72** [comment]
https://github.com/Itseez/opencv/issues/6595

**Comment by mshabunin** [comment]
@bw4sz , since you've stated `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]` in previous issue, we will consider it as a 32-bit platform limitation (as @sturkmen72 wrote). Please, add more details if you are not agree.
