### ISSUE TITLE
errors on build opencv with cvv module and qt5

### ISSUE THREAD

**Issue by Bleach666** [Itseez/opencv#6263]
- OpenCV version:  3.x (current master branch 14.03.2016 ~15.00 GTM

- Win 7 x64, VS 2013, cmake 3.4.3
- Win XP x32, VS 2010, cmake 3.4.3

When checked both of parameters WITH_QT and BUILD_OPENCV_CVV:
- in Winodws 7 I receive 328 errors
- in Windows XP - 6261 errors.
If this parameters chosen separate in the same configuration - build successful.

Archive of 2 log files obtained from msbuild
`msbuild OpenCV.sln /flp:logfile=msvc2010_cvv.log /clp:parameters=ErrorsOnly /t:rebuild`
in attachment.
[err_log.zip](https://github.com/Itseez/opencv/files/172572/err_log.zip)

**Comment by alalek** [comment]
`cvv` is contrib module: https://github.com/Itseez/opencv_contrib/issues/

**Comment by Bleach666** [comment]
I know.. So do not write here bugs from contrib modules?
