### ISSUE TITLE
cv::FileStorage de-serialization of std::vector<cv::KeyPoint> fails

### ISSUE THREAD

**Issue by rwiesen** [Itseez/opencv#6288]
### OpenCV version and host system
- OpenCV version: git b3ac274617beb8e54c8bfebcb141090a57165ea2, but unchanged in HEAD
- Host OS: Windows 7

### In which part of the OpenCV library you got the issue?
- core/types.hpp

### Expected behaviour
- Take a cv:KeyPoint kp with kp.octave = 1 and kp.class_id = -1
- serialize this keypoint as part of a std::vector to a cv::FileStorage
- the entry in the file correctly shows "..., 1, -1, ..."
- deserialize the keypoint
- kp.octave is 1
- kp.class_id is -1

### Actual behaviour
after deserialization:
- kp.octave is 1073741824 (a 1.0f reinterpreted as int)
- kp.class_id is -1082130432 (a -1.0f reinterpreted as int)

### Additional description
cv::Keypoint instances with octave or class_id != 0 are not deserialized correctly.

The cv::KeyPoint class declares octave and class_id as int (in addition to the five float members), but DataType<KeyPoint> declares a vector of seven floats. When read in, the integer values are converted to float in cvReadRawDataSlice(), but interpreted as int in the datastructure.

### Code example to reproduce the issue / Steps to reproduce the issue
```.cpp
// File was written with:
// cv::FileStorage fs( featuresFile, cv::FileStorage::WRITE );
// cv::write( fs, "keypoints", keypoints );
// fs.release();

cv::FileStorage fs;
std::vector<cv::KeyPoint> keypoints;

fs.open( featuresFile, cv::FileStorage::READ );
fs["keypoints"] >> keypoints;
```

**Comment by ohnozzy** [comment]
I'm trying to fix this bug.
After investigation, there is a dedicated function to read vector<KeyPoint> in persistence.hpp
`CV_EXPORTS void read(const FileNode& node, std::vector<KeyPoint>& keypoints);`
However, the '>>' operator does not call the function. DMatch may have similar issue.
I am going to overload the '>>' operator so that it calls the dedicated function in persistence.hpp.

**Comment by ohnozzy** [comment]
I have send a pull request (#6375) for the fix.
