### ISSUE TITLE
Python bindings for solvePnPRansac 

### ISSUE THREAD

**Issue by venabled** [Itseez/opencv#6304]
It appears that the generated python bindings for solvePnPRansac in OpenCV3 have some type of bug that throws an assertion. Using a set of generated 2D/3D correspondences, solvePnP() works fine, but throws an assertion error when using the RANSAC implementation with default parameters. 

### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Mac OS X 10.11.3
- Menpo built python bindings from anaconda.com 

### In which part of the OpenCV library you got the issue?
- calib3d

### Expected behaviour
Calling: 
```                    
cv2.solvePnPRansac(
   world_pts_ned[idx, :].astype(np.float32),
   keypoints[idx, :].astype(np.float32),
   self.K,
   self.distortion)
```

should return: `retval, rvec, tvec, inliers` 

### Actual behaviour
Throws:
 ```
/Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-3.1.0/modules/core/src/matrix.cpp:2355: error: (-215) d == 2 && (sizes[0] == 1 || sizes[1] == 1 || sizes[0]*sizes[1] == 0) in function create
```
### Additional description

Shown also in: 

- http://stackoverflow.com/questions/33696082/error-using-solvepnpransac-function
- http://stackoverflow.com/questions/34309865/opencv-solvepnpransac-error?rq=1

**Comment by venabled** [comment]
As mentioned in the first link, and in the description: calling solvePnP() with: 

```
cv2.solvePnP(
   world_pts_ned[idx, :].astype(np.float32),
   keypoints[idx, :].astype(np.float32),
   self.K,
   self.distortion)
```

works fine. These points were all generated in one of my test cases, and all the points are inliers.

**Comment by venabled** [comment]
Additionally, the return signature has changed, and this is out of sync with the tutorials and existing python docs.

**Comment by venabled** [comment]
Also should mention that I'm using python 2.7.11

**Comment by zhufan** [comment]
look at this: http://stackoverflow.com/questions/30271556/opencv-error-through-calibration-tutorial-solvepnpransac
the last answer. the first argument of solvePnPRansac is a Nx1x3 matrix, and the second argument is a Nx1x2 matrix, but for solvePnP, the first argument  is a Nx3 matrix, and the second argument is a Nx2 matrix

**Comment by venabled** [comment]
@zhufan , adding the extra dimension mentioned in the so answer / your summary was the correct solution here. Would suggest changing the documentation re: the python bindings to reflect this, as this behavior is different than the 2.4.x bindings.

**Comment by yuancaimaiyi** [comment]
opencv3.3.0 sovlePnPRansac works fine
![Uploading out1-usetrue.jpg…]()
