### ISSUE TITLE
VP8 / V9 support

### ISSUE THREAD

**Issue by peters** [Itseez/opencv#6308]
I tried enabling VP8 / VP9 in the latest ffmpeg build (Windows) by adding the following entries:

```
{ 
AV_CODEC_ID_VP8, MKTAG('V', 'P', '8', '0') ,
AV_CODEC_ID_VP9, MKTAG('V', 'P', '9', '0') ,
}
```

Decoding/encoding videos works just fine. Viewing codec information in i.e VLC shows that the correct codec is being used.

Is it really this easy? If not please enlighten me so that I can submit a PR.

/cc @alalek

**Comment by alalek** [comment]
What is OpenCV version (2.4 or master)?

**Comment by peters** [comment]
master :)

**Comment by alalek** [comment]
It is very strange.

Some hacks were added for proper processing of fourcc tags [here](https://github.com/Itseez/opencv/blob/3.1.0/modules/videoio/src/cap_ffmpeg_impl.hpp#L1664-L1693) (to use internal FFMPEG enums instead of OpenCV legacy tables).

And [this line](https://github.com/Itseez/opencv/blob/3.1.0/modules/videoio/src/cap_ffmpeg_impl.hpp#L1675) with "avformat_get_riff_video_tags" should reuse FFMPEG tables with [defined VP8/VP9](https://github.com/FFmpeg/FFmpeg/blob/n3.0/libavformat/riff.c#L306-L307):
```
const AVCodecTag ff_codec_bmp_tags[] = {
...
    { AV_CODEC_ID_VP8,          MKTAG('V', 'P', '8', '0') },
    { AV_CODEC_ID_VP9,          MKTAG('V', 'P', '9', '0') },
...
};
...
const struct AVCodecTag *avformat_get_riff_video_tags(void)
{
    return ff_codec_bmp_tags;
}
```

Do you have any ideas why this doesn't work?

BTW, What is container used for video file (MKV, AVI, WebM)?

**Comment by peters** [comment]
> Do you have any ideas why this doesn't work?

No, I don't. But i'm working on updating the wrapper to use ffmpeg 3.0 (ifdefs). I'll investigate why it does not work as intended. 

> BTW, What is container used for video file (MKV, AVI, WebM)?

WebM

**Comment by peters** [comment]
Btw, do you happen to know which libavcodec version vp8 / v9 was added?

**Comment by alalek** [comment]
I haven't been tried to work with VP9 yet.

BTW, VP9 tag was added into libavformat tables by this [commit](https://github.com/FFmpeg/FFmpeg/commit/eb7f7b797f0ae76a7cf6db7792365998ee6e9cba) in Nov 2013

**Comment by peters** [comment]
> BTW, VP9 tag was added into libavformat tables by this commit in Nov 2013

Ty :)

I have a working patch for ffmpeg 3.0. I'm going to cross-compile it now and run it through our test suite to see if it's working correctly. I've have shimmed the new ABI with `_opencv_ffmpeg` inline methods so that we maintain compability with older ffmpeg versions. 

Should I send a PR for this? It would be nice to have it upstream even if you choose to target an older ffmpeg version.

**Comment by alalek** [comment]
> Should I send a PR for this

Sure! :)

**Comment by peters** [comment]
Awesome :+1: 

Btw, is there an easy way of obtaining the new versioning scheme found in https://github.com/Itseez/opencv_3rdparty/blob/ffmpeg/master/ffmpeg/ffmpeg_version.cmake without looking through the headers?

**Comment by peters** [comment]
```
set(ALIASOF_libavcodec_VERSION 57.24.102)
set(ALIASOF_libavformat_VERSION 57.25.100)
set(ALIASOF_libavutil_VERSION 55.17.103)
set(ALIASOF_libswscale_VERSION 4.0.100)
set(ALIASOF_libavresample_VERSION 3.0.0)
```

**Comment by peters** [comment]
Preliminary patch available here:
https://github.com/peters/opencv/commit/dc5950028aa36a08f63cf23fd3acabe53d689338

**Comment by peters** [comment]
Fixed in https://github.com/Itseez/opencv_3rdparty/commit/ece59ea56ef1efb577fe3065cfa4a63e012369e3
