### ISSUE TITLE
Do I have to compile the Pre-built Libraries ?

### ISSUE THREAD

**Issue by manticore-1** [Itseez/opencv#6319]
Hello
Do I have to compile the Pre-built Libraries which are contained in  [Download opencv-3.1.0.exe (115.1 MB)](https://sourceforge.net/projects/opencvlibrary/files/latest/download?source=files)  ?

**Comment by alalek** [comment]
I have no idea what this question is asking

**Comment by manticore-1** [comment]
Sorry, I'm a new user of c++, Qt and opencv
Ok,  my objective is to use Qt (mingwin) and opencv to gather under windows32.
I downloaded opencv-3.1.0 and extracted its contents into c:\opencv.
Now, I want to know if I can use it in my Qt project or I have to compile it.

**Comment by alalek** [comment]
This package doesn't contain libraries for MINGW (not supported officially), there is only subset for MSVC compilers.
Try to ask help from community here: http://answers.opencv.org
