### ISSUE TITLE
$PREFIX/share/opencv/3rdparty/lib not mentioned in opencv.pc

### ISSUE THREAD

**Issue by Marqin** [Itseez/opencv#6338]
- OpenCV version: 3.1
- Host OS: Linux (Arch Linux) & OS X ( El Capitan )
- Compiler & CMake: GCC 5.3 & CMake 3.5

`libippicv.a` is installed as `$PREFIX/share/opencv/3rdparty/lib/libippicv.a`, but `-L$PREFIX/share/opencv/3rdparty/lib` is not put into `opencv.pc`, so linker, when fed by `pkg-config` flags, fails with:
```
/usr/bin/ld: cannot find -lippicv
```

**Comment by alalek** [comment]
Try the latest master branch.
There were some issues about this: #5841 #5852 #6163 and some fix: #5861
