### ISSUE TITLE
Ocl bug in multiple threads

### ISSUE THREAD

**Issue by xuezu29** [Itseez/opencv#6339]
When using multiple threads,After a period of time the system error:cv::exception,The error is CL_OUT_OF_HOST_MEMORY.If direct call functions without a multi-threaded, can run correctly.
      I guess it is a memory leak beceuse of  multiple threads?

```.cpp
#include "stdafx.h"
#include <cv.h>
#include <highgui.h>
#include <ocl/ocl.hpp>
#include <iostream>
#include <windows.h>
#include <process.h>

using namespace cv;
using namespace std;
using namespace ocl;
unsigned _stdcall ThreaFunc(void* lpParam)
{
	Mat src; 
	src = imread("F:/img/0020/H-1-2.jpg");
	oclMat img;
	img = src;
	//ocl::finish();
	return 0;
}

int _tmain(int argc, _TCHAR* argv[])
{
	DWORD threadId;
	DWORD exitCode = 0;
	HANDLE hthrd;
	for (int i = 0; i < 12000; i++)
	{
		hthrd = (HANDLE)_beginthreadex(NULL, 0, ThreaFunc, (LPVOID)0, 0, NULL);
		
		if (WaitForSingleObject(hthrd, INFINITE) == WAIT_OBJECT_0)
		{
			BOOL a = CloseHandle(hthrd);
		}
                 //ThreaFunc(0);
		cout << i << endl;
	}
	return 0;
}
```

**Comment by alalek** [comment]
> CL_OUT_OF_HOST_MEMORY

```
for (int i = 0; i < 12000; i++)
{
hthrd = (HANDLE)_beginthreadex(NULL, 0, ThreaFunc, (LPVOID)0, 0, NULL);
```

It doesn't look like a normal programming. You need to investigate source of problem yourself.
What is about commented `ocl::finish()`?

**Comment by xuezu29** [comment]
This just a test. Repeatedly open and close the multithreading can appear this problem,so just test,thank you very much.

**Comment by mshabunin** [comment]
Try to use [parallel_for_](http://docs.opencv.org/master/db/de0/group__core__utils.html#gaa42ec9937b847cb52a97c613fc894c4a&gsc.tab=0) from OpenCV.

**Comment by xuezu29** [comment]
I have already solved the problem,it is OK As long as not repeatedly open and close the thread.
