### ISSUE TITLE
[Android]  Raw moments are being capped off by integer maximum limit. Not behaving as double?

### ISSUE THREAD

**Issue by airman00** [Itseez/opencv#6350]
**Setup**
- OpenCV version: 3.1.0 compiled from trunk
- Target OS:  Android 

**Test Scenario:**
I took a test grayscale image (basic shape) and ran the Moments function on the contour on both Python and Android Java. 
Raw moments with a value larger than 2.147483647E9( the max value for an int) are being capped off.

**Python Moments Output**

```
  'm00': 10668.5,
  'm10': 1017600.6666666666,'m01': 796082.5,
  'm20': 119169149.25,'m11': 76968248.375, 'm02': 70682824.08333333,
  'm30': 15792796740.7,'m21': 9322061895.0,'m12': 6883896025.233334,'m03': 6853311179.75,

```
**Android Moments Output ( Notice the last line of raw moments m30,m21,m12,m03)**

```
m00=10671.0, 
 m10=1105790.0, m01=796316.0, 
 m20=1.36694585E8, m11=8.148092E7, m02=7.0708345E7, 
 m30=2.147483647E9, m21=2.147483647E9, m12=2.147483647E9, m03=2.147483647E9, 
```

I am printing out the Android Moments as follows:
`Log.d(TAG, "Contour Moments = " + Imgproc.moments(contours.get(0) )  );`

**Implications**
The incorrect raw moments trickle down into incorrect calculated moments , including HuMoments. This messes up shape matching for example.

Any ideas of what to try?

**Comment by airman00** [comment]
I think I found the problem in Moments.java.

Why is it being cast to (int), thus limiting it to the max value of an integer( 2.147483647E9 )

```
 public Moments(double[] vals) {
        set(vals);
    }

    public void set(double[] vals) {
        if (vals != null) {
            m00 = vals.length > 0 ? (int) vals[0] : 0;
            m10 = vals.length > 1 ? (int) vals[1] : 0;
            m01 = vals.length > 2 ? (int) vals[2] : 0;
            m20 = vals.length > 3 ? (int) vals[3] : 0;
            m11 = vals.length > 4 ? (int) vals[4] : 0;
            m02 = vals.length > 5 ? (int) vals[5] : 0;
            m30 = vals.length > 6 ? (int) vals[6] : 0;
            m21 = vals.length > 7 ? (int) vals[7] : 0;
            m12 = vals.length > 8 ? (int) vals[8] : 0;
            m03 = vals.length > 9 ? (int) vals[9] : 0;
            this.completeState();
        }
```

**Comment by mshabunin** [comment]
@airman00 , thank you for reporting. PR #6351 should fix this issue.
