### ISSUE TITLE
Videocapture *mov`s seems to time out in virtualbox

### ISSUE THREAD

**Issue by justayak** [Itseez/opencv#6356]
From: http://answers.opencv.org/question/91532/videocapture-movs-seems-to-time-out-in-virtualbox/)

I get a strange behavior with Videocapture when I run code inside a Virtualbox client (Client: Ubuntu 15.10 x64) (confirmed with following host systems: Windows & Arch Linux). When the Videocapture object opens a video file everything is fine but when the system idles for too long (e.g. waiting for keyboard input) ~30 seconds the video capture returns an empty list and not the next frame of the video file (VideoCapture::grab returns false). This only seem to happen with *.mov files like the one attached (http://80.86.85.151:91/small.mov). Is this a problem in OpenCV or might something else be the cause?

### Please state the information for your system
- OpenCV version: 3.1.x (current OpenCV master branch)
- "Host" OS: Linux (Ubuntu 15.10) as Virtualbox VM, strangly, outside the virtual machine everything works fine (Outside host systems: Windows and Arch)

### In which part of the OpenCV library you got the issue?
- videoio

### Expected behaviour
when idle for some time, VideoCapture objects deliver the next frame when asked to.

### Actual behaviour
when idle for some time, VideoCapture objects seem to "time out" and deliver empty Mat`s. VideoCapture::grab already returns false!

### Additional description
The issue only seem to happen inside of a virtualbox image of Ubuntu 15.10 x64. When executed on the host, no problems occur.

### Code example to reproduce the issue / Steps to reproduce the issue

Video file: [small.mov.zip](https://github.com/Itseez/opencv/files/199955/small.mov.zip)

```cpp
#include <cv.h>
#include <highgui.h>
#include <opencv2/core/core.hpp> 
#include <opencv2/videoio/videoio.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <string>
#include <iostream>

using namespace cv;
using namespace std;

int main(){

const string ref = "/home/biotracker/Downloads/MVI_7555.MOV";

cv::VideoCapture capt(ref); 
Mat im;
capt >> im;

for (int i = 0; i < 10; i++) {
    cout << "im empty: " << im.empty() << endl;     
    imshow("qq", im);
    char c = waitKey(60000);
    cout << "time is over, nextframe" << endl;
    capt >> im;
}

return 0;
}
```

**Comment by peters** [comment]
It's because in commit https://github.com/Itseez/opencv/commit/da48061910db0ee78396237bc78d6f2e321ea5eb a default timeout of 30s was introduced. You should either run video capture in a separate thread or avoid blocking the main thread for more than 30s :)

**Comment by peters** [comment]
You can disable it by adding the following define: #USE_AV_INTERRUPT_CALLBACK 0

**Comment by justayak** [comment]
Remark: the issue still happens when the code is executed in a separate thread.

Disabling the callback solves the problem. I would suggest to disable the interrupt callback by default

**Comment by alalek** [comment]
@justayak @peters Could you check this patch: #6358?

**Comment by justayak** [comment]
@alalek The patch seems to fix the reported issue, thank you
