### ISSUE TITLE
gstreamer aborts autosearch feature, making some devices unreachable.

### ISSUE THREAD

**Issue by gunnjo** [Itseez/opencv#6357]
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04)

### In which part of the OpenCV library you got the issue?
-videoio

### Expected behaviour
I expect ot be able to open an "OpenNI" device with gstreamer conpiled in, but no gstreamer capable devices available

### Actual behaviour
The gstreamer capture device throws a CV_ERROR when it fails to open a gstreamer device. Preventing the auto selection feature from continuing to the OpenNI open code.

### Additional description
at line 818 of cap_gstreamer.cpp (tag 3.1.0)
you will find the following
            CV_ERROR(CV_StsError, "GStreamer: unable to start pipeline\n");
This line aborts the autosearch feature of VideoCapture with a device # of 0 (first video device found)

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
    VideoCapture cap(0);

    return 0;
}
```

**Comment by alalek** [comment]
@gunnjo Could you please take a look on #6359?
