### ISSUE TITLE
[CMAKE] cmake.exe v3.5 crashes when building opencv

### ISSUE THREAD

**Issue by amroamroamro** [Itseez/opencv#6370]
I discovered a bug in latest CMake 3.5 that affects OpenCV.

In the file [`cmake\cl2cpp.cmake`][4], the code attempts to strip comments from *.cl files using some regular expressions.

This was working fine in 3.4.3, until I tried to build OpenCV using the latest CMake 3.5.1... Something must have changed between 3.4.x and 3.5.x, and now cmake itself crashes during the process! It occurs when it reaches the `bioinspired` module when processing the [`retina_kernel.cl`][3] file.

This was confirmed with cmake 3.5.1, opencv/opencv_contrib 3.1.0, windows 10 (the cmake compilers/generators don't matter). It only manifests on Windows platforms.

After a chat on #cmake, I tracked the issue using the `--trace` flag to this line:

```cmake
  string(REGEX REPLACE "/\\*([^*]/|\\*[^/]|[^*/])*\\*/" ""   lines "${lines}") # multiline comments
```

Apparently CMake [regex-matching][1] is implemented recursively, and that pattern on certain inputs ends up with a call depth too deep  running out of stack space and crashing..

To give an example, here is minimal test case that triggers the bug (happens on Windows, Linux cmake didn't crash):

```cmake
file(READ "C:/opencv_contrib/modules/bioinspired/src/opencl/retina_kernel.cl" lines)
string(REGEX REPLACE "/\\*([^*]/|\\*[^/]|[^*/])*\\*/" "" lines "${lines}")
file(WRITE out.txt "${lines}")
```
``` bat
C:\> cmake -P strip.cmake
```

Parsing C/C++ code this way using regexps is usually [a bad idea][2]. Ideally a proper parser or comment-stripping tool should be used for this task...

For now and as a workaround, we could delete comment lines like `//****************` from [that file][3]. It makes it easier to regex-match that way, and avoid the recursion error for the moment.  :)

[1]: https://cmake.org/gitweb?p=cmake.git;a=blob;f=Source/kwsys/RegularExpression.cxx;h=22593b45cac7b222d45d8c34983522d00d4eba4e;hb=HEAD#l977
[2]: http://stackoverflow.com/a/1732454/97160
[3]: https://github.com/Itseez/opencv_contrib/blob/master/modules/bioinspired/src/opencl/retina_kernel.cl
[4]: https://github.com/Itseez/opencv/blob/master/cmake/cl2cpp.cmake

**Comment by alalek** [comment]
Actually we trying to minimize a set of 3rdparty dependencies. So I'm not sure that we will use some cross-platform comments stripping tool in the near future.
Thanks for workaround again!

**Comment by seanlis** [comment]
I got the same issue with cmake 3.6.2 under windows.

**Comment by alalek** [comment]
This should be workarounded in upstream.
