### ISSUE TITLE
SFM module input parameters

### ISSUE THREAD

**Issue by vimarshc** [Itseez/opencv#6376]
Hi, i have just started experimenting with the SFM module, and I had a question, how would we obtain the input parameters, namely the focal length f, and the center of projection coordinates cx and cy?
I understand that the focal length can be obtained after doing a camera calibration in OpenCV, thus getting back focal lengths fx and fy, as well as the optical centres cx and cy in pixel coordinates.
Are these the same that we need to pass on to the SFM functions, as described in the tutorial:
[http://docs.opencv.org/3.1.0/d5/dab/tutorial_sfm_trajectory_estimation.html#gsc.tab=0](url) 
Also what do we do if fx and fy are not equal?
Thanks!

**Comment by mshabunin** [comment]
_sfm_ module is located in _opencv_contrib_ and all issues and PRs should go into that repository. All questions are better to be asked on the users forum: [answers.opencv.org](http://answers.opencv.org/questions/)
