### ISSUE TITLE
Fail building OpenCV 3.1.0 on OSX 10.11.4 El Capitan

### ISSUE THREAD

**Issue by gunther82** [Itseez/opencv#6409]
I'm trying to compile the OpenCV javacpp-presets 3.1.0 following the instruction here (https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64) on OSX El Capitan version 10.11.4, but I got a lot of errors during the compilation of OpenCV.
This is the list of errors I got:
https://www.dropbox.com/s/zhh7paln3ow9xgc/javacv-preset%20opencv%20MAC%20error.txt?dl=0

Can anyone help?

**Comment by mshabunin** [comment]
We have successfully built OpenCV on MacOSX 10.11.4 with XCode 7.3: [build info](http://master.ocv/buildbot/builders/master-mac/builds/650), [cmake output](http://master.ocv/buildbot/builders/master-mac/builds/650/steps/cmake/logs/stdio) Several compilation warnings had been fixed, but nothing critical.
It is either a problem in version 3.1, either some local configuration issue. Try to use latest master branch version.

Feel free to reopen this issue if the problem will be reproduced during standalone OpenCV build.
