### ISSUE TITLE
Can't build docs. No rule to make target 'docs'

### ISSUE THREAD

**Issue by ramwin** [Itseez/opencv#6436]
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Linux (fedora 23)
- *(if needed)* Compiler & CMake: GCC 5.3.1 & CMake 3.4.1

### In which part of the OpenCV library you got the issue?

- install

### Expected behaviour
make docs  
make html_docs  
then there will be a directory opencv/build/doc/_html/index.html  

### Actual behaviour
> make: *** No rule to make target 'docs'. Stop.

### Additional description
I change the directory to opencv or opencv/build and do the same thing ( "make docs" and "make html_docs" ), they both failed.

**Comment by mshabunin** [comment]
OpenCV 3.x has different target for documentation: `doxygen`. Please, take a look at the [guide](http://docs.opencv.org/master/tutorial_documentation.html#tutorial_documentation_generate).

**Comment by duchengyao** [comment]
I can not open your guide

**Comment by mshabunin** [comment]
@duchengyao , please take a look [here](http://docs.opencv.org/master/d4/db1/tutorial_documentation.html)

**Comment by duchengyao** [comment]
@mshabunin ,thanks so much!
