### ISSUE TITLE
The input "event" parameter of mouse event callback function cannot distinguish mouse wheel scroll down or up.

### ISSUE THREAD

**Issue by LinkHS** [Itseez/opencv#6437]
- OpenCV version: 3.1.0
- Host OS: Windows 10

### In which part of the OpenCV library you got the issue?
Examples:
- highgui
- Mouse event

### Expected behaviour
When I scroll down the mouse wheel, it should print two negative numbers according to below comment in highgui.hpp (EVENT_MOUSEWHEEL     = 10,//!< positive and negative values mean forward and backward scrolling, respectively.).

### Actual behaviour
When I scroll down or scroll up the mouse wheel, it always print "10, 0"

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

void on_mouse(int event, int x, int y, int , void* userdata)
{
	printf("event = %d, %d\n", event, getMouseWheelDelta(EVENT_MOUSEWHEEL));
}

int main()
{
    Mat mSrc = imread("xxxxx.jpg");
    imshow("src", mSrc); 
    setMouseCallback( "src", on_mouse, NULL );

    waitKey(0);

    return 0;
}
```

**Comment by kevin-coder** [comment]
hi, please check whether your function "on_mouse" is correct or not, I see that this function is:
void on_mouse(int event, int x, int y, int , void* userdata), which the 4th parameter is empty.
If you specify "EVENT_MOUSEWHEEL" for this parameter, I think this issue will not happen again. Pleas e have a try.

**Comment by LinkHS** [comment]
Hi Kvin-coder,

Yes, you are right.

I have made such a stupid mistake.

Thanks a lot
