### ISSUE TITLE
Floodfill giving different results on different machines

### ISSUE THREAD

**Issue by changizi** [Itseez/opencv#6449]
- OpenCV version: 3.1
- Host OS: Mac OS X 10.11.4

Issue in  imgproc -> Floodfill function

I have a method that uses floodfill function on an image (saved in jpg). The issue is that I get different results when running the code on different machines, even with same opencv version.
Has anyone else experienced this issue?
I can't figure out what is causing this.

```
#include <iostream>
#include <string>
#include <time.h>
#include <ctime>
#include <cmath>

#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
using namespace std;


void findMaxHistogram(cv::Mat input, cv::Mat mask, int& maxIdx)
{
    cv::Mat hist;  int histSize = 256;
    float range[] = { 0, 256 } ;
    const float* histRange = { range };
    
    calcHist( &input, 1, 0, mask, hist, 1, &histSize, &histRange, true, false );

    cv::minMaxIdx(hist, NULL, NULL, NULL ,  &maxIdx);
}

int main(int argc, const char * argv[]) {
    string fileName_Ref = //original_image_path
    cv::Mat refImage = cv::imread(fileName_Ref);

    cv::Mat blurredImage;
    cv::medianBlur(refImage, blurredImage,19);
    cv::Mat gray_img;
    cv::cvtColor(blurredImage, gray_img, cv::COLOR_BGR2GRAY);
    
    cv::Rect rect = cv::Rect(refImage.cols/2, refImage.rows/5, 1, 3*refImage.rows/5);
    cv::Mat mid_col = gray_img(rect);

    int maxIdx;
    findMaxHistogram(mid_col, cv::Mat(), maxIdx);

    cout << maxIdx << '\n';
    
    for( int y = refImage.rows/5; y <= 4 *blurredImage.rows/5; y++ )
    {
        if (gray_img.at<uchar>(y,blurredImage.cols/2) == maxIdx)
        {
            floodFill( blurredImage, cv::Mat(), cv::Point(blurredImage.cols/2,y), cv::Vec3b(255,255,255), 0, cv::Scalar::all(1), cv::Scalar::all(1) , 8 | 255<<8  );
            break;
        }
    }
    
    cv::imshow("floodfill_result", blurredImage);
     cv::waitKey();
    
    return 0;
}
```

**Comment by StevenPuttemans** [comment]
1. `on different machines` --> can you please be more specific?
2. Also how different are the results, can you quantify this?

**Comment by changizi** [comment]
I tried floodfill on following machines on this image:
![molematching_74_0](https://cloud.githubusercontent.com/assets/8248886/14749185/ec9d264c-0872-11e6-8833-33b0bec0dbf5.jpg)

Mac OS X EI Capitan,  OpenCV version: 3.1:
![flood_fill_mac](https://cloud.githubusercontent.com/assets/8248886/14749161/d37a5324-0872-11e6-91c7-5ffcd1ffbfe2.png)

Ubuntu 14.04.4 LTS,  OpenCV version: 3.1:
![flood_fill_ubuntu](https://cloud.githubusercontent.com/assets/8248886/14749162/d37b3b04-0872-11e6-82b8-b3910feea2ee.png)

diff image:
![diff](https://cloud.githubusercontent.com/assets/8248886/14749195/f8ca30a4-0872-11e6-8ffb-13ac1df93c2e.png)

**Comment by StevenPuttemans** [comment]
How did you install opencv on both systems? If you did through cmake then please provide cmake output for both systems!

**Comment by changizi** [comment]
[opencv_mac_cmake.txt](https://github.com/Itseez/opencv/files/232296/opencv_mac_cmake.txt)
[opencv_mac_ubuntu.txt](https://github.com/Itseez/opencv/files/232297/opencv_mac_ubuntu.txt)

**Comment by sturkmen72** [comment]
if the source file is a jpg maybe this was the reason. did you try to check differences of images without floodfill.

**Comment by changizi** [comment]
Yes I checked the original image on both machines, no difference there.

**Comment by sturkmen72** [comment]
is the original image is jpeg

**Comment by sturkmen72** [comment]
did you open and save it as png in both system then compare png's

**Comment by changizi** [comment]
Yes the original image is jpeg. But the step before floodfill is medianblur and I have checked the output of median blur is the same on both systems.

**Comment by sturkmen72** [comment]
OK. thanks.

**Comment by StevenPuttemans** [comment]
The problem will lie, with 90% certainty, in the fact you are saving the end result in a jpg format. Since it uses the codec present on the system it can differ between OS systems what the default amount of compression is.

Did you save the end result as PNG as said by sulley?

**Comment by StevenPuttemans** [comment]
*sturkmen I mean

**Comment by changizi** [comment]
The end result is saved in png. The original image is in jpg. The difference is obvious in the white pixels of the flood fill results even before saving them (just using imshow to look at the results)

**Comment by FredFG** [comment]
Difference in the system JPEG **readers** could also be causing the artifact. Try saving the original in .png on either platform then running the algorithm on both platforms. Or is this what you've done?
Assuming the OpenCv code base is identical it would be exceedingly strange to give different results.

**Comment by jjyap** [comment]
When using cmake add -DBUILD_JPEG=ON and check to make sure that your OSX and Ubuntu system have the same output in the config in my case (ver 90).

**Comment by changizi** [comment]
The issue was caused by different Jpeg readers. Thanks everyone for your help. Closing the issue.

**Comment by StevenPuttemans** [comment]
:+1:
