### ISSUE TITLE
OpenCL Assertion Error on cvtColor method

### ISSUE THREAD

**Issue by marjinal1st** [Itseez/opencv#6451]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Linux (Ubuntu 14.04)
- Compiler & CMake: GCC 4.8.4 & CMake 3.2.2

### In which part of the OpenCV library you got the issue?
Examples:
- ocl
- converting color space (cvtColor)

### Expected behaviour

Face detection using OpenCL

### Actual behaviour

Assertion error:

```
OpenCV Error: Assertion failed (u->refcount == 0) in handle, file /path/to/opencv/modules/core/src/umatrix.cpp, line 741
```

Called by:

```c++
cvtColor(frame, frameGray, COLOR_BGR2GRAY);
```

Line that fails to assert: [here](https://github.com/Itseez/opencv/blob/92387b1ef8fad15196dd5f7fb4931444a68bc93a/modules/core/src/umatrix.cpp#L741)

### Additional description

**Weird part:** At the first the time I've run this example, it worked without problem. After shutting down and powering the computer again, I got this error. No extra software installations, updates or configurations are performed.

**clinfo** output: [here](https://gist.github.com/marjinal1st/67ed7044b8f9228018b4fddcb84b872f)

### Code example to reproduce the issue / Steps to reproduce the issue

```c++
#include <vector>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

int main(int argc, char **argv)
{
    VideoCapture camera{0};
    CascadeClassifier fd("/usr/local/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml");
    UMat frame, frameGray;
    Mat result;
    vector<Rect> faces;

    while (camera.read(frame)) {
       result = frame.getMat(ACCESS_WRITE);

       cvtColor(frame, frameGray, COLOR_BGR2GRAY);
       equalizeHist(frameGray, frameGray);
       fd.detectMultiScale(frameGray, faces);

       for (auto rect : faces) {
           rectangle(result, rect, Scalar(0, 255, 0), 2);
       }

       imshow("Webcam", result);

       int key = waitKey(1) & 0xFF;

       if (key == 'q') break;
   }

    return EXIT_SUCCESS;
}
```

**Comment by alalek** [comment]
> result = frame.getMat(ACCESS_WRITE);
> cvtColor(frame, frameGray, COLOR_BGR2GRAY);

This assertion is just a message for potential data race: writing via `result` and reading via `cvtColor`.

BTW, OpenCL calls are asynchronous in general.

The right code:
```
// remove: result = frame.getMat(ACCESS_WRITE);
frame.copyTo(result);
```
or
```
// processing: cvtColor, etc
{
    // actually ACCESS_WRITE is not enough
    // (but access flags support is not accurate at this moment
    // so it may provide valid results with current OpenCV versions)
    Mat result = frame.getMat(ACCESS_RW); // local "result"
    for (auto rect: faces) ...
    imshow(result)
} // "result" mapping is released here
```

**Comment by marjinal1st** [comment]
While waiting for your reply, I thought I might try different Nvidia drivers. Installed version **352.63** and run same example. It works now. :neutral_face: 

Updated **clinfo** output is [here](https://gist.github.com/marjinal1st/32c64f3e1a1bc334067cbea16f48335b). Significant differences that I could find are: **_OpenCL version 1.1 to 1.2_** and **_Address Bits 32 Bits to 64 Bits_**

Closing the issue.

**Comment by vade** [comment]
Hi. Apologies for butting in on this thread, but the notion that getMat is asynchronous isn't documented anywhere to my knowledge. 

Is this in fact correct, that for proper synchronous usage of TAPI / UMat the .getMat accessor is considered unsafe?

**Comment by alalek** [comment]
> that getMat is asynchronous

This is not true. But you can't use UMat and mapped Mat simultaneously.
