### ISSUE TITLE
calib_stereo sample fails to write intrinsic parameters because of a hardcoded relative path

### ISSUE THREAD

**Issue by eliao** [Itseez/opencv#6456]
Running calib_stereo on my data results in the following:

```
Running stereo calibration ...
done with RMS error=1.8652
average epipolar err = 0.860128
Error: can not save the intrinsic parameters
```

This is because the sample is hardcoded to write the intrinsics.yml file to "../data/instrinsics.yml".  It should save the file to the current path as it does with the extrinsics.yml.

**Comment by StevenPuttemans** [comment]
Well actually, this is done with a reason. People now know that related to the samples folder, they can find the sample file in the data folder provided in the samples directory of OpenCV repo. I do not think that removing this will help.
