### ISSUE TITLE
missing x86 folder

### ISSUE THREAD

**Issue by vishalezen** [Itseez/opencv#6462]
I am trying to use Opencv in netbeans. For this I am following this video link
[How to set up Opencv and Javacv and Create Sample Project in NetBeans](https://www.youtube.com/watch?v=0mE0LuXi9b8)

While setting the path to the dlls I can not find the x86 folder in the extracted folder of opencv.exe

Any suggestions?
I have downloaded the latest version of openCV for Windows version from opencv.org

**Comment by alalek** [comment]
You need to build Java binary for x86 configuration yourself or try to download old release.
It is removed from distribution to reduce size of package (the most part of desktop systems uses Windows x64).

**Comment by vishalezen** [comment]
Ok I  got it.
Thank you so much :)
