### ISSUE TITLE
[Question] Why cuda::ORB detectAndCompute's  useProvidedKeypoints parameter is forced to be false?

### ISSUE THREAD

**Issue by OzgrCn** [Itseez/opencv#6473]
Hi,
I would like to use cuda::orb compute or detectAndCompute method to describe keypoints that I detect earlier. But when I try to use these methods I got "Assertion failed (useProvidedKeypoints == false) in detectAndCompute" error. When I search on the source code, I see 
```
void ORB_Impl::detectAndCompute(InputArray _image, InputArray _mask, std::vector<KeyPoint>& keypoints, OutputArray _descriptors, bool useProvidedKeypoints){

CV_Assert( useProvidedKeypoints == false ); 
...
```
Why does the function takes a useProvidedKeypoints parameter that is forced to be equal to false?

Is there another way to achieve my goal?
### my system
- OpenCV version:  3.1
- Host OS: Linux (Ubuntu 14.04) 

- cuda::orb, cuda, orb

### Code example 
```
    cv::cuda::GpuMat gpu_img;
    cv::cuda::GpuMat dst;

    cv::Mat img = cv::imread("Lena.pgm", CV_LOAD_IMAGE_GRAYSCALE);
    gpu_img.upload(img);

    cv::Ptr<cv::cuda::ORB> orb = cv::cuda::ORB::create();
    std::vector<cv::KeyPoint> keypoints;
    orb->detect(gpu_img, keypoints); // reason not to use detectAndCompute method only, I detect keypoints earlier and do same calculations to produce new keypoints based on old ones, then I need to describe new ones.   
 orb->compute(gpu_img, keypoints,dst); 
// same with orb->detectAndCompute(gpu_img, noArray(), keypoints,dst, true);
```

**Comment by mshabunin** [comment]
Because `detectAndCompute` is overloaded virtual method (see `cv::Feature2D` class) and it seems that ORB algorithm does not support this flag: [documentation](http://docs.opencv.org/master/db/d95/classcv_1_1ORB.html)

**Comment by OzgrCn** [comment]
I think, there is no reason not to ORB supports this flag algorithmically. And, cv::ORB is fully supporting it. I guess,  cv::cuda::ORB is incomplete about this flag. We were needing it for our thesis about accelerating keypoint detection and description.  So, we modify the cuda::ORB. If you can reopen the issue, I can send a pull request or I can open a new issue.
