### ISSUE TITLE
makePtr<SVM>(filename) error.

### ISSUE THREAD

**Issue by DelightRun** [Itseez/opencv#6475]
- OpenCV version: 3.1
- Host OS:  Mac OS X 10.11.3
- Bug module: May be `core`'s `makePtr` or the `save` method of `SVM` in module `ml`

I use `loadClassifierNM2(/path/to/my/model/xml)` to create ERFilter, then I got:

```
core/src/persistence.cpp:3215: error: (-5) The file node should be a numerical scalar or a sequence in function cvStartReadRawData
```

I have a look at the source of `loadClassifierNM2` [here](https://github.com/Itseez/opencv_contrib/blob/master/modules/text/src/erfilter.cpp),and found that it use a `makePtr(filename)` to create a `Ptr<Model>`, i.e. `Ptr<SVM>`

My training code looks like:

```
Ptr<SVM> classifier;
// setting some configs...
classifier->train(trainData);
classifier->save(/path/to/save/model/xml/);
```

Further more, I checked the saved xml file, it's content looks like:

```
<?xml version="1.0"?>
<opencv_storage>
<opencv_ml_svm>
  <format>3</format>
  <svmType>C_SVC</svmType>
  <kernel>
    <type>RBF</type>
    <gamma>1.</gamma></kernel>
  <C>1.</C>
  <term_criteria><epsilon>1.1920928955078125e-07</epsilon>
    <iterations>1000</iterations></term_criteria>
  <var_count>7</var_count>
  <class_count>2</class_count>
  <class_labels type_id="opencv-matrix">
    <rows>2</rows>
    <cols>1</cols>
    <dt>i</dt>
    <data>
      1 2</data></class_labels>
  <sv_total>1847</sv_total>
  <support_vectors>
    <_>
      3.30395997e-01 9.28250030e-02 7. 3. 1.65315002e-01 1.18093801e+00
      3.</_>
 <!-- other support vectors -->
<!-- other content.... -->
```
I think may be it's the way `SVM` class save support vectors that cause the problem.

BTW, I can load this model correctly via `SVM`'s `load` method.

**Comment by berak** [comment]
this is not a library bug. 

if you look at [one of the pretrained filters](https://github.com/Itseez/opencv_contrib/blob/master/modules/text/samples/trained_classifierNM1.xml) , you see, that was trained using ml::Boost , not ml::SVM

if you want to train your own filters, you will have to use Boost, too, not SVM

**Comment by DelightRun** [comment]
Yes, I know we should use Boost classifier. But in the original paper the author said they use a SVM in second stage:
![qq20160428-0 2x](https://cloud.githubusercontent.com/assets/4102875/14878817/85cabdd6-0d58-11e6-849c-e33aa5198f4f.png)
So I want to test second stage `ERFilter` on SVM.

And, actually i wonder that it's a bug of `makePtr` in `core` module rather than the `ERFilter` class.

I think i'd better do more test on `makePtr` function.

**Comment by DelightRun** [comment]
Oh, yes, i figure it out.
