### ISSUE TITLE
using OpenCL causing SEGFAULT 11

### ISSUE THREAD

**Issue by btut** [Itseez/opencv#6486]
### Please state the information for your system
- OpenCV version: commit 6e5e5d8
- Host OS: Mac OS X 10.10.5
- Target OS: host / Android 5.0
- Compiler & CMake for host: LLVM version 7.0.2 (clang-700.1.81) & CMake 3.3.2
- Compiler for cross-compiling: Android NDK r10e

### In which part of the OpenCV library you got the issue?
-ocl

### Expected behaviour
no Segfault

### Actual behaviour
Segfault

### Additional description
When I try to use OpenCL with `cv::ocl::setUseOpenCL(true);` I get a SEGFAULT 11, withouth that line everything works fine. I experienced this first on Android, then I reproduced the issue on my Mac.
This code might not make a lot of sense as it is, but it reproduces my issue with minimal effort.

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include <stdlib.h>
#include <unistd.h>
#include <opencv2/opencv.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <stdio.h>
#include <opencv2/core/ocl.hpp>

using namespace cv;

struct dataStruct{
        Mat     m;
};

Mat createMat(){
        Mat m;
        m = imread("test.png", CV_LOAD_IMAGE_COLOR);
        return m;
}

int main(int argc, char** argv){

        cv::ocl::setUseOpenCL(true);
        if  ( ! cv::ocl::haveOpenCL ())
        {
                printf("no openCL");
        }else{
                printf("openCL");
        }

        struct dataStruct* d = (struct dataStruct*)malloc(sizeof(struct dataStruct));
        Mat x = createMat();

        d->m.create(1920,1080,CV_8UC1);

        d->m = x;

        return 0;
}
```
This is the stacktrace after the SEGFAULT
`* thread #1: tid = 0x19b0d, 0x000000010014d97c libopencv_core.3.0.dylib`cv::Mat::create(int, int const*, int) + 332, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x000000010014d97c libopencv_core.3.0.dylib`cv::Mat::create(int, int const*, int) + 332
    frame #1: 0x000000010000197e a.out`cv::Mat::create(this=0x0000000101c03a70, _rows=1920, _cols=1080, _type=0) + 174 at mat.inl.hpp:648
    frame #2: 0x000000010000160d a.out`main(argc=1, argv=0x00007fff5fbff650) + 141 at test.cpp:34
    frame #3: 0x00007fff8e3645c9 libdyld.dylib`start + 1`

**Comment by alalek** [comment]
In such cases build and run OpenCV tests at first.

> struct dataStruct* d = (struct dataStruct*)malloc(sizeof(struct dataStruct));

Container is not initialized and can't be used at all. Use "new" operator to initialize container.

**Comment by btut** [comment]
Well, I just recently switched to C++
Thanks for the help and sorry for bothering you with this.
