### ISSUE TITLE
Error: Specified Android native API level 'android-8' is not supported by your NDK/toolchain.

### ISSUE THREAD

**Issue by breezehou** [Itseez/opencv#6493]
- OpenCV version: opencv_contrib-3.1.0
- Host OS: Mac OS X 10.11.4
- Target OS: Android 6.0
- Compiler: android-ndk-r10e

Logs:
... ...
x opencv_contrib-3.1.0/samples/
x opencv_contrib-3.1.0/samples/python2/
x opencv_contrib-3.1.0/samples/python2/common.py
x opencv_contrib-3.1.0/samples/python2/seeds.py
x opencv_contrib-3.1.0/samples/python2/video.py
CMake Error at platforms/android/android.toolchain.cmake:809 (message):
  Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.
Call Stack (most recent call first):
  CMakeFiles/3.2.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:93 (project)
... ...

**Comment by alalek** [comment]
There is nothing to fix in OpenCV actually.
Refer to OpenCV Android tutorials or ask here http;//answers.opencv.org how to specify native API level.

**Comment by breezehou** [comment]
Add -DANDROID_NATIVE_API_LEVEL=xxx to specify API level.

**Comment by akhilc1** [comment]
What is xxx? 'android-15' or '15' for instance take api level 15. @breezehou

**Comment by alalek** [comment]
`ANDROID_NATIVE_API_LEVEL` is OpenCV's CMake variable passed via CMake command line (-D option) or via environment.

> 'android-15' or '15'

Both cases should work.

**Comment by MahsaSeifikar** [comment]
I have the same problem with OpenCV v4.5.0, NDK-r21d, and API 30! is there any solution?
