### ISSUE TITLE
Support Multiple Block and Cell Size for GPU::HOG 

### ISSUE THREAD

**Issue by aakash-thakkar** [Itseez/opencv#6497]
Hello,
Would be really helpful if HOG could support multiple block and cell sizes, trying to do OCR using HOG and SVM and not being able to select cell size is very limiting.

### Please state the information for your system
- OpenCV 3.x
- Host OS: Linux (Ubuntu 14.04)  / Mac OS X 10.11.3 / Windows 10

### In which part of the OpenCV library you got the issue?
- objdetect
- HOG

**Comment by StevenPuttemans** [comment]
I am sorry but this is not true I think. Take a look at the gpu `hog.cpp` sample, right [here](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/samples/gpu/hog.cpp). At [line 290](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/samples/gpu/hog.cpp#L290) you can clearly see that the cell size and block size can be selected as you wish for the HOGDescriptor...
