### ISSUE TITLE
OpenCV Q&A website has been down for 4 days in a row

### ISSUE THREAD

**Issue by StevenPuttemans** [Itseez/opencv#6499]
Hi guys,

Since Alexander Shishkov (@alekcac) is not responding on the designated issue page of the Q&A website, I am trying to get a hold of one of the core devs that could explain or tell us why the Q&A has been down for 4 days? Any problems we can help out with?

Cheers,

Steven

**Comment by alekcac** [comment]
Hi Steven, 

I am in vacation now and I was offline last week. We have some issues with current hosting. In my opinion one of HDDs in our server has hardware issue. We are trying to find the reason of such behavior with hosting support. We will try to fix issues with website as soon as possible.

Alex

**Comment by mshabunin** [comment]
Sites are working now.

**Comment by sitilge** [comment]
opencv.org down again :(

Is there anyone who could solve the problem?

**Comment by mshabunin** [comment]
@sitilge , there is a problem on hosting provider side, we are waiting when it will be solved.
