### ISSUE TITLE
opencv2.4.9  sample:find_obj_fers 

### ISSUE THREAD

**Issue by polyGithub** [Itseez/opencv#6501]
root@poly:c# ./find_obj_ferns 
This program shows the use of the "fern" plannar PlanarObjectDetector point
descriptor classifier
Usage:
./find_obj_ferns <object_filename> <scene_filename>, default: box.png and box_in_scene.png

Trying to load box.png_model.xml.gz ...
The file not found and can not be read. Let's train the model.
Step 1. Finding the robust keypoints ...
..................................................
Done.
Step 2. Training ferns-based planar object detector ...
..................................................
Done.
Step 3. Saving the model to box.png_model.xml.gz ...
Now find the keypoints in the image, try recognize them and compute the homography matrix
Object keypoints: 100
Image keypoints: 300
55.2231ms
^C
root@poly:c# ./find_obj_ferns 
This program shows the use of the "fern" plannar PlanarObjectDetector point
descriptor classifier
Usage:
./find_obj_ferns <object_filename> <scene_filename>, default: box.png and box_in_scene.png

Trying to load box.png_model.xml.gz ...
**terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)**

**Comment by mshabunin** [comment]
Can not reproduce with the latest 2.4 branch version (Ubuntu 14.04):
```
$ ./build/bin/c-example-find_obj_ferns 

This program shows the use of the "fern" plannar PlanarObjectDetector point
descriptor classifier
Usage:
./find_obj_ferns <object_filename> <scene_filename>, default: box.png and box_in_scene.png

Trying to load box.png_model.xml.gz ...
The file not found and can not be read. Let's train the model.
Step 1. Finding the robust keypoints ...
..................................................
Done.
Step 2. Training ferns-based planar object detector ...
..................................................
Done.
Step 3. Saving the model to box.png_model.xml.gz ...
Now find the keypoints in the image, try recognize them and compute the homography matrix
Object keypoints: 100
Image keypoints: 300
30.489ms

$ ./build/bin/c-example-find_obj_ferns 

This program shows the use of the "fern" plannar PlanarObjectDetector point
descriptor classifier
Usage:
./find_obj_ferns <object_filename> <scene_filename>, default: box.png and box_in_scene.png

Trying to load box.png_model.xml.gz ...
Successfully loaded box.png_model.xml.gz.
Now find the keypoints in the image, try recognize them and compute the homography matrix
Object keypoints: 100
Image keypoints: 300
31.4763ms
```
