### ISSUE TITLE
64-bit arm Android can not load the libopencv_java.so

### ISSUE THREAD

**Issue by chenyuantao** [Itseez/opencv#6515]
### the information for my system
- OpenCV version: 2.4.11
- Host OS:  Windows 10
- Target OS:  Android 5.1 / 64-bit armv7 

### Code example to reproduce the issue 
in MainActivity.java
@Override
	public void onResume() {
		super.onResume();
		OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_2_4_11, this, mLoaderCallback);
	}

### LogCat
dlopen("/data/app/org.opencv.engine-2/lib/arm/libopencv_java.so", RTLD_LAZY) failed: dlopen failed: "/data/app/org.opencv.engine-2/lib/arm/libopencv_java.so" is 32-bit instead of 64-bit
OpenCV loading failed!

**Comment by StevenPuttemans** [comment]
Its a [double issue ](https://github.com/Itseez/opencv/issues/4880) and it has been reported! Guess we can close this one down!
