### ISSUE TITLE
Is there any official documentation on installing opencv 3.1.0 on ubuntu 14.04? 

### ISSUE THREAD

**Issue by probal** [Itseez/opencv#6518]
Is there any official documentation on installing opencv 3.1.0 on ubuntu 14.04?

*deleted the default template - @StevenPuttemans*

**Comment by StevenPuttemans** [comment]
Hello there, yes there is, but it might be lacking some information.

- The installation guide for latest 2.4 branch, can be found [here](http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation)
- The installation guide for latest master branch (3.1), can be found [here](http://docs.opencv.org/master/tutorial_linux_install.html#gsc.tab=0)

And many of the OpenCV books have an official repo assigned with some installation guides. For example the OpenCV 3 Blueprints book, which I helped writing, has a decent tutorial right [here](https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/installation_tutorials/installation_linux.md)!

Do feel the need to reopen this question if this does not suit your needs!
