### ISSUE TITLE
hal_intrin.float32x4 fails on 64bit ARM

### ISSUE THREAD

**Issue by tomoaki0705** [Itseez/opencv#6521]
### Please state the information for your system
- OpenCV version: 3.1 / master
- Host OS: Linux (Ubuntu 16.04 64bit)
- Architecture: aarch64 ARM 64bit (ODROID-C2)

### In which part of the OpenCV library you got the issue?
- core
- test of hal_intrin.float32x4

### Expected behaviour
- 11.054862976074219

### Actual behaviour
- 11.054863929748535

### Additional description
- This doesn't happen on ARM 32 bit or other x86, x86_64 architecture
- This doesn't happen on raspberry Pi 3 + Rasbian 32bit

### Code example to reproduce the issue / Steps to reproduce the issue

The error message is as following
```
/home/odroid/opencv-fork/modules/core/test/test_intrin.cpp:578: Failure
Value of: resF[i]
  Actual: 11.054863929748535
Expected: std::sqrt(data1[i]*data1[i] + data2[i]*data2[i])
Which is: 11.054862976074219
```
The main part of the test is comparing the result of std::sqrt against the v_sqrt based on vrsqrteq_f32.
It's very small difference, but fails on test.
For this part, I propose to add one more iteration in v_sqrt

```
@@ -427,6 +427,7 @@ inline v_float32x4 v_sqrt(const v_float32x4& x)
     float32x4_t e = vrsqrteq_f32(x1);
     e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
     e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
+    e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
     return v_float32x4(vmulq_f32(x.val, e));
 }
```

**Comment by kgnk** [comment]
ARM doesn't tell you the precision. Intel `rsqrtps` gets you within [1.5*2^-12](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=rsqrt&expand=4463) relative error. Each round of Newton-Raphson will approximately double the number of bits of precision, so one round of NR gets you just about to 24 bits, which is what 32-bit floating point values have. Having *two* rounds of NR is already erring on the side of more bits.

Converting those floating point values to hex:
- 11.054863929748535 = 4130E0B9; squared is 42F46B87
- 11.054862976074219 = 4130E0B8; squared is 42F46B85
- The input value 122.21 = 42F46B85

This is 1 [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place) and seems acceptable to me.

**Comment by alalek** [comment]
I believe that problem is with tests: `EXPECT_DOUBLE_EQ` should not be used for results calculated with float precision. There is `EXPECT_FLOAT_EQ` for this or even `EXPECT_NEAR`.

**Comment by tomoaki0705** [comment]
+1 for @alalek suggestion.

**Comment by kgnk** [comment]
The test is templated, but the macros are not. Maybe add an overloaded test function that compares either two floats or two doubles and they can use the correct macro.

BTW, I think this case will still fail because the values differ at the eight digit.

**Comment by tomoaki0705** [comment]
Thanks for the comment kgnk.
Indeed, I had to not only use the macro but to implement template functions.

To answer your concern, the test passed on 64bit ARM.
I looked in to the `EXPECT_FLOAT_EQ`, and in there the, it was calling `AlmostEquals` function and it's comparing the distance between `kMaxUlps`
````
  bool AlmostEquals(const FloatingPoint& rhs) const {
    // The IEEE standard says that any comparison operation involving
    // a NAN must return false.
    if (is_nan() || rhs.is_nan()) return false;

    return DistanceBetweenSignAndMagnitudeNumbers(u_.bits_, rhs.u_.bits_)
        <= kMaxUlps;
  }
````
The `kMaxUlps` is a constant, which is 4

````
  static const size_t kMaxUlps = 4;
````
so in this case, the difference between two values is 1 ULP, which is treated as equal based on comparison with 4 ULPS.
