### ISSUE TITLE
OpenCV Q&A Site Unavailable

### ISSUE THREAD

**Issue by RoyiAvital** [Itseez/opencv#6531]
Hello,

I tried approaching OpenCv at admin@opencv.org yet I got no answer for days.
Hence I didn't who to approach besides this forum.

It seems like the Q&A site of OpenCV isn't available for more than few weeks.

Could you please fix it?
It is a great source for OpenCV.

Thank You.

**Comment by alalek** [comment]
Duplicate.
Some notes are here: https://github.com/opencv-infrastructure/answers.opencv.org/issues/22

**Comment by RoyiAvital** [comment]
Sorry, missed that.

Could you delete this?

Thank You.
