### ISSUE TITLE
VS 2015 v120 to v140 C++ platform, assertion issues

### ISSUE THREAD

**Issue by HthSolid** [Itseez/opencv#6533]
Since changing from v120 to v140 platform I encounter many assertion failures. In v120 I dont get any errors.

I have a main function from where I call other functions, since changing to v140 I cannot exit functions without i.e. deallocating Mat, otherwise I get Assertion failures. None of my functions is able to exit and deallocate automatically, same happens if i put it in own scope on exit of that scope.

Somehow I cannot deallocate <vector<vector<Point>> , clear nor anything else works, also tried to erase content, but then get Pointer errors.
How can I deallocate it or what do I forget? (Somehow new to C++, before was more focused on other languages)

In the code below contours and contours_poly prevent to exit the function without error.

I have tried many proposed solutions but so far didnt succeed with any stated that I could find and apply in my research.

### System information
- OpenCV version: 3.1
- Host OS: Windows 7 x64
- Target OS: host (debug x64)

### OpenCV library with issue
- types

### Expected behaviour
Clear assertions on function exit

### Actual behaviour
Assertion failure

### Code example to reproduce the issue / Steps to reproduce the issue

```
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>
#include <Windows.h>
#include <baseapi.h>
#include <allheaders.h>

using namespace std;
using namespace cv;
vector<Rect> textboxes(cv::Mat img, int agg){
	vector<Rect> boundRect;
	cv::Mat img_gray, img_grayB, element, img_sobel, img_threshold;
	img.copyTo(img_gray);
	img.copyTo(img_grayB);

	Sobel(img_gray, img_sobel, CV_8U, 1, 0, 3, 1, 0, BORDER_DEFAULT);
	threshold(img_sobel, img_threshold, 220, 255, CV_THRESH_OTSU + CV_THRESH_BINARY);
	element = getStructuringElement(MORPH_RECT, Size(28,12));
	morphologyEx(img_threshold, img_threshold, CV_MOP_CLOSE, element);
	vector<vector<Point>> contours;
	findContours(img_threshold, contours, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_NONE, Point(0, 0));
	vector<vector<Point>> contours_poly(contours.size());
	for (int i = 0; i < contours.size(); i++) {
			if (contours[i].size() > 100) {
				approxPolyDP(cv::Mat(contours[i]), contours_poly[i], 3, true);
				Rect appRect(boundingRect(cv::Mat(contours_poly[i])));
				if (appRect.width > appRect.height) { //vertical are excluded
					boundRect.push_back(appRect);
				}
			}
	}
	for (int i = 0; i < boundRect.size(); i++) {
			rectangle(img_grayB, boundRect[i], Scalar(0, 255, 0), 3, 8, 0);
		}
	return boundRect;	
}
int main()
{
    cv::Mat imageg, imagecol, orig;
		imageg = imread(mypic, 0); // IMREAD_COLOR); // Read the file
		imagecol = imread(mypic, IMREAD_COLOR); // Read the file in color
		orig = imread(mypic, IMREAD_COLOR);
 if (!imageg.data) // Check for invalid input
		{
			cout << "Could not open or find the image" << endl;
			return -1;
		}
 vector<Rect> Rbox = textboxes(imageg ,1);
    return 0;
}
```

![image](https://cloud.githubusercontent.com/assets/4158547/15188958/a898ff94-17a8-11e6-8e8e-3bb8aff38045.png)

**Comment by kgnk** [comment]
Try building with the [CRT heap debugging](https://msdn.microsoft.com/en-us/library/x98tx3cf(v=vs.100).aspx), particularly with:
```
_CrtSetDbgFlag
    ( _CRTDBG_CHECK_ALWAYS_DF
    | _CRTDBG_ALLOC_MEM_DF
    | _CRTDBG_LEAK_CHECK_DF
    );
```

**Comment by HthSolid** [comment]
As far as I have read the msdn that only gives me the leaks, no?

Already dumped it before but that didnt really give me a clue :)

`#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>

int main(int argc, char** argv)
	{
_CrtSetDbgFlag(_CRTDBG_CHECK_ALWAYS_DF | _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
`

`Detected memory leaks!
Dumping objects ->
{65896} normal block at 0x0000000002F11020, 16 bytes long.
 Data: <  '             > 08 CD 27 00 00 00 00 00 00 00 00 00 00 00 00 00 
{65895} normal block at 0x000000000A03C4E0, 672 bytes long.
 Data: <        ?       > A3 02 00 00 07 08 00 00 3F 00 00 00 16 00 00 00 
{65885} normal block at 0x0000000002F10FD0, 16 bytes long.
 Data: <0               > 30 BD 0F 0A 00 00 00 00 00 00 00 00 00 00 00 00 
{65854} normal block at 0x000000000A0FB970, 992 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{65853} normal block at 0x0000000002F10620, 16 bytes long.
 Data: <  '             > 08 D1 27 00 00 00 00 00 00 00 00 00 00 00 00 00 
{65852} normal block at 0x0000000002F0FCC0, 16 bytes long.
 Data: <  '             > C8 D0 27 00 00 00 00 00 00 00 00 00 00 00 00 00 
{65851} normal block at 0x0000000002F0FBD0, 16 bytes long.
 Data: <  '             > 18 E9 27 00 00 00 00 00 00 00 00 00 00 00 00 00 
{65743} normal block at 0x0000000002F200B0, 512 bytes long.
 Data: <   @    X  @    > B0 90 B3 40 01 00 00 00 58 90 B3 40 01 00 00 00 
{65742} normal block at 0x0000000002C808B0, 1024 bytes long.
 Data: <`  @       @    > 60 91 B3 40 01 00 00 00 90 8F B3 40 01 00 00 00 
{65741} normal block at 0x0000000002F20B30, 1024 bytes long.
 Data: <Xp @       @    > 58 70 AD 40 01 00 00 00 C8 8F B3 40 01 00 00 00 
{65736} normal block at 0x0000000002F03790, 16 bytes long.
 Data: <   @            > D0 02 DF 40 01 00 00 00 00 00 00 00 00 00 00 00 
{65735} normal block at 0x00000000003BCBB0, 64 bytes long.
 Data: <  ;       ;     > B0 CB 3B 00 00 00 00 00 B0 CB 3B 00 00 00 00 00 
{65734} normal block at 0x0000000002F03740, 16 bytes long.
 Data: <   @            > B8 02 DF 40 01 00 00 00 00 00 00 00 00 00 00 00 
{65733} normal block at 0x00000000021D22C0, 48 bytes long.
 Data: < "       "      > C0 22 1D 02 00 00 00 00 C0 22 1D 02 00 00 00 00 
{65730} normal block at 0x0000000002F036F0, 20 bytes long.
 Data: <        psdebug_> 0C 00 00 00 0C 00 00 00 70 73 64 65 62 75 67 5F 
{65724} normal block at 0x00000000021D3EF0, 24 bytes long.
 Data: <        MicroFea> 10 00 00 00 0E 00 00 00 4D 69 63 72 6F 46 65 61 
{65723} normal block at 0x00000000021D3F50, 24 bytes long.
 Data: <        MicroFea> 10 00 00 00 0E 00 00 00 4D 69 63 72 6F 46 65 61 
{65722} normal block at 0x0000000002F036A0, 16 bytes long.
 Data: < 0 @     m @    > 80 30 84 40 01 00 00 00 84 6D 06 40 01 00 00 00 
{65721} normal block at 0x0000000002F03650, 16 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
`

**Comment by kgnk** [comment]
What is your runtime library setting, static or dynamic? If this doesn't match the opencv library, there will be heap problems.

**Comment by HthSolid** [comment]
I think this could be related to CUDA v7.5 not supporting v140 VS2015, investigating that a little.
Since my Lib is static and was build with CUDA on v120 VS2013.
Will sort this out and post my results, but then probably return to 2013.

**Comment by kgnk** [comment]
Allocating in one runtime library and freeing in another will cause heap problems.

**Comment by Dikay900** [comment]
I dont see any cuda related code in your example, but yea Cuda 7.5 doesnt support VS2015. This will hopefully be supported with Cuda 8.0

**Comment by HthSolid** [comment]
CUDA was not the problem, btw CUDA 8 confirmed support of v140 VS2015, will come end of month probably.

**One of the static libs I used was not compiled with v140 VS2015, apparently any difference from compiler libs will cause assertion problems.**
Am more careful, next time, to check all used libs for having all the same compiler.
Happens always if there is any difference between project compiler and compiler lib was compiled with.
Sry for stupidity but I hope it helps others when they face something like this.
