### ISSUE TITLE
Opencv 3.1 AttributeError: 'module' object has no attribute 'FastFeatureDetector'

### ISSUE THREAD

**Issue by littletiger311** [Itseez/opencv#6534]
Opencv 3.1 AttributeError: 'module' object has no attribute 'FastFeatureDetector' error. 

It seems 3.0 is fine.

**Comment by littletiger311** [comment]
fixed, should be cv2.FastFeatureDetector_create()

**Comment by Dikay900** [comment]
Then please close this issue as well. Thanks!

**Comment by StevenPuttemans** [comment]
Did it for you ;)
