### ISSUE TITLE
opencv2 SVM classifiers require manual edit for loading in opencv3

### ISSUE THREAD

**Issue by mixmixmix** [Itseez/opencv#6572]
`<my_svm>` tag from opencv 2 svm classifiers needs to be manually deleted when loading classifiers in opencv 3.1.0:
```
auto svm = cv::ml::SVM::create();
FileStorage fSvm("svm.xml",FileStorage::READ);
svm->read(fSvm->root()); //possibly this can be adjusted to compensate for changes?
```
Error:
```
OpenCV Error: Parsing error (Missing or invalid SVM type) in read_params, file /home/mix/tmp/opencv/modules/ml/src/svm.cpp, line 2123
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/mix/tmp/opencv/modules/ml/src/svm.cpp:2123: error: (-212) Missing or invalid SVM type in function read_params
```
If I delete `<my_svm>` tag, all works fine.

**Comment by LorenaGdL** [comment]
`<my_svm>` tag? I have never seen such tag...
Why aren't you using the load() function?

**Comment by mixmixmix** [comment]
You're right @LorenaGdL , I was using wrong function for loading. The new interface:
`Ptr<SVM> svm = Algorithm::load<SVM>("my_svm_model.xml");` works correctly. 
However the old one `svm->load("model.xml")` won't fail but will load empty model. That's why I used `read()` instead which doesn't have compatibility.
'<my_svm>' tag is in Opencv2 trained classifiers.
