### ISSUE TITLE
package org.opencv.calib3d does not exist

### ISSUE THREAD

**Issue by AlexTS1980** [Itseez/opencv#6576]
hi there, 

I keep getting this error when compiling java source files. I suspect calib3d has been renamed, but not sure what into. Or maybe it is missing from some jar file. Could you help?

best,

Alex  

### System details
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04)  
- cmake version 2.8.12.2
- gcc 4.8.4

**Comment by alalek** [comment]
You should use Q/A forum for asking help: http://answers.opencv.org
