### ISSUE TITLE
Error compiling OpenCV Ubuntu 16.04 with CUDA

### ISSUE THREAD

**Issue by eokeeffe** [Itseez/opencv#6606]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Ubuntu 16.04 LTS
- Nvidia-367 with CUDA 7.5
-Compiler & CMake: GCC 5.3 & CMake 3.5

### In which part of the OpenCV library you got the issue?
Examples:
- core, cuda

Error generated using gcc & cmake in 16.04 LTS 
Error generated:
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;

Using the methods in [https://github.com/BVLC/caffe/issues/4046] by adding 

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")

to the top of the CMakeLists.txt, everything compiled and worked fine

**Comment by alalek** [comment]
Duplicate: #6500
