### ISSUE TITLE
install does not copy ts headers

### ISSUE THREAD

**Issue by berak** [Itseez/opencv#6623]
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04) / Windows 10
- CMake 3.5.2

### In which part of the OpenCV library you got the issue?
installing

### Expected behaviour
all headers from modules/ts/include/opencv2 should get copied during install

### Actual behaviour
* ts.hpp missing from install/include/opencv2
* libopencv_ts310.a is build and installed properly

### Additional description
being able to build unit tests locally (w/o having to recompile all of opencv) is a necessity.
i tried to enable `BUILD_TESTS` as well (though i'd prefer not to), no difference.

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/ts.hpp"
TEST(MyModule, regression_1)
{ 
    int z=42;
    ASSERT_EQ(0, z);
}
TEST(MyModule, regression_2)
{ 
    // not throwing anything counts as "passed"
}
CV_TEST_MAIN("cvmeaow")
```

**Comment by alalek** [comment]
ts module is not a part of official OpenCV API. It is for internal usage only.
You should probably use Google Tests directly.

**Comment by berak** [comment]
hmm, ok.

all i'm saying is - this would simplify *writing* unit tests enormously.
