### ISSUE TITLE
imread JPEG bug

### ISSUE THREAD

**Issue by slr-engineering** [Itseez/opencv#6665]
We seem to have found a bug in the JPEG image reading code (which is new in 3.1) 
in the EXIF parsing functions. 

The EXIF parser hangs in reading the JPEG orientation tag, and the 
imread() function does not return (explanation see below) and hangs.
Probably the jpeg file was created wrong, but opencv should not hang, this 
is the worst possible scenario for us.

### Please state the information for your system
- OpenCV version:  3.1 / Source file contains the problem
- Host OS: Reproduced on Linux (Ubuntu 16.04)  and Windows 10 MSVS 2015

### In which part of the OpenCV library you got the issue?
The module affected is imgcodecs, imread() function.

### Expected behaviour
imread() ignores the faulty JPEG tag, or returns an error.

### Actual behaviour
Function imread() hangs indefinitely due to EXIF parsing source code error.

### Additional description
Should read the JPEG tag length, but tries to fseek by -2 bytes which is casted to 0FFFFFFE. The resulting error is not taken care of and the while() loop runs
indefinitely.

The file affected is 
jpeg_exif.cpp, line 202

### Code example to reproduce the issue / Steps to reproduce the issue
See above.

**Comment by sturkmen72** [comment]
probably duplicate https://github.com/Itseez/opencv/issues/6641

**Comment by slr-engineering** [comment]
Hello,

I wold say hat it is a duplicate.

Oliver


> Am 10.06.2016 um 13:46 schrieb Suleyman TURKMEN <notifications@github.com>:
> 
> probably duplicate #6641 <https://github.com/Itseez/opencv/issues/6641>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Itseez/opencv/issues/6665#issuecomment-225161479>, or mute the thread <https://github.com/notifications/unsubscribe/AS72b0UXpqZnyBQLXA4og12tTBAbtMO3ks5qKU6ggaJpZM4IyyzA>.
> 

SLR Engineering GmbH
www.slr-engineering.at
Dipl.-Ing. Oliver Sidla
os@slr-engineering.at
Gartengasse 19
8010 Graz
Austria
M: +43 (0) 699 118 747 96
