### ISSUE TITLE
ld: library not found for -lgstbase-1.0

### ISSUE THREAD

**Issue by sulmanen** [Itseez/opencv#6684]
Managed to build opencv once but now it fails randomly.

### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Mac OS X 10.11.5
- *(if needed)* Compiler & CMake: Apple LLVM version 7.3.0 (clang-703.0.31) & CMake 3.5.2

### In which part of the OpenCV library you got the issue?
building on os x

### Expected behaviour
builds
### Actual behaviour
[~/work/opencv]> make
[  1%] Built target zlib
[  3%] Built target libtiff
[  7%] Built target libjpeg
[ 10%] Built target libjasper
[ 10%] Built target libpng
[ 14%] Built target IlmImf
[ 16%] Built target opencv_core
[ 20%] Built target opencv_imgproc
[ 21%] Built target opencv_imgcodecs
[ 23%] Built target opencv_videoio
[ 23%] Built target opencv_highgui
[ 23%] Built target opencv_ts
[ 23%] Linking CXX executable ../../bin/opencv_perf_core
ld: library not found for -lgstbase-1.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/opencv_perf_core] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
make: *** [all] Error 2

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
    double d[] = { 546,2435,7,4534,23423,3 };
    cout << "d = 0x" << reinterpret_cast<void*>(d) << endl;

    return 0;
}
```

**Comment by alalek** [comment]
> it fails randomly.

Try to clean build dir completelly.

Please check differences between your build logs and these logs from our Mac build machine:
http://pullrequest.opencv.org/buildbot/builders/precommit_macosx/builds/5614/steps/cmake

**Comment by sulmanen** [comment]
I checked out a fresh copy and now it builds. Tried to clean the directory using git checkout but it seems to have left something changed.

**Comment by alalek** [comment]
Anyway always use CMake for [out-of-source builds](https://cmake.org/Wiki/CMake_FAQ#Out-of-source_build_trees) only. In-source builds are very unpredictable and they are not recommended.
