### ISSUE TITLE
FindContours not working

### ISSUE THREAD

**Issue by vkoushik** [Itseez/opencv#6701]
OpenCV 2.4.13

Mac OSX 10.11.5

Xcode 7.3

Command line tools project

Included the required library files

Program:
 ```
 removeObjFromBg=1-(img32/pat32);
    removeObjFromBg=removeObjFromBg*255;
   // removeObjFromBg.convertTo(img, CV_8U);
    Mat imgAfterThreshold;
    cvtColor(removeObjFromBg, removeObjFromBg, CV_BGR2GRAY,1);

    threshold(removeObjFromBg, imgAfterThreshold, 50, 255, THRESH_BINARY);
   
    vector<vector<Point>> con;
    Mat rgr;
//    cvtColor(img, rgr, CV_RGB2BGR);
    img.convertTo(imgAfterThreshold, CV_32SC1);
    findContours(imgAfterThreshold, con, RETR_EXTERNAL, CHAIN_APPROX_SIMPLE);
or
    img.convertTo(imgAfterThreshold, CV_8UC1);
```

Issue:

The find contours keeps throwing the same error again and again eventhough i changed the mat type to 32sc1 or 8uc1

**OpenCV Error: Unsupported format or combination of formats ([Start]FindContours support only 8uC1 and 32sC1 images) in cvStartFindContours, file /Users/koushikv/Documents/ocv/opencv/modules/imgproc/src/contours.cpp, line 196
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/koushikv/Documents/ocv/opencv/modules/imgproc/src/contours.cpp:196: error: (-210) [Start]FindContours support only 8uC1 and 32sC1 images in function cvStartFindContours**

I tried all the combinations but none works.The code crashes everytime.

**Comment by alalek** [comment]
> code crashes

In general you should handle exceptions in C++ programs if you don't want a crash.

This call
```
img.convertTo(imgAfterThreshold, CV_32SC1);
```
doesn't change number of channels (second parameter is equal to `CV_32S`).
Also you lost result of `imgAfterThreshold` from "threshold" call.

Take a look on OpenCV samples: https://github.com/Itseez/opencv/tree/2.4/samples/cpp

Future questions please post on Q/A forum: http://answers.opencv.org
