### ISSUE TITLE
Python OpenCV - Drawing Function Issue

### ISSUE THREAD

**Issue by legoulart** [Itseez/opencv#6703]
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

### Please state the information for your system
- OpenCV version: 3.x
- Host OS: Linux (Fedora 23)
- Compiler & CMake: GCC 5.3 & CMake 3.5

### In which part of the OpenCV library you got the issue?
- drawing funcions

### Expected behaviour

The code attempts to draw a green square on the window.

### Actual behaviour

I got this working in last week but now nothing happens and I get the error described bellow. The code attempts to draw a green square on the video window. 

          **Traceback (most recent call last):
           File "/home/ggoulart/PycharmProjects/INTPYT_HandTracker/Main.py", line 13, in <module>
           cv2.rectangle(gray, 100, 100, (0,255,0), 3)
           SystemError: new style getargs format but argument is not a tuple**

Can anybody help me?
I've tried convert to a tuple, but nothing changes.

### Code example to reproduce the issue

```
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

# Loop
while (1):

    _, frame = cap.read()

    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    cv2.rectangle(gray, 100, 100, (0,255,0), 3)

    cv2.imshow('Test',gray)

    k = cv2.waitKey(100)
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

**Comment by alalek** [comment]
Usage questions should go here: http://answers.opencv.org

Take a look on OpenCV Python samples: https://github.com/Itseez/opencv/tree/master/samples/python
Try `print(cv2.rectangle.__doc__)` to get function description with some information about parameters.
