### ISSUE TITLE
Python calcCovarMatrix Documentation Wrong?

### ISSUE THREAD

**Issue by AndrewChenUoA** [Itseez/opencv#6751]
In the Operations on Arrays section of the [OpenCV 3.0.0-dev documentation](http://docs.opencv.org/3.0-beta/modules/core/doc/operations_on_arrays.html#calccovarmatrix), the definition for Python calcCovarMatrix is:

`Python: cv2.calcCovarMatrix(samples, flags[, covar[, mean[, ctype]]]) → covar, mean`

However, for whatever reason, the definition that is actually present when calling help(cv2) is:

`Python: cv2.calcCovarMatrix(samples, mean, flags[, covar[, ctype]]) → covar, mean`

mean becomes a required argument, but this behaviour is not explained in any documentation.
OpenCV 3.0.0 is built running on Ubuntu.

**Comment by alalek** [comment]
OpenCV 3.0.0 and mentioned documentation are outdated and not supported anymore.
