### ISSUE TITLE
unable to switch to input window when using grabcut.py with very large image

### ISSUE THREAD

**Issue by jasjuang** [Itseez/opencv#6755]
- OpenCV version: Trunk
- Host OS: Linux (Ubuntu 14.04)

### Steps to reproduce the issue

1. Find a random image that has resolution larger than the current display

2. Type in the below command in terminal
``````
 python /home/jason/opencv/samples/python/grabcut.py ultrahigh.png
``````
I am unable to bring the input window to front hence cannot experiment grabcut on a larger image. I am expecting being able to bring the input window to front.

Low res images works normally since both the output and input window could be both visible at the same time.

**Comment by alalek** [comment]
What is UI backend used?

**Comment by sovrasov** [comment]
@jasjuang Try to comment line 
`cv2.moveWindow('input',img.shape[1]+10,90)`
in grabcut.py

**Comment by alalek** [comment]
This sample works as expected. There are no reasons to write complex logic to process cases which are not related to simple demonstration (like resizing showed windows), because it is a "sample".

**Comment by jasjuang** [comment]
@sovrasov Thanks your solution works, however it appears that grabcut is not capable to process images at such high resolution anyways. When I try to draw the bounding box it freezes for a few minutes and then crashes.
